Repository GenericMappingTools/pygmt, pull requests merged in 2020-06, with the labels that each got.

#468 Add instructions to view the test coverage reports locally
  .gitignore
  CONTRIBUTING.md
  Makefile
Labels: documentation

#472 Update the plotting example using the colormap generated by pygmt.makecpt
  examples/tutorials/plot.py
Labels: documentation

#474 Turn all short aliases into long form
  pygmt/base_plotting.py
  pygmt/figure.py
  pygmt/gridding.py
  pygmt/helpers/decorators.py
  pygmt/helpers/utils.py
  pygmt/mathops.py
  pygmt/modules.py
  pygmt/sampling.py
  pygmt/tests/test_info.py
  pygmt/tests/test_which.py
Labels: documentation

#481 Enhance text with extra functionality and aliases
  pygmt/base_plotting.py
  pygmt/tests/baseline/test_text_angle_font_justify_from_textfile.png
  pygmt/tests/baseline/test_text_fill.png
  pygmt/tests/baseline/test_text_input_remote_filename.png
  pygmt/tests/baseline/test_text_pen.png
  pygmt/tests/baseline/test_text_position.png
  pygmt/tests/baseline/test_text_position_offset_with_line.png
  pygmt/tests/baseline/test_text_round_clearance.png
  pygmt/tests/test_text.py
Labels: enhancement

#488 Change load_earth_relief()'s default resolution to 01d
  .azure-pipelines.yml
  pygmt/clib/conversion.py
  pygmt/clib/session.py
  pygmt/datasets/earth_relief.py
  pygmt/tests/test_datasets.py
  pygmt/tests/test_grdcontour.py
  pygmt/tests/test_grdimage.py
  pygmt/tests/test_grdinfo.py
  pygmt/tests/test_grdtrack.py
  pygmt/tests/test_grdview.py
Labels: enhancement

#490 Fix a bug when passing data to GMT in Session.open_virtual_file()
  pygmt/clib/session.py
  pygmt/tests/baseline/test_plot_lines_with_arrows.png
  pygmt/tests/test_clib.py
  pygmt/tests/test_plot.py
Labels: bug

#484 Unpin pylint version and fix some lint warnings
  .azure-pipelines.yml
  .pylintrc
  environment.yml
  pygmt/__init__.py
  pygmt/base_plotting.py
  pygmt/clib/conversion.py
  pygmt/helpers/utils.py
  pygmt/tests/test_sphinx_gallery.py
Labels: maintenance

#492 Wrap grdcut
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/gridops.py
  pygmt/tests/test_grdcut.py
Labels: feature

#498 Fix several failures due to updates of earth relief data
  pygmt/clib/session.py
  pygmt/tests/test_datasets.py
  pygmt/tests/test_grdinfo.py
  pygmt/tests/test_grdtrack.py
Labels: maintenance
