Repository GenericMappingTools/pygmt, pull requests merged in 2020-12, with the labels that each got.

#705 Add tutorial for contour maps
  doc/index.rst
  examples/tutorials/contour-map.py
Labels: documentation

#710 Add Will Schlitzer to AUTHORS.md
  AUTHORS.md
Labels: maintenance, skip-changelog

#709 Add frame and cmap to the colorbar parameters list
  pygmt/base_plotting.py
Labels: documentation

#716 Let Figure.text() support record-by-record transparency
  pygmt/base_plotting.py
  pygmt/tests/test_text.py
Labels: feature

#719 Changing units to SI units in projections
  examples/tutorials/contour-map.py
Labels: documentation, skip-changelog

#712 Add tutorial for plotting Earth relief
  doc/index.rst
  examples/tutorials/earth-relief.py
Labels: documentation

#721 Add conic projections to the projection gallery
  examples/projections/conic/conic_equidistant.py
  examples/projections/conic/conic_lambert.py
  examples/projections/conic/polyconic.py
Labels: documentation

#723 Adding miscellaneous projections to gallery
  examples/projections/misc/misc_eckertIV.py
  examples/projections/misc/misc_eckertVI.py
  examples/projections/misc/misc_hammer.py
  examples/projections/misc/misc_mollweide.py
  examples/projections/misc/misc_robinson.py
  examples/projections/misc/misc_sinusoidal.py
  examples/projections/misc/misc_van_der_grinten.py
  examples/projections/misc/misc_winkel_tripel.py
Labels: documentation

#713 Migrate documentation deployment from Travis CI to GitHub Actions
  .github/workflows/ci_tests.yaml
  .travis.yml
  CONTRIBUTING.md
  MAINTENANCE.md
  README.rst
Labels: maintenance

#724 Fix a bug of Figure.text() when "text" is a non-string array
  pygmt/base_plotting.py
  pygmt/tests/test_text.py
Labels: bug

#720 Add tutorial for adding a map title
  examples/tutorials/frames.py
Labels: documentation

#727 Adding cylindrical projections to gallery
  examples/projections/cyl/cyl_equal_area.py
  examples/projections/cyl/cyl_equidistant.py
  examples/projections/cyl/cyl_mercator.py
  examples/projections/cyl/cyl_miller.py
  examples/projections/cyl/cyl_transverse_mercator.py
  examples/projections/cyl/cyl_universal_transverse_mercator.py
Labels: documentation

#725 Migrate pytest configurations to pyproject.toml
  CONTRIBUTING.md
  Makefile
  environment.yml
  pyproject.toml
  requirements-dev.txt
Labels: maintenance

#728 Add non-geographic plots to projection gallery
  examples/projections/nongeo/cartesian.py
  examples/projections/nongeo/polar.py
Labels: documentation

#629 Unpin the Sphinx version
  environment.yml
  requirements-dev.txt
Labels: maintenance

#729 Change text when GMTInvalidInput error is raised for basemap
  pygmt/base_plotting.py
  pygmt/tests/test_basemap.py
Labels: documentation

#734 Convert line breaks from DOS to UNIX
  examples/projections/azim/azim_equidistant.py
  examples/projections/azim/azim_general_perspective.py
  examples/projections/azim/azim_general_stereographic.py
  examples/projections/azim/azim_gnomonic.py
  examples/projections/azim/azim_orthographic.py
  examples/projections/nongeo/cartesian.py
Labels: maintenance, skip-changelog

#738 Rename vercel configuration file from now.json to vercel.json
  MAINTENANCE.md
  vercel.json
Labels: maintenance

#736 Check files for UNIX-style line breaks and 644 permission
  .github/workflows/ci_tests.yaml
  .github/workflows/format-command.yml
  CONTRIBUTING.md
Labels: maintenance

#740 Update Python version in install isntructions to Python 3.9
  doc/install.rst
Labels: documentation, skip-changelog

#739 Add test test_basemap_map_scale
  pygmt/tests/test_basemap.py
Labels: maintenance

#744 Add a Makefile target 'distclean' for deleting project metadata files
  Makefile
Labels: maintenance

#741 Add plotting lines tutorial
  doc/index.rst
  examples/tutorials/plot-lines.py
Labels: documentation

#751 Improve the readability of the grdview function
  pygmt/base_plotting.py
Labels: enhancement, skip-changelog

#743 Add tutorial for 3D perspective image
  doc/index.rst
  examples/tutorials/3d-perspective-image.py
Labels: documentation

#759 Fix typo for version number in requirements-dev.txt
  requirements-dev.txt
Labels: maintenance, skip-changelog

#760 Add projection description for Lambert Azimuthal Equal-Area
  examples/projections/azim/azim_lambert.py
Labels: documentation

#752 Add the shading parameter to colorbar() in base_plotting.py
  pygmt/base_plotting.py
  pygmt/tests/test_colorbar.py
Labels: enhancement

#757 Conic projection descriptions
  examples/projections/conic/conic_albers.py
  examples/projections/conic/conic_equidistant.py
  examples/projections/conic/conic_lambert.py
  examples/projections/conic/polyconic.py
Labels: documentation

#761 Add cylindric descriptions
  examples/projections/cyl/cyl_cassini.py
  examples/projections/cyl/cyl_equal_area.py
  examples/projections/cyl/cyl_equidistant.py
  examples/projections/cyl/cyl_mercator.py
  examples/projections/cyl/cyl_miller.py
  examples/projections/cyl/cyl_stereographic.py
  examples/projections/cyl/cyl_transverse_mercator.py
  examples/projections/cyl/cyl_universal_transverse_mercator.py
Labels: documentation

#762 Add miscellaneous projections descriptions
  examples/projections/misc/misc_eckertIV.py
  examples/projections/misc/misc_eckertVI.py
  examples/projections/misc/misc_hammer.py
  examples/projections/misc/misc_mollweide.py
  examples/projections/misc/misc_robinson.py
  examples/projections/misc/misc_sinusoidal.py
  examples/projections/misc/misc_van_der_grinten.py
  examples/projections/misc/misc_winkel_tripel.py
Labels: documentation

#742 Add logarithmic and power projections
  examples/projections/nongeo/cartesian_linear.py
  examples/projections/nongeo/cartesian_logarithmic.py
  examples/projections/nongeo/cartesian_power.py
Labels: documentation

#766 Add description for the "columns" arguments
  pygmt/base_plotting.py
Labels: documentation

#756 Add a CI job testing GMT master branch on Windows
  .github/workflows/ci_tests_dev.yaml
  MAINTENANCE.md
Labels: maintenance

#768 Allow anyone to run the /format command in PRs
  .github/workflows/slash-command-dispatch.yml
Labels: bug, maintenance, skip-changelog, waiting for review

#763 Add a table for compatibility of PyGMT with Python and GMT
  README.rst
Labels: maintenance

#711 Update Tutorials README to remove placeholder line
  examples/tutorials/README.txt
Labels: documentation, skip-changelog

#774 Add a gallery example of setting line colors with a custom CPT
  examples/gallery/line/line-custom-cpt.py
Labels: documentation

#777 Add a gallery example for the fig.image() method
  examples/gallery/plot/image.py
Labels: documentation

#772 Add an example for plotting multi-parameter symbols
  examples/gallery/plot/multi-parameter-symbols.py
Labels: documentation
