Repository GenericMappingTools/pygmt, pull requests merged in 2020-05, with the labels that each got.

#430 Update install instructions
  doc/install.rst
  pygmt/base_plotting.py
  pygmt/sampling.py
Labels: documentation

#446 Simplify PyGMT Release process
  .github/ISSUE_TEMPLATE/release_checklist.md
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  MAINTENANCE.md
Labels: maintenance

#457 Patch release drafter github action
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#452 Update baseline images for updates of earth relief data
  .azure-pipelines.yml
  pygmt/clib/session.py
  pygmt/tests/baseline/test_grdcontour.png
  pygmt/tests/baseline/test_grdcontour_file.png
  pygmt/tests/baseline/test_grdcontour_interval_file_full_opts.png
  pygmt/tests/baseline/test_grdcontour_labels.png
  pygmt/tests/baseline/test_grdcontour_slice.png
  pygmt/tests/baseline/test_grdview_on_a_plane.png
  pygmt/tests/baseline/test_grdview_on_a_plane_styled_with_facadepen.png
  pygmt/tests/baseline/test_grdview_on_a_plane_with_colored_frontal_facade.png
  pygmt/tests/baseline/test_grdview_surface_mesh_plot_styled_with_meshpen.png
  pygmt/tests/baseline/test_grdview_surface_plot_styled_with_contourpen.png
  pygmt/tests/baseline/test_grdview_with_perspective_and_zaxis_frame.png
  pygmt/tests/baseline/test_grdview_with_perspective_and_zscale.png
  pygmt/tests/baseline/test_grdview_with_perspective_and_zsize.png
  pygmt/tests/test_datasets.py
  pygmt/tests/test_grdtrack.py
  pygmt/tests/test_info.py
Labels: maintenance

#454 Fix the test for GMT_COMPATIBILITY=6
  pygmt/tests/test_session_management.py
Labels: maintenance

#459 Update the instructions for testing pygmt install
  doc/install.rst
Labels: documentation

#461 Separate tests of gmtinfo and grdinfo
  pygmt/tests/test_grdinfo.py
  pygmt/tests/test_info.py
Labels: maintenance

#466 Add show_versions() function for printing debugging information used in issue reports
  .github/ISSUE_TEMPLATE/bug_report.md
  Makefile
  doc/api/index.rst
  doc/install.rst
  pygmt/__init__.py
Labels: feature
