Repository GenericMappingTools/pygmt, pull requests merged in 2020-07, with the labels that each got.

#502 Add gallery example for grdview
  examples/gallery/grid/grdview_surface.py
Labels: documentation, scipy-sprint

#503 Temporarily expect failures for some grdcontour and grdview tests
  pygmt/tests/test_grdcontour.py
  pygmt/tests/test_grdview.py
Labels: maintenance

#475 Run Continuous Integration tests on Github Actions
  .azure-pipelines.yml
  .github/workflows/ci_tests.yaml
  Makefile
  README.rst
Labels: maintenance

#511 Patch issues with Github Actions CI cache
  .github/workflows/ci_tests.yaml
Labels: skip-changelog

#509 Allow load_earth_relief() to load pixel or gridline registered data
  pygmt/datasets/earth_relief.py
  pygmt/tests/test_datasets.py
  pygmt/tests/test_grdcontour.py
  pygmt/tests/test_grdimage.py
  pygmt/tests/test_grdinfo.py
  pygmt/tests/test_grdtrack.py
  pygmt/tests/test_grdview.py
  pygmt/tests/test_makecpt.py
Labels: enhancement

#512 Let pytest generate both HTML and XML coverage reports
  .azure-pipelines.yml
  .gitignore
  .travis.yml
  Makefile
Labels: maintenance

#513 Eliminate Azure Pipelines CI jobs, use GitHub Actions instead
  .azure-pipelines.yml
  .github/workflows/ci_tests.yaml
Labels: maintenance

#500 Initialize a GMTDataArrayAccessor
  .github/workflows/ci_tests.yaml
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/modules.py
  pygmt/tests/test_accessor.py
Labels: feature

#519 Run style checks using GitHub Actions instead of Azure Pipelines
  .azure-pipelines.yml
  .github/workflows/ci_tests.yaml
  MAINTENANCE.md
  README.rst
Labels: maintenance

#506 Add shading to grdview gallery example
  examples/gallery/grid/grdview_surface.py
  pygmt/base_plotting.py
Labels: documentation, scipy-sprint

#464 Support various datetime types as input
  pygmt/clib/conversion.py
  pygmt/clib/session.py
  pygmt/tests/baseline/test_plot_datetime.png
  pygmt/tests/test_clib.py
  pygmt/tests/test_plot.py
Labels: feature

#476 Properly allow for either pixel or gridline registered grids
  Makefile
  pygmt/clib/conversion.py
  pygmt/clib/session.py
  pygmt/helpers/decorators.py
  pygmt/tests/baseline/test_grdimage_over_dateline.png
  pygmt/tests/test_grdimage.py
  pygmt/tests/test_grdinfo.py
  pygmt/tests/test_grdview.py
  setup.cfg
Labels: bug

#530 Cache GMT remote data as artifacts on Github
  .github/workflows/cache_data.yaml
  .github/workflows/ci_tests.yaml
  MAINTENANCE.md
Labels: maintenance

#531 Fix the grdtrack example to avoid crashes on macOS
  .github/workflows/ci_tests.yaml
  examples/gallery/grid/track_sampling.py
Labels: bug, documentation

#533 Fix a typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, skip-changelog

#536 Improve the documentation of Figure.shift_origin()
  pygmt/figure.py
Labels: documentation

#518 Re-enable Windows builds
  .github/workflows/ci_tests.yaml
  pygmt/tests/test_image.py
Labels: maintenance, skip-changelog

#537 Raise an error if short- and long-form arguments coexist
  pygmt/helpers/decorators.py
Labels: bug

#538 Remove the Stickler CI configuration file
  .stickler.yml
Labels: maintenance

#539 Ensure surface and grdcut loads GMTDataArray accessor info into xarray
  pygmt/gridding.py
  pygmt/gridops.py
  pygmt/tests/test_grdcut.py
  pygmt/tests/test_surface.py
Labels: bug

#541 Let grdcut() accept xarray.DataArray as input
  pygmt/gridops.py
  pygmt/tests/test_grdcut.py
Labels: feature

#485 Github Actions CI for testing GMT master branch
  .github/workflows/ci_tests_dev.yaml
  MAINTENANCE.md
  README.rst
Labels: maintenance

#544 Automatically cancel in-progress CI runs of old commits
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance

#542 Let load_earth_relief() support all resolutions and optional subregion
  .github/workflows/cache_data.yaml
  pygmt/datasets/earth_relief.py
  pygmt/tests/test_datasets.py
Labels: enhancement

#548 Fix the failing test test_config()
  pygmt/tests/test_config.py
Labels: bug, maintenance, skip-changelog

#547 Add a test to check passing arrays of mixed dtypes to GMT
  pygmt/tests/test_clib.py
  pygmt/tests/test_clib_put_matrix.py
  pygmt/tests/test_clib_put_vector.py
Labels: maintenance, skip-changelog

#551 Add common alias distcalc (j)
  pygmt/helpers/decorators.py
Labels: enhancement, skip-changelog

#550 Add common alias verbose (V)
  pygmt/helpers/decorators.py
Labels: enhancement

#546 Wrap x2sys_init and x2sys_cross
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/tests/test_x2sys_cross.py
  pygmt/tests/test_x2sys_init.py
  pygmt/x2sys.py
Labels: feature

#552 Cleanup track files in test_x2sys_cross_input_two_filenames
  pygmt/tests/test_x2sys_cross.py
Labels: skip-changelog
