Repository GenericMappingTools/pygmt, pull requests merged in 2020-10, with the labels that each got.

#641 Add blackdoc to format Python codes in docstrings
  .github/workflows/ci_tests.yaml
  CONTRIBUTING.md
  Makefile
  environment.yml
  pygmt/base_plotting.py
  pygmt/clib/conversion.py
  pygmt/clib/session.py
  pygmt/figure.py
  pygmt/helpers/decorators.py
  pygmt/helpers/tempfile.py
  pygmt/helpers/utils.py
  requirements-dev.txt
Labels: maintenance

#643 Add Liam's ROSES 2020 PyGMT talk to website
  README.rst
  doc/overview.rst
Labels: documentation

#639 Disallow passing arguments like -XNone to GMT
  pygmt/helpers/utils.py
Labels: bug

#649 Mark xarray shading test fail for GMT<=6.1.1
  pygmt/tests/test_grdimage.py
Labels: maintenance, skip-changelog

#480 Add tutorial for pygmt.Figure.text
  doc/index.rst
  examples/tutorials/text.py
Labels: documentation

#626 Let plot() accept record-by-record transparency
  pygmt/base_plotting.py
  pygmt/tests/test_plot.py
Labels: enhancement

#603 Refactor xfail tests to avoid storing baseline images
  pygmt/tests/test_basemap.py
  pygmt/tests/test_coast.py
  pygmt/tests/test_colorbar.py
  pygmt/tests/test_grdcontour.py
  pygmt/tests/test_legend.py
  pygmt/tests/test_logo.py
  pygmt/tests/test_makecpt.py
  pygmt/tests/test_plot.py
Labels: maintenance

#650 Add more tests for xarray grid shading
  pygmt/tests/test_grdimage.py
Labels: maintenance

#651 Improve documentation of Figure.logo()
  pygmt/base_plotting.py
  pygmt/tests/test_logo.py
Labels: documentation

#654 Add a gallery example for varying transparent points
  examples/gallery/plot/points-transparency.py
Labels: documentation

#659 Fix Github to GitHub
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/cache_data.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .travis.yml
  CONTRIBUTING.md
  MAINTENANCE.md
  README.rst
  doc/_templates/breadcrumbs.html
  doc/changes.rst
  doc/install.rst
  versioneer.py
Labels: documentation, skip-changelog

#662 Add common alias "verbose" (V) to all functions
  pygmt/base_plotting.py
  pygmt/filtering.py
  pygmt/gridding.py
  pygmt/gridops.py
  pygmt/mathops.py
  pygmt/modules.py
  pygmt/sampling.py
Labels: documentation

#661 Add "no_clip" to plot, text, contour and meca
  pygmt/base_plotting.py
Labels: documentation

#660 Add instructions to run specific tests
  CONTRIBUTING.md
Labels: maintenance

#668 Let all tests pass for GMT 6.1.1 and master
  pygmt/tests/test_clib.py
  pygmt/tests/test_grdimage.py
  pygmt/tests/test_info.py
Labels: maintenance, skip-changelog

#646 Add slash command "/format" to automatically format PRs
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/format-command.yml
  .github/workflows/slash-command-dispatch.yml
  CONTRIBUTING.md
Labels: maintenance

#616 Wrap grdfilter
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/gridops.py
Labels: feature

#669 Do not skip xarray shading tests on all platforms
  pygmt/tests/test_grdimage.py
Labels: maintenance, skip-changelog

#664 Improve the gallery example for line styles
  examples/gallery/line/linestyles.py
Labels: documentation

#666 Complete documentation for plot
  pygmt/base_plotting.py
Labels: documentation

#674 Fix typo with doctest-modules
  CONTRIBUTING.md
Labels: documentation, skip-changelog

#675 Upload artifacts showing diff images on test failure
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance

#482 Add tutorial for pygmt.config
  doc/index.rst
  examples/tutorials/configuration.py
Labels: documentation
