Repository GenericMappingTools/pygmt, pull requests merged in 2020-08, with the labels that each got.

#516 Wrap meca
  doc/api/index.rst
  examples/gallery/plot/meca.py
  pygmt/base_plotting.py
  pygmt/tests/baseline/test_meca_loc_array.png
  pygmt/tests/baseline/test_meca_spec_1d_array.png
  pygmt/tests/baseline/test_meca_spec_2d_array.png
  pygmt/tests/baseline/test_meca_spec_dataframe.png
  pygmt/tests/baseline/test_meca_spec_dict_list.png
  pygmt/tests/baseline/test_meca_spec_dictionary.png
  pygmt/tests/baseline/test_meca_spec_file.png
  pygmt/tests/test_meca.py
Labels: feature, scipy-sprint

#553 Update the path to the GMT build script
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog

#554 Improve the workflow to test both GMT master and 6.1 branches
  .github/workflows/ci_tests_dev.yaml
  MAINTENANCE.md
  README.rst
Labels: maintenance

#556 Fix a failing test due to GMT API change
  pygmt/tests/test_clib_put_matrix.py
Labels: bug, maintenance, skip-changelog, upstream

#558 Add Tyler Newton to AUTHORS.md
  AUTHORS.md
Labels: skip-changelog

#520 Wrap GMT_Put_Strings to pass str columns into GMT C API directly
  pygmt/clib/session.py
  pygmt/tests/test_clib.py
  pygmt/tests/test_clib_put_strings.py
Labels: feature, upstream

#562 Allow datetime inputs to region argument
  pygmt/helpers/decorators.py
  pygmt/tests/test_plot.py
Labels: enhancement

#568 Add auto-legend feature to grdcontour and contour
  pygmt/base_plotting.py
Labels: enhancement

#570 Fix pylint 2.6.0 raise-missing-from warning
  pygmt/clib/session.py
Labels: maintenance, skip-changelog

#572 Black lint to remove unneeded commas
  pygmt/base_plotting.py
  pygmt/clib/session.py
  pygmt/tests/test_grdtrack.py
  pygmt/tests/test_session_management.py
Labels: maintenance, skip-changelog
