Repository GenericMappingTools/pygmt, pull requests merged in 2020-09, with the labels that each got.

#577 Bump the required minimum GMT version to 6.1.1
  .github/workflows/cache_data.yaml
  .github/workflows/ci_tests.yaml
  .travis.yml
  doc/install.rst
  environment.yml
  package.json
  pygmt/clib/session.py
  pygmt/figure.py
  pygmt/tests/test_clib.py
  pygmt/tests/test_clib_put_strings.py
Labels: maintenance

#580 Add a test to make sure shift_origin does not crash
  pygmt/tests/test_figure.py
Labels: maintenance

#583 Add a test for Session.write_data() writing netCDF grids
  pygmt/tests/test_clib_put_matrix.py
Labels: maintenance

#585 Revert plotting across dateline workarounds
  Makefile
  examples/gallery/grid/track_sampling.py
  pygmt/tests/test_grdimage.py
  setup.cfg
Labels: maintenance, skip-changelog

#586 Cut Windows CI build time in half to 15 min
  .github/workflows/ci_tests.yaml
Labels: maintenance

#559 Refactor text to use virtualfile_from_vectors instead of pandas tempfile
  pygmt/base_plotting.py
Labels: enhancement, skip-changelog

#588 Improve docstring of data_kind() to include xarray grid
  pygmt/helpers/utils.py
Labels: documentation

#574 Allow pandas.DataFrame table and 1D/2D numpy array inputs into pygmt.info
  pygmt/modules.py
  pygmt/tests/test_info.py
Labels: enhancement

#590 Redesign check_figures_equal testing function to be more explicit
  CONTRIBUTING.md
  pygmt/helpers/testing.py
  pygmt/tests/test_grdimage.py
Labels: maintenance

#592 Add result_images folder to gitignore and make clean list
  .gitignore
  Makefile
Labels: maintenance, skip-changelog

#589 Remove expected failures on grdview tests
  pygmt/tests/test_grdview.py
Labels: maintenance

#575 Sensible array outputs for pygmt info
  pygmt/modules.py
  pygmt/tests/test_info.py
Labels: enhancement

#594 Tiny fixes for the documentation
  README.rst
  examples/tutorials/first-figure.py
Labels: documentation, skip-changelog

#591 Allow passing in pandas dataframes to x2sys_cross
  pygmt/tests/test_x2sys_cross.py
  pygmt/x2sys.py
Labels: enhancement

#581 Add a test for xarray shading
  pygmt/tests/test_grdimage.py
Labels: maintenance

#598 Link to try-gmt binder repository
  README.rst
Labels: documentation

#600 Generalize check figures equal to work with pytest.marks
  CONTRIBUTING.md
  pygmt/helpers/testing.py
Labels: maintenance, skip-changelog

#560 Ensure plotting xarray grids with different central meridians work on some projections
  pygmt/tests/test_grdimage.py
Labels: bug

#599 Changelog entry for v0.2.0
  README.rst
  doc/changes.rst
Labels: skip-changelog

#602 Update release process and checklist template
  .github/ISSUE_TEMPLATE/release_checklist.md
  MAINTENANCE.md
Labels: maintenance

#604 Add an example for different line styles
  doc/conf.py
  examples/gallery/line/README.txt
  examples/gallery/line/linestyles.py
Labels: documentation

#605 Fix Scipy to SciPy
  README.rst
  doc/overview.rst
Labels: documentation, skip-changelog

#606 Fix a typo in the "first figure" tutorial
  examples/tutorials/first-figure.py
Labels: documentation, skip-changelog

#611 Improve Makefile to clean __pycache__ directory recursively
  Makefile
Labels: maintenance

#614 Add alias -t (transparency) to all plotting functions
  pygmt/base_plotting.py
  pygmt/helpers/decorators.py
Labels: enhancement

#621 Enable switching different versions of documentation
  .github/ISSUE_TEMPLATE/release_checklist.md
  doc/_static/version_switch.js
  doc/_templates/layout.html
  doc/conf.py
Labels: documentation

#623 Test if is_nonstr_iter works for numpy arrays
  pygmt/helpers/utils.py
Labels: maintenance, skip-changelog

#625 Add common alias cores (x) for grdimage and other multi-threaded modules
  pygmt/base_plotting.py
  pygmt/helpers/decorators.py
Labels: documentation

#619 Refactor info to allow datetime inputs from xarray.Dataset and pandas.DataFrame tables
  pygmt/modules.py
  pygmt/tests/test_info.py
Labels: enhancement

#624 Add common aliases xshift (X) and yshift (Y)
  pygmt/base_plotting.py
  pygmt/helpers/decorators.py
Labels: documentation

#627 Add common alias perspective (p) for plotting 3D illustrations
  pygmt/base_plotting.py
  pygmt/helpers/decorators.py
Labels: documentation

#620 Complete documentation of grdimage
  pygmt/base_plotting.py
Labels: documentation

#630 Check and lint sphinx configuration file doc/conf.py
  Makefile
  doc/Makefile
  doc/conf.py
Labels: maintenance

#632 Fix two typos in x2sys_cross docstrings
  pygmt/x2sys.py
Labels: documentation, skip-changelog

#596 Remove warnings and improve colorbar gallery example
  examples/gallery/plot/colorbar.py
Labels: documentation

#607 Add an example for scatter plots with auto legends
  examples/gallery/plot/scatter.py
Labels: documentation

#637 Refactor three xfail grdcontour tests
  pygmt/tests/test_grdcontour.py
  pygmt/tests/test_grdimage.py
Labels: maintenance, skip-changelog

#582 Remove testing with GMT 6.1 branch
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog
