Repository GenericMappingTools/pygmt, pull requests merged in 2020-11, with the labels that each got.

#676 Complete most of documentation for makecpt
  doc/conf.py
  pygmt/mathops.py
  pygmt/tests/test_makecpt.py
Labels: documentation

#471 Wrap plot3d
  doc/api/index.rst
  examples/gallery/plot/scatter3d.py
  pygmt/base_plotting.py
  pygmt/tests/test_plot.py
  pygmt/tests/test_plot3d.py
Labels: feature

#678 Add PyGMT Zenodo BibTeX entry to main README.md
  README.rst
Labels: documentation

#673 Refresh Code of Conduct from v1.4 to v2.0
  CODE_OF_CONDUCT.md
  README.rst
Labels: documentation

#680 Fix docstrings for blackdoc v0.3 by adding newline after block
  pygmt/clib/session.py
  pygmt/helpers/tempfile.py
  pygmt/helpers/testing.py
  pygmt/helpers/utils.py
Labels: maintenance, skip-changelog

#681 doc: Fix the description of grdcontour -G option
  pygmt/base_plotting.py
Labels: documentation

#679 Migrate PyPI release to GitHub Actions
  .github/workflows/publish-to-pypi.yml
  .travis.yml
  MAINTENANCE.md
Labels: maintenance

#682 Add "updating citation information" in the release checklist
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: maintenance, skip-changelog

#684 Allow np.object dtypes into virtualfile_from_vectors
  pygmt/clib/session.py
  pygmt/tests/test_clib.py
Labels: enhancement

#687 Bump setup-miniconda to v2.0.0
  .github/workflows/cache_data.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog

#689 Support Python 3.9
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/publish-to-pypi.yml
  doc/install.rst
  environment.yml
  setup.py
Labels: maintenance

#683 Changelog entry for v0.2.1
  README.rst
  doc/_static/version_switch.js
  doc/changes.rst
Labels: maintenance, skip-changelog

#692 Update cache_data workflow to download from successfully cached artifacts
  .github/workflows/cache_data.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog

#667 Migrate coverage configurations to pyproject.toml
  .coveragerc
  Makefile
  environment.yml
  pyproject.toml
  requirements-dev.txt
Labels: maintenance

#695 Switch from versioneer to setuptools-scm
  .codeclimate.yml
  .gitattributes
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/publish-to-pypi.yml
  MAINTENANCE.md
  MANIFEST.in
  doc/conf.py
  pygmt/__init__.py
  pygmt/_version.py
  pyproject.toml
  setup.cfg
  setup.py
  versioneer.py
Labels: maintenance

#696 Remove codeclimate and codacy services
  .codeclimate.yml
  README.rst
Labels: maintenance, skip-changelog

#697 Exclude the CI job for Windows + Python 3.6
  .github/workflows/ci_tests.yaml
Labels: maintenance, skip-changelog

#699 Drop Python 3.6 support
  .github/workflows/ci_tests.yaml
  doc/install.rst
  setup.py
Labels: maintenance

#701 Fix the error message when IPython is not available
  pygmt/figure.py
Labels: bug

#700 Provide basic support for FreeBSD
  pygmt/clib/loading.py
Labels: feature

#707 Add frame as a parameter on the grdview documentation
  pygmt/base_plotting.py
Labels: documentation

#708 Fix typo in link to English Wikipedia page for Iris data set
  examples/gallery/plot/scatter3d.py
Labels: documentation, skip-changelog
