Repository GenericMappingTools/pygmt, pull requests merged in 2021-02, with the labels that each got.

#827 Improve gallery examples
  examples/gallery/coast/borders.py
  examples/gallery/coast/land_and_water.py
  examples/gallery/coast/shorelines.py
  examples/gallery/grid/grdview_surface.py
  examples/gallery/grid/track_sampling.py
  examples/gallery/plot/colorbar.py
  examples/gallery/plot/image.py
  examples/gallery/plot/meca.py
  examples/gallery/plot/multi-parameter-symbols.py
  examples/gallery/plot/points.py
Labels: documentation, skip-changelog

#831 Add slash command '/test-gmt-dev' to test GMT dev version
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/slash-command-dispatch.yml
  MAINTENANCE.md
  README.rst
Labels: maintenance

#788 Wrap inset
  doc/api/index.rst
  doc/index.rst
  examples/gallery/plot/inset.py
  examples/tutorials/inset.py
  pygmt/base_plotting.py
  pygmt/src/__init__.py
  pygmt/src/inset.py
  pygmt/tests/test_inset.py
Labels: feature

#835 Show test execution times in pytest
  pyproject.toml
Labels: maintenance

#836 Add additional video link in text for clarity
  README.rst
Labels: documentation

#838 Add sphinx-copybutton extension to easily copy codes
  doc/_static/style.css
  doc/conf.py
  environment.yml
  requirements-dev.txt
Labels: documentation

#834 Fix config warnings and xfails
  pygmt/tests/baseline/test_config_font_annot.png
  pygmt/tests/baseline/test_config_font_one.png
  pygmt/tests/test_config.py
Labels: maintenance, skip-changelog

#832 Move non-plotting modules to separate files in src directory
  pygmt/__init__.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/tutorial.py
  pygmt/modules.py
  pygmt/src/__init__.py
  pygmt/src/blockmedian.py
  pygmt/src/grdcut.py
  pygmt/src/grdfilter.py
  pygmt/src/grdtrack.py
  pygmt/src/info.py
  pygmt/src/makecpt.py
  pygmt/src/surface.py
  pygmt/src/which.py
Labels: maintenance

#839 Skip workflows in PRs if only non-source-code files are changed
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance

#843 Cleanup the downloaded image in the current directory
  examples/gallery/plot/image.py
Labels: maintenance, skip-changelog

#844 Cache earth_relief_05m_p used in tutorials
  .github/workflows/cache_data.yaml
Labels: maintenance

#848 Update URLs in intersphinx mapping
  doc/conf.py
Labels: maintenance, skip-changelog

#847 Replace np.str and np.object to silence numpy 1.20 deprecation warnings
  pygmt/clib/session.py
  pygmt/tests/test_clib.py
  pygmt/tests/test_clib_put_strings.py
Labels: maintenance, skip-changelog

#849 Move Style Checks CI into a standalone YAML file
  .github/workflows/ci_tests.yaml
  .github/workflows/style_checks.yaml
  CONTRIBUTING.md
  MAINTENANCE.md
Labels: maintenance, skip-changelog

#808 Move plotting functions to separate modules
  pygmt/base_plotting.py
  pygmt/figure.py
  pygmt/src/__init__.py
  pygmt/src/basemap.py
  pygmt/src/coast.py
  pygmt/src/colorbar.py
  pygmt/src/contour.py
  pygmt/src/grdcontour.py
  pygmt/src/grdimage.py
  pygmt/src/grdview.py
  pygmt/src/image.py
  pygmt/src/legend.py
  pygmt/src/logo.py
  pygmt/src/meca.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/text.py
Labels: maintenance

#799 Wrap grdinfo aliases
  pygmt/__init__.py
  pygmt/modules.py
  pygmt/src/__init__.py
  pygmt/src/grdinfo.py
  pygmt/tests/test_grdcut.py
  pygmt/tests/test_grdfilter.py
  pygmt/tests/test_grdinfo.py
Labels: documentation

#850 Fix a warning in test_plot3d_matrix_color
  pygmt/tests/test_plot3d.py
Labels: bug, maintenance, skip-changelog

#852 Redirect users to the forum if they have questions
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: maintenance, skip-changelog

#854 Reorder plotting functions alphabetically in index
  doc/api/index.rst
Labels: documentation, skip-changelog

#726 Add authorship policy
  AUTHORSHIP.md
Labels: good first issue, help wanted, maintenance

#858 Update forum link to pygmt specific category
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
  README.rst
  doc/install.rst
Labels: documentation

#806 Tutorial notebook explanation
  examples/tutorials/3d-perspective-image.py
  examples/tutorials/coastlines.py
  examples/tutorials/configuration.py
  examples/tutorials/contour-map.py
  examples/tutorials/earth-relief.py
  examples/tutorials/first-figure.py
  examples/tutorials/frames.py
  examples/tutorials/inset.py
  examples/tutorials/lines.py
  examples/tutorials/plot.py
  examples/tutorials/regions.py
  examples/tutorials/text.py
Labels: documentation, skip-changelog

#853 Add common alias panel (-c) to all plotting functions
  pygmt/helpers/decorators.py
  pygmt/src/basemap.py
  pygmt/src/coast.py
  pygmt/src/colorbar.py
  pygmt/src/contour.py
  pygmt/src/grdcontour.py
  pygmt/src/grdimage.py
  pygmt/src/grdview.py
  pygmt/src/image.py
  pygmt/src/legend.py
  pygmt/src/logo.py
  pygmt/src/meca.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/text.py
Labels: documentation

#861 Add dependabot to keep GitHub Actions up to date
  .github/dependabot.yml
Labels: maintenance

#862 Update the docstrings of common aliases
  pygmt/helpers/decorators.py
Labels: documentation

#866 Let GMT skip refreshing the server data files
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog

#865 Revise pygmt development installation instructions
  doc/install.rst
  setup.py
Labels: documentation

#702 Improve how PyGMT finds the GMT library
  pygmt/clib/loading.py
  pygmt/tests/test_clib_loading.py
Labels: enhancement

#875 Update formatting for install bullet list
  doc/install.rst
Labels: documentation, skip-changelog

#878 Detect ghostscript and default image viewer in FreeBSD
  pygmt/__init__.py
  pygmt/helpers/utils.py
Labels: enhancement

#877 CI: Add GMT's bin to PATH for GMT dev tests
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog

#873 Let load_earth_relief() support 'region' argument for all resolutions
  pygmt/datasets/earth_relief.py
  pygmt/tests/test_datasets.py
Labels: enhancement

#883 Add alias annotation (A) to Figure.contour()
  pygmt/src/contour.py
Labels: documentation

#857 Add affiliation and ORCID to AUTHORS.md
  AUTHORS.md
  AUTHORSHIP.md
Labels: documentation, skip-changelog

#871 Update tutorials to build faster
  examples/tutorials/3d-perspective-image.py
  examples/tutorials/earth-relief.py
  examples/tutorials/regions.py
Labels: maintenance, skip-changelog

#822 Wrap subplot using with statement
  doc/api/index.rst
  doc/index.rst
  examples/tutorials/subplots.py
  pygmt/figure.py
  pygmt/src/__init__.py
  pygmt/src/subplot.py
  pygmt/tests/test_subplot.py
Labels: feature

#882 Update the doc strings in the non-plotting modules
  pygmt/figure.py
  pygmt/src/blockmedian.py
  pygmt/src/grdcut.py
  pygmt/src/grdfilter.py
  pygmt/src/info.py
  pygmt/src/makecpt.py
  pygmt/src/surface.py
  pygmt/x2sys.py
Labels: documentation

#881 Update the docstrings in the plotting modules
  pygmt/helpers/decorators.py
  pygmt/src/basemap.py
  pygmt/src/coast.py
  pygmt/src/colorbar.py
  pygmt/src/contour.py
  pygmt/src/grdcontour.py
  pygmt/src/grdimage.py
  pygmt/src/grdview.py
  pygmt/src/image.py
  pygmt/src/inset.py
  pygmt/src/legend.py
  pygmt/src/logo.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/text.py
Labels: documentation

#898 Add NSF grant EAR-1948603 to list of funding support
  README.rst
  doc/overview.rst
Labels: documentation, skip-changelog

#899 Update affiliation in AUTHORS.md
  AUTHORS.md
Labels: documentation, skip-changelog

#887 Changelog entry for v0.3.0
  README.rst
  doc/_static/version_switch.js
  doc/changes.rst
Labels: skip-changelog

#906 CI: Run tests in a single CI job (Ubuntu + Python 3.9) for draft PRs
  .github/workflows/ci_tests.yaml
  MAINTENANCE.md
Labels: maintenance

#910 Fix bug that stops Figure.coast from plotting with only dcw
  pygmt/src/coast.py
Labels: bug

#915 Add meghanrjones to AUTHORS.md
  AUTHORS.md
Labels: maintenance, skip-changelog

#900 Ensure proper non-dev version string when publishing to PyPI
  .github/workflows/publish-to-pypi.yml
Labels: maintenance

#918 Update "setting up your environment" in CONTRIBUTING.md #913
  CONTRIBUTING.md
Labels: maintenance, skip-changelog

#812 Move requirements-dev.txt dependencies to environment.yml
  .github/workflows/ci_tests.yaml
  MAINTENANCE.md
  environment.yml
  requirements-dev.txt
  requirements.txt
Labels: maintenance

#926 Small changes to PyData reference in README
  README.rst
Labels: documentation, skip-changelog

#919 Improve the gallery example for datetime inputs
  examples/gallery/plot/datetime-inputs.py
Labels: documentation

#925 Improve the error message for loading a old version of the GMT library
  pygmt/clib/loading.py
  pygmt/tests/test_clib_loading.py
Labels: maintenance

#931 Remove nbsphinx extension
  doc/_templates/breadcrumbs.html
  doc/conf.py
  environment.yml
Labels: maintenance

#930 Improve docstring of x2sys_init and x2sys_cross
  pygmt/x2sys.py
Labels: documentation, skip-changelog

#890 Add a gallery example showing different vector heads and tails
  examples/gallery/line/vector-heads-tails.py
Labels: documentation

#940 Fix old references from gmt to pygmt
  pygmt/clib/session.py
  pygmt/figure.py
Labels: maintenance, skip-changelog

#947 Disable pylint 2.7.0 duplicate-code warning
  .pylintrc
Labels: maintenance, skip-changelog

#944 Fix a typo in README
  README.rst
Labels: documentation, skip-changelog

#938 Update web font to Atkinson Hyperlegible
  doc/_static/fonts/Atkinson-Hyperlegible-Bold-102a.woff2
  doc/_static/fonts/Atkinson-Hyperlegible-BoldItalic-102a.woff2
  doc/_static/fonts/Atkinson-Hyperlegible-Italic-102a.woff2
  doc/_static/fonts/Atkinson-Hyperlegible-Regular-102a.woff2
  doc/_static/style.css
Labels: documentation

#939 Format equation in surface docstring
  pygmt/src/surface.py
Labels: documentation, skip-changelog

#634 Add a workflow checking links in plaintext and HTML files
  .github/workflows/check-links.yml
Labels: maintenance

#951 Move x2sys.py to src folder and split it into x2sys_init and x2sys_cross
  pygmt/__init__.py
  pygmt/src/__init__.py
  pygmt/src/x2sys_cross.py
  pygmt/src/x2sys_init.py
Labels: maintenance, skip-changelog

#953 Fix typo in tutorials
  examples/tutorials/3d-perspective-image.py
  examples/tutorials/coastlines.py
  examples/tutorials/configuration.py
  examples/tutorials/contour-map.py
  examples/tutorials/earth-relief.py
  examples/tutorials/first-figure.py
  examples/tutorials/frames.py
  examples/tutorials/inset.py
  examples/tutorials/lines.py
  examples/tutorials/plot.py
  examples/tutorials/regions.py
  examples/tutorials/text.py
Labels: documentation, skip-changelog

#954 Update docstrings links for return classes
  pygmt/src/blockmedian.py
  pygmt/src/grdcut.py
  pygmt/src/grdfilter.py
  pygmt/src/grdtrack.py
  pygmt/src/info.py
Labels: documentation, skip-changelog

#956 Update plotting module docstrings to use parameter vs. argument
  pygmt/src/blockmedian.py
  pygmt/src/coast.py
  pygmt/src/grd2cpt.py
  pygmt/src/grdinfo.py
  pygmt/src/text.py
Labels: documentation, skip-changelog

#941 Write changelog in markdown using MyST
  .github/release-drafter.yml
  doc/changes.md
  doc/changes.rst
  doc/conf.py
  environment.yml
Labels: documentation

#943 Replace argument with parameter in gallery examples and tutorials
  examples/gallery/coast/borders.py
  examples/gallery/coast/land_and_water.py
  examples/gallery/grid/grdview_surface.py
  examples/gallery/grid/track_sampling.py
  examples/gallery/line/line-custom-cpt.py
  examples/gallery/line/linestyles.py
  examples/gallery/plot/colorbar.py
  examples/gallery/plot/image.py
  examples/gallery/plot/legend.py
  examples/gallery/plot/meca.py
  examples/gallery/plot/multi-parameter-symbols.py
  examples/gallery/plot/points-transparency.py
  examples/gallery/plot/points.py
  examples/gallery/plot/scatter3d.py
  examples/projections/README.txt
  examples/projections/nongeo/cartesian_linear.py
  examples/tutorials/3d-perspective-image.py
  examples/tutorials/first-figure.py
  examples/tutorials/frames.py
  examples/tutorials/inset.py
  examples/tutorials/lines.py
  examples/tutorials/plot.py
  examples/tutorials/regions.py
  examples/tutorials/text.py
Labels: documentation, skip-changelog

#952 Open figures using the associated application on Windows
  pygmt/helpers/utils.py
Labels: enhancement

#957 Use short affiliations in AUTHORS.md
  AUTHORS.md
Labels: documentation, skip-changelog

#959 Improve the .gitignore file
  .gitignore
Labels: maintenance, skip-changelog

#872 Add comprehensive tests for pygmt.clib.loading.clib_full_names
  pygmt/clib/loading.py
  pygmt/tests/test_clib_loading.py
Labels: maintenance

#964 Use Vercel action for continuous documentation
  .github/workflows/continuous-documentation.yml
  MAINTENANCE.md
  package.json
  vercel.json
Labels: maintenance

#969 Disable pull_request_target for the vercel action
  .github/workflows/continuous-documentation.yml
Labels: maintenance, skip-changelog

#970 Fix three tests failing with GMT dev version
  pygmt/tests/baseline/test_basemap_aliases.png
  pygmt/tests/baseline/test_basemap_winkel_tripel.png
  pygmt/tests/baseline/test_plot_projection.png
  pygmt/tests/test_basemap.py
  pygmt/tests/test_plot.py
Labels: maintenance, skip-changelog

#965 Check invalid combinations of resolution and registration in load_earth_relief()
  pygmt/datasets/earth_relief.py
  pygmt/tests/test_datasets.py
Labels: bug

#973 Revert the migration from Vercel App to Vercel action
  .github/workflows/continuous-documentation.yml
  MAINTENANCE.md
  package.json
  vercel.json
Labels: maintenance, skip-changelog

#974 Catch subprocess.CalledProcessError if 'gmt --show-library' fails
  pygmt/clib/loading.py
Labels: bug, skip-changelog

#979 Fix links of GitHub Actions in README.rst
  README.rst
Labels: maintenance, skip-changelog

#978 Separate tests of tutorial dataset and earth_relief dataset into two files
  pygmt/tests/test_datasets_earth_relief.py
  pygmt/tests/test_datasets_tutorial.py
Labels: maintenance, skip-changelog

#980 Add description for more workflows
  MAINTENANCE.md
Labels: maintenance, skip-changelog
