Repository GenericMappingTools/pygmt, pull requests merged in 2021-09, with the labels that each got.

#1469 Add gallery example for grdlandmask
  examples/gallery/images/grdlandmask.py
Labels: documentation

#1475 Allow passing a list to the 'incols' parameter for blockm, grdtrack and text
  pygmt/src/blockm.py
  pygmt/src/grdtrack.py
  pygmt/src/text.py
Labels: bug

#1458 pygmt.surface: Deprecate parameter "outfile" to "outgrid" (remove in v0.7.0)
  pygmt/src/surface.py
  pygmt/tests/test_surface.py
Labels: deprecation, final review call

#1439 Add pygmt.load_dataarray function and refactor modules that return None or xarray.dataarray
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/datasets/earth_relief.py
  pygmt/io.py
  pygmt/src/grdclip.py
  pygmt/src/grdcut.py
  pygmt/src/grdfill.py
  pygmt/src/grdfilter.py
  pygmt/src/grdgradient.py
  pygmt/src/grdlandmask.py
  pygmt/src/grdproject.py
  pygmt/src/grdsample.py
  pygmt/src/surface.py
  pygmt/src/xyz2grd.py
Labels: feature, final review call

#1481 Add geopandas as dependency in CI docs test
  .github/workflows/ci_docs.yml
Labels: maintenance, skip-changelog

#1383 Wrap sphdistance
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/src/__init__.py
  pygmt/src/sphdistance.py
  pygmt/tests/test_sphdistance.py
Labels: feature, final review call

#1474 Add gallery example showing usage of line objects from a geopandas.GeoDataFrame
  examples/gallery/lines/roads.py
Labels: documentation

#1484 Raise an error for zero increment grid
  pygmt/clib/conversion.py
  pygmt/tests/test_clib.py
Labels: bug, final review call

#1382 Add support for passing pathlib.Path objects as filenames
  pygmt/clib/session.py
  pygmt/helpers/utils.py
  pygmt/tests/test_info.py
Labels: enhancement, final review call

#1502 Add missing aliases to pygmt.Figure.plot
  pygmt/src/plot.py
Labels: documentation, final review call

#1499 Add missing aliases to pygmt.grdtrack
  pygmt/src/grdtrack.py
Labels: documentation

#1503 Add missing aliases to pygmt.Figure.plot3d
  pygmt/src/plot3d.py
Labels: documentation

#1501 Add missing aliases to pygmt.surface
  pygmt/src/surface.py
Labels: documentation

#1497 Add missing aliases to pygmt.Figure.velo
  pygmt/src/velo.py
Labels: documentation

#1504 Figure.wiggle: Deprecate parameter "columns" to "incols" (remove in v0.7.0)
  pygmt/src/wiggle.py
  pygmt/tests/test_wiggle.py
Labels: deprecation

#1498 Add missing aliases to pygmt.Figure.wiggle
  pygmt/src/wiggle.py
Labels: documentation, final review call

#1500 Add missing aliases to pygmt.blockmean and pygmt.blockmedian
  pygmt/src/blockm.py
Labels: documentation

#1456 Wrap blockmode
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/src/__init__.py
  pygmt/src/blockm.py
  pygmt/tests/test_blockm.py
Labels: feature

#1478 Raise GMTInvalidInput exception when required z is missing
  pygmt/clib/session.py
  pygmt/helpers/utils.py
  pygmt/src/blockm.py
  pygmt/src/contour.py
  pygmt/src/plot3d.py
  pygmt/src/surface.py
  pygmt/src/wiggle.py
  pygmt/tests/test_clib.py
  pygmt/tests/test_contour.py
  pygmt/tests/test_plot3d.py
  pygmt/tests/test_surface.py
Labels: enhancement

#1428 Add gallery example for grdgradient
  examples/gallery/images/grdgradient.py
  pygmt/helpers/testing.py
Labels: documentation, final review call

#1517 Fix pylint 2.11 consider-using-f-string checker errors
  doc/conf.py
  pygmt/__init__.py
  pygmt/clib/session.py
  pygmt/figure.py
  pygmt/helpers/decorators.py
  pygmt/helpers/testing.py
  pygmt/src/config.py
  pygmt/src/grd2cpt.py
  pygmt/src/legend.py
  pygmt/src/makecpt.py
  pygmt/src/meca.py
  pygmt/src/surface.py
  pygmt/src/x2sys_cross.py
  pygmt/tests/test_clib.py
Labels: maintenance, skip-changelog

#1494 Remove deprecated codecov dependency from CI
  .github/workflows/ci_tests.yaml
  README.rst
  doc/maintenance.md
  environment.yml
Labels: maintenance, final review call

#841 Use mamba to install Continuous Integration dependencies
  .github/workflows/cache_data.yaml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, final review call

#1518 Add tests for load_dataarray to increase code coverage
  pygmt/tests/test_io.py
Labels: maintenance, skip-changelog, final review call

#1525 Use pytest.importorskip for sphinx_gallery test
  pygmt/sphinx_gallery.py
  pygmt/tests/test_sphinx_gallery.py
Labels: maintenance, skip-changelog, final review call

#1524 Support 1d array for outcols in grdtrack and blockm functions
  pygmt/src/blockm.py
  pygmt/src/grdtrack.py
Labels: enhancement, skip-changelog, final review call

#1519 Fix common options in blockm, surface, histogram, rose, and grdtrack
  pygmt/src/blockm.py
  pygmt/src/grdtrack.py
  pygmt/src/histogram.py
  pygmt/src/rose.py
  pygmt/src/surface.py
Labels: bug, skip-changelog

#1420 Add Mars dataset
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/samples.py
  pygmt/tests/test_datasets_samples.py
Labels: feature, final review call

#1496 Make IPython partially optional on CI to increase test coverage of figure.py
  .github/workflows/ci_tests.yaml
  pygmt/src/inset.py
  pygmt/tests/test_figure.py
  pygmt/tests/test_sphinx_gallery.py
Labels: maintenance, final review call

#1523 Let required_z check work on xarray.Dataset inputs
  pygmt/clib/session.py
  pygmt/helpers/utils.py
  pygmt/tests/test_blockm.py
  pygmt/tests/test_clib.py
Labels: bug, skip-changelog, final review call

#1507 Show link checker report date in issue title and exclude mail address
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog

#1455 Expand table-like input options for pygmt.surface
  pygmt/src/surface.py
Labels: enhancement, final review call

#1522 Add a gallery example showing the usage of text symbols
  examples/gallery/symbols/text_symbols.py
Labels: documentation

#1532 Add @mars370d.txt remote file to download_test_data
  pygmt/helpers/testing.py
Labels: maintenance, skip-changelog

#1284 Wrap grd2xyz
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/src/__init__.py
  pygmt/src/grd2xyz.py
  pygmt/tests/test_grd2xyz.py
Labels: feature, final review call

#1531 Expand table-like input options for Figure.contour
  pygmt/src/contour.py
  pygmt/tests/test_contour.py
Labels: enhancement

#1379 Wrap nearneighbor
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/src/__init__.py
  pygmt/src/nearneighbor.py
  pygmt/tests/test_nearneighbor.py
Labels: feature, final review call

#1544 Pin dvc to 2.3.0 as a workaround to fix the recent dvc pulling issue
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  environment.yml
Labels: maintenance, skip-changelog

#1538 pygmt.info: Deprecate parameter "table" to "data" (remove in v0.7.0)
  pygmt/src/info.py
  pygmt/tests/test_geopandas.py
  pygmt/tests/test_info.py
Labels: deprecation

#1541 Add a decorator to raise a FutureWarning when positional arguments are passed for functions that changed parameter orders
  pygmt/helpers/__init__.py
  pygmt/helpers/decorators.py
Labels: maintenance, skip-changelog

#1542 Update the release checklist to remove deprecations and related tests
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: maintenance, skip-changelog

#1545 pygmt.xyz2grd: Rename the parameter 'table' to 'data'
  pygmt/src/xyz2grd.py
  pygmt/tests/test_xyz2grd.py
Labels: maintenance, skip-changelog

#1540 Figure.histogram: Deprecate parameter "table" to "data" (remove in v0.7.0)
  pygmt/src/histogram.py
  pygmt/tests/test_histogram.py
Labels: deprecation

#1434 Wrap sph2grd
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/helpers/testing.py
  pygmt/src/__init__.py
  pygmt/src/sph2grd.py
  pygmt/tests/test_sph2grd.py
Labels: feature

#1551 Update the baseline image for pygmt/test/test_plot.py:test_plot_matrix
  pygmt/tests/baseline/test_plot_matrix.png.dvc
  pygmt/tests/test_plot.py
Labels: maintenance, skip-changelog

#1552 Remove unused global variable 'gmt_version' from tests
  pygmt/tests/test_basemap.py
  pygmt/tests/test_clib.py
  pygmt/tests/test_clib_put_strings.py
Labels: maintenance, skip-changelog

#1491 Expand table-like input options for sphdistance
  doc/api/index.rst
  pygmt/src/sphdistance.py
  pygmt/tests/test_sphdistance.py
Labels: enhancement, skip-changelog, final review call
