Repository GenericMappingTools/pygmt, pull requests merged in 2021-11, with the labels that each got.

#1604 Fix sphinx reference in pygmt/src/sphdistance.py
  pygmt/src/sphdistance.py
Labels: documentation, skip-changelog

#1608 Mark two grdtrack tests as xfail due to upstream GMT 6.3 fixes
  pygmt/tests/test_grdtrack.py
Labels: maintenance, skip-changelog

#1615 Add MaunaLoa_CO2.txt to cached files
  pygmt/helpers/testing.py
Labels: maintenance, skip-changelog

#1601 Add alias for blockmean's -S parameter
  pygmt/src/blockm.py
Labels: documentation, final review call

#1611 Fix missing gcmt convention keys in pygmt.meca
  pygmt/src/meca.py
  pygmt/tests/baseline/test_meca_gcmt_convention.png.dvc
  pygmt/tests/test_meca.py
Labels: bug, final review call

#1610 Add instructions for reporting upstream bugs to contributing.md
  doc/contributing.md
Labels: maintenance

#1603 Reorganize tutorial section in the documentation sidebar
  doc/conf.py
  doc/contributing.md
  doc/index.rst
  examples/tutorials/README.txt
  examples/tutorials/advanced/3d_perspective_image.py
  examples/tutorials/advanced/README.txt
  examples/tutorials/advanced/configuration.py
  examples/tutorials/advanced/contour_map.py
  examples/tutorials/advanced/date_time_charts.py
  examples/tutorials/advanced/earth_relief.py
  examples/tutorials/advanced/insets.py
  examples/tutorials/advanced/subplots.py
  examples/tutorials/advanced/vectors.py
  examples/tutorials/basics/README.txt
  examples/tutorials/basics/coastlines.py
  examples/tutorials/basics/first_figure.py
  examples/tutorials/basics/frames.py
  examples/tutorials/basics/lines.py
  examples/tutorials/basics/plot.py
  examples/tutorials/basics/regions.py
  examples/tutorials/basics/text.py
  pygmt/helpers/decorators.py
  pygmt/src/grdview.py
Labels: documentation, final review call

#1568 Refactor pygmt.surface tests
  pygmt/helpers/testing.py
  pygmt/tests/test_surface.py
Labels: maintenance, skip-changelog, final review call

#1598 Add gallery example to showcase blockmean
  examples/gallery/histograms/blockm.py
Labels: documentation, final review call

#1618 Allow users to set the waiting time when displaying a preview image using an external viewer
  pygmt/figure.py
  pygmt/helpers/utils.py
Labels: enhancement, final review call

#1628 Fix a link in the contributing guide
  doc/contributing.md
Labels: documentation, maintenance, skip-changelog

#1626 Remove disclaimer from install.rst
  doc/install.rst
  doc/overview.rst
Labels: documentation, skip-changelog
