Repository GenericMappingTools/pygmt, pull requests merged in 2021-06, with the labels that each got.

#1312 Allow pygmt.which to accept a list of filenames as input
  pygmt/src/which.py
  pygmt/tests/test_which.py
Labels: enhancement

#1310 Add download_test_data to download data files used in tests
  .github/workflows/cache_data.yaml
  pygmt/helpers/testing.py
Labels: maintenance

#1314 Add regression test for grdimage plotting an xarray.DataArray grid subset
  pygmt/tests/baseline/test_grdimage_global_subset.png.dvc
  pygmt/tests/test_grdimage.py
Labels: final review call, maintenance

#1193 Add a tutorial for datetime data
  doc/index.rst
  examples/tutorials/date_time_charts.py
Labels: documentation

#1321 Bump the minimum required GMT version to 6.2.0
  .github/workflows/cache_data.yaml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  doc/install.rst
  environment.yml
  pygmt/clib/session.py
  pygmt/tests/test_clib.py
Labels: maintenance

#1304 Remove xfail on grdtrack tests for GMT 6.2.0
  pygmt/tests/test_grdtrack.py
Labels: maintenance, skip-changelog

#1323 Remove xfail on makecpt tests for GMT 6.2.0
  pygmt/tests/test_makecpt.py
Labels: maintenance, skip-changelog

#1303 Figure.contour: Deprecate parameter "columns" to "incols" (remove in v0.6.0)
  pygmt/src/contour.py
  pygmt/tests/test_contour.py
Labels: deprecation

#1322 Update colorbar, inset, legend and logo baseline images for GMT 6.2.0
  pygmt/tests/baseline/test_colorbar_box.png.dvc
  pygmt/tests/baseline/test_inset_aliases.png.dvc
  pygmt/tests/baseline/test_inset_context_manager.png.dvc
  pygmt/tests/baseline/test_legend_position.png.dvc
  pygmt/tests/baseline/test_logo_on_a_map.png.dvc
  pygmt/tests/test_plot3d.py
Labels: maintenance, skip-changelog

#1317 Add a workflow to upload baseline images as a release asset
  .github/ISSUE_TEMPLATE/release_checklist.md
  .github/workflows/release-baseline-images.yml
  doc/maintenance.md
Labels: maintenance

#1324 Fix rose tests for GMT 6.2.0
  pygmt/tests/test_rose.py
Labels: maintenance

#750 Allow passing xr.DataArray as shading to grdimage
  pygmt/src/grdimage.py
  pygmt/tests/test_grdimage.py
Labels: enhancement

#1116 Let Figure.savefig support filenames with spaces
  pygmt/figure.py
  pygmt/tests/test_figure.py
Labels: bug

#1337 plot: Fix 'columns' to 'incols' in docstrings
  pygmt/src/plot.py
Labels: documentation, skip-changelog

#1283 Update grdfill parameters for GMT 6.2.0
  pygmt/src/grdfill.py
  pygmt/tests/test_grdfill.py
Labels: enhancement, final review call, skip-changelog

#1282 Support tab completion in Jupyter by inserting aliases into the method signature
  pygmt/helpers/decorators.py
Labels: enhancement, final review call

#1316 Raise a warning for the use of short-form parameters when long-forms are available
  pygmt/helpers/decorators.py
Labels: deprecation

#1335 Move contributing guide details to website and rename two sections
  CONTRIBUTING.md
  doc/conf.py
  doc/contributing.md
  doc/index.rst
Labels: documentation, final review call

#1040 Figure.plot3d: Deprecate parameter "columns" to "incols" (remove in v0.6.0)
  pygmt/src/plot3d.py
  pygmt/tests/test_plot3d.py
Labels: deprecation

#1331 Reinstall optional geopandas dependency on CI tests
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  environment.yml
Labels: final review call, maintenance

#1319 Allow x/y/z input for blockmedian and blockmean
  pygmt/src/blockm.py
  pygmt/tests/test_blockmean.py
  pygmt/tests/test_blockmedian.py
Labels: enhancement, final review call

#1325 Specify rectangle's width and height via style parameter in multi-parameter symbols example
  examples/gallery/symbols/multi_parameter_symbols.py
Labels: documentation, final review call

#1329 Allow pandas.Series inputs to fig.histogram and pygmt.info
  pygmt/clib/session.py
  pygmt/tests/test_histogram.py
  pygmt/tests/test_info.py
Labels: bug, final review call

#1341 Changelog entry for v0.4.0
  README.rst
  doc/_static/version_switch.js
  doc/changes.md
Labels: skip-changelog

#1355 NEP29: Test PyGMT on NumPy 1.21
  .github/workflows/ci_tests.yaml
Labels: maintenance

#1346 Update release documentation based on review comments from v0.4.0
  .github/ISSUE_TEMPLATE/release_checklist.md
  AUTHORSHIP.md
  doc/maintenance.md
Labels: documentation, final review call, skip-changelog

#1359 Mark two velo tests as xfail due to upstream fixes
  pygmt/tests/test_velo.py
Labels: maintenance, skip-changelog

#1357 Move reused ship_data import to pytest fixture in test_surface.py
  pygmt/tests/test_surface.py
Labels: maintenance, skip-changelog

#1353 Move reused data to pytest fixtures in test_grdtrack.py
  pygmt/tests/test_grdtrack.py
Labels: maintenance, skip-changelog

#1348 Add a gallery example showing individual custom symbols
  examples/gallery/symbols/custom_symbols.py
Labels: documentation

#1363 Fixes some typos
  doc/maintenance.md
  examples/gallery/embellishments/solar.py
  examples/tutorials/date_time_charts.py
  examples/tutorials/vectors.py
  pygmt/src/histogram.py
Labels: documentation, skip-changelog

#1343 Add common alias "verbose" (V) to grdlandmask and savefig
  pygmt/figure.py
  pygmt/src/grdlandmask.py
Labels: enhancement
