Repository GenericMappingTools/pygmt, pull requests merged in 2021-12, with the labels that each got.

#1631 Add html-noplot target to doc/Makefile
  doc/Makefile
Labels: maintenance, skip-changelog

#1640 Update Dongdong Tian's affiliation
  AUTHORS.md
  CITATION.cff
Labels: maintenance, skip-changelog

#1642 Fix pylint 2.12 consider-iterating-dictionary checker errors
  pygmt/helpers/decorators.py
  pygmt/src/grd2cpt.py
  pygmt/src/grdclip.py
  pygmt/src/grdcut.py
  pygmt/src/grdfill.py
  pygmt/src/grdfilter.py
  pygmt/src/grdgradient.py
  pygmt/src/grdlandmask.py
  pygmt/src/grdproject.py
  pygmt/src/grdsample.py
  pygmt/src/meca.py
  pygmt/src/nearneighbor.py
  pygmt/src/sph2grd.py
  pygmt/src/sphdistance.py
  pygmt/src/sphinterpolate.py
  pygmt/src/surface.py
  pygmt/src/text.py
  pygmt/src/xyz2grd.py
Labels: maintenance, skip-changelog

#1629 Add issue template for wrapping new module
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/module_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: maintenance, skip-changelog, final review call

#1630 Add issue template with checklist for bumping the minimum required GMT version
  .github/ISSUE_TEMPLATE/bump_gmt_checklist.md
Labels: maintenance, skip-changelog, final review call

#1647 Exclude an invalid link from links checking workflow
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog

#1645 Unpin GMT dev version from conda-forge/label/dev on Windows
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog, final review call

#1648 Update text symbol gallery example
  examples/gallery/symbols/text_symbols.py
Labels: documentation

#1650 Use frame="a" in colorbars_multiple.py
  examples/gallery/embellishments/colorbars_multiple.py
Labels: documentation, skip-changelog

#1649 Bump the minimum required GMT version to 6.3.0
  .github/workflows/cache_data.yaml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  README.rst
  doc/install.rst
  environment.yml
  pygmt/clib/session.py
  pygmt/tests/test_clib.py
Labels: maintenance

#1653 Update baseline image for test_inset_context_manager
  pygmt/tests/baseline/test_inset_context_manager.png.dvc
Labels: maintenance, skip-changelog

#1654 Update test_legend_specfile baseline for GMT 6.3
  pygmt/tests/baseline/test_legend_specfile.png.dvc
Labels: maintenance, skip-changelog

#1655 Update test_rose_bools.png.dvc for GMT 6.3
  pygmt/tests/baseline/test_rose_bools.png.dvc
Labels: maintenance, skip-changelog

#1658 Update fig.basemap baseline images for GMT 6.3.0
  pygmt/tests/baseline/test_basemap_compass.png.dvc
  pygmt/tests/baseline/test_basemap_rose.png.dvc
Labels: maintenance, skip-changelog

#1657 Update xfail velo tests for GMT 6.3
  pygmt/tests/baseline/test_velo_numpy_array_numeric_only.png.dvc
  pygmt/tests/baseline/test_velo_pandas_dataframe.png.dvc
  pygmt/tests/test_velo.py
Labels: maintenance, skip-changelog

#1661 Add conda badge to README
  README.rst
Labels: documentation, skip-changelog

#1667 Remove projection alias from grdsample
  pygmt/src/grdsample.py
Labels: bug, skip-changelog

#1659 Update deprecated -JG syntax
  examples/projections/azim/azim_general_perspective.py
  examples/projections/table/README.txt
Labels: maintenance

#1669 Set timeout limit for CI tests
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog, final review call

#1643 Add more sections to the API docs
  doc/api/index.rst
Labels: documentation

#1670 Update deprecated -g common option syntax
  pygmt/helpers/decorators.py
Labels: maintenance, final review call

#1607 Update the starter tutorial introduction
  .gitignore
  doc/Makefile
  doc/conf.py
  doc/index.rst
  examples/get-started/README.txt
  examples/get-started/first_figure.py
  examples/tutorials/basics/first_figure.py
Labels: documentation

#1675 NEP29: Set minimum required version to NumPy 1.19+
  .github/workflows/ci_tests.yaml
  README.rst
  doc/install.rst
  environment.yml
  requirements.txt
  setup.py
Labels: deprecation

#1676 NEP29: Set minimum required version to Python 3.8+
  .github/workflows/ci_tests.yaml
  doc/install.rst
  setup.py
Labels: deprecation, final review call

#1674 Replace pkg_resources with importlib.metadata
  pygmt/__init__.py
Labels: maintenance, final review call

#1680 Use xarray.testing rather than pygmt.grdinfo in grdlandmask tests
  pygmt/tests/test_grdlandmask.py
Labels: maintenance, skip-changelog

#1677 Use xarray.testing rather than pygmt.grdinfo in grdfill tests
  pygmt/tests/test_grdfill.py
Labels: maintenance, skip-changelog, final review call

#1577 Use Python 3.10 in Continuous Integration tests
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests_dev.yaml
  README.rst
Labels: maintenance
