Repository GenericMappingTools/pygmt, pull requests merged in 2021-04, with the labels that each got.

#1096 Migrate Figure.basemap tests to dvc
  pygmt/tests/baseline/test_basemap.png
  pygmt/tests/baseline/test_basemap.png.dvc
  pygmt/tests/baseline/test_basemap_compass.png.dvc
  pygmt/tests/baseline/test_basemap_list_region.png
  pygmt/tests/baseline/test_basemap_loglog.png
  pygmt/tests/baseline/test_basemap_loglog.png.dvc
  pygmt/tests/baseline/test_basemap_map_scale.png.dvc
  pygmt/tests/baseline/test_basemap_polar.png
  pygmt/tests/baseline/test_basemap_polar.png.dvc
  pygmt/tests/baseline/test_basemap_power_axis.png
  pygmt/tests/baseline/test_basemap_power_axis.png.dvc
  pygmt/tests/baseline/test_basemap_rose.png.dvc
  pygmt/tests/baseline/test_basemap_winkel_tripel.png.dvc
  pygmt/tests/test_basemap.py
Labels: maintenance, skip-changelog

#1155 Remove the extra period from the copyright information in the footer
  doc/conf.py
Labels: documentation, skip-changelog

#1142 Migrate Figure.plot tests to dvc
  pygmt/tests/baseline/test_plot_colors.png
  pygmt/tests/baseline/test_plot_colors.png.dvc
  pygmt/tests/baseline/test_plot_colors_sizes.png
  pygmt/tests/baseline/test_plot_colors_sizes.png.dvc
  pygmt/tests/baseline/test_plot_colors_sizes_proj.png
  pygmt/tests/baseline/test_plot_colors_sizes_proj.png.dvc
  pygmt/tests/baseline/test_plot_datetime.png
  pygmt/tests/baseline/test_plot_datetime.png.dvc
  pygmt/tests/baseline/test_plot_from_file.png
  pygmt/tests/baseline/test_plot_from_file.png.dvc
  pygmt/tests/baseline/test_plot_lines_with_arrows.png
  pygmt/tests/baseline/test_plot_lines_with_arrows.png.dvc
  pygmt/tests/baseline/test_plot_matrix.png
  pygmt/tests/baseline/test_plot_matrix.png.dvc
  pygmt/tests/baseline/test_plot_matrix_color.png
  pygmt/tests/baseline/test_plot_matrix_color.png.dvc
  pygmt/tests/baseline/test_plot_projection.png.dvc
  pygmt/tests/baseline/test_plot_red_circles.png
  pygmt/tests/baseline/test_plot_red_circles.png.dvc
  pygmt/tests/baseline/test_plot_scalar_xy.png
  pygmt/tests/baseline/test_plot_scalar_xy.png.dvc
  pygmt/tests/baseline/test_plot_sizes.png
  pygmt/tests/baseline/test_plot_sizes.png.dvc
  pygmt/tests/baseline/test_plot_sizes_colors_transparencies.png.dvc
  pygmt/tests/baseline/test_plot_transparency.png.dvc
  pygmt/tests/baseline/test_plot_varying_intensity.png.dvc
  pygmt/tests/baseline/test_plot_varying_transparency.png.dvc
  pygmt/tests/baseline/test_plot_vectors.png
  pygmt/tests/baseline/test_plot_vectors.png.dvc
  pygmt/tests/test_plot.py
Labels: maintenance, skip-changelog

#794 Wrap rose
  doc/api/index.rst
  examples/gallery/embellishments/rose.py
  pygmt/figure.py
  pygmt/src/__init__.py
  pygmt/src/rose.py
  pygmt/tests/baseline/test_rose_2d_array_multiple.png.dvc
  pygmt/tests/baseline/test_rose_2d_array_single.png.dvc
  pygmt/tests/baseline/test_rose_bools.png.dvc
  pygmt/tests/baseline/test_rose_data_file.png.dvc
  pygmt/tests/baseline/test_rose_no_sectors.png.dvc
  pygmt/tests/baseline/test_rose_plot_data_using_cpt.png.dvc
  pygmt/tests/baseline/test_rose_plot_with_transparency.png.dvc
  pygmt/tests/test_rose.py
Labels: feature

#1161 Add Abhishek Anant SIngh to AUTHORS.md
  AUTHORS.md
Labels: maintenance, skip-changelog

#1143 Migrate Figure.colorbar tests to use dvc
  pygmt/tests/baseline/test_colorbar_box.png
  pygmt/tests/baseline/test_colorbar_box.png.dvc
  pygmt/tests/baseline/test_colorbar_box_with_clearance.png
  pygmt/tests/baseline/test_colorbar_box_with_fill.png
  pygmt/tests/baseline/test_colorbar_box_with_fill.png.dvc
  pygmt/tests/baseline/test_colorbar_box_with_offset_background.png
  pygmt/tests/baseline/test_colorbar_box_with_pen.png
  pygmt/tests/baseline/test_colorbar_box_with_rounded_corners.png
  pygmt/tests/baseline/test_colorbar_box_with_secondary_border.png
  pygmt/tests/baseline/test_colorbar_positioned_using_justification_code.png
  pygmt/tests/baseline/test_colorbar_positioned_using_map_coordinates.png
  pygmt/tests/baseline/test_colorbar_positioned_using_normalized_coords.png
  pygmt/tests/baseline/test_colorbar_scaled_z_values.png
  pygmt/tests/baseline/test_colorbar_scaled_z_values.png.dvc
  pygmt/tests/baseline/test_colorbar_shading_boolean.png.dvc
  pygmt/tests/baseline/test_colorbar_shading_list.png.dvc
  pygmt/tests/baseline/test_colorbar_truncated_to_zlow_zhigh.png
  pygmt/tests/baseline/test_colorbar_truncated_to_zlow_zhigh.png.dvc
  pygmt/tests/baseline/test_colorbar_using_paper_coordinates.png
  pygmt/tests/baseline/test_colorbar_using_paper_coordinates_horizontal.png
  pygmt/tests/test_colorbar.py
Labels: maintenance, skip-changelog

#1158 Migrate Figure.grdcontour tests to dvc
  pygmt/tests/baseline/test_grdcontour.png
  pygmt/tests/baseline/test_grdcontour.png.dvc
  pygmt/tests/baseline/test_grdcontour_file.png
  pygmt/tests/baseline/test_grdcontour_file.png.dvc
  pygmt/tests/baseline/test_grdcontour_interval_file_full_opts.png
  pygmt/tests/baseline/test_grdcontour_interval_file_full_opts.png.dvc
  pygmt/tests/baseline/test_grdcontour_labels.png
  pygmt/tests/baseline/test_grdcontour_labels.png.dvc
  pygmt/tests/baseline/test_grdcontour_slice.png
  pygmt/tests/baseline/test_grdcontour_slice.png.dvc
  pygmt/tests/test_grdcontour.py
Labels: maintenance, skip-changelog

#1162 Migrate pygmt.grd2cpt tests to use dvc
  pygmt/tests/baseline/test_grd2cpt.png.dvc
  pygmt/tests/test_grd2cpt.py
Labels: maintenance, skip-changelog

#1070 Add a tutorial for plotting vectors
  doc/index.rst
  examples/tutorials/vectors.py
Labels: documentation

#1170 Migrate Figure.subplot tests to dvc
  pygmt/tests/baseline/test_subplot_autolabel_margins_title.png.dvc
  pygmt/tests/baseline/test_subplot_basic_frame.png.dvc
  pygmt/tests/baseline/test_subplot_clearance_and_shared_xy_axis_layout.png.dvc
  pygmt/tests/baseline/test_subplot_direct.png.dvc
  pygmt/tests/test_subplot.py
Labels: maintenance, skip-changelog

#1153 Migrate Figure.meca tests to dvc
  pygmt/tests/baseline/test_meca_loc_array.png
  pygmt/tests/baseline/test_meca_loc_array.png.dvc
  pygmt/tests/baseline/test_meca_spec_1d_array.png
  pygmt/tests/baseline/test_meca_spec_1d_array.png.dvc
  pygmt/tests/baseline/test_meca_spec_2d_array.png
  pygmt/tests/baseline/test_meca_spec_2d_array.png.dvc
  pygmt/tests/baseline/test_meca_spec_dataframe.png
  pygmt/tests/baseline/test_meca_spec_dataframe.png.dvc
  pygmt/tests/baseline/test_meca_spec_dict_list.png
  pygmt/tests/baseline/test_meca_spec_dict_list.png.dvc
  pygmt/tests/baseline/test_meca_spec_dictionary.png
  pygmt/tests/baseline/test_meca_spec_dictionary.png.dvc
  pygmt/tests/baseline/test_meca_spec_file.png
  pygmt/tests/baseline/test_meca_spec_file.png.dvc
  pygmt/tests/test_meca.py
Labels: maintenance, skip-changelog

#1166 Migrate Figure.legend tests to use dvc
  pygmt/tests/baseline/test_legend_default_position.png
  pygmt/tests/baseline/test_legend_default_position.png.dvc
  pygmt/tests/baseline/test_legend_position.png
  pygmt/tests/baseline/test_legend_position.png.dvc
  pygmt/tests/baseline/test_legend_specfile.png
  pygmt/tests/baseline/test_legend_specfile.png.dvc
  pygmt/tests/test_legend.py
Labels: maintenance, skip-changelog

#1164 Migrate Figure.plot3d tests to dvc
  pygmt/tests/baseline/test_plot3d_colors.png.dvc
  pygmt/tests/baseline/test_plot3d_colors_sizes.png.dvc
  pygmt/tests/baseline/test_plot3d_colors_sizes_proj.png.dvc
  pygmt/tests/baseline/test_plot3d_from_file.png.dvc
  pygmt/tests/baseline/test_plot3d_matrix.png.dvc
  pygmt/tests/baseline/test_plot3d_matrix_color.png.dvc
  pygmt/tests/baseline/test_plot3d_projection.png.dvc
  pygmt/tests/baseline/test_plot3d_red_circles_zscale.png.dvc
  pygmt/tests/baseline/test_plot3d_red_circles_zsize.png.dvc
  pygmt/tests/baseline/test_plot3d_scalar_xyz.png.dvc
  pygmt/tests/baseline/test_plot3d_sizes.png.dvc
  pygmt/tests/baseline/test_plot3d_sizes_colors_transparencies.png.dvc
  pygmt/tests/baseline/test_plot3d_transparency.png.dvc
  pygmt/tests/baseline/test_plot3d_varying_transparency.png.dvc
  pygmt/tests/baseline/test_plot3d_vectors.png.dvc
  pygmt/tests/test_plot3d.py
Labels: maintenance, skip-changelog

#1167 Migrate Figure.text tests to dvc
  pygmt/tests/baseline/test_text_angle_30.png
  pygmt/tests/baseline/test_text_angle_30.png.dvc
  pygmt/tests/baseline/test_text_angle_font_justify_from_textfile.png
  pygmt/tests/baseline/test_text_angle_font_justify_from_textfile.png.dvc
  pygmt/tests/baseline/test_text_fill.png
  pygmt/tests/baseline/test_text_fill.png.dvc
  pygmt/tests/baseline/test_text_font_bold.png
  pygmt/tests/baseline/test_text_font_bold.png.dvc
  pygmt/tests/baseline/test_text_input_multiple_filenames.png
  pygmt/tests/baseline/test_text_input_multiple_filenames.png.dvc
  pygmt/tests/baseline/test_text_input_remote_filename.png
  pygmt/tests/baseline/test_text_input_remote_filename.png.dvc
  pygmt/tests/baseline/test_text_input_single_filename.png
  pygmt/tests/baseline/test_text_input_single_filename.png.dvc
  pygmt/tests/baseline/test_text_justify_bottom_right_and_top_left.png
  pygmt/tests/baseline/test_text_justify_bottom_right_and_top_left.png.dvc
  pygmt/tests/baseline/test_text_justify_parsed_from_textfile.png
  pygmt/tests/baseline/test_text_justify_parsed_from_textfile.png.dvc
  pygmt/tests/baseline/test_text_multiple_lines_of_text.png
  pygmt/tests/baseline/test_text_multiple_lines_of_text.png.dvc
  pygmt/tests/baseline/test_text_nonstr_text.png.dvc
  pygmt/tests/baseline/test_text_pen.png
  pygmt/tests/baseline/test_text_pen.png.dvc
  pygmt/tests/baseline/test_text_position.png
  pygmt/tests/baseline/test_text_position.png.dvc
  pygmt/tests/baseline/test_text_position_offset_with_line.png
  pygmt/tests/baseline/test_text_position_offset_with_line.png.dvc
  pygmt/tests/baseline/test_text_round_clearance.png
  pygmt/tests/baseline/test_text_round_clearance.png.dvc
  pygmt/tests/baseline/test_text_single_line_of_text.png
  pygmt/tests/baseline/test_text_single_line_of_text.png.dvc
  pygmt/tests/baseline/test_text_transparency.png.dvc
  pygmt/tests/baseline/test_text_varying_transparency.png.dvc
  pygmt/tests/test_text.py
Labels: maintenance, skip-changelog

#1163 Migrate Figure.inset tests to use dvc
  pygmt/tests/baseline/test_inset_aliases.png.dvc
  pygmt/tests/baseline/test_inset_context_manager.png.dvc
  pygmt/tests/test_inset.py
Labels: maintenance, skip-changelog

#1126 Add more example code standards
  CONTRIBUTING.md
Labels: documentation, skip-changelog

#1165 Migrate pygmt.config tests to dvc
  pygmt/tests/baseline/test_config.png
  pygmt/tests/baseline/test_config.png.dvc
  pygmt/tests/baseline/test_config_font_annot.png.dvc
  pygmt/tests/baseline/test_config_font_one.png.dvc
  pygmt/tests/baseline/test_config_format_time_map.png
  pygmt/tests/baseline/test_config_format_time_map.png.dvc
  pygmt/tests/baseline/test_config_map_annot_offset.png
  pygmt/tests/baseline/test_config_map_annot_offset.png.dvc
  pygmt/tests/baseline/test_config_map_grid_cross_size.png
  pygmt/tests/baseline/test_config_map_grid_cross_size.png.dvc
  pygmt/tests/baseline/test_config_map_grid_pen.png
  pygmt/tests/baseline/test_config_map_grid_pen.png.dvc
  pygmt/tests/baseline/test_config_map_tick_length.png
  pygmt/tests/baseline/test_config_map_tick_length.png.dvc
  pygmt/tests/baseline/test_config_map_tick_pen.png
  pygmt/tests/baseline/test_config_map_tick_pen.png.dvc
  pygmt/tests/test_config.py
Labels: maintenance, skip-changelog

#1168 Migrate makecpt tests to use dvc
  pygmt/tests/baseline/test_makecpt_categorical.png.dvc
  pygmt/tests/baseline/test_makecpt_continuous.png
  pygmt/tests/baseline/test_makecpt_continuous.png.dvc
  pygmt/tests/baseline/test_makecpt_cyclic.png.dvc
  pygmt/tests/baseline/test_makecpt_plot_grid.png.dvc
  pygmt/tests/baseline/test_makecpt_plot_grid_scaled_with_series.png.dvc
  pygmt/tests/baseline/test_makecpt_plot_points.png.dvc
  pygmt/tests/baseline/test_makecpt_reverse_color_and_zsign.png
  pygmt/tests/baseline/test_makecpt_reverse_color_and_zsign.png.dvc
  pygmt/tests/baseline/test_makecpt_reverse_color_only.png
  pygmt/tests/baseline/test_makecpt_reverse_color_only.png.dvc
  pygmt/tests/baseline/test_makecpt_reverse_zsign_only.png
  pygmt/tests/baseline/test_makecpt_to_plot_grid.png
  pygmt/tests/baseline/test_makecpt_to_plot_grid_scaled_with_series.png
  pygmt/tests/baseline/test_makecpt_to_plot_points.png
  pygmt/tests/baseline/test_makecpt_truncated_at_zhigh_only.png
  pygmt/tests/baseline/test_makecpt_truncated_at_zlow_only.png
  pygmt/tests/baseline/test_makecpt_truncated_to_zlow_zhigh.png
  pygmt/tests/baseline/test_makecpt_truncated_zlow_zhigh.png.dvc
  pygmt/tests/test_makecpt.py
Labels: maintenance, skip-changelog

#1174 Set __commit__ to an empty string for non-dev releases
  doc/conf.py
  pygmt/__init__.py
Labels: maintenance, skip-changelog

#1125 Convert booleans arguments in build_arg_string, not in kwargs_to_strings
  pygmt/datasets/earth_relief.py
  pygmt/helpers/decorators.py
  pygmt/helpers/utils.py
  pygmt/src/subplot.py
  pygmt/src/text.py
  pygmt/tests/test_helpers.py
Labels: maintenance

#1178 [Fix]: warning in building the documentation
  examples/tutorials/vectors.py
Labels: documentation

#1179 Fix for non-ASCII quotes to ASCII quotes
  examples/gallery/lines/linestyles.py
  examples/projections/misc/misc_robinson.py
  examples/projections/misc/misc_sinusoidal.py
  examples/projections/misc/misc_winkel_tripel.py
  pygmt/src/coast.py
  pygmt/src/grdtrack.py
Labels: documentation, skip-changelog

#1180 Create Histogram gallery category and move rose.py to the new category
  doc/conf.py
  examples/gallery/histograms/README.txt
  examples/gallery/histograms/rose.py
Labels: documentation, skip-changelog

#1182 Add defaults convention to example code standards
  CONTRIBUTING.md
Labels: documentation, skip-changelog

#1183 Unpin sphinx_rtd_theme from 0.5.1
  .github/workflows/ci_docs.yml
  environment.yml
Labels: maintenance, skip-changelog

#1062 Let Figure.show(method='external') work well in Python scripts
  pygmt/helpers/utils.py
Labels: bug

#1185 Move MAINTENANCE.md to documentation
  MANIFEST.in
  doc/index.rst
  doc/maintenance.md
Labels: maintenance, skip-changelog

#1195 Remove trailing whitespaces from examples
  examples/gallery/embellishments/logo.py
  examples/gallery/maps/borders.py
  examples/gallery/maps/land_and_water.py
  examples/gallery/symbols/datetime_inputs.py
  examples/projections/nongeo/polar.py
Labels: documentation, skip-changelog

#1197 Fix parameters section with sphinx_rtd_theme 5.x.x
  doc/_static/style.css
Labels: maintenance, skip-changelog

#529 Improve Figure.show for displaying previews in Jupyter notebooks and external viewers
  Makefile
  doc/Makefile
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/figure.py
  pygmt/tests/test_figure.py
Labels: enhancement

#1169 Migrate Figure.grdimage tests to use dvc
  pygmt/tests/baseline/test_grdimage.png
  pygmt/tests/baseline/test_grdimage.png.dvc
  pygmt/tests/baseline/test_grdimage_file.png
  pygmt/tests/baseline/test_grdimage_file.png.dvc
  pygmt/tests/baseline/test_grdimage_over_dateline.png
  pygmt/tests/baseline/test_grdimage_over_dateline.png.dvc
  pygmt/tests/baseline/test_grdimage_slice.png
  pygmt/tests/baseline/test_grdimage_slice.png.dvc
Labels: maintenance, skip-changelog

#1013 Use colorblind-friendly colors in the scatter plots gallery example
  examples/gallery/symbols/scatter.py
Labels: documentation

#1199 Remove Jupyter Notebook notes from tutorials
  examples/tutorials/3d_perspective_image.py
  examples/tutorials/coastlines.py
  examples/tutorials/configuration.py
  examples/tutorials/contour_map.py
  examples/tutorials/earth_relief.py
  examples/tutorials/first_figure.py
  examples/tutorials/frames.py
  examples/tutorials/insets.py
  examples/tutorials/lines.py
  examples/tutorials/plot.py
  examples/tutorials/regions.py
  examples/tutorials/text.py
  examples/tutorials/vectors.py
Labels: documentation, skip-changelog

#1194 Apply NIST SI unit convention to some gallery examples
  examples/gallery/embellishments/colorbar.py
  examples/gallery/embellishments/inset.py
  examples/gallery/embellishments/inset_rectangle_region.py
  examples/gallery/images/track_sampling.py
  examples/gallery/lines/line_custom_cpt.py
  examples/gallery/lines/linestyles.py
  examples/gallery/lines/vector_heads_tails.py
  examples/gallery/lines/vector_styles.py
  examples/gallery/symbols/points.py
Labels: documentation

#1206 Remove the "full test" section from installation guide
  doc/install.rst
Labels: documentation

#1211 Add a gallery example showing individual basic geometric symbols
  examples/gallery/symbols/basic_symbols.py
Labels: documentation

#1214 Fixed typo of "projecton" to "projection" in subplot module.
  pygmt/src/subplot.py
Labels: bug

#1160 Document the deprecation policy and addd the deprecate_parameter decorator to deprecate parameters
  doc/maintenance.md
  pygmt/helpers/__init__.py
  pygmt/helpers/decorators.py
Labels: maintenance

#1210 Add a list of external PyGMT resources
  doc/external_resources.md
  doc/index.rst
Labels: documentation

#1220 Bump codecov-action from v1.4.0 to v1.4.1
  .github/workflows/ci_tests.yaml
Labels: maintenance, skip-changelog

#1219 Improve the DVC image diff workflow to support side-by-side comparison of modified images
  .github/workflows/dvc-diff.yml
Labels: maintenance

#1218 Bump the GMT version to 6.2.0rc1 in CI
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  environment.yml
Labels: maintenance

#1221 Update baseline images for basemap
  .github/workflows/dvc-diff.yml
  pygmt/tests/baseline/test_basemap.png.dvc
  pygmt/tests/baseline/test_basemap_compass.png.dvc
  pygmt/tests/baseline/test_basemap_loglog.png.dvc
  pygmt/tests/baseline/test_basemap_map_scale.png.dvc
  pygmt/tests/baseline/test_basemap_power_axis.png.dvc
  pygmt/tests/baseline/test_basemap_rose.png.dvc
  pygmt/tests/baseline/test_basemap_winkel_tripel.png.dvc
  pygmt/tests/test_basemap.py
Labels: maintenance, skip-changelog

#1222 Update fig.coast baseline images for GMT 6.2.0rc1
  pygmt/tests/baseline/test_coast_dcw_list.png.dvc
  pygmt/tests/baseline/test_coast_dcw_single.png.dvc
  pygmt/tests/baseline/test_coast_region.png.dvc
  pygmt/tests/baseline/test_coast_world_mercator.png.dvc
Labels: maintenance, skip-changelog

#1223 Update fig.logo baseline images for GMT 6.2.0rc1
  pygmt/tests/baseline/test_logo.png.dvc
  pygmt/tests/baseline/test_logo_on_a_map.png.dvc
Labels: maintenance, skip-changelog

#1225 Update fig.meca baseline images for GMT 6.2.0rc1
  pygmt/tests/baseline/test_meca_spec_dictionary.png.dvc
Labels: maintenance, skip-changelog

#1226 Update fig.rose baseline images for GMT 6.2.0rc1
  pygmt/tests/baseline/test_rose_2d_array_multiple.png.dvc
  pygmt/tests/baseline/test_rose_2d_array_single.png.dvc
  pygmt/tests/baseline/test_rose_bools.png.dvc
  pygmt/tests/baseline/test_rose_data_file.png.dvc
  pygmt/tests/baseline/test_rose_no_sectors.png.dvc
  pygmt/tests/baseline/test_rose_plot_data_using_cpt.png.dvc
  pygmt/tests/baseline/test_rose_plot_with_transparency.png.dvc
Labels: maintenance, skip-changelog

#1227 Update fig.plot baseline images for GMT 6.2.0rc1
  pygmt/tests/baseline/test_plot_colors.png.dvc
  pygmt/tests/baseline/test_plot_colors_sizes.png.dvc
  pygmt/tests/baseline/test_plot_colors_sizes_proj.png.dvc
  pygmt/tests/baseline/test_plot_datetime.png.dvc
  pygmt/tests/baseline/test_plot_from_file.png.dvc
  pygmt/tests/baseline/test_plot_lines_with_arrows.png.dvc
  pygmt/tests/baseline/test_plot_matrix.png.dvc
  pygmt/tests/baseline/test_plot_matrix_color.png.dvc
  pygmt/tests/baseline/test_plot_projection.png.dvc
  pygmt/tests/baseline/test_plot_red_circles.png.dvc
  pygmt/tests/baseline/test_plot_scalar_xy.png.dvc
  pygmt/tests/baseline/test_plot_sizes.png.dvc
  pygmt/tests/baseline/test_plot_sizes_colors_transparencies.png.dvc
  pygmt/tests/baseline/test_plot_transparency.png.dvc
  pygmt/tests/baseline/test_plot_varying_intensity.png.dvc
  pygmt/tests/baseline/test_plot_varying_transparency.png.dvc
  pygmt/tests/baseline/test_plot_vectors.png.dvc
Labels: maintenance, skip-changelog

#1229 Update fig.colorbar baseline images for GMT 6.2.0rc1
  pygmt/tests/baseline/test_colorbar_box.png.dvc
  pygmt/tests/baseline/test_colorbar_box_with_fill.png.dvc
  pygmt/tests/baseline/test_colorbar_scaled_z_values.png.dvc
  pygmt/tests/baseline/test_colorbar_shading_boolean.png.dvc
  pygmt/tests/baseline/test_colorbar_shading_list.png.dvc
  pygmt/tests/baseline/test_colorbar_truncated_to_zlow_zhigh.png.dvc
Labels: maintenance, skip-changelog

#1230 Update fig.inset baseline images for GMT 6.2.0rc1
  pygmt/tests/baseline/test_inset_aliases.png.dvc
  pygmt/tests/baseline/test_inset_context_manager.png.dvc
Labels: maintenance, skip-changelog

#1228 Update fig.plot3d baseline images for GMT 6.2.0rc1
  pygmt/tests/baseline/test_plot3d_colors.png.dvc
  pygmt/tests/baseline/test_plot3d_colors_sizes.png.dvc
  pygmt/tests/baseline/test_plot3d_colors_sizes_proj.png.dvc
  pygmt/tests/baseline/test_plot3d_from_file.png.dvc
  pygmt/tests/baseline/test_plot3d_matrix.png.dvc
  pygmt/tests/baseline/test_plot3d_matrix_color.png.dvc
  pygmt/tests/baseline/test_plot3d_projection.png.dvc
  pygmt/tests/baseline/test_plot3d_red_circles_zscale.png.dvc
  pygmt/tests/baseline/test_plot3d_red_circles_zsize.png.dvc
  pygmt/tests/baseline/test_plot3d_scalar_xyz.png.dvc
  pygmt/tests/baseline/test_plot3d_sizes.png.dvc
  pygmt/tests/baseline/test_plot3d_sizes_colors_transparencies.png.dvc
  pygmt/tests/baseline/test_plot3d_transparency.png.dvc
  pygmt/tests/baseline/test_plot3d_varying_intensity.png.dvc
  pygmt/tests/baseline/test_plot3d_varying_transparency.png.dvc
  pygmt/tests/baseline/test_plot3d_vectors.png.dvc
Labels: maintenance, skip-changelog

#1224 Update fig.grd baseline images for GMT 6.2.0rc1
  pygmt/tests/baseline/test_grd2cpt.png.dvc
  pygmt/tests/baseline/test_grdcontour.png.dvc
  pygmt/tests/baseline/test_grdcontour_file.png.dvc
  pygmt/tests/baseline/test_grdcontour_interval_file_full_opts.png.dvc
  pygmt/tests/baseline/test_grdcontour_labels.png.dvc
  pygmt/tests/baseline/test_grdcontour_slice.png.dvc
  pygmt/tests/test_grdfilter.py
Labels: maintenance, skip-changelog

#1233 Update fig.legend baseline images for GMT 6.2.0rc1
  pygmt/tests/baseline/test_legend_default_position.png.dvc
  pygmt/tests/baseline/test_legend_entries.png.dvc
  pygmt/tests/baseline/test_legend_position.png.dvc
  pygmt/tests/baseline/test_legend_specfile.png.dvc
Labels: maintenance, skip-changelog

#1234 Update fig.contour baseline images for GMT 6.2.0rc1
  pygmt/tests/baseline/test_contour_from_file.png.dvc
  pygmt/tests/baseline/test_contour_matrix.png.dvc
  pygmt/tests/baseline/test_contour_vec.png.dvc
Labels: maintenance, skip-changelog

#1236 Remove xfails and workarounds for datetime inputs into pygmt.info
  pygmt/tests/test_info.py
Labels: maintenance, upstream

#1237 Update fig.shift_origin baseline images for GMT 6.2.0rc1
  pygmt/tests/baseline/test_figure_shift_origin.png.dvc
Labels: maintenance, skip-changelog

#1238 Update fig.image baseline images for GMT 6.2.0rc1
  pygmt/tests/baseline/test_image.png.dvc
Labels: maintenance, skip-changelog

#1235 Update pygmt.config baseline images for GMT 6.2.0rc1
  pygmt/tests/baseline/test_config.png.dvc
  pygmt/tests/baseline/test_config_font_annot.png.dvc
  pygmt/tests/baseline/test_config_font_one.png.dvc
  pygmt/tests/baseline/test_config_format_time_map.png.dvc
  pygmt/tests/baseline/test_config_map_annot_offset.png.dvc
  pygmt/tests/baseline/test_config_map_grid_cross_size.png.dvc
  pygmt/tests/baseline/test_config_map_grid_pen.png.dvc
  pygmt/tests/baseline/test_config_map_tick_length.png.dvc
  pygmt/tests/baseline/test_config_map_tick_pen.png.dvc
Labels: final review call, maintenance, skip-changelog

#975 Support passing string type numbers, geographic coordinates and datetimes
  doc/api/index.rst
  pygmt/clib/session.py
  pygmt/tests/test_clib_put_vector.py
Labels: feature, upstream

#1145 Wrap wiggle
  doc/api/index.rst
  examples/gallery/lines/wiggle.py
  pygmt/figure.py
  pygmt/src/__init__.py
  pygmt/src/wiggle.py
  pygmt/tests/baseline/test_wiggle.png.dvc
  pygmt/tests/test_wiggle.py
Labels: feature

#1072 Wrap histogram
  doc/api/index.rst
  pygmt/figure.py
  pygmt/src/__init__.py
  pygmt/src/histogram.py
  pygmt/tests/baseline/test_histogram.png.dvc
  pygmt/tests/test_histogram.py
Labels: feature

#1231 Update makecpt baseline images for GMT 6.2.0rc1
  pygmt/tests/baseline/test_makecpt_categorical.png.dvc
  pygmt/tests/baseline/test_makecpt_cyclic.png.dvc
  pygmt/tests/test_makecpt.py
Labels: maintenance, skip-changelog

#1243 Fix pygmt/helpers/testing.py doctest for GMT 6.2.0rc1
  pygmt/helpers/testing.py
Labels: maintenance, skip-changelog

#1248 Run slash command dispatch workflow on Pull Request comments only
  .github/workflows/slash-command-dispatch.yml
Labels: maintenance, skip-changelog

#1244 Disable pylint 2.8 consider-using-with refactoring suggestion
  pygmt/figure.py
Labels: maintenance, skip-changelog

#1232 Update fig.solar baseline images for GMT 6.2.0rc1
  pygmt/tests/baseline/test_solar_set_terminator_datetime.png.dvc
  pygmt/tests/baseline/test_solar_terminators.png.dvc
  pygmt/tests/test_solar.py
Labels: maintenance, skip-changelog

#525 Wrap velo
  doc/api/index.rst
  examples/gallery/seismology/velo_arrow_ellipse.py
  pygmt/figure.py
  pygmt/src/__init__.py
  pygmt/src/velo.py
  pygmt/tests/baseline/test_velo_numpy_array_numeric_only.png.dvc
  pygmt/tests/baseline/test_velo_pandas_dataframe.png.dvc
  pygmt/tests/test_velo.py
Labels: feature, final review call
