Repository GenericMappingTools/pygmt, pull requests merged in 2021-01, with the labels that each got.

#778 Clean up docstring in projections/README.txt
  examples/projections/README.txt
Labels: documentation, skip-changelog

#776 Update GMT argument in the azimuthal projections gallery to doc standards
  examples/projections/azim/azim_equidistant.py
  examples/projections/azim/azim_general_perspective.py
  examples/projections/azim/azim_general_stereographic.py
  examples/projections/azim/azim_gnomonic.py
  examples/projections/azim/azim_lambert.py
  examples/projections/azim/azim_orthographic.py
Labels: documentation

#769 Update test_coast_aliases
  pygmt/tests/test_coast.py
Labels: maintenance

#784 Add Michael Grund to AUTHORS.md
  AUTHORS.md
Labels: maintenance, skip-changelog

#785 Remove timestamp from test_coast_alias
  pygmt/tests/test_coast.py
Labels: maintenance, skip-changelog

#782 Update documentation for multi-parameter-symbols.py
  examples/gallery/plot/multi-parameter-symbols.py
Labels: documentation, skip-changelog

#780 Update GMT argument in the conic projections gallery to doc standards
  examples/projections/conic/conic_albers.py
  examples/projections/conic/conic_equidistant.py
  examples/projections/conic/conic_lambert.py
  examples/projections/conic/polyconic.py
Labels: documentation

#779 Create gallery example for datetime inputs
  examples/gallery/plot/datetime-inputs.py
Labels: documentation

#781 Add lakes alias to Figure.coast()
  pygmt/base_plotting.py
  pygmt/tests/test_coast.py
Labels: documentation

#789 Update GMT argument in the cylindric projections gallery to doc standards
  examples/projections/cyl/cyl_cassini.py
  examples/projections/cyl/cyl_equal_area.py
  examples/projections/cyl/cyl_equidistant.py
  examples/projections/cyl/cyl_mercator.py
  examples/projections/cyl/cyl_miller.py
  examples/projections/cyl/cyl_stereographic.py
  examples/projections/cyl/cyl_transverse_mercator.py
  examples/projections/cyl/cyl_universal_transverse_mercator.py
Labels: documentation

#790 Update GMT argument in the miscellaneous projections gallery to doc standards
  examples/projections/cyl/cyl_stereographic.py
  examples/projections/misc/misc_eckertIV.py
  examples/projections/misc/misc_eckertVI.py
  examples/projections/misc/misc_hammer.py
  examples/projections/misc/misc_mollweide.py
  examples/projections/misc/misc_robinson.py
  examples/projections/misc/misc_sinusoidal.py
  examples/projections/misc/misc_van_der_grinten.py
  examples/projections/misc/misc_winkel_tripel.py
Labels: documentation

#793 Update copyright year to 2021
  LICENSE.txt
Labels: maintenance, skip-changelog

#791 Add args_in_kwargs function
  pygmt/helpers/__init__.py
  pygmt/helpers/utils.py
  pygmt/tests/test_helpers.py
Labels: maintenance

#765 Add dcw alias (E) to Figure.coast
  pygmt/base_plotting.py
  pygmt/tests/test_coast.py
Labels: enhancement

#787 Add GMTInvalidInput Error for Figure.coast
  pygmt/base_plotting.py
  pygmt/tests/test_coast.py
Labels: maintenance

#642 Add docformatter to format plain text in docstrings
  .github/workflows/ci_tests.yaml
  .github/workflows/format-command.yml
  CONTRIBUTING.md
  Makefile
  environment.yml
  pygmt/__init__.py
  pygmt/base_plotting.py
  pygmt/clib/conversion.py
  pygmt/clib/loading.py
  pygmt/clib/session.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/tutorial.py
  pygmt/figure.py
  pygmt/filtering.py
  pygmt/gridding.py
  pygmt/gridops.py
  pygmt/helpers/decorators.py
  pygmt/helpers/tempfile.py
  pygmt/helpers/utils.py
  pygmt/mathops.py
  pygmt/modules.py
  pygmt/sampling.py
  pygmt/tests/test_accessor.py
  pygmt/tests/test_basemap.py
  pygmt/tests/test_blockmedian.py
  pygmt/tests/test_clib.py
  pygmt/tests/test_clib_loading.py
  pygmt/tests/test_clib_put_matrix.py
  pygmt/tests/test_clib_put_strings.py
  pygmt/tests/test_clib_put_vector.py
  pygmt/tests/test_coast.py
  pygmt/tests/test_colorbar.py
  pygmt/tests/test_config.py
  pygmt/tests/test_contour.py
  pygmt/tests/test_datasets.py
  pygmt/tests/test_figure.py
  pygmt/tests/test_grdcontour.py
  pygmt/tests/test_grdcut.py
  pygmt/tests/test_grdimage.py
  pygmt/tests/test_grdinfo.py
  pygmt/tests/test_grdtrack.py
  pygmt/tests/test_grdview.py
  pygmt/tests/test_helpers.py
  pygmt/tests/test_image.py
  pygmt/tests/test_info.py
  pygmt/tests/test_legend.py
  pygmt/tests/test_logo.py
  pygmt/tests/test_makecpt.py
  pygmt/tests/test_meca.py
  pygmt/tests/test_plot.py
  pygmt/tests/test_plot3d.py
  pygmt/tests/test_session_management.py
  pygmt/tests/test_sphinx_gallery.py
  pygmt/tests/test_surface.py
  pygmt/tests/test_text.py
  pygmt/tests/test_which.py
  pygmt/tests/test_x2sys_cross.py
  pygmt/tests/test_x2sys_init.py
  requirements-dev.txt
Labels: maintenance

#795 Recommend using SI units in documentation
  CONTRIBUTING.md
Labels: documentation

#797 Use args_in_kwargs for basemap error raising
  pygmt/base_plotting.py
Labels: maintenance

#796 Add guidelines for types of tests to write
  CONTRIBUTING.md
Labels: documentation

#775 Update CONTRIBUTING.md with formatting conventions
  CONTRIBUTING.md
Labels: maintenance

#800 Add tutorial for region arguments
  doc/index.rst
  examples/tutorials/regions.py
Labels: documentation

#798 Update GMT arguments in coast doc strings
  pygmt/base_plotting.py
Labels: documentation

#686 Split meca into a standalone module from base_plotting.py
  pygmt/base_plotting.py
  pygmt/src/__init__.py
  pygmt/src/meca.py
Labels: maintenance

#810 Add tests for GMTInvalidInput for figure.py
  pygmt/tests/test_figure.py
Labels: maintenance

#811 Fix the Makefile 'distclean' target
  Makefile
Labels: maintenance, skip-changelog

#818 Style and formatting fixes for tutorials
  doc/index.rst
  examples/tutorials/3d-perspective-image.py
  examples/tutorials/coastlines.py
  examples/tutorials/earth-relief.py
  examples/tutorials/frames.py
  examples/tutorials/lines.py
  examples/tutorials/plot.py
  examples/tutorials/regions.py
  examples/tutorials/text.py
Labels: documentation, skip-changelog

#820 Update axis label explanation in frames tutorial
  examples/tutorials/frames.py
Labels: documentation

#816 Improve projection tutorials
  examples/projections/azim/azim_equidistant.py
  examples/projections/azim/azim_general_perspective.py
  examples/projections/azim/azim_general_stereographic.py
  examples/projections/azim/azim_gnomonic.py
  examples/projections/azim/azim_lambert.py
  examples/projections/azim/azim_orthographic.py
  examples/projections/conic/conic_albers.py
  examples/projections/conic/conic_equidistant.py
  examples/projections/cyl/cyl_cassini.py
  examples/projections/cyl/cyl_mercator.py
  examples/projections/cyl/cyl_stereographic.py
  examples/projections/nongeo/cartesian_linear.py
  examples/projections/nongeo/cartesian_logarithmic.py
  examples/projections/nongeo/polar.py
Labels: documentation, skip-changelog

#813 Speedup the Continuous Documentation using mamba
  package.json
Labels: maintenance, skip-changelog

#814 Improve the error message when PyGMT fails to load the GMT library
  pygmt/clib/loading.py
Labels: maintenance

#823 Add a gallery example for logo
  examples/gallery/plot/logo.py
Labels: documentation

#809 Add tests for grdfilter
  pygmt/tests/test_grdfilter.py
Labels: maintenance

#826 Choosing the thumbnail figures in tutorials
  CONTRIBUTING.md
  doc/conf.py
  examples/tutorials/3d-perspective-image.py
  examples/tutorials/coastlines.py
  examples/tutorials/configuration.py
  examples/tutorials/contour-map.py
  examples/tutorials/earth-relief.py
  examples/tutorials/frames.py
  examples/tutorials/lines.py
  examples/tutorials/plot.py
  examples/tutorials/text.py
Labels: documentation

#824 Remove the invalid reference to Ju_full
  examples/projections/table/README.txt
Labels: documentation, skip-changelog
