Repository GenericMappingTools/pygmt, pull requests merged in 2021-05, with the labels that each got.

#1189 Refactor grdtrack to use virtualfile_from_data and improve i/o to pandas.DataFrame
  pygmt/src/grdtrack.py
  pygmt/tests/test_grdtrack.py
Labels: enhancement

#1255 Update Figure.meca 'offset' alias to match GMT 6.2.0rc1 syntax
  pygmt/src/meca.py
Labels: maintenance, skip-changelog

#1256 Add alias name convention to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1251 Added documentation for three oblique mercator projections
  examples/projections/cyl/cyl_oblique_mercator_1.py
  examples/projections/cyl/cyl_oblique_mercator_2.py
  examples/projections/cyl/cyl_oblique_mercator_3.py
  examples/projections/table/README.txt
Labels: documentation

#1254 Figure.plot: Deprecate parameter "sizes" to "size" (remove in v0.6.0)
  examples/gallery/symbols/points_categorical.py
  examples/gallery/symbols/scatter.py
  examples/tutorials/plot.py
  pygmt/src/plot.py
  pygmt/tests/test_plot.py
Labels: deprecation

#1247 Fix ModuleNotFoundError error when IPython is not installed
  pygmt/figure.py
Labels: bug, skip-changelog

#1264 Explicitly use netcdf4 engine in xarray.open_dataarray to read grd files
  pygmt/datasets/earth_relief.py
  pygmt/tests/test_accessor.py
  pygmt/tests/test_clib_put_matrix.py
Labels: bug

#1258 Figure.plot3d: Deprecate parameter "sizes" to "size" (remove in v0.6.0)
  examples/gallery/3d_plots/scatter3d.py
  pygmt/src/plot3d.py
  pygmt/tests/test_plot3d.py
Labels: deprecation

#1260 Clarify that the "color" parameter in plot/plot3d can be 1d array
  pygmt/helpers/decorators.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
Labels: documentation

#1271 Update fig.basemap and pygmt.config baseline images for Ghostscript 9.54.0
  pygmt/tests/baseline/test_basemap_winkel_tripel.png.dvc
  pygmt/tests/baseline/test_config_map_grid_cross_size.png.dvc
  pygmt/tests/baseline/test_config_map_grid_pen.png.dvc
  pygmt/tests/baseline/test_config_map_tick_length.png.dvc
  pygmt/tests/baseline/test_config_map_tick_pen.png.dvc
Labels: maintenance, skip-changelog

#1249 Add parameters to histogram
  pygmt/src/histogram.py
Labels: enhancement

#1267 Add categorical colorbars for plot, plot3d and line colors gallery examples
  examples/gallery/3d_plots/scatter3d.py
  examples/gallery/lines/line_custom_cpt.py
  examples/gallery/symbols/points_categorical.py
Labels: documentation

#1274 Rename Z alias in histogram
  pygmt/src/histogram.py
Labels: enhancement

#1186 Standardize docstrings for table-like inputs
  pygmt/clib/session.py
  pygmt/helpers/decorators.py
  pygmt/helpers/utils.py
  pygmt/src/grdtrack.py
  pygmt/src/histogram.py
  pygmt/src/info.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/rose.py
  pygmt/src/velo.py
  pygmt/src/wiggle.py
Labels: documentation

#1000 Handle geopandas and shapely geometries via __geo_interface__ link
  .github/workflows/ci_tests.yaml
  doc/conf.py
  doc/install.rst
  doc/maintenance.md
  pygmt/clib/session.py
  pygmt/helpers/__init__.py
  pygmt/helpers/decorators.py
  pygmt/helpers/tempfile.py
  pygmt/helpers/utils.py
  pygmt/tests/test_geopandas.py
Labels: feature, final review call

#1261 Wrap grdclip
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/src/__init__.py
  pygmt/src/grdclip.py
  pygmt/tests/test_grdclip.py
Labels: feature

#1272 Add histogram gallery example
  examples/gallery/histograms/histogram.py
Labels: documentation, final review call

#1279 Conda install gmt dev version directly in one step instead of two
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
Labels: maintenance, skip-changelog

#1265 Clarify that the "transparency" parameter in plot/plot3d/text can be 1d array
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/text.py
  pygmt/tests/test_plot.py
  pygmt/tests/test_plot3d.py
Labels: documentation, final review call

#1276 Wrap grdfill
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/src/__init__.py
  pygmt/src/grdfill.py
  pygmt/tests/test_grdfill.py
Labels: feature

#1285 Fix two sphinx warnings for docs build
  pygmt/clib/session.py
  pygmt/src/wiggle.py
Labels: documentation, final review call, skip-changelog

#1280 Refactor blockm* to use virtualfile_from_data and improve i/o
  pygmt/src/blockm.py
  pygmt/tests/test_blockmean.py
  pygmt/tests/test_blockmedian.py
Labels: enhancement, final review call

#1119 Revise Pull Request review process in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1288 Add common alias spacing (-I) for specifying grid increments
  pygmt/helpers/decorators.py
  pygmt/src/blockm.py
  pygmt/src/grdfilter.py
  pygmt/src/surface.py
Labels: documentation

#1269 Wrap grdgradient
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/src/__init__.py
  pygmt/src/grdgradient.py
  pygmt/tests/test_grdgradient.py
Labels: feature, final review call

#1290 Bump GMT version from 6.2.0rc1 to 6.2.0rc2 in CI
  .github/workflows/cache_data.yaml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  environment.yml
Labels: maintenance

#1291 Update fig.basemap, fig.subplot and fig.wiggle baseline images for GMT 6.2.0rc2
  pygmt/tests/baseline/test_basemap_polar.png.dvc
  pygmt/tests/baseline/test_subplot_autolabel_margins_title.png.dvc
  pygmt/tests/baseline/test_subplot_basic_frame.png.dvc
  pygmt/tests/baseline/test_subplot_clearance_and_shared_xy_axis_layout.png.dvc
  pygmt/tests/baseline/test_subplot_direct.png.dvc
  pygmt/tests/baseline/test_wiggle.png.dvc
  pygmt/tests/test_basemap.py
Labels: maintenance

#1292 Update fig.text baseline images for GMT 6.2.0rc2
  pygmt/tests/baseline/test_text_angle_30.png.dvc
  pygmt/tests/baseline/test_text_angle_font_justify_from_textfile.png.dvc
  pygmt/tests/baseline/test_text_fill.png.dvc
  pygmt/tests/baseline/test_text_font_bold.png.dvc
  pygmt/tests/baseline/test_text_input_multiple_filenames.png.dvc
  pygmt/tests/baseline/test_text_input_remote_filename.png.dvc
  pygmt/tests/baseline/test_text_input_single_filename.png.dvc
  pygmt/tests/baseline/test_text_justify_bottom_right_and_top_left.png.dvc
  pygmt/tests/baseline/test_text_justify_parsed_from_textfile.png.dvc
  pygmt/tests/baseline/test_text_multiple_lines_of_text.png.dvc
  pygmt/tests/baseline/test_text_nonstr_text.png.dvc
  pygmt/tests/baseline/test_text_pen.png.dvc
  pygmt/tests/baseline/test_text_position.png.dvc
  pygmt/tests/baseline/test_text_position_offset_with_line.png.dvc
  pygmt/tests/baseline/test_text_round_clearance.png.dvc
  pygmt/tests/baseline/test_text_single_line_of_text.png.dvc
  pygmt/tests/baseline/test_text_transparency.png.dvc
  pygmt/tests/baseline/test_text_varying_transparency.png.dvc
Labels: maintenance, skip-changelog

#1295 Add projection and region to grdview docstring
  pygmt/src/grdview.py
Labels: documentation

#1154 Migrate Figure.grdview tests to dvc
  pygmt/tests/baseline/test_grdview_drapegrid_dataarray.png
  pygmt/tests/baseline/test_grdview_drapegrid_dataarray.png.dvc
  pygmt/tests/baseline/test_grdview_grid_dataarray.png
  pygmt/tests/baseline/test_grdview_grid_dataarray.png.dvc
  pygmt/tests/baseline/test_grdview_grid_file_with_region_subset.png
  pygmt/tests/baseline/test_grdview_grid_file_with_region_subset.png.dvc
  pygmt/tests/baseline/test_grdview_on_a_plane.png
  pygmt/tests/baseline/test_grdview_on_a_plane.png.dvc
  pygmt/tests/baseline/test_grdview_on_a_plane_styled_with_facadepen.png
  pygmt/tests/baseline/test_grdview_on_a_plane_styled_with_facadepen.png.dvc
  pygmt/tests/baseline/test_grdview_on_a_plane_with_colored_frontal_facade.png
  pygmt/tests/baseline/test_grdview_on_a_plane_with_colored_frontal_facade.png.dvc
  pygmt/tests/baseline/test_grdview_surface_mesh_plot_styled_with_meshpen.png
  pygmt/tests/baseline/test_grdview_surface_mesh_plot_styled_with_meshpen.png.dvc
  pygmt/tests/baseline/test_grdview_surface_plot_styled_with_contourpen.png
  pygmt/tests/baseline/test_grdview_surface_plot_styled_with_contourpen.png.dvc
  pygmt/tests/baseline/test_grdview_with_cmap_for_image_plot.png
  pygmt/tests/baseline/test_grdview_with_cmap_for_image_plot.png.dvc
  pygmt/tests/baseline/test_grdview_with_cmap_for_perspective_surface_plot.png
  pygmt/tests/baseline/test_grdview_with_cmap_for_perspective_surface_plot.png.dvc
  pygmt/tests/baseline/test_grdview_with_cmap_for_surface_monochrome_plot.png
  pygmt/tests/baseline/test_grdview_with_cmap_for_surface_monochrome_plot.png.dvc
  pygmt/tests/baseline/test_grdview_with_perspective.png
  pygmt/tests/baseline/test_grdview_with_perspective.png.dvc
  pygmt/tests/baseline/test_grdview_with_perspective_and_zaxis_frame.png
  pygmt/tests/baseline/test_grdview_with_perspective_and_zaxis_frame.png.dvc
  pygmt/tests/baseline/test_grdview_with_perspective_and_zscale.png
  pygmt/tests/baseline/test_grdview_with_perspective_and_zscale.png.dvc
  pygmt/tests/baseline/test_grdview_with_perspective_and_zsize.png
  pygmt/tests/baseline/test_grdview_with_perspective_and_zsize.png.dvc
  pygmt/tests/test_grdview.py
Labels: maintenance, skip-changelog

#1296 Remove xfails on grdimage test for GMT 6.2.0rc2
  pygmt/tests/test_grdimage.py
Labels: maintenance, skip-changelog

#1297 Remove xfails on solar and velo tests for GMT 6.2.0rc2
  pygmt/tests/test_solar.py
  pygmt/tests/test_velo.py
Labels: maintenance, skip-changelog

#1273 Wrap grdlandmask
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/src/__init__.py
  pygmt/src/grdlandmask.py
  pygmt/tests/test_grdlandmask.py
Labels: feature

#1300 Add incols to COMMON_OPTIONS, blockmean, and blockmedian
  pygmt/helpers/decorators.py
  pygmt/src/blockm.py
Labels: enhancement

#1302 Clarify position of deprecate_parameter decorator to be above use_alias
  doc/maintenance.md
  pygmt/helpers/decorators.py
Labels: documentation

#1287 Update the inset gallery example
  examples/gallery/embellishments/inset.py
Labels: documentation

#1298 Figure.plot: Deprecate parameter "columns" to "incols" (remove in v0.6.0)
  pygmt/src/plot.py
  pygmt/tests/test_plot.py
Labels: deprecation

#1307 Let Figure.savefig recommend .eps or .pdf when .ps extension is used
  pygmt/figure.py
  pygmt/tests/test_figure.py
Labels: enhancement

#1301 Add guidelines for managing issues to maintenance.md
  doc/maintenance.md
Labels: documentation, final review call

#1306 Figure.rose: Deprecate parameter "columns" to "incols" (remove in v0.6.0)
  pygmt/src/rose.py
  pygmt/tests/test_rose.py
Labels: deprecation

#1190 Complete documentation for grdtrack
  pygmt/src/grdtrack.py
Labels: documentation, final review call
