Repository GenericMappingTools/pygmt, pull requests merged in 2021-10, with the labels that each got.

#1553 Cache earth_relief_15s tile and set GMT_DATA_SERVER to use https
  .github/workflows/cache_data.yaml
  package.json
  pygmt/helpers/testing.py
Labels: maintenance, skip-changelog

#1548 Figure.wiggle: Reorder input parameter to 'data, x, y, z'
  pygmt/helpers/decorators.py
  pygmt/src/wiggle.py
  pygmt/tests/test_wiggle.py
Labels: deprecation

#1546 Figure.rose: Reorder input parameters to 'data, length, azimuth'
  pygmt/src/rose.py
  pygmt/tests/test_rose.py
Labels: deprecation, final review call

#1547 Figure.plot: Reorder input parameters to "data, x, y"
  examples/gallery/symbols/datetime_inputs.py
  examples/gallery/symbols/points.py
  pygmt/src/plot.py
  pygmt/tests/test_plot.py
Labels: deprecation, final review call

#1560 Figure.plot3d: Reorder input parameters to 'data, x, y, z'
  pygmt/src/plot3d.py
  pygmt/tests/test_plot3d.py
Labels: deprecation, final review call

#1561 Figure.contour: Reorder input parameters to 'data, x, y, z'
  pygmt/src/contour.py
  pygmt/tests/test_contour.py
Labels: deprecation, final review call

#1562 pygmt.surface: Reorder input parameters to 'data, x, y, z'
  pygmt/src/surface.py
Labels: deprecation, final review call

#1554 Document gmtwhich -Ga option to download to appropriate cache folder
  pygmt/src/which.py
Labels: documentation, final review call

#1564 Add tomli as a dependency in GitHub Actions CI
  .github/workflows/ci_tests.yaml
  environment.yml
Labels: maintenance, skip-changelog

#1563 blockmean & blockmode: Fix the alias of 'd' to 'nodata'
  pygmt/src/blockm.py
Labels: bug, skip-changelog

#1530 Raise RuntimeWarning instead of an exception for irregular grid spacing
  pygmt/clib/conversion.py
  pygmt/tests/test_clib.py
Labels: bug, final review call

#1565 pygmt.blockm*: Reorder input parameters to 'data, x, y, z'
  pygmt/src/blockm.py
  pygmt/tests/test_blockm.py
  pygmt/tests/test_blockmedian.py
Labels: deprecation

#1566 Expand table-like input options for xyz2grd
  doc/api/index.rst
  pygmt/src/xyz2grd.py
Labels: enhancement, skip-changelog, final review call

#1567 Update parameter 'table' to 'data' for gallery examples
  examples/gallery/3d_plots/scatter3d.py
  examples/gallery/histograms/histogram.py
  examples/gallery/symbols/points_categorical.py
  examples/tutorials/date_time_charts.py
Labels: documentation, skip-changelog, final review call

#1569 Remove unnecessary returns from surface tests
  pygmt/tests/test_surface.py
Labels: maintenance, skip-changelog

#1570 Use alias long-form for grdimage, text, and psconvert tests
  pygmt/tests/test_grdimage.py
  pygmt/tests/test_psconvert.py
  pygmt/tests/test_text.py
Labels: maintenance, skip-changelog, final review call

#1594 Changelog entry for v0.5.0
  CITATION.cff
  README.rst
  doc/_static/version_switch.js
  doc/changes.md
Labels: skip-changelog, final review call

#1597 Fix typo in BibTeX
  README.rst
Labels: skip-changelog
