Repository GenericMappingTools/pygmt, pull requests merged in 2021-08, with the labels that each got.

#1398 Add 3 arc minute relief tile containing Iceland to cache
  pygmt/helpers/testing.py
Labels: enhancement

#1396 Add gallery example for grdclip
  examples/gallery/images/grdclip.py
Labels: documentation

#1407 Add common option aliases to COMMON_OPTIONS in decorators.py
  pygmt/helpers/decorators.py
  pygmt/src/blockm.py
  pygmt/src/wiggle.py
Labels: documentation, final review call

#1360 Change references from "master" branch to "main" branch
  .github/config.yml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/dvc-diff.yml
  .github/workflows/publish-to-pypi.yml
  .github/workflows/release-drafter.yml
  .github/workflows/style_checks.yaml
  README.rst
  doc/_templates/layout.html
  doc/conf.py
  doc/contributing.md
  doc/external_resources.md
  doc/maintenance.md
Labels: maintenance

#1401 Add tomli as a dependency in GMT Dev Tests
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance

#1415 Combine documentation and compatibility sections in README.rst
  README.rst
Labels: documentation, final review call

#1417 Add Yohai Magen to AUTHORS.md
  AUTHORS.md
Labels: maintenance, skip-changelog

#1414 Changelog entry for v0.4.1
  README.rst
  doc/_static/version_switch.js
  doc/changes.md
Labels: skip-changelog

#636 Wrap xyz2grd
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/src/__init__.py
  pygmt/src/xyz2grd.py
  pygmt/tests/test_xyz2grd.py
Labels: feature, final review call

#1380 Wrap grdsample
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/src/__init__.py
  pygmt/src/grdsample.py
  pygmt/tests/test_grdsample.py
Labels: feature, final review call

#1426 Add area_thresh to COMMON_OPTIONS
  pygmt/helpers/decorators.py
  pygmt/src/coast.py
Labels: enhancement, final review call

#1430 NEP29: Set minimum required version to NumPy 1.18+
  .github/workflows/ci_tests.yaml
  README.rst
  doc/install.rst
  environment.yml
  requirements.txt
  setup.py
Labels: deprecation

#1435 Remove the unused psconvert test test_psconvert_int_options
  pygmt/tests/test_psconvert.py
Labels: maintenance, skip-changelog

#1444 Remove required description from label_placement parameter
  pygmt/src/contour.py
  pygmt/src/grdcontour.py
Labels: documentation, skip-changelog, final review call

#1405 Plot square or cube by default for geopandas Point/MultiPoint types
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/tests/baseline/test_geopandas_plot3d_default_cube.png.dvc
  pygmt/tests/baseline/test_geopandas_plot3d_non_default_circle.png.dvc
  pygmt/tests/baseline/test_geopandas_plot_default_square.png.dvc
  pygmt/tests/baseline/test_geopandas_plot_non_default_circle.png.dvc
  pygmt/tests/test_geopandas.py
Labels: enhancement, final review call

#1446 Add missing common options to contour
  pygmt/src/contour.py
Labels: documentation, final review call

#1423 Update/add grdlandmask parameters and aliases
  doc/api/index.rst
  pygmt/src/grdlandmask.py
Labels: enhancement, final review call

#1449 Add missing aliases to pygmt.Figure.image.py
  pygmt/src/image.py
Labels: documentation, final review call

#1450 Add missing alias to pygmt.Figure.grdview
  pygmt/src/grdview.py
Labels: documentation, final review call

#1452 Add missing aliases to pygmt.Figure.rose
  pygmt/src/rose.py
Labels: documentation, final review call

#1453 Add missing alias to pygmt.Figure.legend
  pygmt/src/legend.py
Labels: documentation, final review call

#1451 Add missing aliases to pygmt.Figure.histogram
  pygmt/src/histogram.py
Labels: documentation, final review call

#1454 Clarifying resolutions of relief grids
  pygmt/datasets/earth_relief.py
Labels: documentation, skip-changelog

#1459 Fix lint warnings for pylint 2.10
  pygmt/helpers/tempfile.py
  pygmt/sphinx_gallery.py
  pygmt/tests/test_helpers.py
  pygmt/tests/test_legend.py
  pygmt/tests/test_meca.py
  pygmt/tests/test_text.py
  pygmt/tests/test_x2sys_cross.py
  pygmt/tests/test_x2sys_init.py
  setup.py
Labels: maintenance, skip-changelog

#1448 Add missing aliases to pygmt.Figure.text
  pygmt/src/text.py
Labels: documentation, final review call

#1438 Plot square or cube by default for OGR/GMT files with Point/MultiPoint types
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/tests/baseline/test_plot3d_ogrgmt_file_multipoint_default_style.png.dvc
  pygmt/tests/baseline/test_plot3d_ogrgmt_file_multipoint_non_default_style.png.dvc
  pygmt/tests/baseline/test_plot_ogrgmt_file_multipoint_default_style.png.dvc
  pygmt/tests/baseline/test_plot_ogrgmt_file_multipoint_non_default_style.png.dvc
  pygmt/tests/test_plot.py
  pygmt/tests/test_plot3d.py
Labels: enhancement, final review call

#1377 Wrap grdproject
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/src/__init__.py
  pygmt/src/grdproject.py
  pygmt/tests/test_grdproject.py
Labels: feature

#1476 Add the 'incols' alias to info
  pygmt/src/info.py
Labels: enhancement
