Repository GenericMappingTools/pygmt, pull requests merged in 2021-03, with the labels that each got.

#907 Update release process in template post v0.3.0
  .github/ISSUE_TEMPLATE/release_checklist.md
  .github/release-drafter.yml
  MAINTENANCE.md
Labels: documentation, skip-changelog

#981 Let 'make clean' delete .eggs and results
  Makefile
Labels: maintenance, skip-changelog

#982 Add 'make package' target for building source and binary distributions
  .github/workflows/publish-to-pypi.yml
  Makefile
Labels: maintenance, skip-changelog

#984 Add Jiayuan Yao to AUTHORS.md
  AUTHORS.md
Labels: maintenance, skip-changelog

#773 Onboarding maintainer checklist
  MAINTENANCE.md
Labels: maintenance

#986 CI: Install ninja to speed up building GMT source code
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog

#985 Cache the 03s earth relief tile @N35E135.earth_relief_03s_g.nc
  .github/workflows/cache_data.yaml
Labels: maintenance, skip-changelog

#802 Expand documentation linking in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#950 Add a gallery example for plotting Cartesian, circular and geographic vectors
  examples/gallery/line/vectors.py
Labels: documentation

#988 Add a reference to vector types example in vector-heads-tails.py
  examples/gallery/line/vector-heads-tails.py
Labels: documentation, skip-changelog

#961 Refactor info and grdinfo to use virtualfile_from_data
  doc/api/index.rst
  pygmt/clib/session.py
  pygmt/src/grdinfo.py
  pygmt/src/info.py
Labels: enhancement

#992 Refactor grd modules to use virtualfile_from_data
  pygmt/clib/session.py
  pygmt/src/grd2cpt.py
  pygmt/src/grdcontour.py
  pygmt/src/grdcut.py
  pygmt/src/grdfilter.py
  pygmt/src/grdimage.py
  pygmt/src/grdtrack.py
  pygmt/src/grdview.py
Labels: maintenance

#997 Fix typo in vector-heads-tails.py
  examples/gallery/line/vector-heads-tails.py
Labels: documentation, skip-changelog

#994 Add common alias coltypes (-f) for specifying i/o data types
  pygmt/helpers/decorators.py
  pygmt/src/basemap.py
  pygmt/src/blockmedian.py
  pygmt/src/grdcontour.py
  pygmt/src/grdcut.py
  pygmt/src/grdfilter.py
  pygmt/src/grdimage.py
  pygmt/src/grdinfo.py
  pygmt/src/grdtrack.py
  pygmt/src/grdview.py
  pygmt/src/info.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/surface.py
  pygmt/src/text.py
Labels: documentation

#960 Let pygmt.info load datetime columns into a str dtype array
  pygmt/src/info.py
  pygmt/tests/test_info.py
Labels: bug

#998 Move codecov.yml into .github directory and increase coverage target to 90 percent
  .github/codecov.yml
Labels: maintenance, skip-changelog

#955 Add gallery example showing different polar projection use cases
  examples/projections/nongeo/polar.py
Labels: documentation

#1002 Refactor Figure.meca() to better determine the data format code
  pygmt/src/meca.py
Labels: maintenance, skip-changelog

#1007 Add Kathryn Materna to AUTHORS.md
  AUTHORS.md
Labels: maintenance, skip-changelog

#999 Explicitly exclude unnecessary files in source distributions
  MANIFEST.in
Labels: maintenance

#1008 Fix a bug in the "frames" tutorials
  examples/tutorials/frames.py
Labels: documentation, skip-changelog

#1004 Add links to projection table
  examples/projections/table/README.txt
Labels: documentation, skip-changelog

#977 Fix issues in loading GMT's shared library
  pygmt/clib/loading.py
  pygmt/tests/test_clib_loading.py
Labels: bug

#1014 Improve the targets in doc/Makefile
  doc/Makefile
Labels: maintenance, skip-changelog

#990 Refactor plot and plot3d to use virtualfile_from_data
  pygmt/clib/session.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/tests/test_info.py
Labels: maintenance

#991 Speedup sphinx-build using parallelization
  doc/Makefile
  pygmt/tests/test_grdinfo.py
Labels: maintenance, skip-changelog

#1030 Remove a duplicated link in check-link.yml
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog

#1031 Support passing a sequence to the spacing parameter of pygmt.info()
  pygmt/src/info.py
Labels: enhancement

#1032 Do NOT fail CI if codecov runs into errors during upload
  .github/workflows/ci_tests.yaml
Labels: maintenance, skip-changelog

#1025 Improve the first figure tutorial
  examples/tutorials/first-figure.py
Labels: documentation, skip-changelog

#1016 Improve the docstring of the pygmt package
  pygmt/__init__.py
Labels: documentation

#1026 Tiny fixes for the plot tutorial
  examples/tutorials/plot.py
Labels: documentation, skip-changelog

#1028 Tiny improvements for the text tutorial
  examples/tutorials/text.py
Labels: documentation, skip-changelog

#1027 Improve documentation for +r option in the regions tutorial
  examples/tutorials/regions.py
Labels: documentation, skip-changelog

#1029 Add instructions to upgrade installed PyGMT version
  doc/install.rst
Labels: documentation

#1037 Set bash to be default shell for Github Actions CI
  .github/workflows/cache_data.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog

#995 Reorganize gallery examples
  doc/conf.py
  doc/index.rst
  examples/gallery/3d_plots/README.txt
  examples/gallery/3d_plots/grdview_surface.py
  examples/gallery/3d_plots/scatter3d.py
  examples/gallery/coast/README.txt
  examples/gallery/embellishments/README.txt
  examples/gallery/embellishments/colorbar.py
  examples/gallery/embellishments/inset.py
  examples/gallery/embellishments/legend.py
  examples/gallery/embellishments/logo.py
  examples/gallery/grid/README.txt
  examples/gallery/images/README.txt
  examples/gallery/images/image.py
  examples/gallery/images/track_sampling.py
  examples/gallery/line/README.txt
  examples/gallery/lines/README.txt
  examples/gallery/lines/line_custom_cpt.py
  examples/gallery/lines/linestyles.py
  examples/gallery/lines/vector_heads_tails.py
  examples/gallery/lines/vectors.py
  examples/gallery/maps/README.txt
  examples/gallery/maps/borders.py
  examples/gallery/maps/land_and_water.py
  examples/gallery/maps/shorelines.py
  examples/gallery/plot/README.txt
  examples/gallery/seismology/README.txt
  examples/gallery/seismology/meca.py
  examples/gallery/symbols/README.txt
  examples/gallery/symbols/datetime_inputs.py
  examples/gallery/symbols/multi_parameter_symbols.py
  examples/gallery/symbols/points.py
  examples/gallery/symbols/points_transparency.py
  examples/gallery/symbols/scatter.py
  examples/tutorials/insets.py
  examples/tutorials/lines.py
Labels: documentation

#1006 Add a gallery example to show coloring of points by categories
  examples/gallery/symbols/points_categorical.py
Labels: documentation

#1020 Add a gallery example of inset map showing a rectangle region
  examples/gallery/embellishments/inset_rectangle_region.py
Labels: documentation

#1019 Add a gallery example for a double y-axes graph
  doc/conf.py
  examples/gallery/basemaps/README.txt
  examples/gallery/basemaps/double_y_axes.py
Labels: documentation

#1034 Add underscore guideline to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1022 Add a gallery example showing different front styles
  examples/gallery/lines/linefronts.py
Labels: documentation

#1044 Link from projection parameter to gallery
  pygmt/helpers/decorators.py
Labels: documentation, skip-changelog

#1043 Copy interval docs from grdcontour.py to the levels docs in contour.py
  pygmt/src/contour.py
  pygmt/src/grdcontour.py
Labels: documentation, skip-changelog

#1051 Tiny improvements for the inset gallery example
  examples/gallery/embellishments/inset.py
Labels: documentation, skip-changelog

#1045 Improve the image size in the documentation
  doc/_static/style.css
  doc/overview.rst
Labels: documentation, skip-changelog

#1053 Tiny improvements for the line tyles gallery example
  examples/gallery/lines/linestyles.py
Labels: documentation, skip-changelog

#1049 Add the link for standard GMT color names in GMT docs
  examples/gallery/maps/land_and_water.py
Labels: documentation, skip-changelog

#1054 Tiny improvement for the sampling along tracks gallery example
  examples/gallery/images/track_sampling.py
Labels: documentation, skip-changelog

#1050 Tiny improvements for the multi-parameter symbols example
  examples/gallery/symbols/multi_parameter_symbols.py
Labels: documentation, skip-changelog

#1052 Update the title for the images/EPS on maps gallery example
  examples/gallery/images/image.py
Labels: documentation, skip-changelog

#1057 Fix some typos
  doc/install.rst
  examples/projections/azim/azim_equidistant.py
  examples/projections/cyl/cyl_universal_transverse_mercator.py
  examples/tutorials/regions.py
  pygmt/datasets/earth_relief.py
  pygmt/helpers/decorators.py
  pygmt/tests/test_session_management.py
Labels: documentation, skip-changelog

#1047 Changelog entry for v0.3.1 release
  README.rst
  doc/_static/version_switch.js
  doc/changes.md
Labels: skip-changelog

#1058 Remove the "GitHub Actions" subsection heading from MAINTENANCE.md
  MAINTENANCE.md
Labels: documentation, skip-changelog

#1033 Separate workflows for running tests and building documentation
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  MAINTENANCE.md
Labels: maintenance

#1066 Fix a typo in the example inset_rectangle_region.py
  examples/gallery/embellishments/inset_rectangle_region.py
Labels: documentation, skip-changelog

#1063 Add Twitter link to the release checklist
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: maintenance, skip-changelog

#976 Allow load_earth_relief() to load the original land-only 01s or 03s SRTM tiles
  pygmt/datasets/earth_relief.py
  pygmt/tests/test_datasets_earth_relief.py
Labels: feature

#1064 Improve documentation in scatter3d.py gallery example
  examples/gallery/3d_plots/scatter3d.py
Labels: documentation, skip-changelog

#1069 CI: Install sphinx-gallery in Tests workflow to increase code coverage
  .github/workflows/ci_tests.yaml
Labels: maintenance, skip-changelog

#1036 Initialize data version control for managing test images
  .dvc/.gitignore
  .dvc/config
  .dvcignore
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .gitignore
  CONTRIBUTING.md
  MAINTENANCE.md
  environment.yml
  pygmt/tests/baseline/test_image.png
  pygmt/tests/baseline/test_image.png.dvc
  pygmt/tests/baseline/test_logo.png
  pygmt/tests/baseline/test_logo.png.dvc
  pygmt/tests/baseline/test_logo_on_a_map.png
  pygmt/tests/baseline/test_logo_on_a_map.png.dvc
  pygmt/tests/test_image.py
  pygmt/tests/test_logo.py
Labels: maintenance

#1079 Fix the next release version in Release Draft template
  .github/release-drafter.yml
Labels: maintenance

#1077 Configure codecov project and patch status settings
  .github/codecov.yml
Labels: maintenance, skip-changelog

#1084 Move class config to pygmt/src/config.py
  pygmt/__init__.py
  pygmt/modules.py
  pygmt/src/__init__.py
  pygmt/src/config.py
Labels: maintenance, skip-changelog

#1083 Add dvc to CONTRIBUTING.md under Testing your code
  CONTRIBUTING.md
Labels: documentation, skip-changelog

#1087 Rename pygmt/modules.py to pygmt/accessors.py
  pygmt/__init__.py
  pygmt/accessors.py
  pygmt/src/config.py
  pygmt/src/x2sys_init.py
Labels: maintenance, skip-changelog

#1085 CI: Add srtm_tiles.nc to cache data
  .github/workflows/cache_data.yaml
Labels: maintenance, skip-changelog

#1089 Add alias 'registration' to methods blockmean, info, grdfilter, surface
  pygmt/helpers/decorators.py
  pygmt/src/blockmedian.py
  pygmt/src/grdfilter.py
  pygmt/src/info.py
  pygmt/src/surface.py
Labels: enhancement

#1088 Add list of aliases to grdinfo docstring
  pygmt/src/grdinfo.py
Labels: documentation, skip-changelog

#1056 Clarify docs on how to start contributing
  CONTRIBUTING.md
Labels: documentation, skip-changelog

#1093 Update docstring in borders gallery example
  examples/gallery/maps/borders.py
Labels: documentation, skip-changelog

#1090 Add alias 'aspatial' to methods blockmedian, info, plot, plot3d, surface
  pygmt/helpers/decorators.py
  pygmt/src/blockmedian.py
  pygmt/src/info.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/surface.py
Labels: enhancement

#1097 Add fractures_06.txt to cache data
  .github/workflows/cache_data.yaml
Labels: maintenance, skip-changelog

#1065 Allow passing a array as intensity for plot
  pygmt/src/plot.py
  pygmt/tests/baseline/test_plot_varying_intensity.png.dvc
  pygmt/tests/test_plot.py
Labels: enhancement

#1100 Fix documentation for alias 'aspatial'
  pygmt/helpers/decorators.py
Labels: documentation, maintenance, skip-changelog

#1108 Update the check_figures_equal testing section in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1110 Rename tutorial.py to samples.py
  pygmt/datasets/__init__.py
  pygmt/datasets/samples.py
  pygmt/tests/test_datasets_samples.py
Labels: maintenance, skip-changelog

#1105 Update "GMT Dev Tests" workflow to test macOS-11.0 and pre-release Python packages
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance

#1109 Allow passing an array as intensity for plot3d
  pygmt/src/plot3d.py
  pygmt/tests/baseline/test_plot3d_varying_intensity.png.dvc
  pygmt/tests/test_plot3d.py
Labels: enhancement

#1101 Add new function to load fractures sample data
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/samples.py
  pygmt/tests/test_datasets_samples.py
Labels: final review call, maintenance

#1074 NEP29: Set minimum required versions to NumPy 1.17+ and Python 3.7+
  .github/workflows/ci_tests.yaml
  MAINTENANCE.md
  README.rst
  doc/install.rst
  environment.yml
  requirements.txt
  setup.py
Labels: deprecation, final review call

#804 Wrap solar
  doc/api/index.rst
  examples/gallery/embellishments/solar.py
  pygmt/figure.py
  pygmt/src/__init__.py
  pygmt/src/solar.py
  pygmt/tests/baseline/test_solar_set_terminator_datetime.png.dvc
  pygmt/tests/baseline/test_solar_terminators.png.dvc
  pygmt/tests/test_solar.py
Labels: feature

#1124 Fix "pandas.Dataframe" to "pandas.DataFrame" in pygmt/datasets/samples.py
  pygmt/datasets/samples.py
Labels: documentation, skip-changelog

#1127 Clarify interplay of spacing and per_column in info
  pygmt/src/info.py
Labels: documentation

#1128 Replace argument with parameter in coastlines tutorial
  examples/tutorials/coastlines.py
Labels: documentation, skip-changelog

#1137 Use smaller figure dimensions in the "Plot lines" tutorial
  examples/tutorials/lines.py
Labels: documentation

#1095 Exclude .dvc and .dvcignore from source package
  MANIFEST.in
Labels: maintenance

#1139 Change the title of the "Set the region" and "Plot lines" tutorials
  examples/tutorials/lines.py
  examples/tutorials/regions.py
Labels: documentation, skip-changelog

#1104 Create Github Action workflow for reporting DVC image diffs
  .github/workflows/dvc-diff.yml
  MAINTENANCE.md
  pygmt/tests/baseline/test_legend_entries.png
  pygmt/tests/baseline/test_legend_entries.png.dvc
  pygmt/tests/test_legend.py
Labels: maintenance

#1144 Fix dvc-diff workflow for multiple changes
  .github/workflows/dvc-diff.yml
Labels: maintenance, skip-changelog

#1146 Migrate test_contour to use dvc
  pygmt/tests/baseline/test_contour_from_file.png
  pygmt/tests/baseline/test_contour_from_file.png.dvc
  pygmt/tests/baseline/test_contour_matrix.png
  pygmt/tests/baseline/test_contour_matrix.png.dvc
  pygmt/tests/baseline/test_contour_vec.png
  pygmt/tests/baseline/test_contour_vec.png.dvc
  pygmt/tests/test_contour.py
Labels: maintenance, skip-changelog

#1103 Migrate Figure.coast tests to dvc
  pygmt/tests/baseline/test_coast.png
  pygmt/tests/baseline/test_coast_aliases.png
  pygmt/tests/baseline/test_coast_dcw_list.png.dvc
  pygmt/tests/baseline/test_coast_dcw_single.png.dvc
  pygmt/tests/baseline/test_coast_iceland.png
  pygmt/tests/baseline/test_coast_region.png.dvc
  pygmt/tests/baseline/test_coast_world_mercator.png
  pygmt/tests/baseline/test_coast_world_mercator.png.dvc
  pygmt/tests/test_coast.py
Labels: maintenance, skip-changelog

#1133 Migrate test_figure_shift_origin to dvc
  pygmt/tests/baseline/test_figure_shift_origin.png.dvc
  pygmt/tests/baseline/test_shift_origin.png
  pygmt/tests/test_figure.py
Labels: maintenance, skip-changelog

#1150 Bump sphinx_rtd_theme from 0.4.3 to 0.5.1
  .github/workflows/ci_docs.yml
  environment.yml
Labels: maintenance, skip-changelog
