Repository GenericMappingTools/pygmt, pull requests merged in 2021-07, with the labels that each got.

#1366 Fix two warnings with pylint v2.9.3
  pygmt/src/meca.py
  pygmt/tests/test_clib.py
Labels: maintenance, skip-changelog

#1376 Change invalid input conditions in grdtrack
  pygmt/src/grdtrack.py
Labels: bug

#1308 Add development toctree and PyGMT team page
  doc/_static/style.css
  doc/index.rst
  doc/team.md
Labels: documentation, final review call

#1369 Fix bug so that x2sys_cross accepts dataframes with NaN values
  pygmt/src/x2sys_cross.py
  pygmt/tests/test_x2sys_cross.py
Labels: bug

#1339 Restructure contributing.md to separate docs/general info from contributing code section
  doc/contributing.md
Labels: documentation, final review call

#1385 Specify header sizes in style.css and remove bold formatting from contributing.md headers
  doc/_static/style.css
  doc/contributing.md
Labels: final review call, maintenance, skip-changelog

#1387 A gallery example for the contour method
  examples/gallery/images/contours.py
Labels: documentation, final review call, scipy-sprint

#1390 Add return statement to grdclip and grdgradient docstring
  pygmt/src/grdclip.py
  pygmt/src/grdgradient.py
Labels: documentation

#1394 Add how to use different colormaps for subplots
  examples/gallery/embellishments/colorbars_multiple.py
Labels: documentation, final review call
