Repository GenericMappingTools/pygmt, pull requests merged in 2022-07, with the labels that each got.

#1982 Update Max's name
  AUTHORS.md
  CITATION.cff
  CODE_OF_CONDUCT.md
  README.rst
  doc/changes.md
  doc/team.md
Labels: documentation, skip-changelog

#1985 NEP29: Set minimum required version to NumPy 1.20+
  .github/workflows/ci_tests.yaml
  README.rst
  doc/install.rst
  environment.yml
  requirements.txt
  setup.py
Labels: deprecation

#1981 Changelog entry for v0.7.0
  CITATION.cff
  README.rst
  doc/_static/version_switch.js
  doc/changes.md
Labels: maintenance, skip-changelog

#1784 Rewrite the meca function to support offsetting and labeling beachballs
  pygmt/src/meca.py
  pygmt/tests/baseline/test_meca_dict_eventname.png.dvc
  pygmt/tests/baseline/test_meca_dict_offset.png.dvc
  pygmt/tests/baseline/test_meca_dict_offset_eventname.png.dvc
  pygmt/tests/baseline/test_meca_spec_dict_list.png.dvc
  pygmt/tests/test_meca.py
Labels: enhancement

#1992 Remove the feedback call for whoever building the GMT sources
  doc/install.rst
Labels: documentation, skip-changelog, final review call

#1996 Fix an incorrect link in external resources page
  doc/external_resources.md
Labels: documentation, skip-changelog

#1965 Use consistent names for pytest fixtures
  pygmt/tests/test_clib.py
  pygmt/tests/test_contour.py
  pygmt/tests/test_dimfilter.py
  pygmt/tests/test_filter1d.py
  pygmt/tests/test_grdclip.py
  pygmt/tests/test_grdcut.py
  pygmt/tests/test_grdfill.py
  pygmt/tests/test_grdfilter.py
  pygmt/tests/test_grdgradient.py
  pygmt/tests/test_grdhisteq.py
  pygmt/tests/test_grdlandmask.py
  pygmt/tests/test_grdproject.py
  pygmt/tests/test_grdsample.py
  pygmt/tests/test_grdtrack.py
  pygmt/tests/test_histogram.py
  pygmt/tests/test_plot.py
  pygmt/tests/test_sphdistance.py
  pygmt/tests/test_sphinterpolate.py
  pygmt/tests/test_surface.py
  pygmt/tests/test_triangulate.py
  pygmt/tests/test_xyz2grd.py
Labels: maintenance, final review call

#1988 Refactor grdview and grdimage to use virtualfile_from_data
  pygmt/src/grdimage.py
  pygmt/src/grdview.py
Labels: maintenance, final review call

#2003 Fix author list of PyGMT v0.7.0
  README.rst
Labels: maintenance, skip-changelog

#2005 Fix figure labels in grdhisteq tutorial
  examples/tutorials/advanced/grid_equalization.py
Labels: documentation, skip-changelog, final review call

#2011 Fix typos in docs
  examples/projections/README.txt
Labels: maintenance, skip-changelog

#1997 Update "Making your first figure" tutorial
  examples/get-started/first_figure.py
Labels: documentation, final review call

#2015 Fix typo in Maintainers Guide
  doc/maintenance.md
Labels: documentation, skip-changelog

#2020 Use the org-wide code of conduct
  .github/config.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.rst
  doc/conf.py
  doc/contributing.md
Labels: maintenance

#2018 Consistent usage of whitespaces across gallery and tutorial examples
  examples/gallery/3d_plots/scatter3d.py
  examples/gallery/embellishments/colorbar.py
  examples/gallery/histograms/blockm.py
  examples/gallery/histograms/histogram.py
  examples/gallery/images/grdclip.py
  examples/gallery/images/grdgradient.py
  examples/gallery/lines/linefronts.py
  examples/gallery/lines/linestyles.py
  examples/gallery/lines/roads.py
  examples/gallery/lines/vector_heads_tails.py
  examples/gallery/symbols/points_categorical.py
  examples/gallery/symbols/points_transparency.py
  examples/tutorials/basics/frames.py
  examples/tutorials/basics/plot.py
Labels: documentation

#2024 Remove title/label-whitespaces-trick from tests
  pygmt/tests/test_basemap.py
  pygmt/tests/test_config.py
Labels: maintenance, skip-changelog, final review call

#2025 Fix a few typos in the examples
  examples/gallery/embellishments/solar.py
  examples/gallery/lines/great_circles.py
  examples/get-started/first_figure.py
  examples/tutorials/advanced/configuration.py
  examples/tutorials/advanced/contour_map.py
  examples/tutorials/advanced/date_time_charts.py
  examples/tutorials/advanced/grid_equalization.py
  examples/tutorials/advanced/insets.py
  examples/tutorials/advanced/vectors.py
Labels: documentation, final review call

#2028 Replace earth by Earth
  examples/projections/azim/azim_gnomonic.py
Labels: documentation, skip-changelog

#2032 Add reference to special symbols in text tutorial
  examples/tutorials/basics/text.py
Labels: documentation, skip-changelog

#1859 Migrate Continuous Documentation from Vercel to Readthedocs
  .readthedocs.yaml
  MANIFEST.in
  ci/requirements/docs.yml
  doc/conf.py
  doc/contributing.md
  doc/maintenance.md
  package.json
  vercel.json
Labels: maintenance, final review call
