Repository GenericMappingTools/pygmt, pull requests merged in 2022-01, with the labels that each got.

#1690 Update copyright year to 2022
  LICENSE.txt
Labels: maintenance, skip-changelog

#1688 Add an "add a title" to starter tutorial
  examples/get-started/first_figure.py
Labels: documentation, final review call

#1692 Add a test to check the incols parameter works for vector inputs
  pygmt/tests/test_info.py
Labels: maintenance, skip-changelog

#1656 Remove xfail from passing grdimage tests
  pygmt/tests/test_grdimage.py
Labels: maintenance, skip-changelog

#1694 Temporarily pin dvc and use verbose pull
  .github/workflows/ci_tests.yaml
Labels: maintenance, skip-changelog

#1685 Use a single function for loading any sample dataset
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/samples.py
  pygmt/tests/test_datasets_samples.py
Labels: feature, deprecation

#1673 Figure.psconvert: Add new aliases and deprecate parameter "icc_gray" (remove in v0.8.0)
  pygmt/figure.py
  pygmt/tests/test_figure.py
Labels: enhancement, final review call

#1696 Add gallery example showing usage of project
  examples/gallery/lines/great_circles.py
Labels: documentation, final review call

#1701 NEP29: Test PyGMT on NumPy 1.22
  .github/workflows/ci_tests.yaml
Labels: maintenance

#1702 Mark test_grdimage_file as xfail for GMT Dev Tests
  pygmt/tests/test_grdimage.py
Labels: maintenance, skip-changelog, final review call

#1703 Mark 4 legend tests as xfail for GMT Dev Tests
  pygmt/tests/test_legend.py
Labels: maintenance, skip-changelog

#1700 Update note on related projects
  README.rst
Labels: documentation, skip-changelog

#1709 Fix sphinx warnings about gmt term
  doc/api/index.rst
  pygmt/figure.py
Labels: maintenance, skip-changelog, final review call

#1689 Add inline example for grdcut
  pygmt/src/grdcut.py
Labels: documentation, final review call

#1712 CI: Pull baseline images before building GMT
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog, final review call

#1714 Unpin dvc
  .github/workflows/ci_tests.yaml
Labels: maintenance, skip-changelog
