Repository GenericMappingTools/pygmt, pull requests merged in 2022-06, with the labels that each got.

#1924 Add inline code examples to contributing guidelines
  doc/contributing.md
Labels: documentation, final review call

#1940 Fix a linting issue with pylint 2.14.0
  pygmt/src/meca.py
Labels: maintenance, skip-changelog

#1937 Redesign the team gallery using sphinx-design's card directive
  .github/workflows/ci_docs.yml
  doc/_static/style.css
  doc/conf.py
  doc/team.md
  environment.yml
Labels: documentation, final review call

#1867 grdtrack: Fix the bug when profile is given
  pygmt/src/grdtrack.py
  pygmt/tests/test_grdtrack.py
Labels: bug, final review call

#1944 Simplify TestPyPI install instructions to just extra-index-url
  doc/install.rst
Labels: documentation, skip-changelog

#1934 Improvement of two gallery examples regarding categorical colormaps
  examples/gallery/3d_plots/scatter3d.py
  examples/gallery/symbols/points_categorical.py
Labels: documentation, final review call

#1941 Add thumbnail images to the external resources page
  doc/external_resources.md
Labels: documentation, final review call

#1945 Set setuptools_scm fallback_version to follow PEP440
  pyproject.toml
Labels: maintenance, final review call

#1652 Wrap binstats
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/helpers/testing.py
  pygmt/src/__init__.py
  pygmt/src/binstats.py
  pygmt/tests/test_binstats.py
Labels: feature, final review call

#1952 Fix typos in workflows
  .github/workflows/cache_data.yaml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
Labels: documentation, skip-changelog

#1949 Update pylint's homepage to https://pylint.pycqa.org
  doc/contributing.md
Labels: maintenance, skip-changelog

#1950 Update the description of setting titles in tutorial
  examples/get-started/first_figure.py
Labels: documentation, skip-changelog, final review call

#1954 Add inline example for grdfill
  pygmt/src/grdfill.py
Labels: documentation, final review call

#1955 Split up functions for loading datasets
  pygmt/datasets/samples.py
Labels: maintenance, final review call

#1958 Add yvonnefroehlich to `AUTHORS.md`
  AUTHORS.md
Labels: maintenance, skip-changelog

#1956 Add inline example to dimfilter
  pygmt/src/dimfilter.py
Labels: documentation, final review call

#1918 Update GMT Dev Tests workflow to test on macOS-12 and ubuntu-22.04
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance

#1963 Support passing data in numpy int8, int16, uint8 and uint16 dtypes to GMT
  pygmt/clib/session.py
  pygmt/tests/test_clib.py
  pygmt/tests/test_clib_put_matrix.py
  pygmt/tests/test_clib_put_vector.py
Labels: enhancement, final review call

#1971 Add two new PyGMT tutorials to external resources
  doc/external_resources.md
Labels: documentation, final review call

#1961 Add a sample dataset MaunaLoa_CO2
  pygmt/datasets/samples.py
  pygmt/tests/test_datasets_samples.py
Labels: enhancement

#1974 Updated Andre Belem in AUTHORS.md
  AUTHORS.md
Labels: maintenance, skip-changelog, final review call

#1976 pygmt.surface: Remove parameter 'outfile', use 'outgrid' instead
  pygmt/src/surface.py
  pygmt/tests/test_surface.py
Labels: deprecation

#1975 Figure.histogram and pygmt.info: Remove parameter 'table', use 'data' instead
  pygmt/src/histogram.py
  pygmt/src/info.py
  pygmt/tests/test_info.py
Labels: deprecation

#1967 Add instructions to install PyGMT using mamba
  README.rst
  doc/install.rst
Labels: documentation

#1977 Figure.wiggle: Remove parameter 'columns', use 'incols' instead.
  pygmt/src/wiggle.py
  pygmt/tests/test_wiggle.py
Labels: deprecation, final review call

#1931 inset: Add aliases for R and J and fix two examples
  examples/gallery/embellishments/inset_rectangle_region.py
  examples/tutorials/advanced/insets.py
  pygmt/src/inset.py
Labels: enhancement, final review call

#1980 Exclude researchgate when checking links
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog

#1962 Update fixture import and docstring in test_filter1d.py
  pygmt/tests/test_filter1d.py
Labels: documentation, skip-changelog, final review call

#1978 blockm/contour/plot/plot3d/rose/surface/wiggle: Change the parameter order of data array and input arrays
  pygmt/helpers/__init__.py
  pygmt/helpers/decorators.py
  pygmt/src/blockm.py
  pygmt/src/contour.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/rose.py
  pygmt/src/surface.py
  pygmt/src/wiggle.py
Labels: deprecation
