Repository GenericMappingTools/pygmt, pull requests merged in 2022-10, with the labels that each got.

#2141 Fix typos in API documentation
  doc/maintenance.md
  pygmt/src/contour.py
  pygmt/src/grdcontour.py
Labels: documentation, skip-changelog, final review call

#2149 Add ternary.txt to cached files
  pygmt/helpers/testing.py
Labels: maintenance, skip-changelog

#2142 Add inline example for coast
  pygmt/src/coast.py
Labels: documentation, final review call

#2136 Improve instructions about setting GMT_LIBRARY_PATH env variable
  doc/install.rst
Labels: documentation

#2146 Add inline example for grdimage
  pygmt/src/grdimage.py
Labels: documentation

#2148 Add inline example for grdcontour
  pygmt/src/grdcontour.py
Labels: documentation, final review call

#2152 Improve comments in example of Cartesian linear projection
  examples/projections/nongeo/cartesian_linear.py
Labels: documentation, skip-changelog, final review call

#2153 Add instructions to install pygmt kernel for Jupyter users
  doc/install.rst
Labels: documentation

#1818 Add GEBCO data source to load_earth_relief
  pygmt/datasets/earth_relief.py
  pygmt/helpers/testing.py
  pygmt/tests/test_datasets_earth_relief.py
Labels: feature, final review call

#2159 SVG format is not supported in psconvert with ghostscript 9.16+
  pygmt/figure.py
Labels: documentation

#2154 Improve comments in example of Cartesian logarthmic projection
  examples/projections/nongeo/cartesian_logarithmic.py
Labels: documentation, skip-changelog, final review call

#2155 Improve comments in example of Cartesian power projection
  examples/projections/nongeo/cartesian_power.py
Labels: documentation, skip-changelog

#2145 Add inline example for grd2cpt
  pygmt/src/grd2cpt.py
Labels: documentation

#2158 doc: Set different html_baseurl for stable and dev versions
  doc/conf.py
Labels: maintenance, final review call

#2170 Figure.psconvert: Check if the given prefix is valid
  pygmt/figure.py
  pygmt/tests/test_psconvert.py
Labels: enhancement, final review call

#2160 Figure.savefig: Raise a FileNotFoundError if the parent directory doesn't exist
  pygmt/figure.py
  pygmt/tests/test_figure.py
Labels: enhancement

#2175 Fix typos in Contributors Guide and Maintainers Guide
  doc/contributing.md
  doc/maintenance.md
Labels: documentation, skip-changelog, final review call

#2110 Improve example for Polar projection
  examples/projections/nongeo/polar.py
Labels: documentation, skip-changelog, final review call

#2126 Add intro tutorial section for creating contour map
  examples/get-started/contour-map.py
  pygmt/helpers/testing.py
Labels: documentation
