Repository GenericMappingTools/pygmt, pull requests merged in 2022-08, with the labels that each got.

#2033 Adjust titles of Oblique Mercator projection examples
  examples/projections/cyl/cyl_oblique_mercator_1.py
  examples/projections/cyl/cyl_oblique_mercator_2.py
  examples/projections/cyl/cyl_oblique_mercator_3.py
  examples/projections/table/README.txt
Labels: documentation, final review call

#2035 Fix typos in cylindrical projection examples
  examples/projections/cyl/cyl_oblique_mercator_3.py
  examples/projections/cyl/cyl_universal_transverse_mercator.py
Labels: documentation, skip-changelog

#1990 Bump the GMT version in CI to 6.4.0
  .github/ISSUE_TEMPLATE/bump_gmt_checklist.md
  .github/workflows/cache_data.yaml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  ci/requirements/docs.yml
  environment.yml
Labels: maintenance

#2040 Fix typo in 'vectors.py'
  examples/tutorials/advanced/vectors.py
Labels: documentation, skip-changelog, final review call

#2039 Fix typo in 'contributing.md'
  doc/contributing.md
Labels: documentation, skip-changelog, final review call

#2041 Fix typos in API documentation
  pygmt/helpers/decorators.py
  pygmt/src/coast.py
  pygmt/src/contour.py
Labels: documentation, skip-changelog

#1883 Update baseline images for GMT 6.4
  pygmt/tests/baseline/test_basemap_compass.png.dvc
  pygmt/tests/baseline/test_basemap_polar.png.dvc
  pygmt/tests/baseline/test_basemap_utm_projection.png.dvc
  pygmt/tests/baseline/test_config_font_annot.png.dvc
  pygmt/tests/baseline/test_config_font_one.png.dvc
  pygmt/tests/baseline/test_config_format_date_map.png.dvc
  pygmt/tests/baseline/test_contour_vec.png.dvc
  pygmt/tests/baseline/test_geopandas_plot3d_default_cube.png.dvc
  pygmt/tests/baseline/test_geopandas_plot3d_non_default_circle.png.dvc
  pygmt/tests/baseline/test_grdcontour.png.dvc
  pygmt/tests/baseline/test_grdcontour_labels.png.dvc
  pygmt/tests/baseline/test_grdimage.png.dvc
  pygmt/tests/baseline/test_grdimage_file.png.dvc
  pygmt/tests/baseline/test_grdimage_global_subset.png.dvc
  pygmt/tests/baseline/test_grdimage_over_dateline.png.dvc
  pygmt/tests/baseline/test_grdimage_slice.png.dvc
  pygmt/tests/baseline/test_grdview_on_a_plane_with_colored_frontal_facade.png.dvc
  pygmt/tests/baseline/test_grdview_with_cmap_for_image_plot.png.dvc
  pygmt/tests/baseline/test_grdview_with_perspective.png.dvc
  pygmt/tests/baseline/test_grdview_with_perspective_and_zaxis_frame.png.dvc
  pygmt/tests/baseline/test_image.png.dvc
  pygmt/tests/baseline/test_inset_context_manager.png.dvc
  pygmt/tests/baseline/test_legend_default_position.png.dvc
  pygmt/tests/baseline/test_legend_entries.png.dvc
  pygmt/tests/baseline/test_legend_position.png.dvc
  pygmt/tests/baseline/test_legend_specfile.png.dvc
  pygmt/tests/baseline/test_logo.png.dvc
  pygmt/tests/baseline/test_makecpt_categorical.png.dvc
  pygmt/tests/baseline/test_makecpt_continuous.png.dvc
  pygmt/tests/baseline/test_makecpt_plot_colorbar_scaled_with_series.png.dvc
  pygmt/tests/baseline/test_makecpt_reverse_color_and_zsign.png.dvc
  pygmt/tests/baseline/test_makecpt_reverse_color_only.png.dvc
  pygmt/tests/baseline/test_makecpt_truncated_zlow_zhigh.png.dvc
  pygmt/tests/baseline/test_meca_spec_1d_array.png.dvc
  pygmt/tests/baseline/test_meca_spec_dataframe.png.dvc
  pygmt/tests/baseline/test_plot3d_colors_sizes_proj.png.dvc
  pygmt/tests/baseline/test_plot3d_matrix.png.dvc
  pygmt/tests/baseline/test_plot3d_ogrgmt_file_multipoint_default_style.png.dvc
  pygmt/tests/baseline/test_plot3d_ogrgmt_file_multipoint_non_default_style.png.dvc
  pygmt/tests/baseline/test_plot3d_projection.png.dvc
  pygmt/tests/baseline/test_plot3d_red_circles_zscale.png.dvc
  pygmt/tests/baseline/test_plot_colors_sizes_proj.png.dvc
  pygmt/tests/baseline/test_plot_matrix.png.dvc
  pygmt/tests/baseline/test_plot_shapefile.png.dvc
  pygmt/tests/baseline/test_rose_2d_array_multiple.png.dvc
  pygmt/tests/baseline/test_rose_2d_array_single.png.dvc
  pygmt/tests/baseline/test_solar_set_terminator_datetime.png.dvc
  pygmt/tests/baseline/test_solar_terminators.png.dvc
  pygmt/tests/baseline/test_text_fill.png.dvc
  pygmt/tests/baseline/test_text_justify_bottom_right_and_top_left.png.dvc
  pygmt/tests/baseline/test_text_multiple_lines_of_text.png.dvc
  pygmt/tests/baseline/test_text_position.png.dvc
  pygmt/tests/baseline/test_text_position_offset_with_line.png.dvc
  pygmt/tests/baseline/test_text_single_line_of_text.png.dvc
  pygmt/tests/baseline/test_velo_numpy_array_numeric_only.png.dvc
  pygmt/tests/baseline/test_velo_pandas_dataframe.png.dvc
  pygmt/tests/baseline/test_wiggle.png.dvc
  pygmt/tests/test_config.py
  pygmt/tests/test_makecpt.py
  pygmt/tests/test_plot.py
Labels: maintenance

#2045 CI: Let the GMT Dev Test workflow pull baseline images from the default branch
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog

#2049 Remove unused readme-example.png
  .github/readme-example.png
Labels: maintenance, skip-changelog

#2048 Fix typos in `psconvert` in the file `figure.py`
  pygmt/figure.py
Labels: documentation, skip-changelog, final review call

#2051 Use GMT-related term 'annotations' in example 'Color points by categories'
  examples/gallery/symbols/points_categorical.py
Labels: documentation, skip-changelog

#2055 Use consistently dots at the end of bullet points in 'Main Features'
  pygmt/__init__.py
Labels: documentation, skip-changelog

#2054 Cache @earth_relief_10m_g.grd file used in the documentation
  pygmt/helpers/testing.py
Labels: maintenance, skip-changelog

#2052 load_earth_relief() now returns gridline-registrated grids by default in GMT 6.4
  pygmt/accessors.py
  pygmt/clib/conversion.py
  pygmt/datasets/earth_relief.py
Labels: maintenance, final review call

#2057 NEP29: Test PyGMT on NumPy 1.23 and 1.21
  .github/workflows/ci_tests.yaml
Labels: maintenance

#2060 Fix typos in Contributors Guide
  doc/contributing.md
Labels: documentation, skip-changelog

#2058 Fix typos in documentation for Polar projection
  examples/projections/nongeo/polar.py
Labels: documentation, skip-changelog

#2064 Fix typos in subsection 'Code Style' of the Contributors Guide
  doc/contributing.md
Labels: documentation, skip-changelog

#2063 Replace 'argument' by 'parameter' in tutorial 'Plotting Earth relief'
  examples/tutorials/advanced/earth_relief.py
Labels: documentation, skip-changelog

#1847 Replace flake8 with flakeheaven
  .github/workflows/format-command.yml
  .github/workflows/style_checks.yaml
  Makefile
  doc/contributing.md
  environment.yml
  examples/gallery/embellishments/colorbar.py
  pyproject.toml
  setup.cfg
Labels: maintenance, final review call

#1848 Migrate project metadata from setup.py to pyproject.toml following PEP621
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  Makefile
  doc/maintenance.md
  pyproject.toml
  setup.py
Labels: maintenance

#2066 Lint docstrings using docformatter 1.5.0
  pygmt/src/filter1d.py
  pygmt/src/histogram.py
  pygmt/src/nearneighbor.py
Labels: maintenance, skip-changelog

#2065 Remove json files from paths-ignore list in workflows
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog

#2074 Fix tiny typo in custom symbols gallery example
  examples/gallery/symbols/custom_symbols.py
Labels: documentation, skip-changelog

#2061 Improve documentation of UTM projection
  examples/projections/cyl/cyl_universal_transverse_mercator.py
Labels: documentation

#2070 Fix typos in first_figure.py
  examples/get-started/first_figure.py
Labels: documentation, skip-changelog, final review call

#2077 Replace 'argument' by 'parameter' in 'contour_map.py' and 'lines.py'
  examples/tutorials/advanced/contour_map.py
  examples/tutorials/basics/lines.py
Labels: documentation, skip-changelog, final review call

#2076 Figure.psconvert: Add a new alias gs_path (-G)
  pygmt/figure.py
Labels: enhancement, final review call

#2080 Remove tomli from GMT Tests and GMT Dev Tests workflows
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance

#2075 Mark tests test_accessor_sliced_datacube and test_grdview_drapegrid_dataarray as xfail
  pygmt/tests/test_accessor.py
  pygmt/tests/test_grdview.py
Labels: maintenance, skip-changelog

#2069 Add optional dependencies to pyproject.toml
  doc/install.rst
  pyproject.toml
Labels: maintenance, final review call

#2053 Add SciPy 2022 talk to presentations
  doc/_static/scipy2022-youtube-thumbnail.jpg
  doc/overview.rst
Labels: documentation

#2081 Add badges for conda package version, license and twitter
  README.rst
Labels: maintenance

#2083 Fix typos in tutorial 'Making subplots'
  examples/tutorials/advanced/subplots.py
Labels: documentation, final review call

#2043 Correct and consistent usage of 'function, 'method', and 'class'
  doc/api/index.rst
  doc/contributing.md
  examples/gallery/3d_plots/scatter3d.py
  examples/gallery/embellishments/colorbars_multiple.py
  examples/gallery/embellishments/inset.py
  examples/gallery/embellishments/inset_rectangle_region.py
  examples/gallery/histograms/blockm.py
  examples/gallery/images/grdclip.py
  examples/gallery/images/grdgradient.py
  examples/gallery/images/grdlandmask.py
  examples/gallery/lines/great_circles.py
  examples/gallery/symbols/points_categorical.py
  examples/get-started/first_figure.py
  examples/tutorials/advanced/configuration.py
  examples/tutorials/advanced/date_time_charts.py
  examples/tutorials/advanced/earth_relief.py
  examples/tutorials/advanced/grid_equalization.py
  examples/tutorials/advanced/insets.py
  examples/tutorials/advanced/subplots.py
  examples/tutorials/advanced/vectors.py
  examples/tutorials/basics/plot.py
  examples/tutorials/basics/regions.py
  pygmt/figure.py
  pygmt/src/grd2cpt.py
  pygmt/src/grdcut.py
  pygmt/src/grdhisteq.py
  pygmt/src/grdimage.py
  pygmt/src/grdinfo.py
  pygmt/src/grdview.py
  pygmt/src/inset.py
  pygmt/src/makecpt.py
  pygmt/src/subplot.py
  pygmt/src/x2sys_cross.py
  pygmt/src/x2sys_init.py
Labels: documentation, final review call

#2086 Use the Ubuntu 22.04 docker image for readthedocs
  .readthedocs.yaml
Labels: maintenance

#2078 Figure.show: Allow keyword arguments passed to Figure.psconvert
  pygmt/figure.py
Labels: enhancement, final review call

#2072 Move docformatter options from Makefile to pyproject.toml
  Makefile
  environment.yml
  pyproject.toml
Labels: final review call

#2082 Fix typos in syntax for highlighting
  doc/contributing.md
  pygmt/figure.py
  pygmt/src/dimfilter.py
  pygmt/src/grdgradient.py
  pygmt/src/grdimage.py
  pygmt/src/makecpt.py
  pygmt/src/select.py
  pygmt/src/which.py
Labels: documentation, skip-changelog

#2089 Update documentation of `pygmt.grd2cpt`
  pygmt/src/grd2cpt.py
Labels: documentation, skip-changelog

#2088 Update docstring of land and water gallery example
  examples/gallery/maps/land_and_water.py
Labels: documentation, skip-changelog

#2094 Fix tiny typo in syntax in documentation of `pygmt.Figure.meca`
  pygmt/src/meca.py
Labels: documentation, skip-changelog

#2093 Move blackdoc options to pyproject.toml
  Makefile
  pyproject.toml
Labels: maintenance

#2101 Use consistent quotes in dataset loading functions
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_relief.py
Labels: documentation, skip-changelog

#2102 Fix typos in coastlines.py, grd2cpt.py, and earth_age.py
  examples/tutorials/basics/coastlines.py
  pygmt/datasets/earth_age.py
  pygmt/src/grd2cpt.py
Labels: documentation, skip-changelog
