Repository GenericMappingTools/pygmt, pull requests merged in 2022-02, with the labels that each got.

#1715 Format with black 22.1.0
  examples/gallery/3d_plots/grdview_surface.py
  examples/gallery/basemaps/double_y_axes.py
  examples/gallery/images/contours.py
  examples/projections/nongeo/cartesian_logarithmic.py
  examples/projections/nongeo/cartesian_power.py
  examples/tutorials/basics/plot.py
  pygmt/tests/test_clib_loading.py
  pygmt/tests/test_contour.py
Labels: maintenance, skip-changelog

#1711 Add inline example for grdclip
  pygmt/src/grdclip.py
Labels: documentation, final review call

#1717 Quick conda install instructions in main README
  README.rst
Labels: documentation, final review call

#1727 Add load_static_earth_relief function for internal testing
  pygmt/helpers/testing.py
  pygmt/tests/test_helpers.py
Labels: maintenance, final review call

#1736 Add static_earth_relief to grd2cpt tests
  pygmt/tests/baseline/test_grd2cpt.png.dvc
  pygmt/tests/test_grd2cpt.py
Labels: maintenance, skip-changelog, final review call

#1738 Add static_earth_relief to grdclip tests
  pygmt/tests/test_grdclip.py
Labels: maintenance, skip-changelog, final review call

#1737 Add static_earth_relief to grd2xyz tests
  pygmt/tests/test_grd2xyz.py
Labels: maintenance, skip-changelog, final review call

#1743 Change test_grdfill.py to use static_earth_relief
  pygmt/tests/test_grdfill.py
Labels: maintenance, skip-changelog, final review call

#1751 Remove unused os import in test_grdcut.py
  pygmt/tests/test_grdcut.py
Labels: maintenance, skip-changelog

#1730 Add inline example for blockmedian
  pygmt/src/blockm.py
Labels: documentation, final review call

#1729 Add inline example for blockmean
  pygmt/src/blockm.py
Labels: documentation, final review call

#1753 Fix blockm inline example missing doctest skip
  pygmt/src/blockm.py
Labels: bug, documentation, skip-changelog

#1746 Change test_grdinfo.py to use static_earth_relief
  pygmt/tests/test_grdinfo.py
Labels: maintenance, skip-changelog, final review call

#1747 Change test_grdvolume.py to use static_earth_relief
  pygmt/tests/test_grdvolume.py
Labels: maintenance, skip-changelog, final review call

#1678 Change test_grdfilter.py to use static_earth_relief
  pygmt/tests/test_grdfilter.py
Labels: maintenance, skip-changelog, final review call

#1679 Change test_grdgradient.py to use static_earth_relief
  pygmt/tests/test_grdgradient.py
Labels: maintenance, skip-changelog, final review call

#1681 Change test_grdsample.py to use static_earth_relief
  pygmt/tests/test_grdsample.py
Labels: maintenance, skip-changelog

#1754 Update Code of Conduct to v2.1
  CODE_OF_CONDUCT.md
  README.rst
Labels: documentation, final review call

#1721 Add inline example for grdlandmask
  pygmt/src/grdlandmask.py
Labels: documentation, final review call

#1683 Change test_grdproject.py to use static_earth_relief
  pygmt/tests/test_grdproject.py
Labels: maintenance, skip-changelog, final review call

#1682 Use xarray.testing rather than pygmt.grdinfo in xyz2grd tests
  pygmt/tests/test_xyz2grd.py
Labels: maintenance, skip-changelog, final review call

#1760 Add Liam's 2021 ROSES video to learning resources
  doc/external_resources.md
Labels: documentation, final review call

#1724 Add inline example for grdsample
  pygmt/src/grdsample.py
Labels: documentation, final review call

#1761 Change session.py to use static_earth_relief
  pygmt/clib/session.py
Labels: maintenance, skip-changelog

#1741 Change test_grdcontour.py to use static_earth_relief
  pygmt/tests/baseline/test_grdcontour.png.dvc
  pygmt/tests/baseline/test_grdcontour_file.png.dvc
  pygmt/tests/baseline/test_grdcontour_interval_file_full_opts.png.dvc
  pygmt/tests/baseline/test_grdcontour_labels.png.dvc
  pygmt/tests/baseline/test_grdcontour_slice.png.dvc
  pygmt/tests/data/contours.txt
  pygmt/tests/test_grdcontour.py
Labels: maintenance, skip-changelog

#1752 Change test_grdview.py to use static_earth_relief
  pygmt/tests/baseline/test_grdview_drapegrid_dataarray.png.dvc
  pygmt/tests/baseline/test_grdview_grid_dataarray.png.dvc
  pygmt/tests/baseline/test_grdview_grid_file_with_region_subset.png.dvc
  pygmt/tests/baseline/test_grdview_on_a_plane.png.dvc
  pygmt/tests/baseline/test_grdview_on_a_plane_styled_with_facadepen.png.dvc
  pygmt/tests/baseline/test_grdview_on_a_plane_with_colored_frontal_facade.png.dvc
  pygmt/tests/baseline/test_grdview_surface_mesh_plot_styled_with_meshpen.png.dvc
  pygmt/tests/baseline/test_grdview_surface_plot_styled_with_contourpen.png.dvc
  pygmt/tests/baseline/test_grdview_with_cmap_for_image_plot.png.dvc
  pygmt/tests/baseline/test_grdview_with_cmap_for_perspective_surface_plot.png.dvc
  pygmt/tests/baseline/test_grdview_with_cmap_for_surface_monochrome_plot.png.dvc
  pygmt/tests/baseline/test_grdview_with_perspective.png.dvc
  pygmt/tests/baseline/test_grdview_with_perspective_and_zaxis_frame.png.dvc
  pygmt/tests/baseline/test_grdview_with_perspective_and_zscale.png.dvc
  pygmt/tests/baseline/test_grdview_with_perspective_and_zsize.png.dvc
  pygmt/tests/test_grdview.py
Labels: maintenance, skip-changelog, final review call

#1755 Migrate pylint settings from .pylintrc to pyproject.toml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .pylintrc
  MANIFEST.in
  pygmt/__init__.py
  pygmt/clib/session.py
  pygmt/helpers/testing.py
  pygmt/tests/test_datasets_samples.py
  pyproject.toml
Labels: maintenance

#1558 Unset GMT_DATA_SERVER and use the default value
  .github/workflows/cache_data.yaml
  package.json
Labels: maintenance, skip-changelog

#1764 Remove Liam's talk from the overview page
  doc/overview.rst
Labels: documentation

#1770 Fix docs workflow on Windows
  examples/tutorials/basics/plot.py
Labels: maintenance, skip-changelog

#1748 Change test_makecpt.py to use colorbar instead of grdimage
  pygmt/tests/baseline/test_makecpt_categorical.png.dvc
  pygmt/tests/baseline/test_makecpt_continuous.png.dvc
  pygmt/tests/baseline/test_makecpt_cyclic.png.dvc
  pygmt/tests/baseline/test_makecpt_plot_colorbar.png.dvc
  pygmt/tests/baseline/test_makecpt_plot_colorbar_scaled_with_series.png.dvc
  pygmt/tests/baseline/test_makecpt_plot_grid.png.dvc
  pygmt/tests/baseline/test_makecpt_plot_grid_scaled_with_series.png.dvc
  pygmt/tests/baseline/test_makecpt_plot_points.png.dvc
  pygmt/tests/baseline/test_makecpt_reverse_color_and_zsign.png.dvc
  pygmt/tests/baseline/test_makecpt_reverse_color_only.png.dvc
  pygmt/tests/baseline/test_makecpt_truncated_zlow_zhigh.png.dvc
  pygmt/tests/test_makecpt.py
Labels: maintenance, skip-changelog, final review call

#1771 Add a test to make sure the incols parameter works for pandas.DataFrame
  pygmt/tests/baseline/test_plot_dataframe_incols.png.dvc
  pygmt/tests/test_plot.py
Labels: maintenance, final review call
