Repository GenericMappingTools/pygmt, pull requests merged in 2022-09, with the labels that each got.

#2096 Fix typos in documentation of `pygmt.makecpt`
  pygmt/src/makecpt.py
Labels: documentation, skip-changelog, final review call

#2106 Set `Note` followed by a `:` into bold style in the documentation
  pygmt/datasets/earth_relief.py
  pygmt/helpers/decorators.py
  pygmt/src/grdimage.py
  pygmt/src/image.py
  pygmt/src/project.py
  pygmt/src/subplot.py
  pygmt/src/wiggle.py
  pygmt/src/x2sys_cross.py
Labels: documentation, skip-changelog, final review call

#2105 Complete inline example of `pygmt.Figure` class
  pygmt/figure.py
Labels: documentation, skip-changelog, final review call

#2104 Replace single by double quotation marks in documentation of `pygmt.Figure.velo`, `pygmt.grd2cpt`, `pygmt.Figure.subplot`
  pygmt/src/grd2cpt.py
  pygmt/src/subplot.py
  pygmt/src/velo.py
Labels: documentation, skip-changelog

#2107 Use SI units in gallery example 'Legend' and test example in Contributors Guide
  doc/contributing.md
  examples/gallery/embellishments/legend.py
Labels: documentation, skip-changelog

#2103 Replace 'option' by 'parameter' in documentation of `pygmt.Figure.velo`, `pygmt.select`, `pygmt.which`
  pygmt/src/select.py
  pygmt/src/velo.py
  pygmt/src/which.py
Labels: documentation, skip-changelog

#2108 Replace single by double quotation marks in API documentation
  pygmt/src/grdcontour.py
  pygmt/src/grdfilter.py
  pygmt/src/grdimage.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
Labels: documentation, skip-changelog

#2109 Add an empty setup.cfg file for backward compatibility with pip<21.3
  setup.cfg
Labels: maintenance, skip-changelog, final review call

#2112 Add PyOpenSci peer reviewed badge to main README.rst
  README.rst
Labels: documentation, final review call

#2114 Fix typos in docs and examples
  examples/gallery/lines/wiggle.py
  examples/tutorials/basics/regions.py
  pygmt/src/legend.py
  pygmt/src/solar.py
  pygmt/src/wiggle.py
Labels: documentation, skip-changelog

#1521 Add a gallery example showing the usage of vertical and horizontal bars
  examples/gallery/symbols/bars.py
Labels: documentation, final review call

#2079 Add a workflow and Makefile target to test old GMT versions every Tuesday
  .github/workflows/ci_tests_legacy.yaml
  Makefile
Labels: maintenance, final review call

#2091 Convert bug report markdown issue template into yaml configured form
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: documentation, final review call

#1838 pygmt.show_versions: Show GMT binary version and hide the Python interpreter path
  pygmt/__init__.py
  pygmt/clib/session.py
  pygmt/tests/test_clib.py
Labels: maintenance, upstream

#2090 Update documentation of `pygmt.Figure.rose`
  pygmt/src/rose.py
Labels: documentation, skip-changelog, final review call

#2023 Improve tutorial frames.py
  examples/tutorials/basics/frames.py
Labels: documentation, final review call

#1431 Wrap ternary
  doc/api/index.rst
  pygmt/figure.py
  pygmt/src/__init__.py
  pygmt/src/ternary.py
  pygmt/tests/baseline/test_ternary.png.dvc
  pygmt/tests/test_ternary.py
Labels: feature

#2119 Fix typos in API documentation
  pygmt/helpers/decorators.py
  pygmt/src/basemap.py
  pygmt/src/coast.py
  pygmt/src/grdproject.py
Labels: documentation, skip-changelog, final review call

#2118 Update documentation of `pygmt.project`
  pygmt/src/project.py
Labels: documentation, skip-changelog

#2120 Remove unnecessary typecheck settings for pylint
  pyproject.toml
Labels: maintenance, skip-changelog

#1932 Use longname placeholders in the docstrings for common options
  pygmt/figure.py
  pygmt/helpers/decorators.py
  pygmt/src/basemap.py
  pygmt/src/binstats.py
  pygmt/src/blockm.py
  pygmt/src/coast.py
  pygmt/src/colorbar.py
  pygmt/src/contour.py
  pygmt/src/dimfilter.py
  pygmt/src/grd2cpt.py
  pygmt/src/grd2xyz.py
  pygmt/src/grdclip.py
  pygmt/src/grdcontour.py
  pygmt/src/grdcut.py
  pygmt/src/grdfill.py
  pygmt/src/grdfilter.py
  pygmt/src/grdgradient.py
  pygmt/src/grdhisteq.py
  pygmt/src/grdimage.py
  pygmt/src/grdinfo.py
  pygmt/src/grdlandmask.py
  pygmt/src/grdproject.py
  pygmt/src/grdsample.py
  pygmt/src/grdtrack.py
  pygmt/src/grdview.py
  pygmt/src/grdvolume.py
  pygmt/src/histogram.py
  pygmt/src/image.py
  pygmt/src/info.py
  pygmt/src/inset.py
  pygmt/src/legend.py
  pygmt/src/logo.py
  pygmt/src/makecpt.py
  pygmt/src/meca.py
  pygmt/src/nearneighbor.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/project.py
  pygmt/src/rose.py
  pygmt/src/select.py
  pygmt/src/solar.py
  pygmt/src/sph2grd.py
  pygmt/src/sphdistance.py
  pygmt/src/sphinterpolate.py
  pygmt/src/subplot.py
  pygmt/src/surface.py
  pygmt/src/ternary.py
  pygmt/src/text.py
  pygmt/src/triangulate.py
  pygmt/src/velo.py
  pygmt/src/which.py
  pygmt/src/wiggle.py
  pygmt/src/x2sys_cross.py
  pygmt/src/x2sys_init.py
  pygmt/src/xyz2grd.py
Labels: maintenance, final review call

#2122 Fix typos in API documentation
  pygmt/figure.py
  pygmt/src/contour.py
  pygmt/src/grdcontour.py
  pygmt/src/grdtrack.py
  pygmt/src/meca.py
  pygmt/src/text.py
  pygmt/src/x2sys_cross.py
Labels: documentation, skip-changelog, final review call

#2124 Figure.histogram and Figure.ternary: Fix incorrect docstrings 'color' to 'fill'
  pygmt/helpers/decorators.py
  pygmt/src/histogram.py
  pygmt/src/ternary.py
Labels: documentation, skip-changelog, final review call

#2133 Fix typos in API documentation
  doc/contributing.md
  pygmt/helpers/decorators.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/solar.py
  pygmt/src/text.py
  pygmt/src/velo.py
Labels: documentation, skip-changelog

#2134 Fix default for `pen` parameter in API documentation
  pygmt/src/coast.py
  pygmt/src/solar.py
  pygmt/src/text.py
  pygmt/src/velo.py
Labels: documentation, skip-changelog
