Repository GenericMappingTools/pygmt, pull requests merged in 2022-04, with the labels that each got.

#1863 Update earth_relief test for SRTM15+ v2.4 release
  pygmt/tests/test_datasets_earth_relief.py
Labels: maintenance, skip-changelog

#1815 None shall not pass args_in_kwargs
  pygmt/helpers/utils.py
Labels: bug, final review call

#1837 Refractor build_arg_string to also deal with infile and outfile
  pygmt/helpers/utils.py
  pygmt/src/blockm.py
  pygmt/src/contour.py
  pygmt/src/grd2cpt.py
  pygmt/src/grd2xyz.py
  pygmt/src/grdclip.py
  pygmt/src/grdcontour.py
  pygmt/src/grdcut.py
  pygmt/src/grdfill.py
  pygmt/src/grdfilter.py
  pygmt/src/grdgradient.py
  pygmt/src/grdhisteq.py
  pygmt/src/grdimage.py
  pygmt/src/grdinfo.py
  pygmt/src/grdlandmask.py
  pygmt/src/grdproject.py
  pygmt/src/grdsample.py
  pygmt/src/grdtrack.py
  pygmt/src/grdview.py
  pygmt/src/grdvolume.py
  pygmt/src/histogram.py
  pygmt/src/image.py
  pygmt/src/info.py
  pygmt/src/legend.py
  pygmt/src/makecpt.py
  pygmt/src/meca.py
  pygmt/src/nearneighbor.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/project.py
  pygmt/src/rose.py
  pygmt/src/select.py
  pygmt/src/sph2grd.py
  pygmt/src/sphdistance.py
  pygmt/src/sphinterpolate.py
  pygmt/src/surface.py
  pygmt/src/text.py
  pygmt/src/triangulate.py
  pygmt/src/velo.py
  pygmt/src/which.py
  pygmt/src/wiggle.py
  pygmt/src/x2sys_cross.py
  pygmt/src/x2sys_init.py
  pygmt/src/xyz2grd.py
Labels: maintenance, final review call

#1858 Replace "module" by "method"
  doc/contributing.md
  doc/maintenance.md
  examples/gallery/lines/vector_heads_tails.py
  examples/get-started/README.txt
  examples/get-started/first_figure.py
  examples/projections/README.txt
  examples/tutorials/basics/frames.py
  pygmt/src/__init__.py
  pygmt/src/grd2cpt.py
  pygmt/src/grdimage.py
  pygmt/src/grdproject.py
  pygmt/src/grdview.py
  pygmt/src/makecpt.py
  pygmt/src/subplot.py
Labels: maintenance, skip-changelog

#1857 Allow passing None explicitly to pygmt functions Part 1
  pygmt/src/grd2cpt.py
  pygmt/src/grd2xyz.py
  pygmt/src/grdgradient.py
  pygmt/src/grdimage.py
  pygmt/src/grdview.py
  pygmt/src/makecpt.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/project.py
  pygmt/src/solar.py
  pygmt/src/text.py
  pygmt/src/velo.py
  pygmt/tests/test_grd2xyz.py
  pygmt/tests/test_grdgradient.py
  pygmt/tests/test_grdimage.py
  pygmt/tests/test_text.py
Labels: bug, final review call

#1862 Allow passing None explicitly to pygmt functions Part 2
  pygmt/src/nearneighbor.py
  pygmt/src/sphdistance.py
  pygmt/src/sphinterpolate.py
  pygmt/src/surface.py
  pygmt/src/text.py
  pygmt/src/xyz2grd.py
Labels: bug, final review call

#1831 Fix pathlib support for plot and plot3d
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/tests/test_plot.py
  pygmt/tests/test_plot3d.py
Labels: bug, final review call

#1868 NEP29: Run PyGMT tests and docs build on Python 3.10
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
Labels: maintenance, final review call

#1866 Let slash command /test-gmt-dev report job URL
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, final review call

#1872 Allow passing None explicitly to pygmt functions Part 3
  pygmt/figure.py
  pygmt/src/grdclip.py
  pygmt/src/grdcut.py
  pygmt/src/grdfill.py
  pygmt/src/grdfilter.py
  pygmt/src/grdlandmask.py
  pygmt/src/grdproject.py
  pygmt/src/grdsample.py
  pygmt/src/info.py
  pygmt/src/legend.py
  pygmt/src/sph2grd.py
  pygmt/src/sphdistance.py
  pygmt/src/xyz2grd.py
Labels: bug

#1821 Add a tutorial for grdhisteq
  examples/tutorials/advanced/grid_equalization.py
Labels: documentation, final review call

#1874 Changelog entry for v0.6.1
  CITATION.cff
  README.rst
  doc/_static/version_switch.js
  doc/changes.md
Labels: maintenance, skip-changelog, final review call

#1492 Wrap dimfilter
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/src/__init__.py
  pygmt/src/dimfilter.py
  pygmt/tests/test_dimfilter.py
Labels: feature

#1877 Move matplotlib import inside the check_figures_equal function
  .github/workflows/cache_data.yaml
  pygmt/helpers/testing.py
Labels: maintenance, skip-changelog

#1865 Pull dvc baseline images from gmt-6.4 branch to test GMT dev
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance

#1881 Fix the test_gmt_dev workflow to show URL
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog

#1882 Pull baseline images from the gmt-6.4 branch only for scheduled jobs
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog

#1894 Added alias for F in basemap
  pygmt/src/basemap.py
Labels: documentation, final review call

#1896 Remove unused gmt_version variable in tests
  pygmt/tests/test_grdimage.py
  pygmt/tests/test_legend.py
Labels: maintenance, skip-changelog

#1895 Mark test_accessor_sliced_datacube as xfail due to upstream bug
  pygmt/tests/test_accessor.py
Labels: maintenance, skip-changelog

#1906 Update GMT-6.4 baseline image for test_grdimage_global_subset
  pygmt/tests/baseline/test_grdimage_global_subset.png.dvc
Labels: maintenance, skip-changelog

#1905 Update GMT-6.4 baseline image for test_grdimage_over_dateline
  pygmt/tests/baseline/test_grdimage_over_dateline.png.dvc
Labels: maintenance, skip-changelog

#1904 Update GMT-6.4 baseline image for test_grdimage_file
  pygmt/tests/baseline/test_grdimage_file.png.dvc
Labels: maintenance, skip-changelog

#1903 Update GMT-6.4 baseline image for test_grdimage_slice
  pygmt/tests/baseline/test_grdimage_slice.png.dvc
Labels: maintenance, skip-changelog

#1902 Update GMT-6.4 baseline image for test_grdimage
  pygmt/tests/baseline/test_grdimage.png.dvc
Labels: maintenance, skip-changelog

#1901 Update GMT-6.4 baseline image for test_config tests
  pygmt/tests/baseline/test_config_font_annot.png.dvc
  pygmt/tests/baseline/test_config_font_one.png.dvc
  pygmt/tests/test_config.py
Labels: maintenance, skip-changelog

#1900 Update GMT-6.4 baseline image for test_inset_context_manager
  pygmt/tests/baseline/test_inset_context_manager.png.dvc
Labels: maintenance, skip-changelog

#1899 Update GMT-6.4 baseline image for test_makecpt_categorical
  pygmt/tests/baseline/test_makecpt_categorical.png.dvc
  pygmt/tests/test_makecpt.py
Labels: maintenance, skip-changelog

#1898 Update GMT-6.4 baseline image for test_legend_specfile
  pygmt/tests/baseline/test_legend_specfile.png.dvc
Labels: maintenance, skip-changelog

#1897 Update GMT-6.4 baseline image for test_plot_shapefile (#1888)
  pygmt/tests/baseline/test_plot_shapefile.png.dvc
  pygmt/tests/test_plot.py
Labels: maintenance, skip-changelog

#1909 basemap: Plotting frames if required parameters are not given
  pygmt/src/basemap.py
  pygmt/tests/baseline/test_basemap_required_args.png.dvc
  pygmt/tests/test_basemap.py
Labels: feature request
