Repository GenericMappingTools/pygmt, pull requests merged in 2022-11, with the labels that each got.

#2176 Replace "option" by "parameter" in tests
  pygmt/tests/test_coast.py
  pygmt/tests/test_info.py
  pygmt/tests/test_solar.py
Labels: documentation, skip-changelog

#2179 Fix docstrings for blackdoc v0.3.8 by adding newline after functions
  pygmt/helpers/decorators.py
  pygmt/helpers/testing.py
Labels: maintenance, skip-changelog

#2180 CI: Surround pytest>=6.0 with single quotes
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, skip-changelog

#2177 Figure.plot: Deprecate parameter "color" to "fill" (remove in v0.12.0)
  pygmt/src/plot.py
Labels: deprecation, final review call

#2178 Figure.plot3d: Deprecate parameter "color" to "fill" (remove in v0.12.0)
  pygmt/src/plot3d.py
Labels: deprecation, final review call

#2183 Correct syntax for `error_bar` of `pygmt.Figure.plot`
  pygmt/src/plot.py
Labels: documentation, skip-changelog

#2181 Figure.rose: Deprecate parameter color to fill (remove in v0.12.0)
  examples/gallery/histograms/rose.py
  pygmt/src/rose.py
  pygmt/tests/test_rose.py
Labels: deprecation

#2174 meca: Fix the bug when passing a dict of scalar values to the spec parameter
  pygmt/src/meca.py
  pygmt/tests/test_meca.py
Labels: bug, final review call

#2123 Update documentation of `select.py`
  pygmt/src/select.py
Labels: documentation, skip-changelog, final review call

#2186 Change "triple"/"quadruple" to "triplet"/"quadruplet" in the documentation
  examples/gallery/embellishments/colorbar.py
  pygmt/helpers/decorators.py
  pygmt/src/blockm.py
  pygmt/src/contour.py
  pygmt/src/nearneighbor.py
  pygmt/src/plot3d.py
  pygmt/src/project.py
  pygmt/src/surface.py
  pygmt/src/wiggle.py
Labels: documentation, skip-changelog, final review call

#1964 Figure.text: Deprecate parameter "incols" to "use_word" (remove in v0.10.0)
  pygmt/src/text.py
Labels: enhancement, final review call

#2189 Figure.plot: Update parameter 'color' to 'fill' in test_plot.py
  pygmt/tests/test_plot.py
Labels: maintenance, skip-changelog, final review call

#2195 Fix typos in earth_age.py
  pygmt/datasets/earth_age.py
Labels: maintenance, skip-changelog

#2193 Figure.plot3d: Update parameter 'color' to 'fill' in test_plot3d.py
  pygmt/tests/test_plot3d.py
Labels: maintenance, skip-changelog, final review call

#2191 Fix typos in tutorial and docs "text.py"
  examples/tutorials/basics/text.py
  pygmt/src/text.py
Labels: documentation, skip-changelog, final review call

#2197 Figure.meca: Fix typos in docs
  pygmt/src/meca.py
Labels: documentation, skip-changelog

#2162 load_earth_relief: Add the support of data source 'synbath'
  pygmt/datasets/earth_relief.py
  pygmt/helpers/testing.py
  pygmt/tests/test_datasets_earth_relief.py
Labels: feature, final review call

#2071 Deprecate xshift (X) and yshift (Y) aliases from all plotting modules (remove in v0.12.0)
  examples/gallery/3d_plots/scatter3d.py
  pygmt/helpers/decorators.py
  pygmt/src/basemap.py
  pygmt/src/coast.py
  pygmt/src/colorbar.py
  pygmt/src/contour.py
  pygmt/src/grdcontour.py
  pygmt/src/grdimage.py
  pygmt/src/grdview.py
  pygmt/src/histogram.py
  pygmt/src/image.py
  pygmt/src/legend.py
  pygmt/src/logo.py
  pygmt/src/meca.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/rose.py
  pygmt/src/solar.py
  pygmt/src/subplot.py
  pygmt/src/ternary.py
  pygmt/src/text.py
  pygmt/src/velo.py
  pygmt/src/wiggle.py
  pygmt/tests/test_config.py
  pygmt/tests/test_figure.py
Labels: deprecation, final review call

#2198 Figure.plot: Update parameter 'color' to 'fill' in test_legend.py and test_makecpt.py
  pygmt/tests/test_legend.py
  pygmt/tests/test_makecpt.py
Labels: maintenance, skip-changelog, final review call

#2207 Remove the maintainers field from pyproject.toml
  pyproject.toml
Labels: maintenance, skip-changelog

#2206 Figure.velo: Deprecate parameters "color" to "fill" and "uncertaintycolor" to "uncertaintyfill" (remove in v0.12.0)
  pygmt/src/velo.py
  pygmt/tests/test_velo.py
Labels: deprecation, final review call

#2201 Update parameter 'color' to 'fill' in examples and tutorials
  examples/gallery/3d_plots/scatter3d.py
  examples/gallery/basemaps/double_y_axes.py
  examples/gallery/embellishments/legend.py
  examples/gallery/histograms/blockm.py
  examples/gallery/images/track_sampling.py
  examples/gallery/lines/great_circles.py
  examples/gallery/lines/linefronts.py
  examples/gallery/lines/vector_heads_tails.py
  examples/gallery/lines/vector_styles.py
  examples/gallery/symbols/bars.py
  examples/gallery/symbols/basic_symbols.py
  examples/gallery/symbols/custom_symbols.py
  examples/gallery/symbols/datetime_inputs.py
  examples/gallery/symbols/multi_parameter_symbols.py
  examples/gallery/symbols/points.py
  examples/gallery/symbols/points_categorical.py
  examples/gallery/symbols/points_transparency.py
  examples/gallery/symbols/scatter.py
  examples/gallery/symbols/text_symbols.py
  examples/projections/nongeo/cartesian_logarithmic.py
  examples/projections/nongeo/cartesian_power.py
  examples/tutorials/advanced/date_time_charts.py
  examples/tutorials/advanced/vectors.py
  examples/tutorials/basics/plot.py
Labels: maintenance, skip-changelog

#2210 Fix a broken link in the contributing guides
  CONTRIBUTING.md
Labels: maintenance, skip-changelog

#2192 load_earth_relief: Add the support of data source 'GEBCOSI'
  pygmt/datasets/earth_relief.py
  pygmt/helpers/testing.py
  pygmt/tests/test_datasets_earth_relief.py
Labels: feature

#2202 Figure.meca: Fix beachball offsetting with dict/pandas inputs
  pygmt/src/meca.py
  pygmt/tests/test_meca.py
Labels: bug, final review call

#2212 Use remove_version keyword arguments in the deprecate_parameter decorator
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/rose.py
  pygmt/src/velo.py
Labels: maintenance, skip-changelog

#2214 Convert feature request issue template into yaml configured form
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: maintenance, final review call

#2213 pygmt.config: Support tab auto-completion for all GMT defaults
  pygmt/src/config.py
Labels: enhancement, final review call
