Repository GenericMappingTools/pygmt, pull requests merged in 2022-03, with the labels that each got.

#1768 Fix header links and sphinx warnings
  doc/api/index.rst
  doc/conf.py
  doc/contributing.md
  doc/install.rst
Labels: maintenance, skip-changelog, final review call

#1695 Fix UnicodeDecodeError with shapefiles for plot and plot3d
  pygmt/helpers/testing.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/tests/baseline/test_plot_shapefile.png.dvc
  pygmt/tests/test_plot.py
Labels: bug, final review call

#1769 Add a shorter video introduction to the home page
  README.rst
Labels: documentation, final review call

#1773 Consistently use the load_sample_data function in tests
  pygmt/tests/test_blockm.py
  pygmt/tests/test_blockmedian.py
  pygmt/tests/test_grdimage.py
  pygmt/tests/test_grdtrack.py
  pygmt/tests/test_nearneighbor.py
  pygmt/tests/test_rose.py
  pygmt/tests/test_select.py
  pygmt/tests/test_sphinterpolate.py
  pygmt/tests/test_x2sys_cross.py
  pygmt/tests/test_xyz2grd.py
Labels: maintenance, skip-changelog, final review call

#1762 Change test_grdtrack.py to use static_earth_relief
  pygmt/tests/data/track.txt
  pygmt/tests/test_grdtrack.py
Labels: maintenance, skip-changelog

#1756 Add inline example for select
  pygmt/src/select.py
Labels: documentation, final review call

#1776 Update the contributing guide about pushing changes to dvc and git
  doc/contributing.md
Labels: documentation, final review call

#1781 Update Wei Ji's affiliation to OSU
  AUTHORS.md
  CITATION.cff
Labels: maintenance, skip-changelog

#1782 Increase code coverage for grdtrack tests
  pygmt/tests/test_grdtrack.py
Labels: maintenance, skip-changelog, final review call

#1718 Add inline example for sph2grd
  pygmt/src/sph2grd.py
Labels: documentation, final review call

#1785 Update dataset links to the new remote-datasets site
  doc/conf.py
  examples/tutorials/advanced/earth_relief.py
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_relief.py
Labels: documentation, final review call

#1789 Fix test_plot_shapefile by downloading cache files first
  pygmt/tests/test_plot.py
Labels: maintenance, skip-changelog

#1790 Use pytest-doctestplus to skip some inline doctests
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  Makefile
  environment.yml
  pygmt/src/grdlandmask.py
Labels: maintenance

#1783 List key development dependencies to install for new contributors
  doc/contributing.md
  environment.yml
Labels: documentation, final review call

#1794 Remove grdimage, legend and plot3d xfail markers
  pygmt/tests/test_grdimage.py
  pygmt/tests/test_legend.py
  pygmt/tests/test_plot3d.py
Labels: maintenance, skip-changelog

#1798 Fix a typo in test_plot_shapefile
  pygmt/tests/test_plot.py
Labels: maintenance, skip-changelog

#1793 Update existing inline examples to the new doctest style
  pygmt/src/blockm.py
  pygmt/src/grd2xyz.py
  pygmt/src/grdclip.py
  pygmt/src/grdcut.py
  pygmt/src/grdgradient.py
  pygmt/src/grdproject.py
  pygmt/src/grdsample.py
  pygmt/src/inset.py
  pygmt/src/select.py
  pygmt/src/sph2grd.py
Labels: maintenance, skip-changelog, final review call

#1433 Wrap grdhisteq
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/src/__init__.py
  pygmt/src/grdhisteq.py
  pygmt/tests/test_grdhisteq.py
Labels: feature, final review call

#1792 Raise an exception if the given parameter is not recognized and is longer than 2 characters
  pygmt/helpers/utils.py
Labels: enhancement, final review call

#1725 Add inline example for grdtrack
  pygmt/src/grdtrack.py
Labels: documentation, final review call

#1804 Fix the spacing parameter and check required parameters in xyz2grd
  pygmt/src/xyz2grd.py
  pygmt/tests/test_xyz2grd.py
Labels: bug

#1806 Figure.contour/plot/plot3d/rose: Remove parameter "columns", use "incols" instead
  pygmt/src/contour.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/rose.py
  pygmt/tests/test_contour.py
  pygmt/tests/test_plot.py
  pygmt/tests/test_plot3d.py
  pygmt/tests/test_rose.py
Labels: deprecation, final review call

#1805 Fix the spacing parameter processing for many modules
  pygmt/src/blockm.py
  pygmt/src/grdfilter.py
  pygmt/src/grdlandmask.py
  pygmt/src/grdproject.py
  pygmt/src/nearneighbor.py
  pygmt/src/surface.py
Labels: bug, final review call

#1809 Figure.plot/plot3d: Remove parameter "sizes", use "size" instead
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/tests/test_plot.py
  pygmt/tests/test_plot3d.py
Labels: deprecation

#1811 Fix a broken link in documentation and exclude an invalid link
  .github/workflows/check-links.yml
  pygmt/datasets/earth_age.py
Labels: maintenance, skip-changelog

#1487 Allow passing arguments containing spaces into pygmt functions
  examples/gallery/embellishments/legend.py
  pygmt/figure.py
  pygmt/helpers/utils.py
  pygmt/src/config.py
  pygmt/src/subplot.py
  pygmt/src/text.py
  pygmt/tests/baseline/test_basemap_utm_projection.png.dvc
  pygmt/tests/baseline/test_config_format_date_map.png.dvc
  pygmt/tests/baseline/test_rose_no_sectors.png.dvc
  pygmt/tests/test_basemap.py
  pygmt/tests/test_config.py
  pygmt/tests/test_figure.py
  pygmt/tests/test_grdproject.py
  pygmt/tests/test_legend.py
  pygmt/tests/test_psconvert.py
  pygmt/tests/test_rose.py
Labels: bug, final review call

#1813 Use 'Note' rather than 'Notes' as docstring section header
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_relief.py
  pygmt/src/grdhisteq.py
Labels: documentation, skip-changelog

#1812 Standardize output types for grdhisteq methods
  pygmt/src/grdhisteq.py
  pygmt/tests/test_grdhisteq.py
Labels: bug, documentation, skip-changelog, final review call

#1719 Add inline example for xyz2grd
  pygmt/src/xyz2grd.py
Labels: documentation, final review call

#1726 Add inline example for grdvolume
  pygmt/src/grdvolume.py
Labels: documentation

#1822 Strengthen the release checklist and maintenance instructions
  .github/ISSUE_TEMPLATE/release_checklist.md
  doc/maintenance.md
Labels: documentation, maintenance, skip-changelog, final review call

#1826 Remove the GMT6.0 dependency information from README
  README.rst
Labels: documentation, skip-changelog, final review call

#1716 Add link to GMT full option list for grdproject, grdsample and project
  pygmt/src/grdimage.py
  pygmt/src/grdproject.py
  pygmt/src/grdsample.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/project.py
  pygmt/src/solar.py
  pygmt/src/text.py
  pygmt/src/wiggle.py
Labels: documentation, skip-changelog, final review call

#1823 Use the build package to build sdist and wheel distributions
  .github/workflows/cache_data.yaml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/publish-to-pypi.yml
  Makefile
  environment.yml
Labels: maintenance, final review call

#1842 Add regression test for grdfill crash
  pygmt/tests/test_grdfill.py
Labels: maintenance, skip-changelog, final review call

#1844 Format author affiliations in CITATION.cff and AUTHORS.md
  AUTHORS.md
  CITATION.cff
Labels: documentation

#1846 Let pygmt.show_versions() report geopandas version
  pygmt/__init__.py
Labels: maintenance

#1845 Migrate build system settings to pyproject.toml following pep517 and pep518
  .github/workflows/publish-to-pypi.yml
  pyproject.toml
  setup.py
Labels: maintenance

#1843 Fix workflows for slash commands /format and /test-gmt-dev
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/format-command.yml
Labels: maintenance, skip-changelog
