Repository GenericMappingTools/pygmt, pull requests merged in 2023-11, with the labels that each got.

#2787 Tests: Replace deprecated "np.random.seed()" with "np.random.Generator()" (NPY002 warning by ruff)
  pygmt/tests/test_io.py
  pygmt/tests/test_x2sys_cross.py
Labels: maintenance, skip-changelog

#2782 Enable ruff's NumPy-specific rules
  pyproject.toml
Labels: maintenance

#2799 Adjust documentation of roads example
  examples/gallery/lines/roads.py
Labels: documentation, skip-changelog

#2802 Fix typo in grid gradient example
  examples/gallery/images/grdgradient_shading.py
Labels: documentation, skip-changelog

#2803 Figure.velo: Update docstrings related to "fill" and "uncertaintyfill"
  pygmt/src/velo.py
Labels: documentation, skip-changelog

#2796 Add gallery example showing usage of polygon objects from a geopandas.GeoDataFrame (choropleth map)
  examples/gallery/maps/choropleth_map.py
Labels: documentation

#2805 Gallery example "choropleth map": Use code block separator "# %%"
  examples/gallery/maps/choropleth_map.py
Labels: documentation, skip-changelog

#2770 Use ruff format to ensure UNIX line endings in Python files
  Makefile
  pygmt/tests/test_basemap.py
  pygmt/tests/test_clib_loading.py
  pyproject.toml
Labels: maintenance

#2811 CI: Add glib as a dependency in GMT Dev Tests to build GMT source codes
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog

#2810 CI: Require at least one code block separator for example files in the Style Checks workflow
  .github/workflows/style_checks.yaml
  doc/contributing.md
Labels: maintenance, final review call

#2807 Remote datasets: Update file names of images
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_mask.py
  pygmt/datasets/earth_relief.py
Labels: documentation, skip-changelog

#2821 Tutorial "Plotting Earth relief": Fix typos
  examples/tutorials/advanced/earth_relief.py
Labels: documentation, skip-changelog

#2818 Run 'make clean' to delete ruff's cache
  Makefile
Labels: maintenance, skip-changelog

#2824 CI: Pin Python to 3.12 in the environment.yml file for ReadTheDocs
  ci/requirements/docs.yml
Labels: maintenance, skip-changelog

#2819 Use ruff to format codes so remove black
  .github/workflows/format-command.yml
  .github/workflows/style_checks.yaml
  Makefile
  doc/contributing.md
  environment.yml
Labels: maintenance, final review call

#2815 Enable ruff's pylint rules (PL) and remove pylint
  .github/workflows/style_checks.yaml
  Makefile
  doc/conf.py
  doc/contributing.md
  environment.yml
  pygmt/__init__.py
  pygmt/clib/loading.py
  pygmt/clib/session.py
  pygmt/datasets/tile_map.py
  pygmt/figure.py
  pygmt/helpers/tempfile.py
  pygmt/helpers/testing.py
  pygmt/helpers/utils.py
  pygmt/sphinx_gallery.py
  pygmt/src/__init__.py
  pygmt/src/basemap.py
  pygmt/src/coast.py
  pygmt/src/colorbar.py
  pygmt/src/config.py
  pygmt/src/contour.py
  pygmt/src/grdcontour.py
  pygmt/src/grdhisteq.py
  pygmt/src/grdimage.py
  pygmt/src/grdview.py
  pygmt/src/histogram.py
  pygmt/src/image.py
  pygmt/src/inset.py
  pygmt/src/legend.py
  pygmt/src/logo.py
  pygmt/src/meca.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/rose.py
  pygmt/src/shift_origin.py
  pygmt/src/solar.py
  pygmt/src/subplot.py
  pygmt/src/ternary.py
  pygmt/src/text.py
  pygmt/src/tilemap.py
  pygmt/src/timestamp.py
  pygmt/src/triangulate.py
  pygmt/src/velo.py
  pygmt/src/wiggle.py
  pygmt/tests/test_clib.py
  pygmt/tests/test_clib_loading.py
  pygmt/tests/test_contour.py
  pygmt/tests/test_figure.py
  pygmt/tests/test_histogram.py
  pygmt/tests/test_plot.py
  pygmt/tests/test_x2sys_cross.py
  pygmt/tests/test_x2sys_init.py
  pyproject.toml
Labels: maintenance, final review call

#2816 Simplify checks like "x is not None or y is not None or z is not None"
  pygmt/src/text.py
Labels: maintenance, skip-changelog

#2828 Pin Python to 3.12 in environment.yml
  environment.yml
Labels: maintenance, skip-changelog

#2825 Enable ruff's flake8-bugbear (B) rules
  examples/gallery/images/rgb_image.py
  pygmt/clib/conversion.py
  pygmt/clib/session.py
  pygmt/tests/test_clib.py
  pyproject.toml
Labels: maintenance, final review call

#2830 Enable ruff's pandas-vet (PD) rules
  pygmt/clib/conversion.py
  pygmt/tests/test_blockmedian.py
  pygmt/tests/test_datasets_earth_vertical_gravity_gradient.py
  pygmt/tests/test_datasets_samples.py
  pygmt/tests/test_select.py
  pygmt/tests/test_surface.py
  pyproject.toml
Labels: maintenance

#2829 Enable ruff's flake8-simplify (SIM) rules
  pygmt/clib/session.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/load_remote_dataset.py
  pyproject.toml
Labels: maintenance, needs review

#2833 Recommend Miniforge instead of Mambaforge
  doc/contributing.md
  doc/install.rst
Labels: documentation

#2840 doc: Update the extlinks settings for Sphinx > 6
  doc/conf.py
Labels: maintenance, skip-changelog
