Repository GenericMappingTools/pygmt, pull requests merged in 2023-10, with the labels that each got.

#2705 Intro "2. Create a contour map": Correct explanation of "pen" parameter
  examples/get_started/02_contour_map.py
Labels: documentation, skip-changelog

#2710 decorators.py: Sort COMMON_DOCSTRINGS alphabetically
  pygmt/helpers/decorators.py
Labels: documentation, skip-changelog, final review call

#2713 Move variable __gmt_version__ to pygmt.clib to avoid cyclic-import errors
  pygmt/__init__.py
  pygmt/clib/__init__.py
  pygmt/src/ternary.py
  pygmt/src/timestamp.py
  pygmt/tests/test_accessor.py
  pygmt/tests/test_grdfill.py
  pygmt/tests/test_meca.py
Labels: maintenance, needs review

#2717 Switch away from Stamen basemaps
  examples/gallery/maps/tilemaps.py
  pygmt/datasets/tile_map.py
  pygmt/src/tilemap.py
Labels: documentation

#2709 Gallery example "Clipping grid values": Add annotations to frames
  examples/gallery/images/grdclip.py
Labels: documentation, skip-changelog, final review call

#2724 gallery example "Blockmean" : Remove un-needed square brackets
  examples/gallery/histograms/blockm.py
Labels: documentation, skip-changelog

#2719 clib: Fix the bug when passing multiple columns of strings with variable lengths to the GMT C API
  pygmt/clib/session.py
  pygmt/tests/test_clib.py
Labels: bug, final review call

#2721 Remove the invalid comment 'Choose how data will be passed ...'
  pygmt/src/blockm.py
  pygmt/src/contour.py
  pygmt/src/meca.py
  pygmt/src/nearneighbor.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/project.py
  pygmt/src/rose.py
  pygmt/src/select.py
  pygmt/src/surface.py
  pygmt/src/triangulate.py
  pygmt/src/velo.py
  pygmt/src/wiggle.py
Labels: maintenance, skip-changelog, final review call

#2708 pygmt.grdtrack: Simplify the handling of optional virtual files
  pygmt/src/grdtrack.py
Labels: maintenance, skip-changelog, final review call

#2732 Remove Max from the maintainers list
  doc/team.md
Labels: maintenance, skip-changelog

#2735 Disable pylint's line-length checking
  pyproject.toml
Labels: maintenance, skip-changelog

#2734 CI: List installed Python packages for easier debugging
  .github/workflows/format-command.yml
  .github/workflows/style_checks.yaml
Labels: maintenance, skip-changelog, needs review

#2728 Remote datasets: Include images of the official documentation in API reference
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/earth_geoid.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_mask.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/earth_vertical_gravity_gradient.py
Labels: documentation, skip-changelog, final review call

#2739 Figure.timestamp: Minor improvement to the docs
  pygmt/src/timestamp.py
Labels: documentation, skip-changelog

#2740 Inline examples: Use "longitude" and "latitude" instead of "x" and "y" and add units in comments
  pygmt/src/blockm.py
  pygmt/src/grd2xyz.py
  pygmt/src/grdclip.py
  pygmt/src/grdcut.py
  pygmt/src/grdgradient.py
  pygmt/src/grdhisteq.py
  pygmt/src/grdlandmask.py
  pygmt/src/grdproject.py
  pygmt/src/grdsample.py
  pygmt/src/grdtrack.py
  pygmt/src/grdvolume.py
  pygmt/src/sph2grd.py
  pygmt/src/x2sys_init.py
Labels: documentation, skip-changelog, final review call

#2743 Add the Japanese "PyGMT-HOWTO" tutorial to "External Resources"
  doc/external_resources.md
Labels: documentation, final review call

#2745 Remote datasets: Update filenames of remote dataset images
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/earth_geoid.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_mask.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/earth_vertical_gravity_gradient.py
Labels: documentation, skip-changelog

#2726 pygmt.which: Fix the bug when passing multiple files
  pygmt/src/which.py
  pygmt/tests/test_which.py
Labels: bug, needs review

#2747 Replace flakeheaven and isort with ruff
  .github/workflows/format-command.yml
  .github/workflows/style_checks.yaml
  .gitignore
  Makefile
  doc/conf.py
  doc/contributing.md
  environment.yml
  examples/projections/cyl/cyl_universal_transverse_mercator.py
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/earth_geoid.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_mask.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/earth_vertical_gravity_gradient.py
  pygmt/datasets/samples.py
  pygmt/src/nearneighbor.py
  pyproject.toml
Labels: maintenance

#2748 Remote dataset "IGPP Global Earth Free-Air Anomaly": Fix typo in docs
  pygmt/datasets/earth_free_air_anomaly.py
Labels: documentation, skip-changelog

#2749 ruff: Enable the UP (pyupgrade) rules and upgrade to new syntax
  doc/conf.py
  pygmt/clib/session.py
  pygmt/datasets/load_remote_dataset.py
  pygmt/figure.py
  pygmt/helpers/tempfile.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/text.py
  pygmt/tests/test_x2sys_init.py
  pyproject.toml
Labels: maintenance

#2746 API reference: Shorten supported argument types in docstrings
  pygmt/helpers/decorators.py
  pygmt/src/binstats.py
  pygmt/src/blockm.py
  pygmt/src/coast.py
  pygmt/src/colorbar.py
  pygmt/src/contour.py
  pygmt/src/grd2cpt.py
  pygmt/src/grdclip.py
  pygmt/src/grdcontour.py
  pygmt/src/grdcut.py
  pygmt/src/grdfill.py
  pygmt/src/grdgradient.py
  pygmt/src/grdhisteq.py
  pygmt/src/grdlandmask.py
  pygmt/src/grdtrack.py
  pygmt/src/grdvolume.py
  pygmt/src/histogram.py
  pygmt/src/info.py
  pygmt/src/inset.py
  pygmt/src/meca.py
  pygmt/src/nearneighbor.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/project.py
  pygmt/src/rose.py
  pygmt/src/select.py
  pygmt/src/sph2grd.py
  pygmt/src/sphdistance.py
  pygmt/src/sphinterpolate.py
  pygmt/src/subplot.py
  pygmt/src/surface.py
  pygmt/src/ternary.py
  pygmt/src/text.py
  pygmt/src/timestamp.py
  pygmt/src/triangulate.py
  pygmt/src/velo.py
  pygmt/src/wiggle.py
  pygmt/src/xyz2grd.py
Labels: documentation, skip-changelog

#2720 Figure.text: Support passing in a list of angle/font/justify values
  pygmt/src/text.py
  pygmt/tests/baseline/test_text_angle_justify_font_arrays.png.dvc
  pygmt/tests/test_text.py
Labels: feature, final review call

#2754 CI: Pin ghostscript to 9.54.0 in Tests and Dev Tests workflows
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog

#2756 Simplify the use of is_nonstr_iter
  pygmt/helpers/utils.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/text.py
Labels: maintenance, skip-changelog

#2758 Remote datasets: Remove "Global" from dataset names
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/earth_geoid.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_mask.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/earth_vertical_gravity_gradient.py
  pygmt/datasets/load_remote_dataset.py
  pygmt/tests/test_datasets_earth_free_air_anomaly.py
  pygmt/tests/test_datasets_earth_geoid.py
  pygmt/tests/test_datasets_earth_vertical_gravity_gradient.py
Labels: documentation, skip-changelog, final review call

#2759 Figure.meca: Simplify the codes for overriding values from parameters
  pygmt/src/meca.py
Labels: maintenance, skip-changelog

#2761 Add Zenodo's GMT community to the maintainer's onboarding list
  doc/maintenance.md
Labels: maintenance, final review call

#2692 NEP29: Test PyGMT on NumPy 1.26
  .github/workflows/ci_tests.yaml
Labels: maintenance

#2698 Figure.savefig: Support generating GeoTIFF file (with extension '.tiff')
  pygmt/figure.py
  pygmt/tests/test_figure.py
Labels: feature

#2762 Gallery example "Legend": Update regarding input data and multi-column legends
  examples/gallery/embellishments/legend.py
Labels: documentation

#2771 Figure.savefig: Support saving figures in PPM (.ppm) format
  pygmt/figure.py
  pygmt/tests/test_figure.py
Labels: enhancement, final review call

#2773 CI: Test GMT dev version on Windows by building from source
  .github/workflows/ci_tests_dev.yaml
  pygmt/tests/test_clib_loading.py
Labels: maintenance, needs review

#2776 CI: Remove the setup-node workaround from the dvc-diff workflow
  .github/workflows/dvc-diff.yml
Labels: maintenance, skip-changelog

#2780 pygmt.filter1d: Fix the bug that the first line is read as headers
  pygmt/src/filter1d.py
  pygmt/tests/test_filter1d.py
Labels: bug

#2778 Get the list of dependencies from package metadata
  pygmt/__init__.py
Labels: maintenance

#2766 Figure.savefig: Add the 'worldfile' parameter to write a companion world file for raster images
  pygmt/figure.py
  pygmt/tests/test_figure.py
Labels: feature

#2783 CI: Pin ghostscript to 9.54.0 for docs
  .github/workflows/ci_docs.yml
  ci/requirements/docs.yml
Labels: maintenance, skip-changelog

#2784 Move virtualfile-related tests into a separate test file
  pygmt/tests/test_clib.py
  pygmt/tests/test_clib_virtualfiles.py
Labels: maintenance, skip-changelog, needs review

#2777 Release Drafter: Automatically replace GitHub handles with names and links
  .github/release-drafter.yml
Labels: maintenance
