Repository GenericMappingTools/pygmt, pull requests merged in 2023-12, with the labels that each got.

#2839 Enable testing pd.Int32Dtype/pd.Int64Dtype for geopandas integration
  pygmt/tests/test_geopandas.py
Labels: maintenance, skip-changelog

#2838 Add the full changelog link to the release drafter template
  .github/release-drafter.yml
Labels: maintenance, final review call

#2842 Figure.inset: Fix typos in docstring of "box" parameter
  pygmt/src/inset.py
Labels: documentation, skip-changelog

#2832 Figure.text: Improve the documentation to clarify the order of columns in the input files
  pygmt/src/text.py
Labels: documentation, skip-changelog, final review call

#2835 Enable ruff's flynt (FLY) rules
  pygmt/helpers/decorators.py
  pygmt/src/ternary.py
  pygmt/tests/test_clib.py
  pygmt/tests/test_figure.py
  pyproject.toml
Labels: maintenance, final review call

#2837 Enable ruff's flake8-implicit-str-concat (ISC) rules
  pygmt/clib/session.py
  pygmt/helpers/utils.py
  pyproject.toml
Labels: maintenance

#2850 Refactor clib_full_names to avoid use of the assert keyword
  pygmt/clib/loading.py
Labels: maintenance, skip-changelog, final review call

#2851 Refactor the Session.virtualfile_from_data method to avoid use of the assert keyword
  pygmt/clib/session.py
Labels: maintenance, skip-changelog, final review call

#2857 Update README to clarify official and non-official GMT-related projects
  README.rst
Labels: documentation, skip-changelog, final review call

#2813 TYP: Improve the doc style for type hints
  .github/workflows/ci_docs.yml
  ci/requirements/docs.yml
  doc/conf.py
  environment.yml
Labels: maintenance, typing

#2860 Tiny improvements of functions strings
  pygmt/helpers/decorators.py
  pygmt/src/image.py
Labels: documentation, skip-changelog

#2823 Figure.coast: Add alias "box" for "-F"
  pygmt/src/coast.py
Labels: enhancement, final review call

#2855 Enable ruff's flake8-future-annotations (FA) rules
  pygmt/datasets/load_remote_dataset.py
  pyproject.toml
Labels: maintenance, final review call

#2866 Enable ruff's flake8-pie (PIE) rules
  examples/gallery/lines/line_custom_cpt.py
  pyproject.toml
Labels: maintenance, final review call

#2861 Use consistent descriptions for the grid parameter
  pygmt/helpers/decorators.py
  pygmt/src/dimfilter.py
  pygmt/src/grd2cpt.py
  pygmt/src/grd2xyz.py
  pygmt/src/grdclip.py
  pygmt/src/grdcontour.py
  pygmt/src/grdcut.py
  pygmt/src/grdfill.py
  pygmt/src/grdfilter.py
  pygmt/src/grdgradient.py
  pygmt/src/grdhisteq.py
  pygmt/src/grdimage.py
  pygmt/src/grdinfo.py
  pygmt/src/grdproject.py
  pygmt/src/grdsample.py
  pygmt/src/grdtrack.py
  pygmt/src/grdview.py
  pygmt/src/grdvolume.py
Labels: documentation, skip-changelog, final review call

#2722 Add a tutorial for working with table inputs in PyGMT
  examples/get_started/04_table_inputs.py
Labels: documentation, final review call

#2869 RUF005: Use the unpacking operator to concatenate collections
  pygmt/helpers/decorators.py
  pygmt/helpers/utils.py
  pygmt/src/grdtrack.py
  pygmt/src/meca.py
  pygmt/tests/test_clib_loading.py
Labels: maintenance, final review call

#2871 RUF010: Avoid calling str() within an f-string
  pygmt/clib/session.py
Labels: maintenance, final review call

#2876 Enable the PDF format documentation in the ReadTheDocs site
  .readthedocs.yaml
Labels: maintenance, final review call

#2878 Enable ruff's BLE/ICN/PGH/RSE/TCH/TID/YTT rules
  pyproject.toml
Labels: maintenance, needs review

#2868 Add a 'Common installation issues' section to the install guides
  doc/install.rst
Labels: documentation, final review call

#2874 docs: Use consistent description for the 'outgrid' parameter
  pygmt/helpers/decorators.py
  pygmt/src/binstats.py
  pygmt/src/dimfilter.py
  pygmt/src/grdclip.py
  pygmt/src/grdcut.py
  pygmt/src/grdfill.py
  pygmt/src/grdfilter.py
  pygmt/src/grdgradient.py
  pygmt/src/grdhisteq.py
  pygmt/src/grdlandmask.py
  pygmt/src/grdproject.py
  pygmt/src/grdsample.py
  pygmt/src/nearneighbor.py
  pygmt/src/sph2grd.py
  pygmt/src/sphdistance.py
  pygmt/src/sphinterpolate.py
  pygmt/src/surface.py
  pygmt/src/triangulate.py
  pygmt/src/xyz2grd.py
Labels: documentation, final review call

#2867 TYP: Add type hints for the 'registration' parameter in pygmt.datasets.load_* functions
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/earth_geoid.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_mask.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/earth_vertical_gravity_gradient.py
Labels: maintenance, typing

#2877 Enable ruff's pep8-naming (N) rules
  pygmt/exceptions.py
  pygmt/helpers/testing.py
  pygmt/src/config.py
  pygmt/src/grdhisteq.py
  pygmt/src/triangulate.py
  pyproject.toml
Labels: maintenance, needs review

#2859 TYP: Add type hints support for pygmt.datasets.load_sample_data
  pygmt/datasets/samples.py
Labels: maintenance, needs review, typing

#2882 Enable ruff's flake8-builtins (A) rules
  doc/conf.py
  pyproject.toml
Labels: maintenance, needs review

#2826 Let kwargs_to_strings work with default values and postional arguments
  pygmt/helpers/decorators.py
  pygmt/src/subplot.py
  pygmt/src/timestamp.py
  pygmt/src/which.py
Labels: bug

#2883 Create skip_if_no helper function to skip tests when missing a package
  pygmt/helpers/testing.py
  pygmt/tests/test_helpers.py
Labels: maintenance

#2880 Refactor the _get_ghostscript_version function to avoid try-except in loops
  pygmt/__init__.py
Labels: maintenance, skip-changelog, needs review

#2774 pyarrow: Check compatibility of pyarrow-backed pandas objects with numeric dtypes
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
  doc/install.rst
  pygmt/tests/test_clib_virtualfiles.py
  pygmt/tests/test_geopandas.py
  pygmt/tests/test_info.py
Labels: maintenance

#2885 Refactor the kwargs_to_strings decorator to avoid try-except in loops
  pygmt/helpers/decorators.py
Labels: maintenance, skip-changelog

#2886 Enable ruff's perflint (PERF) rules
  pygmt/__init__.py
  pyproject.toml
Labels: maintenance

#2887 Enable ruff's flake8-comprehensions (C4) rules
  examples/gallery/seismology/meca.py
  pyproject.toml
Labels: maintenance, needs review

#2845 pyarrow: Support date32[day] and date64[ms] dtypes in pandas objects
  .github/workflows/ci_doctests.yaml
  doc/install.rst
  pygmt/clib/conversion.py
  pygmt/tests/test_info.py
Labels: enhancement, final review call

#2891 Move pytest import inside of skip_if_no function
  pygmt/helpers/testing.py
Labels: maintenance, skip-changelog

#2669 Tutorial "Plotting datetime charts": Improve docs and fix typos
  examples/tutorials/advanced/date_time_charts.py
Labels: documentation, skip-changelog, final review call

#2888 ruff: Fix violations of ruff's S607 rule
  pygmt/clib/loading.py
  pygmt/helpers/utils.py
  pygmt/tests/test_clib_loading.py
Labels: maintenance, needs review

#2892 Enable ruff's flake8-bandit (S) rules
  pygmt/helpers/utils.py
  pyproject.toml
Labels: maintenance

#2894 Enable ruff's flake8-print (T20) rules
  pygmt/clib/session.py
  pygmt/tests/test_clib_virtualfiles.py
  pyproject.toml
Labels: maintenance

#2897 Enable ruff's flake8-return (RET) rules and ignore RET504
  pyproject.toml
Labels: maintenance

#2904 Docs: Correct syntax of function string for "projection" parameter
  pygmt/helpers/decorators.py
Labels: documentation, skip-changelog

#2898 Enable ruff's flake8-executable (EXE) rules
  pyproject.toml
Labels: maintenance, needs review

#2899 Enable ruff's flake8-pytest-style (PT) rules
  pygmt/tests/test_clib.py
  pygmt/tests/test_clib_loading.py
  pygmt/tests/test_clib_virtualfiles.py
  pygmt/tests/test_geopandas.py
  pygmt/tests/test_helpers.py
  pygmt/tests/test_meca.py
  pygmt/tests/test_x2sys_cross.py
  pygmt/tests/test_x2sys_init.py
  pyproject.toml
Labels: maintenance

#2901 Enable ruff's ruff-specific (RUF) rules
  examples/gallery/images/rgb_image.py
  examples/gallery/lines/roads.py
  examples/projections/conic/conic_lambert.py
  examples/projections/conic/polyconic.py
  examples/projections/cyl/cyl_miller.py
  examples/projections/misc/misc_eckertIV.py
  examples/projections/misc/misc_eckertVI.py
  examples/projections/misc/misc_mollweide.py
  pygmt/clib/session.py
  pygmt/helpers/utils.py
  pygmt/src/config.py
  pygmt/tests/test_text.py
  pyproject.toml
Labels: maintenance

#2900 Enable ruff's flake8-unused-arguments (ARG) rules
  pygmt/clib/session.py
  pygmt/sphinx_gallery.py
  pygmt/tests/test_clib.py
  pygmt/tests/test_clib_loading.py
  pygmt/tests/test_figure.py
  pygmt/tests/test_info.py
  pyproject.toml
Labels: maintenance

#2908 Setup Continuous Benchmarking workflow with pytest-codspeed
  .github/ISSUE_TEMPLATE/bump_gmt_checklist.md
  .github/workflows/benchmarks.yml
  README.rst
  doc/maintenance.md
  pygmt/tests/test_basemap.py
Labels: maintenance

#2907 Figure.grdimage: Remove the unsupported 'img_out'/'A' parameter
  pygmt/src/grdimage.py
  pygmt/tests/test_grdimage.py
Labels: deprecation

#2912 Silence PytestUnknownMarkWarning by setting marker for pytest-benchmark
  pyproject.toml
Labels: maintenance, skip-changelog

#2822 Add gallery example "Scale bar"
  examples/gallery/embellishments/scalebar.py
Labels: documentation, final review call

#2913 CI: Fail the DVC step if dvc fails to pulling baseline images
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
  .github/workflows/release-baseline-images.yml
Labels: maintenance, skip-changelog, needs review

#2921 Intro "4. PyGMT I/O: Table inputs": Fix typos
  examples/get_started/04_table_inputs.py
Labels: documentation, skip-changelog

#2919 README: Improve formulation
  README.rst
Labels: documentation, skip-changelog

#2920 Figure.inset: Improve formulation of comment in inline example
  pygmt/src/inset.py
Labels: documentation, skip-changelog

#2915 Wrap long lines in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, skip-changelog

#2911 Mark unit tests with @pytest.mark.benchmark part 1
  .github/workflows/benchmarks.yml
  pygmt/tests/test_geopandas.py
  pygmt/tests/test_grd2cpt.py
  pygmt/tests/test_grd2xyz.py
  pygmt/tests/test_grdclip.py
  pygmt/tests/test_grdcontour.py
  pygmt/tests/test_grdcut.py
  pygmt/tests/test_grdfill.py
  pygmt/tests/test_grdfilter.py
  pygmt/tests/test_grdgradient.py
  pygmt/tests/test_grdhisteq.py
  pygmt/tests/test_grdimage.py
  pygmt/tests/test_grdimage_image.py
  pygmt/tests/test_grdinfo.py
  pygmt/tests/test_grdlandmask.py
  pygmt/tests/test_grdproject.py
  pygmt/tests/test_grdsample.py
  pygmt/tests/test_grdtrack.py
  pygmt/tests/test_grdview.py
  pygmt/tests/test_grdvolume.py
  pygmt/tests/test_histogram.py
  pygmt/tests/test_info.py
  pygmt/tests/test_inset.py
  pygmt/tests/test_io.py
  pygmt/tests/test_legend.py
  pygmt/tests/test_logo.py
  pygmt/tests/test_makecpt.py
  pygmt/tests/test_meca.py
  pygmt/tests/test_nearneighbor.py
  pygmt/tests/test_plot.py
  pygmt/tests/test_plot3d.py
  pygmt/tests/test_project.py
  pygmt/tests/test_psconvert.py
  pygmt/tests/test_rose.py
  pygmt/tests/test_select.py
  pygmt/tests/test_session_management.py
  pygmt/tests/test_solar.py
  pygmt/tests/test_sph2grd.py
  pygmt/tests/test_sphdistance.py
  pygmt/tests/test_sphinterpolate.py
  pygmt/tests/test_subplot.py
  pygmt/tests/test_surface.py
  pygmt/tests/test_ternary.py
  pygmt/tests/test_text.py
  pygmt/tests/test_tilemap.py
  pygmt/tests/test_timestamp.py
  pygmt/tests/test_triangulate.py
  pygmt/tests/test_velo.py
  pygmt/tests/test_which.py
  pygmt/tests/test_wiggle.py
  pygmt/tests/test_x2sys_cross.py
  pygmt/tests/test_x2sys_init.py
  pygmt/tests/test_xyz2grd.py
Labels: maintenance, skip-changelog

#2922 Refactor test_image to plot @circuit.png instead of test_logo.png
  .github/workflows/ci_tests_legacy.yaml
  pygmt/helpers/testing.py
  pygmt/tests/baseline/test_image.png.dvc
  pygmt/tests/test_image.py
Labels: maintenance, skip-changelog

#2909 Use ruff to format code snippets in docstrings and remove blackdoc
  .github/workflows/format-command.yml
  .github/workflows/style_checks.yaml
  Makefile
  doc/contributing.md
  environment.yml
  pygmt/accessors.py
  pygmt/clib/session.py
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/helpers/decorators.py
  pygmt/helpers/tempfile.py
  pygmt/helpers/testing.py
  pygmt/src/blockm.py
  pygmt/src/grdclip.py
  pygmt/src/grdfill.py
  pygmt/src/grdsample.py
  pygmt/src/meca.py
  pygmt/src/solar.py
  pygmt/src/sph2grd.py
  pygmt/src/surface.py
  pyproject.toml
Labels: maintenance

#2923 CI: Download cached remote files in benchmarks.yml
  .github/workflows/benchmarks.yml
Labels: maintenance, skip-changelog

#2916 Update maintainers guides
  doc/maintenance.md
Labels: documentation, skip-changelog

#2927 Gallery: Start only the first word of the title with an upper-case letter
  examples/gallery/3d_plots/scatter3d.py
  examples/gallery/images/rgb_image.py
  examples/gallery/maps/borders.py
  examples/gallery/maps/choropleth_map.py
  examples/gallery/symbols/patterns.py
Labels: documentation, skip-changelog

#2931 CI: Avoid pulling GMT baseline images in the "GMT Dev Tests" workflow
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog, needs review
