Repository GenericMappingTools/pygmt, pull requests merged in 2023-02, with the labels that each got.

#2344 Format with black 23.1.0
  examples/gallery/symbols/bars.py
  pygmt/src/wiggle.py
Labels: maintenance, skip-changelog

#2343 Update Wei Ji's affiliation to DevSeed
  AUTHORS.md
  CITATION.cff
Labels: documentation, skip-changelog

#2341 Fix the test for the default registration of earth_mag4km_02m dataset (#2341
  pygmt/helpers/testing.py
  pygmt/tests/test_datasets_earth_magnetic_anomaly.py
Labels: maintenance, skip-changelog, final review call

#2349 Fix pylint 2.16.0 use-dict-literal errors
  pygmt/figure.py
  pygmt/helpers/tempfile.py
  pygmt/helpers/utils.py
  pygmt/tests/test_clib.py
  pygmt/tests/test_dimfilter.py
  pygmt/tests/test_figure.py
  pygmt/tests/test_grdclip.py
  pygmt/tests/test_grdcut.py
  pygmt/tests/test_grdfill.py
  pygmt/tests/test_grdfilter.py
  pygmt/tests/test_grdgradient.py
  pygmt/tests/test_grdhisteq.py
  pygmt/tests/test_grdimage.py
  pygmt/tests/test_grdlandmask.py
  pygmt/tests/test_grdproject.py
  pygmt/tests/test_grdsample.py
  pygmt/tests/test_meca.py
  pygmt/tests/test_plot.py
  pygmt/tests/test_plot3d.py
  pygmt/tests/test_surface.py
  pygmt/tests/test_triangulate.py
  pygmt/tests/test_xyz2grd.py
Labels: maintenance, skip-changelog, final review call

#2324 build_arg_string: Accept a dict containing configurable GMT parameters
  pygmt/helpers/utils.py
Labels: maintenance, final review call

#2348 Improve the error messages for invalid data sources of remote datasets (#2348)Co-authored-by: Michael Grund <23025878+michaelgrund@users.noreply.github.com>
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/load_remote_dataset.py
Labels: documentation, skip-changelog, final review call

#2321 pygmt.surface: Add aliases for "C", "L", "M", and "T"
  pygmt/src/surface.py
Labels: enhancement, final review call

#2351 Improve docstrings for "fill"
  pygmt/helpers/decorators.py
  pygmt/src/histogram.py
  pygmt/src/rose.py
  pygmt/src/solar.py
  pygmt/src/text.py
  pygmt/src/velo.py
  pygmt/src/wiggle.py
Labels: documentation, skip-changelog, final review call

#2356 Add an inline example for load_earth_vertical_gravity_gradient
  pygmt/datasets/earth_vertical_gravity_gradient.py
Labels: documentation, final review call

#2339 Revert "Pin fsspec to 2022.11.0 as a workaround for upstream dvc issues (#2338)" (#2339
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, skip-changelog

#2355 Add an inline example for load_earth_mask
  pygmt/datasets/earth_mask.py
Labels: documentation

#2360 Improve documentation of pygmt.Figure.meca
  pygmt/src/meca.py
Labels: documentation, skip-changelog, final review call

#2359 CI: Fix the comment format of the dvc-diff workflow
  .github/workflows/dvc-diff.yml
Labels: maintenance, skip-changelog

#2342 Add the GMTSampleData class to simplify the load_sample_data and list_sample_data functions (#2342)Co-authored-by: Will Schlitzer <schlitzer90@gmail.com> Co-authored-by: Yvonne Fröhlich <94163266+yvonnefroehlich@users.noreply.github.com> Co-authored-by: Michael Grund <23025878+michaelgrund@users.noreply.github.com>
  pygmt/datasets/samples.py
  pygmt/tests/test_datasets_samples.py
Labels: maintenance, final review call

#2363 Improve the code logic for checking registration of remote datasets
  pygmt/datasets/load_remote_dataset.py
Labels: maintenance, skip-changelog, final review call

#2371 Do not show the 'Methods Summary' heading if a class only have the __init__ method
  doc/_templates/autosummary/class.rst
Labels: maintenance, skip-changelog, final review call

#2369 Add working example to quickstart section of README
  README.rst
Labels: documentation, final review call

#2370 GMTDataArrayAccessor: Add inline examples for setting GMT specific properties (#2370)Co-authored-by: Michael Grund <23025878+michaelgrund@users.noreply.github.com>
  pygmt/accessors.py
Labels: documentation, final review call

#2366 Add a package-level variable __gmt_version__ for development use
  pygmt/__init__.py
  pygmt/src/ternary.py
  pygmt/tests/test_accessor.py
  pygmt/tests/test_grdfill.py
Labels: maintenance

#2345 Figure.meca: Add aliases for C, E, G, and W
  pygmt/src/meca.py
Labels: enhancement, final review call

#2375 Document limitations of GMT xarray accessors
  pygmt/accessors.py
Labels: documentation, final review call
