Repository GenericMappingTools/pygmt, pull requests merged in 2023-06, with the labels that each got.

#2553 Figure.meca: Expand docstrings for "compressionfill", "cmap", and "offset"
  pygmt/src/meca.py
Labels: documentation, skip-changelog

#2549 CI: Fix and simplify the dvc-diff workflow
  .github/workflows/dvc-diff.yml
Labels: maintenance

#2559 CI: Remove the deprecated cml-publish command from the dvc-diff workflow
  .github/workflows/dvc-diff.yml
Labels: maintenance

#2556 Improve comment in example "Cartesian, circular, and geographic vectors"
  examples/gallery/lines/vector_styles.py
Labels: documentation, skip-changelog

#2557 Clarify formulation in example "Vector heads and tails"
  examples/gallery/lines/vector_heads_tails.py
Labels: documentation, skip-changelog

#2560 Bump actions/setup-node from 1 to 3.6.0
  .github/workflows/dvc-diff.yml
Labels: maintenance, skip-changelog, needs review

#2561 Fix the command to extract GMT CLI for GMT>=6.4.0
  doc/contributing.md
Labels: maintenance, skip-changelog, final review call

#2566 Figure.meca: the 'scale' parameter can accept int/float/str values
  pygmt/src/meca.py
  pygmt/tests/test_meca.py
Labels: bug, final review call

#2565 Figure.meca: Refactor tests for plotting multiple focal mechanisms
  pygmt/tests/baseline/test_meca_loc_array.png.dvc
  pygmt/tests/baseline/test_meca_spec_2d_array.png.dvc
  pygmt/tests/baseline/test_meca_spec_dataframe.png.dvc
  pygmt/tests/baseline/test_meca_spec_multiple_focalmecha.png.dvc
  pygmt/tests/test_meca.py
Labels: maintenance, final review call

#2538 Unpin docformatter 1.5.1
  .github/workflows/format-command.yml
  .github/workflows/style_checks.yaml
  environment.yml
  pygmt/tests/test_grdcut.py
  pygmt/tests/test_grdproject.py
  pygmt/tests/test_plot.py
  pygmt/tests/test_plot3d.py
  pygmt/tests/test_psconvert.py
  pyproject.toml
Labels: maintenance, skip-changelog

#2567 Fix the failing test for PyGMTScraper when sphinx-gallery is not installed
  .github/workflows/ci_tests_legacy.yaml
  pygmt/tests/test_sphinx_gallery.py
Labels: maintenance, skip-changelog, needs review

#2568 Unpin geopandas 0.13.0 in CI docs build
  .github/workflows/ci_docs.yml
  ci/requirements/docs.yml
Labels: maintenance, skip-changelog

#2569 Set date_format to ISO8601 to silence pandas 2.0 UserWarning on read_csv
  .github/workflows/ci_tests_legacy.yaml
  pygmt/src/x2sys_cross.py
  pygmt/tests/test_x2sys_cross.py
Labels: maintenance

#2525 CI: Install geopandas using pip in the "GMT Dev Tests" workflow
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog, needs review

#2552 Figure.meca: Expand docstring for the scale parameter
  pygmt/src/meca.py
Labels: documentation, skip-changelog, final review call

#2570 Set rtol=1e-5 to fix broken tests on macOS due to floating point precision
  pygmt/tests/test_datasets_earth_age.py
  pygmt/tests/test_datasets_earth_magnetic_anomaly.py
Labels: maintenance, skip-changelog, final review call

#2572 Figure.meca: Refactor the two tests for offsetting beachballs
  pygmt/tests/baseline/test_meca_offset.png.dvc
  pygmt/tests/test_meca.py
Labels: maintenance, final review call

#2577 Fix typo in tutorial "Cartesian histograms"
  examples/tutorials/advanced/cartesian_histograms.py
Labels: documentation, skip-changelog

#2581 NEP29: Test PyGMT on NumPy 1.25
  .github/workflows/ci_tests.yaml
Labels: maintenance

#2583 CI: Update dvc's argument --show-md to --md for dvc 3.x
  .github/workflows/dvc-diff.yml
Labels: maintenance, skip-changelog, needs review

#2582 Figure.meca: Add a test for passing event names via pandas.DataFrame
  pygmt/tests/baseline/test_meca_eventname.png.dvc
  pygmt/tests/test_meca.py
Labels: maintenance, upstream

#2586 NEP29: Set minimum required version to NumPy 1.22+
  .github/workflows/ci_tests.yaml
  README.rst
  ci/requirements/docs.yml
  doc/install.rst
  environment.yml
  pyproject.toml
  requirements.txt
Labels: deprecation

#2073 Test test_accessor_sliced_datacube now passes with GMT 6.5.0
  pygmt/tests/test_accessor.py
Labels: maintenance, skip-changelog, needs review

#2589 Use concurrency to cancel previous runs
  .github/workflows/ci_docs.yml
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, needs review
