Repository GenericMappingTools/pygmt, pull requests merged in 2023-09, with the labels that each got.

#2383 Add tutorial to explain naming of PyGMT figure elements
  examples/get_started/03_figure_element.py
Labels: documentation, final review call

#2652 Remove the unused pygmt.test() function
  doc/api/index.rst
  pygmt/__init__.py
Labels: deprecation, final review call

#2653 Fix typos in first figure tutorial
  examples/get_started/01_first_figure.py
Labels: documentation, skip-changelog, needs review

#2651 Changelog entry for v0.10.0
  CITATION.cff
  README.rst
  doc/_static/version_switch.js
  doc/changes.md
Labels: maintenance, skip-changelog, final review call

#2655 Make Yvonne a Maintainer of PyGMT
  doc/team.md
Labels: maintenance, skip-changelog

#2663 Fix typos in frames tutorial
  examples/tutorials/basics/frames.py
Labels: documentation, skip-changelog

#2656 Improve the onboarding access checklist for contributors, maintainers and administrators
  doc/maintenance.md
Labels: documentation, final review call

#2664 Fix typo in projections overview
  examples/projections/table/README.txt
Labels: documentation, skip-changelog

#2665 Fix typos in gallery examples
  examples/gallery/embellishments/colorbars_multiple.py
  examples/gallery/embellishments/inset_rectangle_region.py
  examples/gallery/embellishments/logo.py
  examples/gallery/images/contours.py
  examples/gallery/images/grdgradient.py
  examples/gallery/images/grdgradient_shading.py
  examples/gallery/lines/great_circles.py
  examples/gallery/maps/country_polygons.py
  examples/gallery/symbols/datetime_inputs.py
Labels: documentation, skip-changelog, final review call

#2659 Use beginning of first paragraph for "tooltip" by Sphinx Gallery extension
  examples/gallery/basemaps/ternary.py
  examples/gallery/embellishments/colorbars_multiple.py
  examples/gallery/embellishments/timestamp.py
  examples/gallery/histograms/blockm.py
  examples/gallery/histograms/histogram.py
  examples/gallery/histograms/scatter_and_histograms.py
  examples/gallery/images/contours.py
  examples/gallery/images/cross_section.py
  examples/gallery/images/grdclip.py
  examples/gallery/images/grdgradient.py
  examples/gallery/images/grdgradient_shading.py
  examples/gallery/images/grdlandmask.py
  examples/gallery/images/image.py
  examples/gallery/images/rgb_image.py
  examples/gallery/lines/decorated_lines.py
  examples/gallery/lines/envelope.py
  examples/gallery/lines/quoted_lines.py
  examples/gallery/lines/roads.py
  examples/gallery/maps/country_polygons.py
  examples/gallery/maps/tilemaps.py
  examples/gallery/symbols/bars.py
  examples/gallery/symbols/points_categorical.py
  examples/gallery/symbols/text_symbols.py
  examples/get_started/03_figure_element.py
  examples/tutorials/advanced/cartesian_histograms.py
  examples/tutorials/advanced/date_time_charts.py
  examples/tutorials/advanced/grid_equalization.py
  examples/tutorials/advanced/subplots.py
  examples/tutorials/advanced/vectors.py
  examples/tutorials/advanced/working_with_panel.py
  examples/tutorials/basics/text.py
Labels: bug, skip-changelog, final review call

#2654 Improve comments in tutorial "2. Create a contour map"
  examples/get_started/02_contour_map.py
Labels: documentation, skip-changelog, final review call

#2670 Fix several typos, detected by codespell
  doc/conf.py
  examples/gallery/histograms/scatter_and_histograms.py
  pygmt/accessors.py
  pygmt/src/meca.py
Labels: maintenance, skip-changelog

#2673 Use codespell to check common misspellings
  .github/ISSUE_TEMPLATE/release_checklist.md
  Makefile
  environment.yml
  pyproject.toml
Labels: maintenance

#2675 Update Contributors Guide regarding position of the thumbnail figure comment
  doc/contributing.md
Labels: documentation, skip-changelog, final review call

#2677 Use `====` as title unterline in the examples (gallery, tutorials, intro)
  examples/gallery/3d_plots/grdview_surface.py
  examples/gallery/3d_plots/scatter3d.py
  examples/gallery/basemaps/double_y_axes.py
  examples/gallery/basemaps/ternary.py
  examples/gallery/embellishments/colorbar.py
  examples/gallery/embellishments/colorbars_multiple.py
  examples/gallery/embellishments/inset.py
  examples/gallery/embellishments/inset_rectangle_region.py
  examples/gallery/embellishments/legend.py
  examples/gallery/embellishments/logo.py
  examples/gallery/embellishments/solar.py
  examples/gallery/embellishments/timestamp.py
  examples/gallery/histograms/blockm.py
  examples/gallery/histograms/histogram.py
  examples/gallery/histograms/rose.py
  examples/gallery/histograms/scatter_and_histograms.py
  examples/gallery/images/contours.py
  examples/gallery/images/grdclip.py
  examples/gallery/images/grdgradient.py
  examples/gallery/images/grdgradient_shading.py
  examples/gallery/images/grdlandmask.py
  examples/gallery/images/image.py
  examples/gallery/images/rgb_image.py
  examples/gallery/images/track_sampling.py
  examples/gallery/lines/decorated_lines.py
  examples/gallery/lines/envelope.py
  examples/gallery/lines/great_circles.py
  examples/gallery/lines/line_custom_cpt.py
  examples/gallery/lines/linefronts.py
  examples/gallery/lines/linestyles.py
  examples/gallery/lines/quoted_lines.py
  examples/gallery/lines/roads.py
  examples/gallery/lines/vector_heads_tails.py
  examples/gallery/lines/vector_styles.py
  examples/gallery/lines/wiggle.py
  examples/gallery/maps/borders.py
  examples/gallery/maps/country_polygons.py
  examples/gallery/maps/land_and_water.py
  examples/gallery/maps/shorelines.py
  examples/gallery/maps/tilemaps.py
  examples/gallery/seismology/meca.py
  examples/gallery/seismology/velo_arrow_ellipse.py
  examples/gallery/symbols/bars.py
  examples/gallery/symbols/basic_symbols.py
  examples/gallery/symbols/custom_symbols.py
  examples/gallery/symbols/datetime_inputs.py
  examples/gallery/symbols/multi_parameter_symbols.py
  examples/gallery/symbols/patterns.py
  examples/gallery/symbols/points.py
  examples/gallery/symbols/points_categorical.py
  examples/gallery/symbols/points_transparency.py
  examples/gallery/symbols/scatter.py
  examples/gallery/symbols/text_symbols.py
  examples/tutorials/basics/plot.py
Labels: documentation, skip-changelog, final review call

#2681 doc: Link to GMT 6.4 documentation instead of the latest one
  .github/ISSUE_TEMPLATE/bump_gmt_checklist.md
  .github/workflows/check-links.yml
  doc/conf.py
Labels: documentation

#2678 Update README for the "Intro to PyGMT"
  examples/get_started/01_first_figure.py
  examples/get_started/README.txt
Labels: documentation, skip-changelog, final review call

#2676 Gallery example colorbar: Add code and explanation for "frame" parameter
  examples/gallery/embellishments/colorbar.py
Labels: documentation, skip-changelog, final review call

#2680 Update link to GMT docs "Chart of Octal Codes for Characters" (cookbook to reference)
  pygmt/helpers/utils.py
Labels: documentation, skip-changelog

#2684 CI: Pin GMT to a specific build on RTD
  ci/requirements/docs.yml
Labels: maintenance, skip-changelog, needs review

#2682 Use :gmt-docs: instead of full links
  doc/contributing.md
  examples/gallery/embellishments/legend.py
  examples/gallery/lines/decorated_lines.py
  examples/gallery/lines/quoted_lines.py
  examples/gallery/symbols/patterns.py
Labels: documentation, skip-changelog, final review call

#2688 Fix typos in documentations of datasets
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/earth_geoid.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_mask.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/earth_vertical_gravity_gradient.py
Labels: documentation, skip-changelog, final review call

#2690 Merge dataset-independent tests into a separate test file
  pygmt/tests/test_datasets_earth_age.py
  pygmt/tests/test_datasets_earth_free_air_anomaly.py
  pygmt/tests/test_datasets_earth_geoid.py
  pygmt/tests/test_datasets_earth_magnetic_anomaly.py
  pygmt/tests/test_datasets_earth_mask.py
  pygmt/tests/test_datasets_earth_relief.py
  pygmt/tests/test_datasets_earth_vertical_gravity_gradient.py
  pygmt/tests/test_datasets_load_remote_datasets.py
Labels: maintenance, final review call

#2691 Figure.savefig: Support .jpeg as JPEG image extension
  pygmt/figure.py
  pygmt/tests/test_figure.py
Labels: enhancement, final review call

#2697 Figure.savefig: Support uppercase file extensions (e.g., PNG, PDF)
  pygmt/figure.py
  pygmt/tests/test_figure.py
Labels: enhancement, final review call

#2701 CI: Change tilemap source from Stamen to OpenStreetMap
  pygmt/tests/baseline/test_tilemap_no_clip_False.png.dvc
  pygmt/tests/baseline/test_tilemap_no_clip_True.png.dvc
  pygmt/tests/baseline/test_tilemap_ogc_wgs84.png.dvc
  pygmt/tests/baseline/test_tilemap_web_mercator.png.dvc
  pygmt/tests/test_tilemap.py
Labels: maintenance, skip-changelog

#2702 Fix typos in "Figure.meca"
  pygmt/src/meca.py
Labels: documentation, skip-changelog
