Repository GenericMappingTools/pygmt, pull requests merged in 2023-03, with the labels that each got.

#2125 Add function to load raster tile maps using contextily
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
  ci/requirements/docs.yml
  doc/api/index.rst
  doc/conf.py
  doc/install.rst
  environment.yml
  pygmt/__init__.py
  pygmt/datasets/__init__.py
  pygmt/datasets/tile_map.py
  pyproject.toml
Labels: feature, final review call

#2385 Recommend Mambaforge and mamba in the installation and contributing guides
  doc/contributing.md
  doc/install.rst
Labels: documentation, final review call

#2208 Add Figure.timestamp to plot the GMT timestamp logo
  doc/api/index.rst
  pygmt/figure.py
  pygmt/src/__init__.py
  pygmt/src/timestamp.py
  pygmt/tests/baseline/test_timestamp.png.dvc
  pygmt/tests/baseline/test_timestamp_font.png.dvc
  pygmt/tests/baseline/test_timestamp_justification.png.dvc
  pygmt/tests/baseline/test_timestamp_label.png.dvc
  pygmt/tests/baseline/test_timestamp_offset.png.dvc
  pygmt/tests/test_timestamp.py
Labels: feature, final review call

#2389 NEP29: Set minimum required version to NumPy 1.21+
  README.rst
  ci/requirements/docs.yml
  doc/install.rst
  environment.yml
  pyproject.toml
  requirements.txt
Labels: deprecation

#2393 Fix bug with different band dtype from load_tile_map by casting to uint8
  pygmt/datasets/tile_map.py
Labels: bug

#2357 pygmt.Figure.colorbar: Add aliases for L and Z
  pygmt/src/colorbar.py
Labels: enhancement, final review call

#2392 Fix typos in docs of "pygmt.Figure.colorbar"
  pygmt/src/colorbar.py
Labels: documentation, skip-changelog, final review call

#2382 Fix typos in docs of "pygmt.grdinfo"
  pygmt/src/grdinfo.py
Labels: documentation, skip-changelog, final review call

#2135 Recommend Figure.timestamp and remove timestamp (U) alias from all plotting methods
  pygmt/helpers/decorators.py
  pygmt/src/basemap.py
  pygmt/src/coast.py
  pygmt/src/contour.py
  pygmt/src/grdcontour.py
  pygmt/src/grdimage.py
  pygmt/src/histogram.py
  pygmt/src/image.py
  pygmt/src/legend.py
  pygmt/src/logo.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/rose.py
  pygmt/src/solar.py
  pygmt/src/ternary.py
  pygmt/src/text.py
  pygmt/src/velo.py
  pygmt/src/wiggle.py
  pygmt/tests/test_timestamp.py
Labels: deprecation, final review call

#2397 Fix the check links workflow with lychee-action v1.6.1
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog

#2400 Do not raise a KeyError exception if attribute actual_range doesn't exist
  pygmt/datasets/load_remote_dataset.py
Labels: maintenance, skip-changelog

#2399 Allow printing show_versions() to in-memory buffer to enable testing
  pygmt/__init__.py
  pygmt/tests/test_init.py
Labels: maintenance, final review call

#2391 Add a gallery example for the Figure.timestamp method
  examples/gallery/embellishments/timestamp.py
Labels: documentation, final review call

#2403 Allow getting the parameter API_IMAGE_LAYOUT for GMT>=6.4.0
  pygmt/clib/session.py
Labels: maintenance, skip-changelog, final review call

#2406 Correct docs for "wedge" (w) symbol in gallery example "Multi-parameter symbols"
  examples/gallery/symbols/multi_parameter_symbols.py
Labels: documentation, skip-changelog

#2402 Update the documentation template to show class attributes
  doc/_templates/autosummary/class.rst
  pygmt/accessors.py
Labels: documentation, skip-changelog

#2395 Expand Colorbar gallery example for categorical data
  examples/gallery/embellishments/colorbar.py
Labels: enhancement

#2411 pygmt.grdfilter: Add the missing grid registration to suppress warnings
  pygmt/src/grdfilter.py
Labels: maintenance, skip-changelog

#2408 Improve the docstrings for the GMT_Open_VirtualFile wrapper
  pygmt/clib/session.py
Labels: maintenance, skip-changelog, final review call

#2376 Use "general" verb form in docstrings
  pygmt/figure.py
  pygmt/helpers/decorators.py
  pygmt/src/basemap.py
  pygmt/src/binstats.py
  pygmt/src/coast.py
  pygmt/src/colorbar.py
  pygmt/src/contour.py
  pygmt/src/dimfilter.py
  pygmt/src/filter1d.py
  pygmt/src/grd2cpt.py
  pygmt/src/grdgradient.py
  pygmt/src/grdhisteq.py
  pygmt/src/grdimage.py
  pygmt/src/grdinfo.py
  pygmt/src/grdlandmask.py
  pygmt/src/grdview.py
  pygmt/src/histogram.py
  pygmt/src/image.py
  pygmt/src/inset.py
  pygmt/src/legend.py
  pygmt/src/logo.py
  pygmt/src/makecpt.py
  pygmt/src/meca.py
  pygmt/src/nearneighbor.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/rose.py
  pygmt/src/select.py
  pygmt/src/text.py
  pygmt/src/triangulate.py
  pygmt/src/velo.py
  pygmt/src/wiggle.py
  pygmt/src/x2sys_init.py
Labels: documentation, skip-changelog, final review call

#2410 Add gallery example for scatter plot with histograms on sides
  examples/gallery/histograms/scatter_and_histograms.py
Labels: documentation, final review call

#2415 Fix the failing plot3d_projection test
  pygmt/tests/baseline/test_plot3d_projection.png.dvc
  pygmt/tests/test_plot3d.py
Labels: maintenance, skip-changelog

#2285 Add checking GMT Legacy/Dev Tests to the release checklist
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: maintenance, skip-changelog, final review call

#2418 Set "frame" parameter for the first figure of the gallery example "Timestamp"
  examples/gallery/embellishments/timestamp.py
Labels: enhancement, skip-changelog, final review call

#2329 Add a gallery example showing how to use patterns via the "fill" parameter (or similiar parameters)
  examples/gallery/symbols/patterns.py
Labels: documentation, final review call

#2420 Remove --sdist --wheel flags from the build command
  Makefile
Labels: maintenance, final review call

#2354 Add a gallery example showing how to use advanced grdgradient via the "azimuth" & "normalize" parameters
  examples/gallery/images/grdgradient_shading.py
Labels: documentation, final review call

#2427 Figure.subplot: Fix strange positioning issues after exiting subplot
  examples/gallery/images/grdgradient_shading.py
  pygmt/src/subplot.py
  pygmt/tests/baseline/test_subplot_outside_plotting_positioning.png.dvc
  pygmt/tests/test_subplot.py
Labels: bug

#2425 Figure.timestamp: Let the 'text' parameter work for GMT<=6.4.0 and raise a warning for long text
  pygmt/src/timestamp.py
  pygmt/tests/baseline/test_timestamp_text_truncated.png.dvc
  pygmt/tests/test_timestamp.py
Labels: enhancement, final review call

#2430 Add Jing-Hui to AUTHORS.md
  AUTHORS.md
Labels: maintenance, skip-changelog, final review call

#2432 Recommend Python 3.11 in the install instructions and fix some typos
  doc/contributing.md
  doc/install.rst
Labels: documentation, skip-changelog, final review call

#2434 Figure.timestamp: Improve documentation and gallery example
  examples/gallery/embellishments/timestamp.py
  pygmt/src/timestamp.py
  pygmt/tests/test_timestamp.py
Labels: documentation, skip-changelog, final review call

#2440 Minor improvement of docs of gallery example "Colorbars"
  examples/gallery/embellishments/colorbar.py
Labels: enhancement, skip-changelog, final review call

#2433 Expand gallery example "Focal mechanisms" to use "*fill" and "pen"
  examples/gallery/seismology/meca.py
Labels: enhancement, needs review

#2444 Skip the doctest for load_earth_vertical_gravity_gradient
  pygmt/datasets/earth_vertical_gravity_gradient.py
Labels: maintenance, skip-changelog, final review call

#2384 Revise the notes about registration and gtype of remote datasets
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/earth_geoid.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_mask.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/earth_vertical_gravity_gradient.py
Labels: documentation, needs review

#2441 Replace ModuleNotFoundError with the more general ImportError
  pygmt/datasets/tile_map.py
  pygmt/figure.py
  pygmt/tests/test_figure.py
Labels: maintenance, final review call

#2373 Add inline example for colorbar
  pygmt/src/colorbar.py
Labels: documentation, final review call

#2381 Add inline example for grdview
  pygmt/src/grdview.py
Labels: documentation, final review call

#2453 Publish to TestPyPI and PyPI via OpenID Connect token
  .github/workflows/publish-to-pypi.yml
  doc/maintenance.md
Labels: maintenance

#2443 Add a new target 'doctest' to run doctests only and simplify Makefile
  Makefile
Labels: maintenance, final review call

#2454 Update the test_subplot_outside_plotting_positioning test and increase the RMS tolerance
  pygmt/tests/test_subplot.py
Labels: maintenance, skip-changelog, needs review

#2458 pygmt.set_display: Add inline examples and improve documentation
  pygmt/figure.py
Labels: documentation, final review call

#2457 Fix typos in docstrings of "pygmt.Figure.histogram"
  pygmt/src/histogram.py
Labels: documentation, skip-changelog, final review call

#2394 Add Figure.tilemap to plot XYZ tile maps
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
  ci/requirements/docs.yml
  doc/api/index.rst
  doc/conf.py
  doc/install.rst
  environment.yml
  pygmt/datasets/tile_map.py
  pygmt/figure.py
  pygmt/src/__init__.py
  pygmt/src/tilemap.py
  pygmt/tests/baseline/test_tilemap_no_clip_False.png.dvc
  pygmt/tests/baseline/test_tilemap_no_clip_True.png.dvc
  pygmt/tests/baseline/test_tilemap_ogc_wgs84.png.dvc
  pygmt/tests/baseline/test_tilemap_web_mercator.png.dvc
  pygmt/tests/test_tilemap.py
  pyproject.toml
Labels: feature, final review call

#2417 Fix setting "sharex", "sharey", and "frame" of Figure.subplot in combination with Figure.basemap
  pygmt/src/basemap.py
  pygmt/tests/baseline/test_basemap_required_args.png.dvc
  pygmt/tests/baseline/test_basemap_subplot.png.dvc
  pygmt/tests/test_basemap.py
Labels: bug, final review call

#2459 Use the minigallery directive to insert mini gallery in API documentation
  doc/_templates/autosummary/class.rst
  doc/_templates/autosummary/function.rst
  doc/_templates/autosummary/method.rst
Labels: maintenance, final review call

#2468 Temporarily pin funcy<2.0 for dvc fix
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, skip-changelog

#2461 "pygmt.Figure.grdimage": Expand docstring for "nan_transparent" parameter
  pygmt/src/grdimage.py
Labels: documentation, skip-changelog

#2471 Sort drafted changelog by title
  .github/release-drafter.yml
Labels: maintenance, skip-changelog

#2469 Changelog entry for v0.9.0
  CITATION.cff
  README.rst
  doc/_static/version_switch.js
  doc/changes.md
Labels: maintenance, skip-changelog, final review call
