Repository GenericMappingTools/pygmt, pull requests merged in 2023-05, with the labels that each got.

#2498 Add tutorial to show interactive data visualization via 'panel'
  .github/workflows/ci_docs.yml
  ci/requirements/docs.yml
  environment.yml
  examples/tutorials/advanced/working_with_panel.py
Labels: documentation, final review call

#2439 Move sphinx-gallery as an optional dependency for testing
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_legacy.yaml
  pygmt/sphinx_gallery.py
Labels: maintenance, skip-changelog, needs review

#2532 Fix typo in gallery example "Color points by categories"
  examples/gallery/symbols/points_categorical.py
Labels: documentation, skip-changelog

#2531 Improve comments of gallery example "3-D Scatter plots"
  examples/gallery/3d_plots/scatter3d.py
Labels: documentation, skip-changelog, final review call

#2445 Add tutorial for cartesian histograms
  examples/tutorials/advanced/cartesian_histograms.py
Labels: documentation, final review call

#2536 Migrate provision-with-micromamba to setup-micromamba
  .github/workflows/cache_data.yaml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance

#2542 Fix typo in docs of "Figure.rose"
  pygmt/src/rose.py
Labels: documentation, skip-changelog

#2541 Improve comments in inline examples of "pygmt.grdhisteq*"
  pygmt/src/grdhisteq.py
Labels: documentation, skip-changelog

#2545 CI: Do not use geopandas 0.13.0 in docs
  .github/workflows/ci_docs.yml
  ci/requirements/docs.yml
Labels: maintenance, skip-changelog, needs review

#2551 Fix typo in documentation of "Figure.meca"
  pygmt/src/meca.py
Labels: documentation, skip-changelog

#2548 Fix typo in documentation of Robinson projection
  examples/projections/misc/misc_robinson.py
Labels: documentation, skip-changelog, final review call

#2533 Figure.meca: Refactor tests for plotting a single focal mechanism
  pygmt/tests/baseline/test_meca_gcmt_convention.png.dvc
  pygmt/tests/baseline/test_meca_spec_1d_array.png.dvc
  pygmt/tests/baseline/test_meca_spec_dictionary.png.dvc
  pygmt/tests/baseline/test_meca_spec_file.png.dvc
  pygmt/tests/baseline/test_meca_spec_single_focalmecha.png.dvc
  pygmt/tests/test_meca.py
Labels: maintenance, final review call
