Repository GenericMappingTools/pygmt, pull requests merged in 2023-04, with the labels that each got.

#2470 Unpin funcy
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, skip-changelog, needs review

#2482 Pin docformatter to 1.5.1 in workflows and <1.6.0 in environment.yml
  .github/workflows/format-command.yml
  .github/workflows/style_checks.yaml
  environment.yml
Labels: maintenance

#2481 Use np.asarray to convert a 1-D array to datetime type in array_to_datetime
  examples/tutorials/advanced/date_time_charts.py
  pygmt/clib/conversion.py
  pygmt/clib/session.py
Labels: maintenance, final review call

#2475 Fix typo regarding GMT 6 citation
  README.rst
Labels: maintenance, skip-changelog

#2474 Change compressionfill color in meca gallery example
  examples/gallery/seismology/meca.py
Labels: documentation, skip-changelog

#2473 Remove the deprecated incols parameter from Figure.text (deprecated since v0.8.0)
  pygmt/src/text.py
Labels: deprecation

#2486 Update matplotlib link in gallery example "Scatter plots with a legend"
  examples/gallery/symbols/scatter.py
Labels: documentation, skip-changelog

#2477 Remove ResearchGate from release checklist
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: maintenance, skip-changelog

#2484 Exclude bots from contributors in release drafter
  .github/release-drafter.yml
Labels: maintenance

#2485 Move Figure.shift_origin to a standalone Python file
  pygmt/figure.py
  pygmt/src/__init__.py
  pygmt/src/shift_origin.py
Labels: enhancement, final review call

#2487 NEP29: Set minimum required version to Python 3.9+
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_legacy.yaml
  README.rst
  doc/install.rst
  pyproject.toml
Labels: deprecation, final review call

#2491 Remove dummy_context and use contextlib.nullcontext instead
  pygmt/clib/session.py
  pygmt/helpers/__init__.py
  pygmt/helpers/utils.py
  pygmt/src/x2sys_cross.py
Labels: maintenance, final review call

#2492 pygmt.show_versions: Show versions of IPython and rioxarray
  pygmt/__init__.py
Labels: maintenance, final review call

#2456 CI: Add the "Doctests" workflow to run doctests weekly
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  doc/maintenance.md
Labels: maintenance, final review call

#2496 CI: Add detailed descriptions in the workflow files and update maintainer guides
  .github/workflows/cache_data.yaml
  .github/workflows/check-links.yml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
  .github/workflows/dvc-diff.yml
  .github/workflows/format-command.yml
  .github/workflows/publish-to-pypi.yml
  .github/workflows/release-baseline-images.yml
  .github/workflows/release-drafter.yml
  .github/workflows/slash-command-dispatch.yml
  .github/workflows/style_checks.yaml
  doc/maintenance.md
Labels: maintenance

#2504 Fix typo in docstrings of pygmt.Figure.colorbar
  pygmt/src/colorbar.py
Labels: documentation, skip-changelog

#2505 Silent a pandas 2.0 warning by speicifying the time precision
  pygmt/helpers/decorators.py
Labels: maintenance, skip-changelog, final review call

#2488 Use substitutions to show the minimum required Python and GMT versions dynamically in installation guides
  .github/ISSUE_TEMPLATE/bump_gmt_checklist.md
  doc/conf.py
  doc/install.rst
Labels: maintenance, final review call

#2506 Move pip as a dev dependency and ipython as an optional dependency
  ci/requirements/docs.yml
  environment.yml
Labels: maintenance, skip-changelog

#2500 clib.Session: Wrap the GMT_Get_Common API function
  doc/api/index.rst
  pygmt/clib/session.py
Labels: enhancement

#2508 Add link to upstream GMT docs in pygmt.Figure.legend
  pygmt/src/legend.py
Labels: documentation, skip-changelog

#2435 CI: Use mamba-org/provision-with-micromamba to setup micromamba
  .github/ISSUE_TEMPLATE/bump_gmt_checklist.md
  .github/workflows/cache_data.yaml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, needs review

#2512 Improve comments of gallery example "Color points by categories"
  examples/gallery/symbols/points_categorical.py
Labels: documentation, skip-changelog, final review call

#2501 Improve docs of "pygmt.grd2cpt" and "pygmt.makecpt"
  pygmt/src/grd2cpt.py
  pygmt/src/makecpt.py
Labels: documentation, skip-changelog, final review call

#2516 CI: Use macos-13 for Tests Dev workflow and consistently use lower-case runner names
  .github/workflows/cache_data.yaml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, skip-changelog, needs review

#2520 Highlight arguments for "style" attribute of "pen" parameter in Gallery example "Line styles"
  examples/gallery/lines/linestyles.py
Labels: documentation, skip-changelog

#2517 Improve docs of "pygmt.grd2cpt" and "pygmt.makecpt" (02)
  pygmt/src/grd2cpt.py
  pygmt/src/makecpt.py
Labels: documentation, skip-changelog, final review call

#2521 Add link to GMT docs "Vector Attributes" in Gallery example "Vector heads and tails" ?
  examples/gallery/lines/vector_heads_tails.py
Labels: documentation, skip-changelog, final review call
