Repository GenericMappingTools/pygmt, pull requests merged in 2023-01, with the labels that each got.

#2291 Update copyright license year to 2023
  LICENSE.txt
Labels: maintenance, skip-changelog

#2295 Fix tiny typo in Maintenance Guide
  doc/maintenance.md
Labels: documentation, skip-changelog

#2289 Exclude an invalid link and timeout twitter links in the 'Check Links' workflow
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog

#2278 doc: Use plural for units for the other quantities
  examples/gallery/3d_plots/scatter3d.py
  examples/gallery/embellishments/colorbar.py
  examples/gallery/histograms/blockm.py
  examples/gallery/symbols/points_categorical.py
  examples/get_started/01_first_figure.py
  examples/tutorials/advanced/vectors.py
  examples/tutorials/basics/plot.py
  pygmt/src/colorbar.py
  pygmt/src/grdproject.py
  pygmt/src/grdtrack.py
  pygmt/src/inset.py
  pygmt/src/sphdistance.py
  pygmt/src/text.py
  pygmt/src/wiggle.py
  pygmt/src/x2sys_init.py
Labels: documentation, skip-changelog, final review call

#2301 Remove the deprecated load_japan_quakes function (deprecated since v0.6.0)
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/samples.py
  pygmt/tests/test_datasets_samples.py
Labels: deprecation, final review call

#2307 Use consistently 1-D, 2-D, or 3-D in 'session.py' and 'conversion.py' (with hyphen and capitalized)
  pygmt/clib/conversion.py
  pygmt/clib/session.py
Labels: maintenance, skip-changelog, final review call

#2293 Move IPython to optional dependencies and remove the default channel
  environment.yml
Labels: maintenance, skip-changelog, final review call

#2297 Fix the error message in the _check_dtype_and_dim function
  pygmt/clib/session.py
Labels: maintenance, skip-changelog, final review call

#2312 pygmt.grdtrack: Remove the warning about the incorrect parameter order of 'points, grid' (warned since v0.7.0)
  pygmt/src/grdtrack.py
  pygmt/tests/test_grdtrack.py
Labels: deprecation, final review call

#2303 Remove the deprecated load_fractures_compilation function (deprecated since v0.6.0)
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/samples.py
  pygmt/tests/test_datasets_samples.py
Labels: deprecation, final review call

#2316 Use "data" consistently with plural
  examples/projections/nongeo/polar.py
  examples/tutorials/advanced/date_time_charts.py
  examples/tutorials/basics/plot.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/samples.py
  pygmt/src/dimfilter.py
Labels: documentation, skip-changelog, final review call

#2308 Remove the deprecated load_ocean_ridge_points function (deprecated since v0.6.0)
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/samples.py
  pygmt/tests/test_datasets_samples.py
Labels: deprecation, final review call

#2317 Improve formulations in API Reference table
  pygmt/__init__.py
  pygmt/src/grdclip.py
  pygmt/src/histogram.py
  pygmt/src/surface.py
  pygmt/src/ternary.py
Labels: documentation, skip-changelog

#2327 Improve comments of the gallery example "Histogram"
  examples/gallery/histograms/histogram.py
Labels: documentation, skip-changelog, final review call

#2305 Remove the deprecated load_sample_bathymetry function (deprecated since v0.6.0)
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/samples.py
  pygmt/tests/test_datasets_samples.py
Labels: deprecation

#2326 Eliminate unnecessary variables in earth_age.py and earth_relief.py
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_relief.py
Labels: maintenance, skip-changelog, final review call

#2328 load_earth_magnatic_anomaly: Fix the description of resolution and registration
  pygmt/datasets/earth_magnetic_anomaly.py
Labels: documentation, skip-changelog, final review call

#2309 Remove the deprecated load_hotspots function (deprecated since v0.6.0)
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/samples.py
  pygmt/tests/test_datasets_samples.py
Labels: deprecation, needs review

#2306 Remove the deprecated load_usgs_quakes function (deprecated since v0.6.0)
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/samples.py
  pygmt/tests/test_datasets_samples.py
Labels: deprecation

#2320 Convert comments to module docstrings and fix the missing-docstring pylint issues
  doc/api/index.rst
  pygmt/clib/__init__.py
  pygmt/datasets/__init__.py
  pygmt/exceptions.py
Labels: maintenance, skip-changelog

#2310 Add load_earth_mask function for GSHHG Global Earth Mask dataset
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/earth_mask.py
  pygmt/datasets/load_remote_dataset.py
  pygmt/helpers/testing.py
  pygmt/tests/test_datasets_earth_mask.py
Labels: feature, final review call

#2332 Fix the formatting of docstrings in load_earth_relief and load_earth_magnetic_anomaly
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_relief.py
Labels: documentation, skip-changelog, final review call

#2333 Figure.solar: Improve docs and example
  examples/gallery/embellishments/solar.py
  pygmt/src/solar.py
Labels: documentation, skip-changelog, final review call

#2334 Fix the description of default registration in _load_remote_dataset
  pygmt/datasets/load_remote_dataset.py
Labels: documentation, skip-changelog

#2331 pygmt.config: Correctly resetting to default values that contain whitespaces
  pygmt/src/config.py
  pygmt/tests/test_config.py
Labels: bug

#2315 Add project keywords to the pyproject.toml file
  pyproject.toml
Labels: documentation, final review call

#2336 Improve formulation of the "Main Features" list in the API Reference
  README.rst
  doc/overview.rst
  pygmt/__init__.py
Labels: documentation, skip-changelog, final review call

#2335 Slight improvements of text and comments in gallery example "Line fronts"
  examples/gallery/lines/linefronts.py
Labels: documentation, skip-changelog, final review call

#2338 Pin fsspec to 2022.11.0 as a workaround for upstream dvc issues
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, skip-changelog, needs review

#2337 Consistently use delim_whitespace=True instead of sep=r'\s+' in pd.read_csv calls
  pygmt/datasets/samples.py
  pygmt/tests/test_contour.py
  pygmt/tests/test_grdtrack.py
  pygmt/tests/test_surface.py
  pygmt/tests/test_triangulate.py
Labels: maintenance, skip-changelog

#2304 Remove the deprecated load_mars_shape function (deprecated since v0.6.0)
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/samples.py
  pygmt/tests/test_datasets_samples.py
Labels: deprecation
