Repository GenericMappingTools/pygmt, pull requests merged in 2023-08, with the labels that each got.

#2618 pygmt.grdfill: Add alias "no_data" for "N"
  pygmt/src/grdfill.py
Labels: enhancement, final review call

#2619 Update Michael's affiliation
  AUTHORS.md
  CITATION.cff
Labels: documentation, skip-changelog

#2518 pygmt.select: Fix typos
  pygmt/src/select.py
Labels: documentation, skip-changelog, final review call

#2493 Better handling of optional virtual files (e.g., shading in Figure.grdimage)
  pygmt/clib/session.py
  pygmt/helpers/utils.py
  pygmt/src/dimfilter.py
  pygmt/src/grdimage.py
  pygmt/src/grdview.py
  pygmt/tests/test_clib.py
Labels: enhancement, final review call

#2519 pygmt.which: Update doctstring for "download" parameter
  pygmt/src/which.py
Labels: documentation, skip-changelog, final review call

#2620 Use consistently "netCDF"
  doc/contributing.md
  examples/gallery/images/track_sampling.py
  pygmt/src/grdfilter.py
  pygmt/src/grdtrack.py
  pygmt/src/nearneighbor.py
  pygmt/src/surface.py
  pygmt/tests/test_clib_put_matrix.py
  pygmt/tests/test_grdimage.py
  pygmt/tests/test_grdtrack.py
  pygmt/tests/test_grdview.py
  pygmt/tests/test_io.py
  pygmt/tests/test_nearneighbor.py
Labels: documentation, skip-changelog, final review call

#2623 Gitignore .flakeheaven_cache folder
  .gitignore
Labels: maintenance, skip-changelog

#2590 Allow passing RGB xarray.DataArray images into grdimage
  pygmt/clib/session.py
  pygmt/helpers/__init__.py
  pygmt/helpers/tempfile.py
  pygmt/helpers/utils.py
  pygmt/src/grdimage.py
  pygmt/src/tilemap.py
  pygmt/tests/baseline/test_grdimage_image.png.dvc
  pygmt/tests/test_grdimage_image.py
Labels: enhancement, final review call

#2617 pygmt.grdfilter: Improve documentation
  pygmt/src/grdfilter.py
Labels: documentation, skip-changelog, final review call

#2632 load_earth_mask: Keep data's encoding to correctly infer data's registration and gtype information
  pygmt/datasets/earth_mask.py
  pygmt/tests/test_datasets_earth_mask.py
Labels: bug, final review call

#2634 Exclude DVC files from source/binary distributions
  MANIFEST.in
Labels: maintenance, final review call

#2635 Figure.image: Deprecate parameter "bit_color" to "bitcolor" (remove in v0.12.0)
  pygmt/src/grdimage.py
Labels: deprecation, final review call

#2592 geopandas: Mapping int/int64 to int32 for OGR_GMT format
  pygmt/helpers/tempfile.py
  pygmt/tests/baseline/test_geopandas_plot_int_dtypes.png.dvc
  pygmt/tests/test_geopandas.py
Labels: bug, final review call

#2584 Support non-ASCII characters in function arguments
  examples/gallery/embellishments/colorbar.py
  examples/gallery/symbols/text_symbols.py
  pygmt/helpers/utils.py
  pygmt/tests/baseline/test_non_ascii_to_octal.png.dvc
  pygmt/tests/test_helpers.py
Labels: feature, needs review

#2515 Add gallery example "Cross-section along a transect"
  examples/gallery/images/cross_section.py
Labels: documentation, final review call

#2638 Figure.text: Support non-ASCII characters in the 'text' parameter
  pygmt/helpers/__init__.py
  pygmt/src/text.py
  pygmt/tests/baseline/test_text_nonascii.png.dvc
  pygmt/tests/test_text.py
Labels: feature, final review call

#2642 Add ResearchGate version upload to Release checklist
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: maintenance, skip-changelog, final review call

#2643 Expand documentation for Cartesian projections
  examples/projections/nongeo/cartesian_linear.py
  examples/projections/nongeo/cartesian_logarithmic.py
  examples/projections/nongeo/cartesian_power.py
Labels: documentation, skip-changelog, final review call

#2644 Use Okina in Hawaiʻi and ā with macron in Mānoa
  AUTHORS.md
  CITATION.cff
  doc/overview.rst
  examples/gallery/lines/roads.py
  pygmt/clib/session.py
Labels: documentation, skip-changelog

#2647 Change create-or-update-comment@v3 parameter reaction-type to reactions
  .github/workflows/format-command.yml
Labels: maintenance, skip-changelog, final review call

#2648 Fix typo in vectors tutorial
  examples/tutorials/advanced/vectors.py
Labels: documentation, skip-changelog, final review call

#2641 Add gallery example for plotting an RGB image from an xarray.DataArray
  examples/gallery/images/rgb_image.py
Labels: documentation, final review call

#2636 Fix tests for Aug 2023 updated remote datasets
  pygmt/tests/test_datasets_earth_age.py
  pygmt/tests/test_datasets_earth_free_air_anomaly.py
  pygmt/tests/test_datasets_earth_geoid.py
  pygmt/tests/test_datasets_earth_magnetic_anomaly.py
  pygmt/tests/test_datasets_earth_relief.py
  pygmt/tests/test_datasets_earth_vertical_gravity_gradient.py
Labels: maintenance

#2428 Add gallery example to show usage of dcw parameter in Figure.coast
  examples/gallery/maps/country_polygons.py
Labels: documentation, final review call

#2466 pygmt.select: Add aliases for "C", "F", and "L"
  pygmt/src/select.py
Labels: enhancement, final review call
