Repository GenericMappingTools/pygmt, pull requests merged in 2023-07, with the labels that each got.

#2068 Update baseline image for test test_grdview_drapegrid_dataarray
  pygmt/tests/baseline/test_grdview_drapegrid_dataarray.png.dvc
  pygmt/tests/test_grdview.py
Labels: maintenance, skip-changelog, needs review

#2563 Add gallery example "Quoted lines" (`style="q"`)
  examples/gallery/lines/quoted_lines.py
Labels: documentation, final review call

#2564 Add gallery example "Decorated lines" (`style="~"`)
  examples/gallery/lines/decorated_lines.py
Labels: documentation

#2573 Document the default CPT for GMT remote datasets
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/earth_vertical_gravity_gradient.py
Labels: documentation, final review call

#2593 Fix typo in inset tutorial
  examples/tutorials/advanced/insets.py
Labels: documentation, skip-changelog

#2595 Add private function _validate_data_input to validate input data
  pygmt/helpers/utils.py
Labels: maintenance, needs review

#2596 Add links in gallery example "Fronts"
  examples/gallery/lines/linefronts.py
Labels: documentation, skip-changelog

#2597 Add checking NEP29 in the release checklist
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: maintenance, skip-changelog, final review call

#2576 Figure.meca: Fix beachball offsetting for ndarray input (requires GMT>=6.5.0)
  pygmt/src/meca.py
  pygmt/tests/test_meca.py
Labels: bug, upstream, final review call

#2585 Create gallery example to show usage of tile maps
  examples/gallery/maps/tilemaps.py
Labels: documentation

#2600 Use consistent term for the main line in the gallery examples "Line fronts", "Quoted lines", and "Decorated lines"
  examples/gallery/lines/decorated_lines.py
  examples/gallery/lines/quoted_lines.py
Labels: documentation, skip-changelog, final review call

#2606 Mention GMT docs regarding more complicated legends in gallery example "Legends"
  examples/gallery/embellishments/legend.py
Labels: documentation, skip-changelog, final review call

#2612 CI: Run dev tests on Scientific Python nightly wheels
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, final review call

#2604 Improve docs of pygmt.xyz2grd
  pygmt/helpers/decorators.py
  pygmt/src/xyz2grd.py
Labels: documentation, skip-changelog, final review call

#2608 Figure.colorbar: Add alias "Q"
  pygmt/src/colorbar.py
Labels: enhancement, final review call

#2587 Add gallery example showing how to build an envelope around a curve
  examples/gallery/lines/envelope.py
Labels: documentation, final review call

#2616 pygmt.grdfilter: Improve inline examples
  pygmt/src/grdfilter.py
Labels: documentation, skip-changelog, final review call

#2615 Figure.image: Add alias "bitcolor" for "G"
  pygmt/src/image.py
Labels: documentation, enhancement, final review call
