Repository GenericMappingTools/pygmt, pull requests merged in 2024-01, with the labels that each got.

#2937 CI: Cache the earth_day_01d_p grid
  pygmt/helpers/testing.py
Labels: maintenance

#2940 Figure.meca: Fix typo pricipal_axis -> principal_axis
  pygmt/src/meca.py
Labels: bug

#2941 Make a duplicate fixture for pandas dtypes including pyarrow types
  pygmt/tests/test_clib_virtualfiles.py
Labels: maintenance, skip-changelog

#2938 Set GMT_SESSION_NAME to a unique name on Windows for multiprocessing support
  pygmt/session_management.py
  pygmt/tests/test_session_management.py
Labels: enhancement, needs review

#2930 Improve performance by avoiding loading the GMT library repeatedly
  pygmt/clib/session.py
  pygmt/tests/test_clib_loading.py
Labels: enhancement, needs review

#2890 Figure.timestamp: Add type hints to parameters
  pygmt/src/timestamp.py
Labels: maintenance, typing

#2948 Examples: Improve argument passed to the "frame" parameter of colorbar
  examples/gallery/images/grdgradient_shading.py
  examples/tutorials/basics/plot.py
Labels: documentation, skip-changelog

#2943 Duplicate mutable objects to avoid failures when running tests in random order
  pygmt/tests/test_geopandas.py
  pygmt/tests/test_grdimage_image.py
Labels: maintenance, skip-changelog, final review call

#2939 CI: Trigger the cache_data workflow in PRs if cache files are added/deleted/updated
  .github/workflows/cache_data.yaml
  pygmt/helpers/caching.py
  pygmt/helpers/testing.py
Labels: maintenance, final review call

#2947 CI: Remove the pytest-benchmark plugin from the benchmarks workflow
  .github/workflows/benchmarks.yml
Labels: maintenance, skip-changelog, final review call

#2946 CI: Set cache-downloads to false to speedup the "Setup Micromamba" step
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, final review call

#2881 Figure.solar: Add type hints to the 'terminator' parameter and simplify codes
  pygmt/src/solar.py
Labels: maintenance, needs review, typing

#2925 Enable ruff's pydocstyle (D) rules and remove docformatter
  .github/workflows/format-command.yml
  .github/workflows/style_checks.yaml
  Makefile
  doc/contributing.md
  environment.yml
  examples/gallery/3d_plots/grdview_surface.py
  examples/gallery/lines/vector_styles.py
  examples/tutorials/advanced/working_with_panel.py
  pygmt/figure.py
  pygmt/helpers/decorators.py
  pygmt/helpers/tempfile.py
  pygmt/helpers/utils.py
  pygmt/src/config.py
  pygmt/src/grdhisteq.py
  pygmt/src/grdtrack.py
  pygmt/tests/__init__.py
  pygmt/tests/test_clib_loading.py
  pyproject.toml
Labels: maintenance, needs review

#2944 Add common alias cores (x) for grdlandmask
  pygmt/src/grdlandmask.py
  pygmt/tests/test_grdlandmask.py
Labels: enhancement

#2950 Use GITHUB_TOKEN instead of PAT in "Slash Command Dispatch" and "GMT Dev Tests" workflows
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/slash-command-dispatch.yml
Labels: maintenance, needs review

#2951 CI: Run certain GitHub Actions workflows on official repo only
  .github/workflows/benchmarks.yml
  .github/workflows/check-links.yml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests_legacy.yaml
  .github/workflows/release-drafter.yml
Labels: maintenance

#2945 Benchmark grdsample, grdfilter and sph2grd with fixed cores
  pygmt/tests/test_grdfilter.py
  pygmt/tests/test_grdsample.py
  pygmt/tests/test_sph2grd.py
Labels: maintenance

#2954 Contributors Guide: Close Python code block
  doc/contributing.md
Labels: documentation, skip-changelog

#2955 ReadtheDocs: Cancel building pull requests for non-docs changes
  .readthedocs.yaml
Labels: maintenance, skip-changelog

#2957 Exclude CODE_OF_CONDUCT.md, AUTHORSHIP.md and pygmt/tests directory from distributions
  MANIFEST.in
  pyproject.toml
Labels: maintenance

#2952 CI: Trigger workflows based on changed files
  .github/workflows/benchmarks.yml
  .github/workflows/cache_data.yaml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
  .github/workflows/publish-to-pypi.yml
  .github/workflows/release-drafter.yml
  .github/workflows/type_checks.yml
Labels: maintenance, skip-changelog

#2924 Mark unit tests with @pytest.mark.benchmark part 2
  .github/workflows/benchmarks.yml
  pygmt/tests/test_accessor.py
  pygmt/tests/test_binstats.py
  pygmt/tests/test_blockm.py
  pygmt/tests/test_blockmedian.py
  pygmt/tests/test_clib.py
  pygmt/tests/test_clib_loading.py
  pygmt/tests/test_clib_put_matrix.py
  pygmt/tests/test_clib_put_strings.py
  pygmt/tests/test_clib_put_vector.py
  pygmt/tests/test_clib_virtualfiles.py
  pygmt/tests/test_coast.py
  pygmt/tests/test_colorbar.py
  pygmt/tests/test_config.py
  pygmt/tests/test_contour.py
  pygmt/tests/test_datasets_load_remote_datasets.py
  pygmt/tests/test_datasets_samples.py
  pygmt/tests/test_dimfilter.py
  pygmt/tests/test_figure.py
  pygmt/tests/test_filter1d.py
Labels: maintenance, skip-changelog

#2958 CI: Run benchmarks if PR is labeled with "run/benchmark"
  .github/workflows/benchmarks.yml
Labels: maintenance, needs review, run/benchmark

#2960 CI: Run "GMT Dev Tests" if PR is labeled with 'run/test-gmt-dev'
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/slash-command-dispatch.yml
Labels: maintenance, final review call, run/test-gmt-dev

#2962 Bump the GMT version in CI to 6.5.0
  .github/workflows/benchmarks.yml
  .github/workflows/cache_data.yaml
  .github/workflows/check-links.yml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_legacy.yaml
  ci/requirements/docs.yml
  doc/conf.py
  environment.yml
Labels: maintenance, run/benchmark

#2694 Bump ghostscript to 10.02.1
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  ci/requirements/docs.yml
Labels: maintenance, needs review

#2934 Add zoom_adjust param to pygmt.datasets.load_tile_map and Figure.tilemap
  pygmt/datasets/tile_map.py
  pygmt/src/tilemap.py
Labels: enhancement, upstream, final review call

#2884 Support timedelta64 dtype as input
  pygmt/clib/session.py
  pygmt/tests/baseline/test_plot_timedelta64.png.dvc
  pygmt/tests/test_clib_put_vector.py
  pygmt/tests/test_plot.py
Labels: feature, final review call

#2889 Figure.timestamp: Improve an existing test to check floating-point offset
  pygmt/tests/baseline/test_timestamp_offset.png.dvc
  pygmt/tests/test_timestamp.py
Labels: maintenance, skip-changelog, final review call

#2964 Update baseline images for basemap tests
  pygmt/tests/baseline/test_basemap.png.dvc
  pygmt/tests/baseline/test_basemap_compass.png.dvc
  pygmt/tests/baseline/test_basemap_loglog.png.dvc
  pygmt/tests/baseline/test_basemap_map_scale.png.dvc
  pygmt/tests/baseline/test_basemap_polar.png.dvc
  pygmt/tests/baseline/test_basemap_power_axis.png.dvc
  pygmt/tests/baseline/test_basemap_rose.png.dvc
  pygmt/tests/baseline/test_basemap_subplot.png.dvc
  pygmt/tests/baseline/test_basemap_utm_projection.png.dvc
  pygmt/tests/baseline/test_basemap_winkel_tripel.png.dvc
Labels: maintenance, skip-changelog, final review call

#2968 Update baseline images for meca tests
  pygmt/tests/baseline/test_meca_dict_offset_eventname.png.dvc
  pygmt/tests/baseline/test_meca_eventname.png.dvc
  pygmt/tests/baseline/test_meca_offset.png.dvc
  pygmt/tests/baseline/test_meca_spec_multiple_focalmecha.png.dvc
  pygmt/tests/baseline/test_meca_spec_single_focalmecha.png.dvc
Labels: maintenance, skip-changelog, final review call

#2965 Update baseline images for coast tests
  pygmt/tests/baseline/test_coast_dcw_list.png.dvc
  pygmt/tests/baseline/test_coast_dcw_single.png.dvc
  pygmt/tests/baseline/test_coast_region.png.dvc
  pygmt/tests/baseline/test_coast_world_mercator.png.dvc
Labels: maintenance, skip-changelog, final review call

#2973 Update baseline images for histogram, inset, logo, legend, velo, wiggle and ternary
  pygmt/tests/baseline/test_histogram.png.dvc
  pygmt/tests/baseline/test_inset_aliases.png.dvc
  pygmt/tests/baseline/test_inset_context_manager.png.dvc
  pygmt/tests/baseline/test_legend_default_position.png.dvc
  pygmt/tests/baseline/test_legend_position.png.dvc
  pygmt/tests/baseline/test_legend_specfile.png.dvc
  pygmt/tests/baseline/test_logo.png.dvc
  pygmt/tests/baseline/test_logo_on_a_map.png.dvc
  pygmt/tests/baseline/test_ternary.png.dvc
  pygmt/tests/baseline/test_ternary_1_label.png.dvc
  pygmt/tests/baseline/test_ternary_3_labels.png.dvc
  pygmt/tests/baseline/test_velo_numpy_array_numeric_only.png.dvc
  pygmt/tests/baseline/test_wiggle.png.dvc
Labels: maintenance, skip-changelog

#2976 Update baseline images for contour, grdcontour, grdview and geopandas tests
  pygmt/tests/baseline/test_contour_from_file.png.dvc
  pygmt/tests/baseline/test_contour_matrix.png.dvc
  pygmt/tests/baseline/test_contour_vec.png.dvc
  pygmt/tests/baseline/test_geopandas_plot3d_default_cube.png.dvc
  pygmt/tests/baseline/test_geopandas_plot3d_non_default_circle.png.dvc
  pygmt/tests/baseline/test_geopandas_plot_default_square.png.dvc
  pygmt/tests/baseline/test_geopandas_plot_int_dtypes.png.dvc
  pygmt/tests/baseline/test_geopandas_plot_non_default_circle.png.dvc
  pygmt/tests/baseline/test_grdcontour.png.dvc
  pygmt/tests/baseline/test_grdcontour_interval_file_full_opts.png.dvc
  pygmt/tests/baseline/test_grdcontour_labels.png.dvc
  pygmt/tests/baseline/test_grdcontour_slice.png.dvc
  pygmt/tests/baseline/test_grdview_with_perspective.png.dvc
  pygmt/tests/baseline/test_non_ascii_to_octal.png.dvc
Labels: maintenance, skip-changelog

#2971 Update baseline images for plot3d tests
  pygmt/tests/baseline/test_plot3d_colors.png.dvc
  pygmt/tests/baseline/test_plot3d_colors_sizes.png.dvc
  pygmt/tests/baseline/test_plot3d_matrix_color.png.dvc
  pygmt/tests/baseline/test_plot3d_ogrgmt_file_multipoint_default_style.png.dvc
  pygmt/tests/baseline/test_plot3d_ogrgmt_file_multipoint_non_default_style.png.dvc
  pygmt/tests/baseline/test_plot3d_projection.png.dvc
  pygmt/tests/baseline/test_plot3d_red_circles_zscale.png.dvc
  pygmt/tests/baseline/test_plot3d_red_circles_zsize.png.dvc
  pygmt/tests/baseline/test_plot3d_scalar_xyz.png.dvc
  pygmt/tests/baseline/test_plot3d_sizes.png.dvc
  pygmt/tests/baseline/test_plot3d_sizes_colors_transparencies.png.dvc
  pygmt/tests/baseline/test_plot3d_varying_transparency.png.dvc
Labels: maintenance, skip-changelog

#2972 Update baseline images for plot tests
  pygmt/tests/baseline/test_plot_colors.png.dvc
  pygmt/tests/baseline/test_plot_colors_sizes.png.dvc
  pygmt/tests/baseline/test_plot_colors_sizes_proj.png.dvc
  pygmt/tests/baseline/test_plot_dataframe_incols.png.dvc
  pygmt/tests/baseline/test_plot_datetime.png.dvc
  pygmt/tests/baseline/test_plot_from_file.png.dvc
  pygmt/tests/baseline/test_plot_lines_with_arrows.png.dvc
  pygmt/tests/baseline/test_plot_matrix.png.dvc
  pygmt/tests/baseline/test_plot_matrix_color.png.dvc
  pygmt/tests/baseline/test_plot_ogrgmt_file_multipoint_default_style.png.dvc
  pygmt/tests/baseline/test_plot_ogrgmt_file_multipoint_non_default_style.png.dvc
  pygmt/tests/baseline/test_plot_projection.png.dvc
  pygmt/tests/baseline/test_plot_red_circles.png.dvc
  pygmt/tests/baseline/test_plot_scalar_xy.png.dvc
  pygmt/tests/baseline/test_plot_shapefile.png.dvc
  pygmt/tests/baseline/test_plot_sizes.png.dvc
  pygmt/tests/baseline/test_plot_sizes_colors_transparencies.png.dvc
  pygmt/tests/baseline/test_plot_varying_intensity.png.dvc
  pygmt/tests/baseline/test_plot_varying_transparency.png.dvc
  pygmt/tests/baseline/test_plot_vectors.png.dvc
Labels: maintenance, skip-changelog

#2977 Update baseline images for grd2cpt, makecpt and subplot tests
  pygmt/tests/baseline/test_grd2cpt.png.dvc
  pygmt/tests/baseline/test_makecpt_categorical.png.dvc
  pygmt/tests/baseline/test_makecpt_continuous.png.dvc
  pygmt/tests/baseline/test_makecpt_cyclic.png.dvc
  pygmt/tests/baseline/test_makecpt_plot_colorbar.png.dvc
  pygmt/tests/baseline/test_makecpt_plot_colorbar_scaled_with_series.png.dvc
  pygmt/tests/baseline/test_makecpt_reverse_color_and_zsign.png.dvc
  pygmt/tests/baseline/test_makecpt_reverse_color_only.png.dvc
  pygmt/tests/baseline/test_makecpt_truncated_zlow_zhigh.png.dvc
  pygmt/tests/baseline/test_subplot_autolabel_margins_title.png.dvc
  pygmt/tests/baseline/test_subplot_basic_frame.png.dvc
  pygmt/tests/baseline/test_subplot_clearance_and_shared_xy_axis_layout.png.dvc
  pygmt/tests/baseline/test_subplot_direct.png.dvc
  pygmt/tests/baseline/test_subplot_outside_plotting_positioning.png.dvc
Labels: maintenance, skip-changelog

#2982 Add ruff's badge to README
  README.rst
Labels: documentation, skip-changelog, final review call

#2981 Simplify two colorbar tests and remove all others
  pygmt/tests/baseline/test_colorbar.png.dvc
  pygmt/tests/baseline/test_colorbar_box.png.dvc
  pygmt/tests/baseline/test_colorbar_box_with_fill.png.dvc
  pygmt/tests/baseline/test_colorbar_scaled_z_values.png.dvc
  pygmt/tests/baseline/test_colorbar_shading_boolean.png.dvc
  pygmt/tests/baseline/test_colorbar_shading_list.png.dvc
  pygmt/tests/baseline/test_colorbar_truncated_to_zlow_zhigh.png.dvc
  pygmt/tests/test_colorbar.py
Labels: maintenance, skip-changelog, final review call

#2984 Update baseline images for grdimage tests
  pygmt/tests/baseline/test_grdimage.png.dvc
  pygmt/tests/baseline/test_grdimage_file.png.dvc
  pygmt/tests/baseline/test_grdimage_global_subset.png.dvc
  pygmt/tests/baseline/test_grdimage_slice.png.dvc
  pygmt/tests/test_grdimage.py
Labels: maintenance, skip-changelog

#2963 Fix fixture_xr_image to open earth_day_01d_p directly with rioxarray
  pygmt/helpers/caching.py
  pygmt/tests/baseline/test_tilemap_no_clip_False.png.dvc
  pygmt/tests/baseline/test_tilemap_no_clip_True.png.dvc
  pygmt/tests/baseline/test_tilemap_ogc_wgs84.png.dvc
  pygmt/tests/baseline/test_tilemap_web_mercator.png.dvc
  pygmt/tests/test_grdimage_image.py
Labels: maintenance, needs review

#2953 doc: Convert overview source code from ReST to Markdown
  doc/conf.py
  doc/index.rst
  doc/overview.md
  doc/overview.rst
Labels: maintenance, needs review

#2989 Minor fix to hide the ruff directive in docs
  examples/gallery/lines/roads.py
Labels: maintenance, skip-changelog

#2990 Links to GMT 6.5: Update "cookbook" to "reference"
  examples/gallery/embellishments/colorbar.py
  examples/gallery/embellishments/colorbars_multiple.py
  examples/gallery/lines/linestyles.py
  examples/gallery/symbols/custom_symbols.py
  examples/gallery/symbols/patterns.py
  examples/gallery/symbols/text_symbols.py
  examples/get_started/02_contour_map.py
  examples/projections/nongeo/cartesian_linear.py
  examples/tutorials/advanced/earth_relief.py
  examples/tutorials/basics/text.py
  pygmt/helpers/decorators.py
  pygmt/src/grd2cpt.py
  pygmt/src/makecpt.py
  pygmt/src/select.py
  pygmt/src/shift_origin.py
  pygmt/src/text.py
  pygmt/src/velo.py
Labels: documentation, skip-changelog, final review call

#2978 Update min/max value of remote datasets for recent upstream changes
  pygmt/tests/test_datasets_earth_age.py
  pygmt/tests/test_datasets_earth_free_air_anomaly.py
  pygmt/tests/test_datasets_earth_geoid.py
  pygmt/tests/test_datasets_earth_magnetic_anomaly.py
  pygmt/tests/test_datasets_earth_relief.py
  pygmt/tests/test_datasets_earth_vertical_gravity_gradient.py
Labels: maintenance, skip-changelog, final review call

#2879 Figure.shift_origin: Improve docstrings, add inline examples and add type hints
  examples/gallery/3d_plots/scatter3d.py
  pygmt/src/shift_origin.py
Labels: documentation, needs review, typing

#2917 Refactor the internal _load_remote_dataset function to simplify datasets' definitions
  pygmt/datasets/load_remote_dataset.py
Labels: maintenance, needs review

#2994 Figure.plot: Update docstring for "connection" parameter to GMT 6.5
  pygmt/src/plot.py
Labels: documentation

#2997 Let 'ruff check --fix' always exit with zero
  Makefile
Labels: maintenance

#2995 CI: Temporarily delete two examples files to make ReadTheDocs pass again
  .readthedocs.yaml
Labels: maintenance, skip-changelog

#2991 NEP29: Set minimum required version to NumPy 1.23+
  .github/workflows/ci_tests.yaml
  README.rst
  ci/requirements/docs.yml
  doc/install.rst
  environment.yml
  pyproject.toml
  requirements.txt
Labels: deprecation, needs review

#2992 doc: Convert the installation guides source code from ReST to Markdown
  doc/conf.py
  doc/index.rst
  doc/install.md
  doc/install.rst
Labels: maintenance, final review call

#2986 Update output shape and mean values from some x2sys_cross tests
  pygmt/tests/test_x2sys_cross.py
Labels: maintenance, needs review

#3004 Set rtol to 1e-4 to avoid system-dependent floating-point differences
  pygmt/tests/test_x2sys_cross.py
Labels: maintenance, skip-changelog

#3005 Update baseline images for test_grdimage_image
  pygmt/tests/baseline/test_grdimage_image.png.dvc
Labels: maintenance, skip-changelog

#3006 Slightly increase the tolerance for test_grdimage_global_subset
  pygmt/tests/test_grdimage.py
Labels: maintenance, skip-changelog

#3001 doc: Add 'Doctests workflow' to release checklist and GMT bumping checklist
  .github/ISSUE_TEMPLATE/bump_gmt_checklist.md
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: maintenance, skip-changelog, needs review

#3000 Revert "CI: Temporarily delete two examples files to make ReadTheDocs pass again (#2995)"
  .readthedocs.yaml
Labels: maintenance, skip-changelog

#3007 Figure.tilemap: Fix typo
  pygmt/src/tilemap.py
Labels: documentation, skip-changelog

#3008 Figure.text: Fix highlighting
  pygmt/src/text.py
Labels: documentation, skip-changelog

#2996 Rename API function Session.open_virtual_file to Session.open_virtualfile (remove in v0.15.0)
  doc/api/index.rst
  pygmt/clib/session.py
  pygmt/tests/test_clib_virtualfiles.py
Labels: deprecation, needs review

#3014 CI: Fix the condition for cancel builds on ReadTheDocs
  .readthedocs.yaml
Labels: maintenance, skip-changelog

#2999 Add gallery example for plotting connection lines ("connection" parameter of Figure.plot)
  examples/gallery/lines/connection_lines.py
Labels: documentation, final review call

#3002 Figure.timestamp: Deprecate parameter 'justification' to 'justify' (remove in v0.13.0)
  examples/gallery/embellishments/timestamp.py
  pygmt/src/timestamp.py
  pygmt/tests/baseline/test_timestamp_justify.png.dvc
  pygmt/tests/test_timestamp.py
Labels: deprecation

#3016 Gallery example "Decorated lines": Rotation of symbols ("+apangle")
  examples/gallery/lines/decorated_lines.py
Labels: documentation, skip-changelog, final review call

#3018 Remove X (Twitter) from README and checklists
  .github/ISSUE_TEMPLATE/release_checklist.md
  .github/workflows/check-links.yml
  README.rst
Labels: maintenance, skip-changelog

#2847 Add load_mars_relief to load Mars relief dataset in various resolutions and registrations
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/load_remote_dataset.py
  pygmt/datasets/mars_relief.py
  pygmt/helpers/caching.py
  pygmt/tests/test_datasets_mars_relief.py
Labels: feature, needs review

#2674 Add load_moon_relief to load Moon relief dataset in various resolutions and registrations
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/load_remote_dataset.py
  pygmt/datasets/moon_relief.py
  pygmt/helpers/caching.py
  pygmt/tests/test_datasets_moon_relief.py
Labels: feature, needs review

#2906 Add load_venus_relief to load Venus relief dataset in various resolutions
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/load_remote_dataset.py
  pygmt/datasets/venus_relief.py
  pygmt/helpers/caching.py
  pygmt/tests/test_datasets_venus_relief.py
Labels: feature, needs review

#3015 Add gallery example showing how to adjust line segment ends (caps and joints)
  examples/gallery/lines/line_segment_ends.py
Labels: documentation, final review call

#3019 Increase image comparison tolerance to 3.6 for test_grdimage_global_subset
  pygmt/tests/test_grdimage.py
Labels: maintenance, skip-changelog

#3020 CI: Cache gmt_hash_server.txt and gmt_data_server.txt files
  .github/workflows/benchmarks.yml
  .github/workflows/cache_data.yaml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, skip-changelog

#3021 Fix failing tests for legacy GMT versions
  pygmt/tests/test_datasets_earth_relief.py
  pygmt/tests/test_datasets_load_remote_datasets.py
  pygmt/tests/test_x2sys_cross.py
Labels: maintenance, skip-changelog, needs review

#2862 Move compatibility table from README to separate file
  .github/ISSUE_TEMPLATE/bump_gmt_checklist.md
  .github/ISSUE_TEMPLATE/release_checklist.md
  README.rst
  doc/index.rst
  doc/install.md
  doc/maintenance.md
  doc/minversions.rst
Labels: documentation, needs review

#3023 README: Fix link to minimum-supported-versions table
  README.rst
Labels: documentation, skip-changelog
