Repository GenericMappingTools/pygmt, pull requests merged in 2024-09, with the labels that each got.

#3418 PYGMT_USE_EXTERNAL_DISPLAY should NOT disable image display in Jupyter notebook environment
  pygmt/figure.py
  pygmt/tests/test_figure.py
Labels: bug, needs review

#3406 DOC: Generate the list of supported fonts dynamically from codes
  doc/_static/style.css
  doc/conf.py
  doc/techref/fonts.md
Labels: documentation, maintenance, skip-changelog, final review call

#3409 DOC: Generate the charset tables dynamically from codes
  doc/techref/encodings.md
Labels: documentation, maintenance, skip-changelog, final review call

#3316 Tutorial: Adding a data set on top of a topographic surface via "drapegrid" of "Figure.grdview"
  examples/tutorials/advanced/draping_on_3d_surface.py
Labels: documentation, final review call

#3421 Figure.show: Refactor codes, improve docstrings and add type hints
  pygmt/figure.py
Labels: maintenance, skip-changelog, needs review

#3396 pygmt.set_display: Fix the bug that `method=None` doesn't reset to the default display method
  pygmt/figure.py
  pygmt/tests/test_figure.py
Labels: bug, final review call

#3422 Fix typos in Draping a dataset tutorial
  examples/tutorials/advanced/draping_on_3d_surface.py
Labels: documentation, skip-changelog

#3370 Fix typos in documentation and codes
  doc/maintenance.md
  doc/techref/encodings.md
  doc/techref/projections.md
  examples/gallery/basemaps/ternary.py
  examples/gallery/embellishments/colorbar.py
  examples/gallery/lines/vector_heads_tails.py
  examples/gallery/lines/vector_styles.py
  examples/tutorials/advanced/non_ascii_text.py
Labels: documentation, skip-changelog

#3425 Changelog entry for v0.13.0
  CITATION.cff
  README.md
  doc/_static/version_switch.js
  doc/changes.md
  doc/minversions.md
Labels: maintenance, skip-changelog, final review call

#3427 Remove the deprecated build_arg_string function (deprecated since v0.12.0)
  pygmt/helpers/__init__.py
  pygmt/helpers/utils.py
Labels: deprecation, final review call

#3428 Figure.grdcontour: Remove the deprecated syntax for the 'annotation' parameter
  pygmt/src/grdcontour.py
  pygmt/tests/test_grdcontour.py
Labels: deprecation, final review call

#3431 CI: Pin actions/upload-artifact and peter-evans/slash-command-dispatch to the latest tag
  .github/workflows/cache_data.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/slash-command-dispatch.yml
Labels: maintenance, skip-changelog, final review call

#3348 doc: Rename sphinx-gallery's README.txt to GALLERY_HEADER.rst and require Sphinx-Gallery>=0.17.0
  doc/_templates/breadcrumbs.html
  environment.yml
  examples/gallery/3d_plots/GALLERY_HEADER.rst
  examples/gallery/GALLERY_HEADER.rst
  examples/gallery/basemaps/GALLERY_HEADER.rst
  examples/gallery/embellishments/GALLERY_HEADER.rst
  examples/gallery/histograms/GALLERY_HEADER.rst
  examples/gallery/images/GALLERY_HEADER.rst
  examples/gallery/lines/GALLERY_HEADER.rst
  examples/gallery/maps/GALLERY_HEADER.rst
  examples/gallery/seismology/GALLERY_HEADER.rst
  examples/gallery/symbols/GALLERY_HEADER.rst
  examples/get_started/GALLERY_HEADER.rst
  examples/projections/GALLERY_HEADER.rst
  examples/projections/azim/GALLERY_HEADER.rst
  examples/projections/conic/GALLERY_HEADER.rst
  examples/projections/cyl/GALLERY_HEADER.rst
  examples/projections/misc/GALLERY_HEADER.rst
  examples/projections/nongeo/GALLERY_HEADER.rst
  examples/tutorials/GALLERY_HEADER.rst
  examples/tutorials/advanced/GALLERY_HEADER.rst
  examples/tutorials/basics/GALLERY_HEADER.rst
Labels: maintenance, needs review

#3374 Improve the release checklist based on experience with v0.13.0 release
  .github/ISSUE_TEMPLATE/4-release_checklist.md
Labels: maintenance, skip-changelog, final review call

#3439 Gallery example "vector styles": Fix typos
  examples/gallery/lines/vector_styles.py
Labels: documentation, skip-changelog

#3437 Figure.legend: Refactor to simplify the logic of checking legend specification
  pygmt/src/legend.py
  pygmt/tests/test_legend.py
Labels: maintenance, skip-changelog

#3436 check_figures_equal: Initialize fig_ref and fig_test to avoid UnboundLocalError when crashes
  pygmt/helpers/testing.py
Labels: maintenance, skip-changelog

#3434 Figure.savefig: Refactor if-else statements to match-case statements
  pygmt/figure.py
Labels: maintenance, skip-changelog

#3433 pygmt.show_versions: Add a test to check GMT-Ghostscript warnings
  pygmt/tests/test_show_versions.py
Labels: maintenance, skip-changelog

#3440 Add type hints to the unique_name function and the GMTTempFile class
  pygmt/helpers/tempfile.py
Labels: maintenance, skip-changelog, final review call

#3326 Add the Session.virtualfile_from_stringio method to allow StringIO input for certain functions/methods
  doc/api/index.rst
  pygmt/clib/session.py
  pygmt/helpers/utils.py
  pygmt/tests/test_clib_virtualfiles.py
Labels: feature, needs review

#3443 Bump to Ghostscript 10.04.0
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  ci/requirements/docs.yml
  environment.yml
Labels: maintenance

#3438 Figure.legend: Support passing a StringIO object as the legend specification
  pygmt/src/legend.py
  pygmt/tests/test_legend.py
Labels: enhancement

#3432 Document the environment variables that can affect the behavior of PyGMT
  doc/_static/style.css
  doc/install.md
  doc/techref/environment_variables.md
  doc/techref/index.md
  pygmt/clib/loading.py
  pygmt/clib/session.py
  pygmt/figure.py
  pygmt/src/timestamp.py
  pygmt/src/x2sys_cross.py
  pygmt/src/x2sys_init.py
Labels: documentation

#3447 Update "PyData Ecosystem" to "Scientific Python Ecosystem"
  README.md
  examples/tutorials/advanced/date_time_charts.py
  pygmt/__init__.py
Labels: documentation, final review call

#3365 Refactor Figure.text to make it more readable/maintainable
  pygmt/src/text.py
Labels: maintenance, skip-changelog

#3446 Correctly reserve the grid data dtype by converting ctypes array to numpy array with np.ctypeslib.as_array
  pygmt/datatypes/grid.py
  pygmt/datatypes/image.py
  pygmt/tests/test_sphinterpolate.py
Labels: bug, final review call, run/benchmark

#3407 DOC/projections: Simplify links in the projection table to use directly the titles of the examples
  doc/techref/projections.md
  examples/projections/azim/azim_equidistant.py
  examples/projections/azim/azim_general_perspective.py
  examples/projections/azim/azim_general_stereographic.py
  examples/projections/azim/azim_gnomonic.py
  examples/projections/azim/azim_lambert.py
  examples/projections/azim/azim_orthographic.py
  examples/projections/conic/conic_albers.py
  examples/projections/conic/conic_equidistant.py
  examples/projections/conic/conic_lambert.py
  examples/projections/conic/polyconic.py
  examples/projections/cyl/cyl_cassini.py
  examples/projections/cyl/cyl_equal_area.py
  examples/projections/cyl/cyl_equidistant.py
  examples/projections/cyl/cyl_mercator.py
  examples/projections/cyl/cyl_miller.py
  examples/projections/cyl/cyl_oblique_mercator_1.py
  examples/projections/cyl/cyl_oblique_mercator_2.py
  examples/projections/cyl/cyl_oblique_mercator_3.py
  examples/projections/cyl/cyl_stereographic.py
  examples/projections/cyl/cyl_transverse_mercator.py
  examples/projections/cyl/cyl_universal_transverse_mercator.py
  examples/projections/misc/misc_eckertIV.py
  examples/projections/misc/misc_eckertVI.py
  examples/projections/misc/misc_hammer.py
  examples/projections/misc/misc_mollweide.py
  examples/projections/misc/misc_robinson.py
  examples/projections/misc/misc_sinusoidal.py
  examples/projections/misc/misc_van_der_grinten.py
  examples/projections/misc/misc_winkel_tripel.py
Labels: documentation, maintenance, skip-changelog, final review call

#3452 CI: Pin ghostscript<10 for GMT 6.3/6.4 in the GMT Legacy Tests workflow
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, skip-changelog

#3455 GeoPandas: Explicitly convert columns with overflow integers to avoid OverflowError with fiona 1.10
  pygmt/helpers/tempfile.py
Labels: bug

#3420 CI: Add a separate CI job on Ubuntu to test geopandas v0.x
  .github/workflows/ci_tests.yaml
Labels: maintenance

#3453 Remove unused CSS classes for style.css
  doc/_static/style.css
Labels: maintenance, skip-changelog

#3460 SPEC 0: Set minimum supported versions to pandas>=2.0 and xarray>=2023.04
  .github/workflows/ci_tests.yaml
  environment.yml
  pyproject.toml
  requirements.txt
Labels: deprecation

#3451 Combine the Oblique Mercator projection pages into one page
  doc/techref/projections.md
  examples/projections/cyl/cyl_oblique_mercator.py
  examples/projections/cyl/cyl_oblique_mercator_1.py
  examples/projections/cyl/cyl_oblique_mercator_2.py
  examples/projections/cyl/cyl_oblique_mercator_3.py
Labels: documentation

#3462 Mention breaking change regarding extra quotation marks around text strings in changelog v0.12.0
  doc/changes.md
Labels: documentation

#3449 Add enums GridFormat for GMT grid format ID
  pygmt/enums.py
Labels: maintenance

#3463 Set the 'Conventions' attribute to 'CF-1.7' for netCDF grids only
  pygmt/datatypes/header.py
Labels: bug

#3128 GMT_IMAGE: Implement the GMT_IMAGE.to_dataarray method for 3-band images
  pygmt/datatypes/grid.py
  pygmt/datatypes/header.py
  pygmt/datatypes/image.py
  pygmt/tests/test_clib_read_data.py
Labels: enhancement

#3465 clib.loading: Improve the typing hints and docstrings
  pygmt/clib/loading.py
Labels: maintenance, skip-changelog, final review call

#3461 Figure.plot & Figure.plot3d: Move common codes into _common.py
  pygmt/src/_common.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
Labels: maintenance, skip-changelog, final review call

#2235 Add function to load Blue Marble dataset
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/earth_day.py
  pygmt/datasets/load_remote_dataset.py
  pygmt/tests/test_datasets_earth_day.py
  pygmt/tests/test_grdimage_image.py
Labels: feature, final review call

#3471 Fix earth_day_01d_p to earth_day_01d
  doc/changes.md
  pygmt/datatypes/image.py
  pygmt/helpers/caching.py
  pygmt/tests/test_clib_read_data.py
Labels: maintenance, skip-changelog

#3467 DOC: Update URLs from "http" to "https" if available
  .github/ISSUE_TEMPLATE/1-bug_report.yaml
  AUTHORS.md
  README.md
  doc/_static/version_switch.js
  doc/_templates/footer.html
  doc/contributing.md
  doc/overview.md
  examples/gallery/lines/roads.py
  pygmt/src/grd2cpt.py
  pygmt/src/makecpt.py
  pygmt/src/select.py
Labels: maintenance, skip-changelog, final review call

#3464 DOC/projections: Make example design consistent
  examples/projections/azim/azim_equidistant.py
  examples/projections/azim/azim_general_perspective.py
  examples/projections/azim/azim_general_stereographic.py
  examples/projections/azim/azim_gnomonic.py
  examples/projections/azim/azim_lambert.py
  examples/projections/azim/azim_orthographic.py
  examples/projections/conic/conic_albers.py
  examples/projections/conic/conic_equidistant.py
  examples/projections/conic/conic_lambert.py
  examples/projections/conic/polyconic.py
  examples/projections/cyl/cyl_cassini.py
  examples/projections/cyl/cyl_equal_area.py
  examples/projections/cyl/cyl_equidistant.py
  examples/projections/cyl/cyl_mercator.py
  examples/projections/cyl/cyl_miller.py
  examples/projections/cyl/cyl_oblique_mercator.py
  examples/projections/cyl/cyl_stereographic.py
  examples/projections/cyl/cyl_transverse_mercator.py
  examples/projections/cyl/cyl_universal_transverse_mercator.py
  examples/projections/misc/misc_eckertIV.py
  examples/projections/misc/misc_eckertVI.py
  examples/projections/misc/misc_hammer.py
  examples/projections/misc/misc_mollweide.py
  examples/projections/misc/misc_robinson.py
  examples/projections/misc/misc_sinusoidal.py
  examples/projections/misc/misc_van_der_grinten.py
  examples/projections/misc/misc_winkel_tripel.py
  examples/projections/nongeo/cartesian_linear.py
  examples/projections/nongeo/cartesian_logarithmic.py
  examples/projections/nongeo/cartesian_power.py
  examples/projections/nongeo/polar.py
Labels: documentation, skip-changelog, final review call

#3472 DOC: Fix typo "ontop" to "on top"
  examples/projections/nongeo/cartesian_linear.py
  examples/projections/nongeo/cartesian_logarithmic.py
  examples/projections/nongeo/cartesian_power.py
Labels: documentation, skip-changelog

#3474 Earth day/night remote dataset: Fix typo - use plural
  pygmt/datasets/earth_day.py
  pygmt/datasets/earth_night.py
Labels: documentation, skip-changelog
