Repository GenericMappingTools/pygmt, pull requests merged in 2024-03, with the labels that each got.

#3068 clib: Rename the virtualfile_from_data method to virtualfile_in
  doc/api/index.rst
  pygmt/clib/session.py
  pygmt/src/binstats.py
  pygmt/src/blockm.py
  pygmt/src/contour.py
  pygmt/src/dimfilter.py
  pygmt/src/filter1d.py
  pygmt/src/grd2cpt.py
  pygmt/src/grd2xyz.py
  pygmt/src/grdclip.py
  pygmt/src/grdcontour.py
  pygmt/src/grdcut.py
  pygmt/src/grdfill.py
  pygmt/src/grdfilter.py
  pygmt/src/grdgradient.py
  pygmt/src/grdhisteq.py
  pygmt/src/grdimage.py
  pygmt/src/grdinfo.py
  pygmt/src/grdproject.py
  pygmt/src/grdsample.py
  pygmt/src/grdtrack.py
  pygmt/src/grdview.py
  pygmt/src/grdvolume.py
  pygmt/src/histogram.py
  pygmt/src/info.py
  pygmt/src/meca.py
  pygmt/src/nearneighbor.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/project.py
  pygmt/src/rose.py
  pygmt/src/select.py
  pygmt/src/sph2grd.py
  pygmt/src/sphdistance.py
  pygmt/src/sphinterpolate.py
  pygmt/src/surface.py
  pygmt/src/ternary.py
  pygmt/src/text.py
  pygmt/src/tilemap.py
  pygmt/src/triangulate.py
  pygmt/src/velo.py
  pygmt/src/wiggle.py
  pygmt/src/xyz2grd.py
  pygmt/tests/test_clib_virtualfiles.py
Labels: deprecation

#3080 Makefile: Remove unused variable, fix pygmt to $PROJECT and remove .benchmarks directory
  Makefile
Labels: maintenance, skip-changelog

#3082 Use consistent names (vintbl and vingrd) for input virtual files
  pygmt/src/binstats.py
  pygmt/src/blockm.py
  pygmt/src/contour.py
  pygmt/src/dimfilter.py
  pygmt/src/filter1d.py
  pygmt/src/grd2cpt.py
  pygmt/src/grd2xyz.py
  pygmt/src/grdclip.py
  pygmt/src/grdcontour.py
  pygmt/src/grdcut.py
  pygmt/src/grdfill.py
  pygmt/src/grdfilter.py
  pygmt/src/grdgradient.py
  pygmt/src/grdimage.py
  pygmt/src/grdinfo.py
  pygmt/src/grdproject.py
  pygmt/src/grdsample.py
  pygmt/src/grdtrack.py
  pygmt/src/grdview.py
  pygmt/src/grdvolume.py
  pygmt/src/histogram.py
  pygmt/src/info.py
  pygmt/src/meca.py
  pygmt/src/nearneighbor.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/project.py
  pygmt/src/rose.py
  pygmt/src/select.py
  pygmt/src/sph2grd.py
  pygmt/src/sphdistance.py
  pygmt/src/sphinterpolate.py
  pygmt/src/surface.py
  pygmt/src/ternary.py
  pygmt/src/text.py
  pygmt/src/tilemap.py
  pygmt/src/velo.py
  pygmt/src/wiggle.py
  pygmt/src/xyz2grd.py
Labels: maintenance, needs review

#3079 Enable the test_load_libgmt_fails test on Windows
  pygmt/tests/test_clib_loading.py
Labels: maintenance, skip-changelog, final review call

#3078 TYP: Add type hints to the clib.loading.clib_full_names/load_libgmt functions
  pygmt/clib/loading.py
Labels: skip-changelog, final review call, typing

#3091 Fix typo in "clib/session.py"
  pygmt/clib/session.py
Labels: documentation, skip-changelog

#2729 Wrap GMT's standard data type GMT_DATASET for table inputs
  pygmt/datatypes/dataset.py
Labels: enhancement

#3093 Figure.grdview: Fix typo in docs
  pygmt/src/grdview.py
Labels: documentation, skip-changelog

#3087 TYP: Add type hints and improve docstrings of load_tile_map function
  pygmt/datasets/tile_map.py
Labels: skip-changelog, final review call, typing

#3083 clib: Add virtualfile_to_dataset method for converting virtualfile to a dataset
  doc/api/index.rst
  pygmt/clib/session.py
Labels: enhancement, final review call

#3096 doc: Move virtualfile_from_* methods as low-level API functions
  doc/api/index.rst
Labels: documentation, skip-changelog, needs review

#3097 pygmt.grd2xyz: Improve performance by storing output in virtual files
  pygmt/helpers/decorators.py
  pygmt/src/grd2xyz.py
  pygmt/tests/test_grd2xyz.py
Labels: maintenance, final review call, run/benchmark

#3098 Add doctests for the validate_output_table_type function
  pygmt/helpers/validators.py
Labels: maintenance, skip-changelog, final review call

#3085 pygmt.filter1d: Improve performance by storing output in virtual files
  pygmt/src/filter1d.py
  pygmt/tests/test_filter1d.py
Labels: maintenance

#3112 Bump to ghotscript 10.03.0
  .github/workflows/ci_docs.yml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  ci/requirements/docs.yml
  environment.yml
Labels: maintenance

#3110 pygmt.project: Add 'output_type' parameter for output in pandas/numpy/file formats
  pygmt/src/project.py
Labels: enhancement, final review call

#3062 Fix the DataArray repr in the load_tile_map doctest for xarray v2024.02
  pygmt/datasets/tile_map.py
Labels: maintenance, skip-changelog

#3108 pygmt.select: Improve performance by storing output in virtual files
  pygmt/src/select.py
Labels: maintenance, final review call

#3106 pygmt.grdtrack: Add 'output_type' parameter for output in pandas/numpy/file formats
  pygmt/src/grdtrack.py
Labels: enhancement, final review call

#3102 pygmt.grdvolume: Refactor to store output in virtual files instead of temporary files
  pygmt/src/grdvolume.py
  pygmt/tests/test_grdvolume.py
Labels: maintenance

#3107 pygmt.triangulate.delaunay_triples: Improve performance by storing output in virtual files
  pygmt/src/triangulate.py
  pygmt/tests/test_triangulate.py
Labels: maintenance

#3113 Fix ghostscript typo in environment.yml
  environment.yml
Labels: maintenance, skip-changelog

#3118 CI: Ignore ResearchGate homepage in the links check
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog, final review call

#3121 Datetime tutorial: Change symbol usde in first code example to fix failing under Windows
  examples/tutorials/advanced/date_time_charts.py
Labels: bug, skip-changelog

#3122 pygmt.grdvolume: Fix a failing doctest
  pygmt/src/grdvolume.py
Labels: maintenance, skip-changelog, final review call

#3123 datetime tutorial: Rewrap to 88 characters
  examples/tutorials/advanced/date_time_charts.py
Labels: documentation, skip-changelog

#3124 clib: Change the parameter order and set output_type to pandas in virtualfile_to_dataset
  pygmt/clib/session.py
  pygmt/src/blockm.py
  pygmt/src/filter1d.py
  pygmt/src/grd2xyz.py
  pygmt/src/grdhisteq.py
  pygmt/src/grdtrack.py
  pygmt/src/grdvolume.py
  pygmt/src/project.py
  pygmt/src/select.py
  pygmt/src/triangulate.py
Labels: maintenance, skip-changelog, final review call

#3095 TYP: Add type hints to the Figure.tilemap method
  pygmt/src/tilemap.py
Labels: skip-changelog, final review call, typing

#3127 Wrap GMT's data structure GMT_GRID_HEADER for grid/image/cube headers
  pygmt/datatypes/grid.py
Labels: enhancement, needs review

#3119 Migrate from os.path to pathlib
  examples/gallery/images/image.py
  examples/tutorials/basics/text.py
  pygmt/figure.py
  pygmt/helpers/tempfile.py
  pygmt/helpers/testing.py
  pygmt/src/grdfilter.py
  pygmt/src/x2sys_cross.py
  pygmt/tests/test_accessor.py
  pygmt/tests/test_clib.py
  pygmt/tests/test_clib_virtualfiles.py
  pygmt/tests/test_contour.py
  pygmt/tests/test_figure.py
  pygmt/tests/test_grd2cpt.py
  pygmt/tests/test_grdcontour.py
  pygmt/tests/test_grdtrack.py
  pygmt/tests/test_helpers.py
  pygmt/tests/test_info.py
  pygmt/tests/test_makecpt.py
  pygmt/tests/test_plot.py
  pygmt/tests/test_plot3d.py
  pygmt/tests/test_psconvert.py
  pygmt/tests/test_session_management.py
  pygmt/tests/test_sphinx_gallery.py
  pygmt/tests/test_text.py
  pygmt/tests/test_x2sys_cross.py
  pygmt/tests/test_x2sys_init.py
Labels: maintenance, final review call

#3129 Enable ruff's PTH (flake8-use-pathlib) rules and fix violations
  examples/tutorials/basics/text.py
  pygmt/clib/session.py
  pygmt/datatypes/dataset.py
  pygmt/figure.py
  pygmt/helpers/tempfile.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/tests/test_helpers.py
  pygmt/tests/test_legend.py
  pygmt/tests/test_meca.py
  pygmt/tests/test_plot.py
  pygmt/tests/test_plot3d.py
  pygmt/tests/test_text.py
  pygmt/tests/test_x2sys_cross.py
  pygmt/tests/test_x2sys_init.py
  pyproject.toml
Labels: maintenance, needs review

#3133 CI: Configure workflows to run on 'workflow_dispatch' event
  .github/workflows/cache_data.yaml
  .github/workflows/check-links.yml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance

#3135 Tests: Suppress warnings by explicitly setting output_type to 'file'
  pygmt/tests/test_blockm.py
  pygmt/tests/test_blockmedian.py
  pygmt/tests/test_grdtrack.py
  pygmt/tests/test_project.py
  pygmt/tests/test_select.py
Labels: maintenance, skip-changelog, final review call

#3138 Fix typo in colorbar example
  examples/gallery/embellishments/colorbar.py
Labels: documentation, skip-changelog

#3136 Add sequence_to_ctypes_array to convert a sequence to a ctypes array
  pygmt/clib/conversion.py
  pygmt/clib/session.py
Labels: maintenance, final review call

#3137 Add strings_to_ctypes_array to convert a sequence of strings into a ctypes array
  pygmt/clib/conversion.py
  pygmt/clib/session.py
Labels: maintenance

#2742 Figure.plot: Refactor to increase code readability
  pygmt/src/plot.py
Labels: maintenance, skip-changelog

#3140 Session.virtualfile_to_dataset: Add new parameters 'dtype'/'index_col' for pandas output
  pygmt/clib/session.py
  pygmt/datatypes/dataset.py
  pygmt/src/grdhisteq.py
Labels: enhancement, needs review

#3145 gitignore: Ignore the sg_execution_times.rst file generated by Sphinx-Gallery
  .gitignore
Labels: maintenance, skip-changelog

#3143 Figure.plot3d: Refactor to increase code readability
  pygmt/src/plot3d.py
Labels: maintenance, skip-changelog, final review call

#3131 GMT_DATASET.to_dataframe: Return an empty DataFrame if a file contains no data
  pygmt/datatypes/dataset.py
  pygmt/tests/test_datatypes_dataset.py
Labels: enhancement

#3139 Session.call_module: Support passing a list of argument strings
  pygmt/clib/session.py
  pygmt/tests/test_clib.py
Labels: enhancement
