Repository GenericMappingTools/pygmt, pull requests merged in 2024-04, with the labels that each got.

#3151 SPEC 0: Bump minimum supported versions to xarray 2022.06
  .github/workflows/ci_tests.yaml
  doc/minversions.md
  environment.yml
  pyproject.toml
  requirements.txt
Labels: maintenance

#3134 GMT_GRID_HEADER: Parse grid header and add grid properties
  pygmt/datatypes/grid.py
  pygmt/datatypes/header.py
Labels: enhancement

#3153 Refactor the test_call_module_empty_argument test
  pygmt/tests/test_clib.py
Labels: maintenance, skip-changelog, final review call

#3157 Session.virtualfile_to_dataset: Add 'strings' output type for the array of trailing texts
  pygmt/clib/session.py
  pygmt/datatypes/dataset.py
Labels: enhancement, final review call

#3148 pygmt.which: Refactor to get rid of temporary files
  pygmt/src/which.py
Labels: maintenance, final review call, run/benchmark

#3152 Wrap GMT_Inquire_VirtualFile to get the family of virtualfiles
  pygmt/clib/session.py
  pygmt/tests/test_clib_virtualfiles.py
Labels: enhancement, final review call

#3149 Add function build_arg_list for building arguments list from keyword dictionaries
  pygmt/helpers/__init__.py
  pygmt/helpers/decorators.py
  pygmt/helpers/utils.py
Labels: enhancement, final review call

#3165 Switch to official GitHub action for managing app tokens
  .github/workflows/format-command.yml
Labels: maintenance

#3166 CI: Use gh to create issues in Check Links workflow
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog, final review call

#3174 GMT_DATASET: Add workaround for None values in the trailing text
  .github/workflows/cache_data.yaml
  pygmt/datatypes/dataset.py
  pygmt/tests/test_datatypes_dataset.py
Labels: maintenance, final review call

#2398 Wrap GMT's standard data type GMT_GRID for grids
  doc/api/index.rst
  pygmt/clib/session.py
  pygmt/datatypes/grid.py
  pygmt/helpers/decorators.py
  pygmt/src/binstats.py
  pygmt/src/dimfilter.py
  pygmt/src/grdclip.py
  pygmt/src/grdfill.py
  pygmt/src/grdfilter.py
  pygmt/src/grdgradient.py
  pygmt/src/grdhisteq.py
  pygmt/src/grdlandmask.py
  pygmt/src/grdproject.py
  pygmt/src/grdsample.py
  pygmt/src/nearneighbor.py
  pygmt/src/sph2grd.py
  pygmt/src/sphdistance.py
  pygmt/src/sphinterpolate.py
  pygmt/src/surface.py
  pygmt/src/triangulate.py
  pygmt/src/xyz2grd.py
  pygmt/tests/test_datasets_load_remote_datasets.py
  pygmt/tests/test_sphinterpolate.py
Labels: enhancement

#3175 CI: Use GH_TOKEN instead of GITHUB_TOKEN for GitHub CLI
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog

#3171 Reorganize the list of data files for caching
  pygmt/helpers/caching.py
Labels: maintenance, skip-changelog, final review call

#3177 tests/test_datatypes_dataset: Fix typo in comment
  pygmt/tests/test_datatypes_dataset.py
Labels: documentation, skip-changelog

#3179 Add a test for typesetting quotation marks
  pygmt/tests/baseline/test_text_quotation_marks.png.dvc
  pygmt/tests/test_text.py
Labels: maintenance, skip-changelog

#2760 Tutorial "Plotting text": Rewrite to improve structure, add parameters, add list input
  examples/tutorials/basics/text.py
Labels: documentation, final review call

#3185 CI: Remove the 'add reaction' step from the format workflow
  .github/workflows/format-command.yml
Labels: maintenance, skip-changelog, final review call

#3186 Gallery example "Custom symbols": Mention own coustom symbols
  examples/gallery/symbols/custom_symbols.py
Labels: documentation, final review call

#3183 Remove sequence_space converter from kwargs_to_string
  pygmt/helpers/decorators.py
Labels: deprecation, skip-changelog, final review call

#3188 CI: Use 'gh run download' to download GMT cache artifacts
  .github/workflows/benchmarks.yml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, skip-changelog, needs review

#3184 Deprecate the build_arg_string function in v0.12.0 (will be removed in v0.14.0) and use build_arg_list instead
  pygmt/helpers/utils.py
Labels: deprecation, final review call

#3187 CI: Use 'gh release' to upload assets to release
  .github/workflows/release-baseline-images.yml
Labels: maintenance, final review call

#3189 CI: Consistently use github.token instead of secrets.GITHUB_TOKEN
  .github/workflows/check-links.yml
  .github/workflows/dvc-diff.yml
  .github/workflows/release-drafter.yml
  .github/workflows/slash-command-dispatch.yml
Labels: maintenance

#3120 Refactor the _load_remote_dataset function to load tiled and non-tiled grids in a consistent way
  pygmt/datasets/load_remote_dataset.py
  pygmt/tests/test_accessor.py
Labels: enhancement, final review call

#3195 Update the list of cached data files
  pygmt/helpers/caching.py
  pygmt/tests/test_datatypes_dataset.py
Labels: maintenance, skip-changelog

#3196 CI: slash-commands-dispatch: Fix typo
  .github/workflows/slash-command-dispatch.yml
Labels: bug, skip-changelog

#3198 Mark three x2sys_cross as xfail on macOS
  pygmt/tests/test_x2sys_cross.py
Labels: maintenance, skip-changelog, final review call

#3048 Remote Datasets: Adjust attributes - remove "title", use default of "name" and "long_name", introduce "description"
  examples/tutorials/advanced/grid_equalization.py
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/earth_geoid.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_mask.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/earth_vertical_gravity_gradient.py
  pygmt/datasets/load_remote_dataset.py
  pygmt/src/grd2xyz.py
  pygmt/tests/test_datasets_earth_age.py
  pygmt/tests/test_datasets_earth_free_air_anomaly.py
  pygmt/tests/test_datasets_earth_geoid.py
  pygmt/tests/test_datasets_earth_magnetic_anomaly.py
  pygmt/tests/test_datasets_earth_mask.py
  pygmt/tests/test_datasets_earth_relief.py
  pygmt/tests/test_datasets_earth_vertical_gravity_gradient.py
  pygmt/tests/test_datasets_load_remote_datasets.py
  pygmt/tests/test_datasets_mars_relief.py
  pygmt/tests/test_datasets_mercury_relief.py
  pygmt/tests/test_datasets_moon_relief.py
  pygmt/tests/test_datasets_pluto_relief.py
  pygmt/tests/test_datasets_venus_relief.py
Labels: maintenance, final review call

#3192 Fix the bug for support of left/right single quotation marks
  pygmt/helpers/utils.py
  pygmt/tests/test_text.py
Labels: enhancement, final review call

#3199 non_ascii_to_octal: Return the input string if it only contains printable ASCII characters
  pygmt/helpers/utils.py
Labels: enhancement, final review call

#3202 _load_remote_dataset: Rename parameter names and remove trailing underscore from prefix
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/earth_geoid.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_mask.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/earth_vertical_gravity_gradient.py
  pygmt/datasets/load_remote_dataset.py
  pygmt/datasets/mars_relief.py
  pygmt/datasets/mercury_relief.py
  pygmt/datasets/moon_relief.py
  pygmt/datasets/pluto_relief.py
  pygmt/datasets/venus_relief.py
  pygmt/tests/test_datasets_load_remote_datasets.py
Labels: maintenance, skip-changelog

#3204 Rename issue template to set the order of issue templates
  .github/ISSUE_TEMPLATE/1-bug_report.yaml
  .github/ISSUE_TEMPLATE/2-feature_request.yaml
  .github/ISSUE_TEMPLATE/3-module_request.yaml
  .github/ISSUE_TEMPLATE/4-release_checklist.md
  .github/ISSUE_TEMPLATE/5-bump_gmt_checklist.md
Labels: maintenance, skip-changelog

#3203 Simplify the load_earth_magnetic_anomaly and load_earth_relief functions
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_relief.py
Labels: maintenance, skip-changelog, final review call

#3116 Figure.grdcontour: Adjust processing of arguments passed to the "annotation" and "interval" parameters, deprecate "sequence_plus"
  pygmt/src/grdcontour.py
  pygmt/tests/baseline/test_grdcontour_multiple_levels.png.dvc
  pygmt/tests/baseline/test_grdcontour_one_level.png.dvc
  pygmt/tests/test_grdcontour.py
Labels: enhancement, final review call

#2706 Figure.contour: Adjust processing of arguments passed to the "annotation" and "levels" parameters
  pygmt/datasets/earth_relief.py
  pygmt/src/contour.py
  pygmt/tests/baseline/test_contour_interval.png.dvc
  pygmt/tests/baseline/test_contour_multiple_levels.png.dvc
  pygmt/tests/baseline/test_contour_one_level.png.dvc
  pygmt/tests/test_contour.py
Labels: enhancement

#3207 Remove sequence_plus converter from kwargs_to_string
  pygmt/helpers/decorators.py
Labels: deprecation

#3209 Figure.grdcontour: Deprecate parameter "interval" to "levels" (FutureWarning since v0.12.0, will be removed in v0.16.0)
  examples/get_started/02_contour_map.py
  examples/tutorials/advanced/contour_map.py
  pygmt/src/grdcontour.py
  pygmt/tests/test_grdcontour.py
Labels: deprecation

#3210 Figure.contour & Figur.grdcontour: Improve docstring of pen
  pygmt/src/contour.py
  pygmt/src/grdcontour.py
Labels: documentation

#3212 Tutorial and Intro for Figure.grdcontour: Adjust line length and parameter order
  examples/get_started/02_contour_map.py
  examples/tutorials/advanced/contour_map.py
Labels: maintenance, skip-changelog

#3214 Document that a list of file names, pathlib.Path objects, URLs or remote files are supported
  examples/get_started/04_table_inputs.py
Labels: documentation

#3211 Fix some typos
  .github/dependabot.yml
  .github/workflows/ci_docs.yml
  doc/changes.md
  doc/contributing.md
  pygmt/datatypes/dataset.py
Labels: maintenance, skip-changelog
