Repository GenericMappingTools/pygmt, pull requests merged in 2024-06, with the labels that each got.

#3182 pygmt.x2sys_cross: Refactor to use virtualfiles for output tables [BREAKING CHANGE: Dummy times in 3rd and 4th columns now have np.timedelta64 type]
  pygmt/src/x2sys_cross.py
  pygmt/tests/test_x2sys_cross.py
Labels: enhancement, needs review

#3283 Add pre-commit config with pre-commit-hooks
  .github/workflows/format-command.yml
  .github/workflows/style_checks.yaml
  .pre-commit-config.yaml
  CODE_OF_CONDUCT.md
  MANIFEST.in
  Makefile
  doc/_templates/autosummary/class.rst
  doc/_templates/autosummary/exception.rst
  doc/_templates/autosummary/function.rst
  doc/changes.md
  doc/contributing.md
  doc/team.md
  environment.yml
  examples/projections/README.txt
  pygmt/tests/data/contours.txt
Labels: maintenance

#3285 Remove CODE_OF_CONDUCT.md and use the organization-wide CODE OF CONDUCT file
  CODE_OF_CONDUCT.md
  MANIFEST.in
  README.md
Labels: maintenance, skip-changelog

#3286 SPEC 0: Set minimum required version to NumPy 1.24+
  .github/workflows/ci_tests.yaml
  doc/minversions.md
  environment.yml
  pyproject.toml
  requirements.txt
Labels: deprecation

#3288 Mark one x2sys_cross test as xfail in the GMT Legacy Tests workflow
  pygmt/tests/test_x2sys_cross.py
Labels: maintenance, skip-changelog

#3289 Fix a typo in _show_versions.py
  pygmt/_show_versions.py
Labels: maintenance, skip-changelog

#3226 CI: Unpin NumPy in the GMT Dev Tests workflow (#3208)
  .github/workflows/ci_tests_dev.yaml
  pygmt/clib/conversion.py
Labels: maintenance, skip-changelog, run/test-gmt-dev

#3292 CI: Test NumPy 2.0 in the GMT Tests workflow
  .github/workflows/ci_tests.yaml
Labels: maintenance, final review call

#3295 Workaround for the pd.read_csv's index_col bug in pandas 3.0 dev version
  pygmt/tests/test_grdhisteq.py
Labels: maintenance, skip-changelog, run/test-gmt-dev

#3296 CI: Bump to ubuntu-24.04 and mambaforge-23.11 in ReadTheDocs
  .readthedocs.yaml
Labels: maintenance

#3297 CI: Remove the deprecated lychee option and specify the report file name in the Check Links workflow
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog

#3299 CI: Exclude some GitHub links in the Check Links workflow
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog

#3304 CI: Temporarily pin geopandas<1.0 in the Docs workflow
  .github/workflows/ci_docs.yml
Labels: maintenance, skip-changelog, needs review

#3206 Refactor to improve the user experience with non-ASCII characters
  doc/index.md
  doc/techref/encodings.md
  doc/techref/index.md
  pygmt/encodings.py
  pygmt/helpers/utils.py
  pygmt/tests/test_text.py
Labels: enhancement, final review call

#3306 Fix a typo with Markdown syntax
  doc/techref/index.md
Labels: documentation, skip-changelog
