Repository GenericMappingTools/pygmt, pull requests merged in 2024-11, with the labels that each got.

#3565 Replace the list of support numpy dtypes with DTYPES_NUMERIC in tests
  pygmt/tests/test_clib_put_matrix.py
  pygmt/tests/test_clib_put_vector.py
  pygmt/tests/test_clib_virtualfile_from_matrix.py
  pygmt/tests/test_clib_virtualfile_from_vectors.py
  pygmt/tests/test_clib_virtualfiles.py
  pygmt/tests/test_grdimage_image.py
Labels: maintenance, skip-changelog, final review call

#3571 DOC/examples: Rename folder "get_started" to "intro"
  .gitignore
  doc/Makefile
  doc/conf.py
  doc/index.md
  examples/intro/01_first_figure.py
  examples/intro/02_contour_map.py
  examples/intro/03_figure_element.py
  examples/intro/04_table_inputs.py
  examples/intro/GALLERY_HEADER.rst
Labels: documentation, skip-changelog, final review call

#3570 DOC: Improvements of installation guide
  doc/install.md
Labels: documentation, skip-changelog, final review call

#3576 pygmt.datasets.load_tile_map: Fix the rio.crs output for rasterio 1.4.2
  pygmt/datasets/tile_map.py
Labels: maintenance, skip-changelog, final review call

#3578 Make naming in install.md consistent
  doc/install.md
Labels: documentation, skip-changelog

#3577 Refactor to specify numpy dtypes in a consistent way
  examples/gallery/symbols/datetime_inputs.py
  examples/tutorials/advanced/date_time_charts.py
  pygmt/clib/session.py
  pygmt/datatypes/dataset.py
  pygmt/helpers/tempfile.py
  pygmt/src/info.py
  pygmt/src/text.py
  pygmt/tests/test_clib_dataarray_to_matrix.py
  pygmt/tests/test_clib_put_strings.py
  pygmt/tests/test_clib_put_vector.py
  pygmt/tests/test_geopandas.py
  pygmt/tests/test_info.py
  pygmt/tests/test_plot.py
  pygmt/tests/test_triangulate.py
Labels: maintenance, skip-changelog, needs review

#3568 Figure.savefig: Add a new test for the show parameter and simplify existing tests.
  pygmt/tests/test_figure.py
Labels: maintenance, skip-changelog, final review call

#3566 Support 1-D/2-D numpy arrays with longlong and ulonglong dtype
  pygmt/clib/session.py
Labels: enhancement, final review call

#3581 Add the private _to_numpy function to convert anything to a numpy array
  pygmt/clib/conversion.py
Labels: enhancement

#3586 DOC/installation guide: Fix links to examples
  doc/install.md
Labels: documentation, skip-changelog

#3567 Test timedelta64 dtype arrays with various date/time units
  pygmt/tests/test_clib_put_vector.py
Labels: maintenance, skip-changelog, needs review

#3580 Figure.show: Raise ImportError instead of GMTError if IPython is not installed but required
  pygmt/figure.py
  pygmt/tests/test_figure.py
Labels: enhancement, final review call

#3579 Figure.savefig: Clarify that 'transparent' also works for the PNG file associated with the KML format
  pygmt/figure.py
  pygmt/tests/test_figure.py
Labels: documentation

#3587 DOC/tutorial "Plotting lines": General improvements
  examples/tutorials/basics/lines.py
Labels: documentation, skip-changelog

#3592 Add PyArrow as an optional dependency
  .github/workflows/ci_docs.yml
  .github/workflows/type_checks.yml
  ci/requirements/docs.yml
  environment.yml
  pyproject.toml
Labels: enhancement, final review call

#3590 Move Figure.shift_origin tests into a separate test file
  pygmt/tests/baseline/test_figure_shift_origin.png.dvc
  pygmt/tests/baseline/test_shift_origin.png.dvc
  pygmt/tests/test_figure.py
  pygmt/tests/test_shift_origin.py
Labels: maintenance, skip-changelog, needs review

#3583 clib.converison._to_numpy: Add tests for numpy arrays of numpy numeric dtypes
  pygmt/tests/test_clib_to_numpy.py
Labels: maintenance, skip-changelog, final review call

#3597 Pin sphinx_rst_theme to < 3.0 for docs
  .github/workflows/ci_docs.yml
  ci/requirements/docs.yml
  environment.yml
Labels: documentation, maintenance, skip-changelog, final review call

#3599 clib.conversion._to_numpy: Add tests for pyarrow.array with pyarrow numeric dtypes
  pygmt/tests/test_clib_to_numpy.py
Labels: maintenance, skip-changelog, needs review

#3605 CI: Install pandas 2.1 + pyarrow in the Python 3.11 job
  .github/workflows/ci_tests.yaml
Labels: maintenance, skip-changelog, final review call

#3603 Figure.plot/Figure.plot3d: Improve the check of the "style" parameter for "v" or "V"
  pygmt/src/plot.py
  pygmt/src/plot3d.py
Labels: bug

#3585 clib.conversion._to_numpy: Add tests for pandas.Series with pyarrow numeric dtypes
  pygmt/tests/test_clib_to_numpy.py
Labels: maintenance, skip-changelog, needs review

#3601 clib.conversion._to_numpy: Add tests for Python list of strings and NumPy array with string type
  pygmt/tests/test_clib_to_numpy.py
Labels: maintenance, skip-changelog, final review call

#3617 pyarrow: Map date32[day]/date64[ms] dtypes in pandas objects to np.datetime64 with correct date/time units
  pygmt/clib/conversion.py
Labels: enhancement

#3609 clib.conversion._to_numpy: Add tests for pyarrow.array with date32/date64 dtype
  pygmt/tests/test_clib_to_numpy.py
Labels: maintenance, skip-changelog, final review call

#3619 pyarrow: Support pyarrow arrays with string/large_string/string_view types
  pygmt/clib/conversion.py
Labels: enhancement

#3608 clib.conversion._to_numpy: Add tests for pyarrow.array with pyarrow string types
  pygmt/tests/test_clib_to_numpy.py
Labels: maintenance, skip-changelog

#2933 pyarrow: Check compatibility of pyarrow.array with string type
  doc/conf.py
  doc/ecosystem.md
  pygmt/_typing.py
  pygmt/clib/conversion.py
  pygmt/src/text.py
  pygmt/tests/test_clib_virtualfile_from_vectors.py
  pygmt/tests/test_text.py
Labels: maintenance

#3607 clib.conversion._to_numpy: Add tests for pandas.Series with pandas string dtype
  pygmt/clib/conversion.py
  pygmt/clib/session.py
  pygmt/tests/test_clib_to_numpy.py
Labels: maintenance, skip-changelog, final review call

#3620 CI: Use pytest '--override-ini' to override 'addopts' setting in the "Benchmarks" workflow
  .github/workflows/benchmarks.yml
Labels: maintenance, skip-changelog

#3614 Simplify the type hints for the supported encodings
  pygmt/encodings.py
  pygmt/helpers/utils.py
Labels: skip-changelog, final review call, typing

#3616 Document the support policy for optional packages
  README.md
  doc/minversions.md
Labels: documentation

#3618 CI: Run the 'GMT Tests' workflow on Python 3.10/3.12 with optional packages and Python 3.11 without optional packages
  .github/workflows/ci_tests.yaml
  pygmt/datasets/tile_map.py
  pygmt/tests/test_clib_to_numpy.py
Labels: maintenance

#3611 Ensure non-ASCII characters are typeset correctly even if PS_CHAR_ENCODING is not 'ISOLatin1+'
  pygmt/helpers/utils.py
  pygmt/src/text.py
  pygmt/tests/test_text.py
Labels: enhancement, final review call

#3624 DOC/Gallery example "Multi-parameter symbols": Show applying a inner diameter ("+i") to a pie wedge ("w")
  examples/gallery/symbols/multi_parameter_symbols.py
Labels: documentation, enhancement, skip-changelog, final review call

#3632 Update the Dependencies Policy section in Maintainers Guides
  doc/maintenance.md
Labels: documentation, skip-changelog, final review call

#3633 DOC/Gallery example "Configuring PyGMT defaults": General improvements
  examples/tutorials/advanced/configuration.py
Labels: documentation, maintenance, skip-changelog

#3626 DOC/advanced Tutorial "Cartesian histograms": General improvements
  examples/tutorials/advanced/cartesian_histograms.py
Labels: documentation, maintenance, skip-changelog

#3623 DOC/Gallery example "Cross-section along a transect": General improvements
  examples/gallery/images/cross_section.py
Labels: documentation, maintenance, skip-changelog

#3625 DOC/Gallery example "Envelope": General improvements
  examples/gallery/lines/envelope.py
Labels: documentation, maintenance, skip-changelog, final review call

#3634 DOC/Projections "Polar": General improvements
  examples/projections/nongeo/polar.py
Labels: documentation, maintenance, skip-changelog, final review call

#3572 DOC: Make bullet point lists consistent in docstrings (":" and lower-case) Part I
  pygmt/src/binstats.py
  pygmt/src/blockm.py
  pygmt/src/coast.py
  pygmt/src/dimfilter.py
  pygmt/src/filter1d.py
  pygmt/src/grd2xyz.py
Labels: documentation, skip-changelog, final review call

#3641 Pin numpy<2 in ci_tests_legacy.yaml
  .github/workflows/ci_tests_legacy.yaml
  Makefile
Labels: maintenance

#3642 Fix doctest on pygmt.datasets.tile_map.load_tile_map in ci_tests_legacy
  pygmt/datasets/tile_map.py
Labels: maintenance, skip-changelog

#3644 Remove the sg_execution_times.rst file auto-generated by sphinx-gallery
  doc/Makefile
Labels: maintenance, skip-changelog

#3648 _check_encoding: Improve efficiency by creating dict outside the for loop
  pygmt/helpers/utils.py
Labels: maintenance, final review call

#3593 DOC: Add basic tutorial "Plotting polygons"
  examples/tutorials/basics/polygons.py
Labels: documentation, final review call

#3650 Fix typo in polygons.py
  examples/tutorials/basics/polygons.py
Labels: documentation, skip-changelog

#3653 GMT_DATASET: Refactor nested classes to improve code readability
  pygmt/datatypes/dataset.py
Labels: maintenance, needs review

#3652 clib.conversion.strings_to_ctypes_array: Add a doctest for numpy string array
  pygmt/clib/conversion.py
Labels: maintenance, skip-changelog, final review call

#3628 DOC/Gallery example "Scatter plot with histograms": General improvements
  examples/gallery/histograms/scatter_and_histograms.py
  examples/tutorials/advanced/cartesian_histograms.py
  pygmt/src/histogram.py
Labels: documentation, skip-changelog

#3621 clib.conversion._to_numpy: Add tests for PyArrow's timestamp type
  pygmt/tests/test_clib_to_numpy.py
Labels: maintenance, skip-changelog

#3659 DOC/advanced tutorial "Cartesian histograms": Fix typo
  examples/tutorials/advanced/cartesian_histograms.py
Labels: documentation, skip-changelog, final review call

#3658 DOC/gallery example "Cross section": Fix typo
  examples/gallery/images/cross_section.py
Labels: documentation, skip-changelog, final review call

#3657 clib.conversion._to_numpy: Shorten test names
  pygmt/tests/test_clib_to_numpy.py
Labels: maintenance, skip-changelog, final review call

#3662 Bump to ruff>=0.8.0 and rename rule TCH to TC
  environment.yml
  pyproject.toml
Labels: maintenance, final review call

#3661 Enable ruff's EM (flake8-errmsg) rules and fix violations
  pygmt/accessors.py
  pygmt/clib/loading.py
  pygmt/clib/session.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/samples.py
  pygmt/helpers/decorators.py
  pygmt/helpers/tempfile.py
  pygmt/helpers/testing.py
  pygmt/helpers/utils.py
  pygmt/helpers/validators.py
  pygmt/io.py
  pygmt/src/coast.py
  pygmt/src/dimfilter.py
  pygmt/src/filter1d.py
  pygmt/src/grd2cpt.py
  pygmt/src/grd2xyz.py
  pygmt/src/grdfill.py
  pygmt/src/grdgradient.py
  pygmt/src/grdhisteq.py
  pygmt/src/grdimage.py
  pygmt/src/grdlandmask.py
  pygmt/src/grdproject.py
  pygmt/src/grdtrack.py
  pygmt/src/legend.py
  pygmt/src/makecpt.py
  pygmt/src/meca.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/project.py
  pygmt/src/psconvert.py
  pygmt/src/solar.py
  pygmt/src/sphdistance.py
  pygmt/src/subplot.py
  pygmt/src/text.py
  pygmt/src/tilemap.py
  pygmt/src/velo.py
  pygmt/src/which.py
  pygmt/src/x2sys_cross.py
  pygmt/src/xyz2grd.py
  pygmt/tests/test_clib_loading.py
  pyproject.toml
Labels: maintenance, final review call

#3663 Fix the docstrings of the pygmt.end function
  pygmt/session_management.py
Labels: documentation, skip-changelog, final review call
