Repository GenericMappingTools/pygmt, pull requests merged in 2024-12, with the labels that each got.

#3660 clib.conversion._to_numpy: Use pytest.mark.skipif to skip string_view type test for pyarrow < 16
  pygmt/tests/test_clib_to_numpy.py
Labels: maintenance, skip-changelog, final review call

#3664 DOC/advanced tutorial "Plotting datetime charts": Minor update of code for pandas version
  examples/tutorials/advanced/date_time_charts.py
Labels: maintenance, skip-changelog

#3665 Enable ruff's TRY (tryceratops) rules
  pyproject.toml
Labels: maintenance, final review call

#3668 CI: Pin rasterio < 1.4.3 temporarily
  .github/workflows/ci_docs.yml
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
  ci/requirements/docs.yml
Labels: maintenance

#3667 CI: Pin to sphinx>=6.2 for docs build on Python 3.13
  .github/workflows/ci_docs.yml
  ci/requirements/docs.yml
  doc/conf.py
  environment.yml
Labels: maintenance

#3554 load_tile_map: Add the new parameter 'crs' to set the CRS of the returned dataarray
  pygmt/datasets/tile_map.py
  pygmt/src/tilemap.py
  pygmt/tests/test_tilemap.py
Labels: enhancement, final review call

#3669 Fix typos OGC:WGS84 to OGC:CRS84
  pygmt/src/tilemap.py
  pygmt/tests/baseline/test_tilemap_ogc_crs84.png.dvc
  pygmt/tests/test_tilemap.py
Labels: documentation, needs review

#3666 List function aliases in a more compact layout
  pygmt/helpers/decorators.py
Labels: documentation, needs review

#3672 clib.session: Add the GMT_SESSION_NOGDALCLOSE flag to keep GDAL open
  pygmt/clib/session.py
Labels: bug

#3305 CI: Unpin geopandas and rasterio after the fix in #3672
  .github/workflows/ci_docs.yml
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
  ci/requirements/docs.yml
Labels: maintenance, skip-changelog, needs review

#3674 Bump to ruff 0.8.2
  environment.yml
  pygmt/tests/test_datasets_earth_vertical_gravity_gradient.py
Labels: maintenance, skip-changelog, final review call

#3677 CI: Test NumPy 2.2 in the GMT Tests workflow
  .github/workflows/ci_tests.yaml
Labels: maintenance

#3596 Improve the workarounds for handling pandas nullable dtypes in pandas<=2.1
  pygmt/clib/conversion.py
Labels: bug

#3584 clib.converison._to_numpy: Add tests for pandas.Series with pandas numeric dtypes
  pygmt/tests/test_clib_to_numpy.py
  pygmt/tests/test_clib_vectors_to_arrays.py
Labels: maintenance, skip-changelog

#3686 Improve the description of rioxarray on the Ecosystem page
  doc/ecosystem.md
Labels: documentation, skip-changelog, final review call

#3695 CI: Install dvc via uv in the "GMT Tests" workflow
  .github/workflows/ci_tests.yaml
Labels: maintenance, skip-changelog

#3490 Add support for Python 3.13
  .github/workflows/benchmarks.yml
  .github/workflows/cache_data.yaml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/format-command.yml
  .github/workflows/publish-to-pypi.yml
  .github/workflows/style_checks.yaml
  .github/workflows/type_checks.yml
  ci/requirements/docs.yml
  doc/install.md
  environment.yml
  pyproject.toml
Labels: maintenance

#3606 SPEC 0: Bump minimum supported version to Python 3.11
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_legacy.yaml
  environment.yml
  pygmt/tests/test_clib_put_vector.py
  pyproject.toml
Labels: deprecation

#3697 SPEC 0: Bump minimum supported version to NumPy 1.25
  .github/workflows/ci_tests.yaml
  environment.yml
  pyproject.toml
  requirements.txt
Labels: deprecation, needs review

#3698 CI: Install pyarrow-core instead of pyarrow from conda-forge
  .github/workflows/benchmarks.yml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_legacy.yaml
  ci/requirements/docs.yml
  doc/install.md
  environment.yml
Labels: maintenance

#3693 Add enums GridRegistration and GridType for grid registration and type
  doc/_templates/autosummary/enums.rst
  doc/api/index.rst
  pygmt/enums.py
Labels: enhancement

#3701 CI: Use windows-2025 in the GMT Dev Tests workflow
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance

#3689 Add the GMT/PyGMT preworkshop at AGU24 to the "External resources" section
  doc/external_resources.md
Labels: documentation, final review call

#3685 Add the PyGMT talk at AGU24 to the "Overview" section
  doc/overview.md
Labels: documentation, final review call

#3716 External Resources / AGU24 workshop: Link directly to Jupter book instead of GitHub repo
  doc/external_resources.md
Labels: maintenance, skip-changelog

#3715 Figure: Add type hints to the _preview method
  pygmt/figure.py
Labels: skip-changelog, typing

#3721 Remote datasets: Add note for exact resolution
  pygmt/datasets/mars_relief.py
  pygmt/datasets/mercury_relief.py
  pygmt/datasets/moon_relief.py
  pygmt/datasets/pluto_relief.py
Labels: maintenance, skip-changelog

#3703 CI: Ensure no hyphens in Python file and directory names in the "Style Checks" workflow
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/style_checks.yaml
  doc/contributing.md
Labels: maintenance

#3706 Remote datasets: Add "load_earth_dist" to load "GSHHG Earth distance to shoreline" dataset
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/earth_dist.py
  pygmt/datasets/load_remote_dataset.py
  pygmt/helpers/caching.py
  pygmt/tests/test_datasets_earth_dist.py
Labels: feature

#3714 Add notes for issue templates that are only meant for project maintainers
  .github/ISSUE_TEMPLATE/4-release_checklist.md
  .github/ISSUE_TEMPLATE/5-bump_gmt_checklist.md
Labels: maintenance, skip-changelog

#3719 Add 'geodatasets' as a dependency for docs and update the choropleth example
  .github/workflows/ci_docs.yml
  ci/requirements/docs.yml
  environment.yml
  examples/gallery/maps/choropleth_map.py
Labels: maintenance

#3718 Remote datasets: Add "load_earth_mean_dynamic_topography" to load "CNES Earth Mean Dynamic Topography" dataset
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/earth_mean_dynamic_topography.py
  pygmt/datasets/load_remote_dataset.py
  pygmt/helpers/caching.py
  pygmt/tests/test_datasets_mean_dynamic_topography.py
Labels: feature

#3717 Remote datasets: Add "load_earth_mean_sea_surface" to load "CNES Earth Mean Sea Surface" dataset
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/earth_mean_sea_surface.py
  pygmt/datasets/load_remote_dataset.py
  pygmt/helpers/caching.py
  pygmt/tests/test_datasets_earth_mean_sea_surface.py
Labels: feature

#3723 Enable ruff's flake8-todos (TD) rules
  pyproject.toml
Labels: maintenance

#923 Add Figure.hlines for plotting horizontal lines
  doc/api/index.rst
  pygmt/figure.py
  pygmt/src/__init__.py
  pygmt/src/hlines.py
  pygmt/tests/baseline/test_hlines_clip.png.dvc
  pygmt/tests/baseline/test_hlines_geographic_global_d.png.dvc
  pygmt/tests/baseline/test_hlines_geographic_global_g.png.dvc
  pygmt/tests/baseline/test_hlines_multiple_lines.png.dvc
  pygmt/tests/baseline/test_hlines_one_line.png.dvc
  pygmt/tests/baseline/test_hlines_polar_projection.png.dvc
  pygmt/tests/test_hlines.py
Labels: feature

#3725 Remote Datasets: Use complete word for units in "load_remote_dataset" and related tests
  pygmt/datasets/load_remote_dataset.py
  pygmt/tests/test_datasets_earth_dist.py
  pygmt/tests/test_datasets_earth_geoid.py
Labels: maintenance, skip-changelog

#3690 Simplify two clib loading tests using unittest.mock
  pygmt/tests/test_clib_loading.py
Labels: maintenance, skip-changelog

#3722 Use TODO comments to track deprecations and workarounds
  pygmt/clib/conversion.py
  pygmt/clib/session.py
  pygmt/conftest.py
  pygmt/datasets/tile_map.py
  pygmt/figure.py
  pygmt/helpers/tempfile.py
  pygmt/src/ternary.py
  pygmt/src/timestamp.py
  pygmt/tests/test_accessor.py
  pygmt/tests/test_clib_to_numpy.py
  pygmt/tests/test_clib_virtualfile_from_vectors.py
  pygmt/tests/test_clib_virtualfile_in.py
  pygmt/tests/test_clib_virtualfiles.py
  pygmt/tests/test_datasets_earth_relief.py
  pygmt/tests/test_grdimage.py
  pygmt/tests/test_meca.py
  pygmt/tests/test_x2sys_cross.py
Labels: maintenance, final review call

#3726 Add Figure.vlines for plotting vertical lines
  doc/api/index.rst
  pygmt/figure.py
  pygmt/src/__init__.py
  pygmt/src/hlines.py
  pygmt/src/vlines.py
  pygmt/tests/baseline/test_vlines_clip.png.dvc
  pygmt/tests/baseline/test_vlines_geographic_global.png.dvc
  pygmt/tests/baseline/test_vlines_multiple_lines.png.dvc
  pygmt/tests/baseline/test_vlines_one_line.png.dvc
  pygmt/tests/baseline/test_vlines_polar_projection.png.dvc
  pygmt/tests/test_vlines.py
Labels: feature

#3727 Remote datasets: Add "uncertainty" parameter to "load_earth_free_air_anomaly" to load the "free-air anomaly uncertainty" dataset
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/load_remote_dataset.py
  pygmt/helpers/caching.py
  pygmt/tests/test_datasets_earth_free_air_anomaly.py
Labels: feature

#3729 DOC: Typo fixes / formulation improvements
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/earth_vertical_gravity_gradient.py
  pygmt/datasets/mars_relief.py
  pygmt/datasets/mercury_relief.py
  pygmt/datasets/moon_relief.py
  pygmt/datasets/pluto_relief.py
Labels: documentation, skip-changelog

#3517 Figure.meca: Improve documentation
  pygmt/src/meca.py
Labels: documentation, skip-changelog

#3728 Remote datasets: Add load_earth_deflection to load "IGPP Earth east-west and north-south deflection" datasets
  doc/api/index.rst
  pygmt/datasets/__init__.py
  pygmt/datasets/earth_deflection.py
  pygmt/datasets/load_remote_dataset.py
  pygmt/helpers/caching.py
  pygmt/tests/test_datasets_earth_deflection.py
Labels: feature

#3711 Update the gallery example for plotting lines with LineString/MultiLineString geometry
  examples/gallery/lines/linestrings.py
  examples/gallery/lines/roads.py
Labels: documentation

#3733 Typo fixes before v0.14.0
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/figure.py
  pygmt/src/meca.py
  pyproject.toml
Labels: documentation, skip-changelog

#3730 Changelog entry for v0.14.0
  CITATION.cff
  README.md
  doc/_static/version_switch.js
  doc/changes.md
  doc/minversions.md
Labels: maintenance, skip-changelog
