Repository GenericMappingTools/pygmt, pull requests merged in 2024-10, with the labels that each got.

#3450 Set minimum supported version to GMT>=6.4.0
  .github/workflows/ci_tests_legacy.yaml
  doc/contributing.md
  doc/install.md
  pygmt/clib/__init__.py
  pygmt/clib/session.py
  pygmt/src/timestamp.py
  pygmt/tests/test_accessor.py
  pygmt/tests/test_clib.py
  pygmt/tests/test_datasets_load_remote_datasets.py
  pygmt/tests/test_grdfill.py
  pygmt/tests/test_grdfilter.py
  pygmt/tests/test_grdlandmask.py
  pygmt/tests/test_grdsample.py
  pygmt/tests/test_sph2grd.py
  pygmt/tests/test_subplot.py
Labels: deprecation

#3480 data_kind: Add more tests to demonstrate the data kind of various data types
  pygmt/helpers/utils.py
  pygmt/tests/test_blockm.py
  pygmt/tests/test_blockmedian.py
  pygmt/tests/test_geopandas.py
  pygmt/tests/test_grdtrack.py
  pygmt/tests/test_grdview.py
  pygmt/tests/test_nearneighbor.py
  pygmt/tests/test_surface.py
  pygmt/tests/test_triangulate.py
  pygmt/tests/test_x2sys_cross.py
Labels: maintenance, skip-changelog, needs review

#3466 Document the built-in patterns in the Technical Reference section
  doc/techref/index.md
  doc/techref/patterns.md
  examples/gallery/symbols/patterns.py
Labels: documentation, final review call

#3488 DOC: Fix link to "sphinx-doc"
  doc/_templates/footer.html
Labels: maintenance, skip-changelog

#3483 GMTDataArrayAccessor: Simplify the codes for the grid registration and gtype during initialization
  pygmt/accessors.py
Labels: maintenance, skip-changelog, final review call

#3485 CI: Use macOS 15 in the 'GMT Dev Tests' workflow
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog, run/test-gmt-dev

#3481 data_kind: Refactor the if-else statements into match-case statements
  pygmt/helpers/utils.py
Labels: maintenance, skip-changelog, final review call

#3358 Add a test for plotting global grid without the redundant 360 longitude
  pygmt/tests/baseline/test_grdimage_grid_no_redunant_360.png.dvc
  pygmt/tests/test_grdimage.py
Labels: maintenance, upstream, final review call, run/test-gmt-dev

#3492 clib.conversion: Remove the as_c_contiguous function and use np.ascontiguousarray instead
  pygmt/clib/conversion.py
  pygmt/clib/session.py
Labels: maintenance, final review call

#3493 **Breaking**: Figure.text: Fix typesetting of integers when mixed with floating-point values
  pygmt/src/text.py
  pygmt/tests/baseline/test_text_nonstr_text.png.dvc
Labels: bug, final review call

#3499 DOC: Use MyST syntax for linking other files
  doc/install.md
  doc/maintenance.md
  doc/team.md
  doc/techref/fonts.md
  doc/techref/projections.md
Labels: documentation, skip-changelog, final review call

#3491 Add type hints to Figure._preview method and improve docstrings
  pygmt/figure.py
Labels: skip-changelog, final review call, typing

#3503 clib: Fix the return type from ctp.c_uint to ctp.c_int for Session.inquire_virtualfile
  pygmt/clib/session.py
Labels: bug, skip-changelog, final review call

#3501 DOC: Minor improvement of highlighting in docstrings
  pygmt/figure.py
  pygmt/src/surface.py
Labels: documentation, skip-changelog

#3497 Add a doctest for checking ndims when the input is a sequence of scalars
  pygmt/clib/conversion.py
Labels: maintenance, skip-changelog, final review call

#3498 Remove unnecessary np.atleast_1d calls from Figure.text and Session.virtualfile_in
  pygmt/clib/session.py
  pygmt/src/text.py
Labels: maintenance, skip-changelog, final review call

#3502 clib: Switch the order of if-conditions to improve the Session.call_module performance
  pygmt/clib/session.py
Labels: maintenance, skip-changelog, final review call, run/benchmark

#3505 Fix the conversion error for pandas.Series with missing values in pandas<=2.1
  pygmt/clib/conversion.py
Labels: bug

#3459 Add type hints for GMT anchor codes
  pygmt/_typing.py
  pygmt/helpers/utils.py
  pygmt/src/text.py
  pygmt/src/timestamp.py
Labels: maintenance, skip-changelog, typing

#3504 clib.Session: Add type hints and reformat docstrings (part 1)
  pygmt/clib/session.py
Labels: maintenance, skip-changelog, typing

#3496 clib.conversion: Add type hints and improve docstrings for dataarray_to_matrix, vectors_to_arrays, and array_to_datetime
  pygmt/clib/conversion.py
Labels: maintenance, skip-changelog, final review call, typing

#3508 CI: Bump to macOS-13 in the 'GMT Legacy Tests' workflow
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, skip-changelog, final review call

#3511 DOC/external resources: Update link to "PyGMT HOWTO"
  doc/external_resources.md
Labels: documentation, skip-changelog

#3514 Silence a mypy warning with mypy v1.12.0
  pygmt/datasets/load_remote_dataset.py
Labels: maintenance, skip-changelog, final review call

#3512 Split tests related to virtualfiles into multiple test files
  pygmt/tests/test_clib_inquire_virtualfile.py
  pygmt/tests/test_clib_virtualfile_from_matrix.py
  pygmt/tests/test_clib_virtualfile_from_stringio.py
  pygmt/tests/test_clib_virtualfile_from_vectors.py
  pygmt/tests/test_clib_virtualfile_in.py
  pygmt/tests/test_clib_virtualfiles.py
Labels: maintenance, skip-changelog

#3516 Split tests in test_clib.py into mutliple smaller test files
  pygmt/tests/test_clib.py
  pygmt/tests/test_clib_call_module.py
  pygmt/tests/test_clib_create_data.py
  pygmt/tests/test_clib_dataarray_to_matrix.py
  pygmt/tests/test_clib_extract_region.py
  pygmt/tests/test_clib_write_data.py
Labels: maintenance, skip-changelog, final review call

#3515 clib.Session: Add type hints and improve docstrings of the Session create/destroy methods
  pygmt/clib/session.py
Labels: maintenance, final review call, typing

#3351 **Breaking**: data_kind: Now 'matrix' represents a 2-D numpy array and unrecognized data types fall back to 'vectors'
  pygmt/clib/session.py
  pygmt/helpers/utils.py
  pygmt/src/legend.py
  pygmt/src/x2sys_cross.py
  pygmt/tests/test_clib_virtualfile_in.py
Labels: maintenance

#3482 **Breaking**: data_kind: data is None and required now returns the 'empty' kind
  pygmt/clib/session.py
  pygmt/helpers/utils.py
  pygmt/src/legend.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/text.py
Labels: maintenance

#3521 clib.Session.virtualfile_in: Refactor if-else statements into match-case statements
  pygmt/clib/session.py
Labels: maintenance, skip-changelog, needs review

#3518 GeoPandas: Improve the interger overflow check using np.iinfo
  pygmt/helpers/tempfile.py
Labels: maintenance, skip-changelog

#3523 clib.session: Refactor to simplify the checking of currently open session
  pygmt/clib/session.py
Labels: maintenance, skip-changelog

#3524 CI: Exclude the pre-commit-ci bots in release drafter
  .github/release-drafter.yml
Labels: maintenance, skip-changelog, final review call

#3525 DOC: Change "Pandas" to "pandas"
  .github/ISSUE_TEMPLATE/4-release_checklist.md
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  README.md
  doc/maintenance.md
  doc/minversions.md
  pygmt/_show_versions.py
Labels: documentation, skip-changelog

#3528 Add "Preview" to Pull Request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, skip-changelog, final review call

#3529 DOC: Add the missing .md suffix to doc/techref/index.md
  doc/techref/index.md
Labels: documentation, skip-changelog

#3533 Fix a link in .dvcignore
  .dvcignore
Labels: documentation, skip-changelog, final review call

#3534 Fix several small typos
  examples/tutorials/advanced/draping_on_3d_surface.py
  pygmt/accessors.py
  pygmt/tests/baseline/test_grdimage_grid_no_redundant_360.png.dvc
  pygmt/tests/test_clib_read_data.py
  pygmt/tests/test_datatypes_dataset.py
  pygmt/tests/test_grdimage.py
Labels: maintenance, skip-changelog, final review call

#3527 Add two tests for the deprecated Session.open_virtual_file and Session.virtualfile_from_data methods
  pygmt/clib/session.py
  pygmt/tests/test_clib_virtualfile_in.py
  pygmt/tests/test_clib_virtualfiles.py
Labels: maintenance, skip-changelog, final review call

#3531 Enable ruff's flake8-commas (COM) and refurb (FURB) rules
  pyproject.toml
Labels: maintenance, final review call

#3530 clib.Session: Add type hints and format docstrings for some Session methods
  pygmt/clib/conversion.py
  pygmt/clib/session.py
Labels: skip-changelog, final review call, typing

#3535 CI: Unpin pandas in the 'GMT Legacy Tests' workflow
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, skip-changelog

#3539 Gallery example "Quoted lines": Fix typo
  examples/gallery/lines/quoted_lines.py
Labels: documentation, skip-changelog

#3536 CI: Sort URLs alphabetically and remove/merge some URLs in the "Check Links" workflow
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog

#3475 Add the PyGMT ecosystem page
  doc/ecosystem.md
  doc/index.md
Labels: documentation

#3538 Refactor the _get_module_version function using importlib and add two more tests
  pygmt/_show_versions.py
  pygmt/tests/test_show_versions.py
Labels: maintenance

#3506 Add instructions for installing optional dependencies
  doc/install.md
Labels: documentation, final review call

#3522 clib.Session.virtualfile_from_vectors: Now takes a sequence of vectors as its single argument (Passing multiple arguments will be unsupported in v0.16.0)
  pygmt/clib/session.py
  pygmt/tests/test_clib_virtualfile_from_vectors.py
Labels: deprecation

#3544 Add three tests for the launch_external_viewer function
  pygmt/tests/test_helpers.py
Labels: maintenance, skip-changelog

#3537 Simplify the _get_default_display_method tests using unittest.mock
  pygmt/tests/test_figure.py
Labels: maintenance, skip-changelog

#3540 Fix badge links, use consistent badge style and update badge order
  README.md
Labels: maintenance, skip-changelog, final review call

#3541 Fix the _validate_data_input function after refactoring data_kind
  pygmt/helpers/utils.py
Labels: maintenance, skip-changelog, final review call

#3549 clib.conversion.vectors_to_arrays: Move inline doctests into a separate test file
  pygmt/clib/conversion.py
  pygmt/tests/test_clib_vectors_to_arrays.py
Labels: maintenance, skip-changelog

#3550 CI: Install DCW and GSHHG datasets on Linux/macOS in the "GMT Dev Tests" workflow
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog, final review call, run/test-gmt-dev

#3532 clib.Session.create_data: Improve docstrings and fix the comments for the `dim` parameter
  pygmt/clib/conversion.py
  pygmt/clib/session.py
  pygmt/tests/test_clib_create_data.py
  pygmt/tests/test_clib_put_matrix.py
  pygmt/tests/test_clib_put_strings.py
  pygmt/tests/test_clib_put_vector.py
  pygmt/tests/test_clib_virtualfiles.py
Labels: documentation, skip-changelog, final review call

#3553 Move Figure.psconvert into a separate file
  pygmt/figure.py
  pygmt/src/__init__.py
  pygmt/src/psconvert.py
Labels: maintenance

#3552 clib.Session: Add type hints and refactor the _parse_constant and _parse_pad methods
  pygmt/clib/session.py
Labels: maintenance, skip-changelog

#3555 DOC: Fix typos "Scientific" to "scientific"
  README.md
  doc/changes.md
  doc/maintenance.md
  doc/minversions.md
Labels: documentation, skip-changelog

#3557 CI: Use the 'ubuntu-latest' runner in the 'Benchmarks' workflow
  .github/workflows/benchmarks.yml
Labels: maintenance, skip-changelog, final review call, run/benchmark

#1117 Figure.plot: Add the "symbol" parameter to support plotting data points with varying symbols
  pygmt/src/plot.py
  pygmt/tests/baseline/test_plot_symbol.png.dvc
  pygmt/tests/test_plot.py
Labels: enhancement, needs review

#3559 Figure.plot3d: Add the "symbol" parameter to support plotting data points with varying symbols
  pygmt/src/plot3d.py
  pygmt/tests/baseline/test_plot3d_symbol.png.dvc
  pygmt/tests/test_plot3d.py
Labels: enhancement, needs review

#3558 Refactor _load_remote_dataset to avoid typing hints issues
  pygmt/datasets/load_remote_dataset.py
Labels: maintenance, skip-changelog, typing

#3560 Fix the typing hints for grd2xyz
  pygmt/src/grd2xyz.py
Labels: skip-changelog, final review call, typing

#3563 Improve the data type checking for 2-D arrays passed to the GMT C API
  pygmt/clib/session.py
Labels: maintenance, needs review

#3548 pygmt.set_display: Improve the test by checking if the preview image is opened in the expected way
  pygmt/figure.py
  pygmt/tests/test_figure.py
Labels: maintenance, skip-changelog
