Repository GenericMappingTools/pygmt, pull requests merged in 2024-08, with the labels that each got.

#3364 Let pygmt.show_versions show GDAL version
  pygmt/_show_versions.py
Labels: maintenance

#3363 Convert projection table from reStructuredText to Markdown
  doc/techref/index.md
  doc/techref/projections.md
  doc/techref/projections.rst
Labels: documentation

#3368 Remove the verbose='d' setting in test_which_nonascii_path
  pygmt/tests/test_which.py
Labels: maintenance, skip-changelog

#3372 SPEC 0: Bump minimum supported versions to xarray 2022.09
  .github/workflows/ci_tests.yaml
  doc/minversions.md
  environment.yml
  pyproject.toml
  requirements.txt
Labels: maintenance, needs review

#3367 Patch the callback print function to suppress the UnicodeDecodeError
  pygmt/clib/session.py
Labels: maintenance

#3373 Format the author list into a table
  AUTHORS.md
Labels: documentation, skip-changelog

#3376 pygmt.show_versions: Remove _get_gdal_version and create a dictionary for dependency versions
  pygmt/_show_versions.py
Labels: maintenance, final review call

#3380 Determine the minimum required versions of dependencies from package metadata for docs
  doc/conf.py
  doc/install.md
  doc/minversions.md
Labels: maintenance, needs review

#3378 Document the supported 35 standard Postscript fonts in the Technical Reference section
  doc/techref/fonts.md
  doc/techref/index.md
  examples/gallery/symbols/text_symbols.py
  examples/tutorials/basics/text.py
Labels: documentation

#3386 TYP: Remove unnecessary 'from __future__ import annotations' statements
  pygmt/src/shift_origin.py
  pygmt/src/solar.py
  pygmt/src/timestamp.py
Labels: skip-changelog, typing

#3387 Rename test_init.py to test_show_versions.py
  pygmt/tests/test_show_versions.py
Labels: maintenance, skip-changelog

#3384 GMT_IMAGE: Remove 'nan_value' from the doctest since it depends on GMT versions
  pygmt/datatypes/image.py
Labels: maintenance, skip-changelog, final review call

#3385 TYP: Add typing hints to the return values for modules that output a grid
  pygmt/src/binstats.py
  pygmt/src/dimfilter.py
  pygmt/src/grdclip.py
  pygmt/src/grdcut.py
  pygmt/src/grdfill.py
  pygmt/src/grdfilter.py
  pygmt/src/grdgradient.py
  pygmt/src/grdhisteq.py
  pygmt/src/grdlandmask.py
  pygmt/src/grdproject.py
  pygmt/src/grdsample.py
  pygmt/src/nearneighbor.py
  pygmt/src/sph2grd.py
  pygmt/src/sphdistance.py
  pygmt/src/sphinterpolate.py
  pygmt/src/surface.py
  pygmt/src/triangulate.py
  pygmt/src/xyz2grd.py
Labels: maintenance, skip-changelog, final review call

#3382 Figure.ternary: Improve the handling of the alabel/blabel/clabel parameters
  pygmt/src/ternary.py
Labels: maintenance, skip-changelog

#3383 doc: Simplify the "minimum required versions" page using MyST customized URL schemes
  doc/minversions.md
Labels: maintenance, needs review

#3388 Move Will from Active Maintainers to Distinguished Contributors
  doc/team.md
Labels: maintenance, needs review

#3393 Exclude links in minversions from checks
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog

#3390 Link to the PyGMT Team page in AUTHORS.md and vice versa
  AUTHORS.md
  doc/team.md
Labels: documentation, skip-changelog, final review call

#3379 Add sphinx extension myst-nb to enable writing executable Markdown notebooks
  .github/workflows/ci_docs.yml
  ci/requirements/docs.yml
  doc/conf.py
  doc/install.md
  environment.yml
Labels: documentation

#3394 Update minimum value on GEBCO grid
  pygmt/tests/test_datasets_earth_relief.py
Labels: maintenance, skip-changelog

#3389 Add a tutorial for typesetting non-ASCII characters
  examples/tutorials/advanced/non_ascii_text.py
Labels: documentation, needs review

#3403 CI: Exclude links in minversions from checks
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog

#3401 CI: Test NumPy 2.1 in the GMT Tests workflow
  .github/workflows/ci_tests.yaml
Labels: maintenance

#3404 Update the onboarding access checklist in Maintainers Guides
  doc/maintenance.md
Labels: maintenance

#3408 CI: Fix the name of the 'build' package to 'python-build' on conda-forge
  .github/workflows/cache_data.yaml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_legacy.yaml
  ci/requirements/docs.yml
  environment.yml
Labels: maintenance

#3412 Refactor launch_external_viewer to use match-case statements
  pygmt/_show_versions.py
  pygmt/clib/loading.py
  pygmt/helpers/utils.py
Labels: maintenance, skip-changelog

#3414 Add pre-commit.ci configurations to enable auto updates of hooks
  .pre-commit-config.yaml
Labels: maintenance

#3415 CI: Skip the chmod hook in pre-commit.ci
  .pre-commit-config.yaml
Labels: maintenance, skip-changelog

#3411 DOC: Add an offboarding access checklist for maintainers
  doc/maintenance.md
Labels: documentation, final review call

#3395 Figure.savefig: Add type hints and improve docstrings
  pygmt/figure.py
Labels: skip-changelog, typing

#3419 Fix "sphinx-gallery" to "sphinx_gallery" when importing
  pygmt/tests/test_sphinx_gallery.py
Labels: bug, maintenance, skip-changelog, final review call
