Repository GenericMappingTools/pygmt, pull requests merged in 2024-07, with the labels that each got.

#3307 Add pytest conftest.py file to suppress warnings with NumPy 2.0
  pygmt/conftest.py
Labels: maintenance, skip-changelog, needs review

#3311 Gallery examples: Minor typo fixes
  examples/gallery/basemaps/double_y_axes.py
  examples/gallery/basemaps/ternary.py
  examples/gallery/embellishments/inset.py
Labels: documentation, skip-changelog

#3313 Fix typo in AUTHORS.md
  AUTHORS.md
Labels: skip-changelog

#3317 Enable ruff's literal-membership (PLR6201) rule and fix violations
  pygmt/accessors.py
  pygmt/clib/session.py
  pygmt/datasets/load_remote_dataset.py
  pygmt/figure.py
  pygmt/helpers/tempfile.py
  pygmt/helpers/validators.py
  pygmt/src/meca.py
  pygmt/src/tilemap.py
  pygmt/tests/test_clib.py
  pygmt/tests/test_clib_loading.py
  pyproject.toml
Labels: maintenance, run/benchmark

#3319 Enable ruff's unspecified-encoding (PLW1514) rule and fix violations
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/tests/test_datatypes_dataset.py
  pygmt/tests/test_helpers.py
  pygmt/tests/test_legend.py
  pygmt/tests/test_meca.py
  pygmt/tests/test_plot.py
  pygmt/tests/test_plot3d.py
  pygmt/tests/test_text.py
  pyproject.toml
Labels: maintenance

#3321 Replace rio.set_crs with rio.write_crs in load_tile_map function
  pygmt/datasets/tile_map.py
Labels: bug

#3322 load_tile_map: Fix the raster band indexing, should start from 1
  pygmt/datasets/tile_map.py
Labels: bug

#3323 load_tile_map: Register the rio accessor by importing rioxarray so the returned raster has CRS
  pygmt/datasets/tile_map.py
Labels: bug, needs review

#3330 Run pytest with `--color=yes` to force GitHub Actions logs to have color
  pyproject.toml
Labels: maintenance

#3327 clib: Improve docstrings, comments, type hints and codes of some Session methods
  pygmt/clib/session.py
Labels: maintenance, skip-changelog, final review call

#3325 Figure.coast: Improve documentation
  pygmt/src/coast.py
Labels: documentation, skip-changelog, final review call

#3329 Add typing hints for the returned value of load_xxx functions
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/earth_geoid.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_mask.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/earth_vertical_gravity_gradient.py
  pygmt/datasets/load_remote_dataset.py
  pygmt/datasets/mars_relief.py
  pygmt/datasets/mercury_relief.py
  pygmt/datasets/moon_relief.py
  pygmt/datasets/pluto_relief.py
  pygmt/datasets/samples.py
  pygmt/datasets/tile_map.py
  pygmt/datasets/venus_relief.py
Labels: skip-changelog, typing

#3336 build_arg_list: Raise an exception if an invalid output file name is given
  pygmt/helpers/utils.py
  pygmt/tests/test_helpers.py
Labels: maintenance, needs review, run/benchmark

#3334 pygmt.grd2cpt & pygmt.makecpt: Simplify the logic for dealing with CPT output
  pygmt/src/grd2cpt.py
  pygmt/src/makecpt.py
Labels: maintenance, needs review, run/benchmark

#3324 Wrap the GMT API function GMT_Read_Data to read data into GMT data containers
  doc/api/index.rst
  pygmt/clib/conversion.py
  pygmt/clib/session.py
  pygmt/tests/test_clib_read_data.py
Labels: feature

#3340 Gallery example "Color points by categories": Update "color" to "fill" in introduction text
  examples/gallery/symbols/points_categorical.py
Labels: maintenance, skip-changelog

#3335 Refactor the data_kind and validate_data_input functions
  pygmt/clib/session.py
  pygmt/helpers/__init__.py
  pygmt/helpers/utils.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/text.py
  pygmt/tests/test_helpers.py
Labels: maintenance, skip-changelog, needs review

#3341 Gallery examples: Fix typos
  examples/gallery/maps/country_polygons.py
  examples/gallery/symbols/points.py
Labels: documentation, skip-changelog

#3343 Update link to the cpt-city recourses
  pygmt/src/grd2cpt.py
  pygmt/src/makecpt.py
Labels: maintenance, skip-changelog

#3344 Extral resources: Update thumbnail image for "PyGMT HOWTO"
  doc/external_resources.md
Labels: maintenance

#3312 Examples: Make position codes consistent in comments
  examples/gallery/3d_plots/grdview_surface.py
  examples/gallery/basemaps/double_y_axes.py
  examples/gallery/embellishments/colorbar.py
  examples/gallery/embellishments/inset.py
  examples/gallery/embellishments/inset_rectangle_region.py
  examples/gallery/embellishments/legend.py
  examples/gallery/embellishments/logo.py
  examples/gallery/embellishments/timestamp.py
  examples/gallery/images/cross_section.py
  examples/gallery/images/grdlandmask.py
  examples/gallery/lines/wiggle.py
  examples/gallery/maps/borders.py
  examples/tutorials/advanced/insets.py
Labels: documentation, skip-changelog, final review call

#3350 Temporarily pin sphinx-gallery<0.17.0
  .github/workflows/ci_docs.yml
  ci/requirements/docs.yml
  environment.yml
Labels: maintenance

#3345 Extral resources: Update thumbnail image for "PyGMT HOWTO" - 02
  doc/external_resources.md
Labels: maintenance, skip-changelog

#3310 Support non-ASCII characters in ISO-8859-x charsets
  doc/techref/encodings.md
  pygmt/encodings.py
  pygmt/helpers/__init__.py
  pygmt/helpers/utils.py
  pygmt/src/text.py
  pygmt/tests/baseline/test_text_nonascii_iso8859.png.dvc
  pygmt/tests/test_text.py
Labels: enhancement, final review call

#3347 Fix the grant numbers for the support of PyGMT
  doc/overview.md
Labels: documentation, skip-changelog

#3353 Fix the tile_map doctest which has different output on Windows in the GMT Legacy Tests
  pygmt/datasets/tile_map.py
Labels: maintenance, skip-changelog, final review call

#3354 Figure.text: Fix link to "Technical Reference/Supported Encodings..."
  pygmt/src/text.py
Labels: documentation, skip-changelog

#3356 Move projection table to Technical References
  .github/workflows/ci_docs.yml
  ci/requirements/docs.yml
  doc/techref/index.md
  doc/techref/projections.rst
  environment.yml
  examples/projections/README.txt
Labels: documentation, skip-changelog

#3338 Wrap GMT's standard data type GMT_IMAGE for images
  pygmt/clib/session.py
  pygmt/datatypes/__init__.py
  pygmt/datatypes/image.py
  pygmt/tests/test_clib_read_data.py
Labels: feature, final review call

#3280 Add a test to make sure PyGMT works with paths that contain non-ASCII characters
  pygmt/tests/test_which.py
Labels: maintenance

#3254 Refactor clib to avoid checking GMT version repeatedly and only check once when loading the GMT library
  .github/ISSUE_TEMPLATE/5-bump_gmt_checklist.md
  doc/conf.py
  pygmt/clib/__init__.py
  pygmt/clib/loading.py
  pygmt/clib/session.py
  pygmt/tests/test_clib.py
  pygmt/tests/test_clib_loading.py
Labels: maintenance, needs review, run/benchmark
