Repository GenericMappingTools/pygmt, pull requests merged in 2025-06, with the labels that each got.

#3955 GMTDataArrayAccessor: Improve the documentation to clarify how the accessor works
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_day.py
  pygmt/datasets/earth_deflection.py
  pygmt/datasets/earth_dist.py
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/earth_geoid.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_mask.py
  pygmt/datasets/earth_mean_dynamic_topography.py
  pygmt/datasets/earth_mean_sea_surface.py
  pygmt/datasets/earth_night.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/earth_vertical_gravity_gradient.py
  pygmt/datasets/mars_relief.py
  pygmt/datasets/mercury_relief.py
  pygmt/datasets/moon_relief.py
  pygmt/datasets/pluto_relief.py
  pygmt/datasets/venus_relief.py
  pygmt/xarray/accessor.py
Labels: documentation, final review call

#3961 Add a helper function sequence_join to join a sequence by a separator
  pygmt/helpers/__init__.py
  pygmt/helpers/utils.py
  pygmt/src/grdclip.py
Labels: enhancement

#3013 Figure.coast/pygmt.select/pygmt.grdlandmask: Use long names ("crude"/"low"/"intermediate"/"high"/"full") for the 'resolution' parameter
  examples/tutorials/basics/coastlines.py
  pygmt/src/_common.py
  pygmt/src/coast.py
  pygmt/src/grdlandmask.py
  pygmt/src/select.py
  pygmt/tests/test_coast.py
Labels: enhancement, needs review, run/benchmark

#3964 DOC: Typo fixes (singular-plural)
  examples/gallery/histograms/blockm.py
  examples/gallery/images/grdlandmask.py
  examples/tutorials/advanced/3d_perspective_image.py
  examples/tutorials/advanced/cartesian_histograms.py
  examples/tutorials/advanced/insets.py
  pygmt/src/basemap.py
  pygmt/src/coast.py
  pygmt/src/grdsample.py
Labels: documentation, skip-changelog

#3966 DOC: Update docs to use consistently x-* and y-* (with hyphen) - 02
  examples/gallery/basemaps/double_y_axes.py
  examples/gallery/histograms/scatter_and_histograms.py
  examples/gallery/images/contours.py
  examples/gallery/lines/vector_styles.py
  examples/tutorials/advanced/vectors.py
  examples/tutorials/basics/polygons.py
Labels: documentation, skip-changelog

#3921 Update affiliation of YF
  AUTHORS.md
Labels: maintenance, skip-changelog

#3979 Figure.coast: Parameter 'shorelines' also accepts bool
  pygmt/src/coast.py
Labels: documentation, skip-changelog

#3965 Improve decorators @use_alias/@fmt_docstrings to list non-aliased aliases
  pygmt/helpers/decorators.py
  pygmt/src/coast.py
  pygmt/src/grdclip.py
  pygmt/src/grdfill.py
  pygmt/src/grdlandmask.py
  pygmt/src/meca.py
  pygmt/src/select.py
  pygmt/src/solar.py
  pygmt/src/ternary.py
  pygmt/src/text.py
  pygmt/src/wiggle.py
  pygmt/tests/test_coast.py
Labels: enhancement

#3963 pygmt.grdlandmask: Improve the checking of parameters 'maskvalues'/'bordervalues'
  pygmt/src/grdlandmask.py
Labels: enhancement, final review call

#3977 Add youtube links on landing and overview pages
  README.md
  doc/overview.md
Labels: documentation, skip-changelog, needs review

#3971 Changelog entry for v0.16.0
  CITATION.cff
  README.md
  doc/_static/version_switch.js
  doc/changes.md
  doc/minversions.md
Labels: maintenance, skip-changelog, final review call

#3982 Fix the bug when passing a sequence that contains True to a parameter
  pygmt/helpers/utils.py
  pygmt/tests/baseline/test_basemap_frame_sequence_true.png.dvc
  pygmt/tests/test_basemap.py
Labels: bug, needs review
