Repository GenericMappingTools/pygmt, pull requests merged in 2025-04, with the labels that each got.

#3887 Update the release checklist post v0.15.0 release
  .github/ISSUE_TEMPLATE/4-release_checklist.md
Labels: maintenance, skip-changelog, final review call

#3891 DOC: Fix formatting in grdfill docstrings
  pygmt/src/grdfill.py
Labels: maintenance, skip-changelog, needs review

#3894 Fix the sphinterpolate failing test in the GMT Dev Tests
  pygmt/tests/test_sphinterpolate.py
Labels: maintenance, skip-changelog

#3896 CI: Remove NumPy version from the Tests workflow name
  .github/workflows/ci_tests.yaml
Labels: maintenance, skip-changelog

#3892 Unpin sphinx_rtd_theme and add a workaround for v3.0
  .github/workflows/ci_docs.yml
  ci/requirements/docs.yml
  doc/_static/style.css
  doc/_templates/layout.html
  environment.yml
Labels: maintenance, final review call

#3699 Set license and license-files key in project metadata to follow PEP639
  pyproject.toml
Labels: maintenance

#3900 DOCS: Update solar to always use "day-night"
  pygmt/src/solar.py
Labels: documentation, skip-changelog

#3899 Reformat AUTHORSHIP.md to wrap lines at 88 characters
  AUTHORSHIP.md
Labels: documentation, skip-changelog

#3905 Add mailmap to consolidate author identities and correctly count contributions
  .mailmap
  MANIFEST.in
Labels: maintenance, skip-changelog, final review call

#3893 Session.virtualfile_from_vectors: Remove the deprecated '*args' parameter [deprecated since v0.14.0]
  pygmt/clib/session.py
  pygmt/tests/test_clib_virtualfile_from_vectors.py
Labels: deprecation, final review call

#3895 SPEC 0: Bump minimum supported version to pandas>=2.1
  .github/workflows/ci_tests.yaml
  environment.yml
  pygmt/clib/conversion.py
  pygmt/tests/test_clib_to_numpy.py
  pyproject.toml
  requirements.txt
Labels: deprecation, final review call

#3908 Bump minimum supported version to geopandas>=1.0
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_legacy.yaml
  environment.yml
  pygmt/helpers/tempfile.py
  pyproject.toml
Labels: deprecation

#3823 Session.virtualfile_in: Deprecate the parameter 'extra_arrays'. Prepare and pass a dictionary of arrays instead (will be removed in v0.20.0)
  pygmt/clib/session.py
  pygmt/helpers/utils.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/text.py
  pygmt/tests/test_clib_virtualfile_in.py
  pygmt/tests/test_plot3d.py
Labels: deprecation

#3904 Update the AUTHORSHIP and Maintainers' Guides to reflect co-author contributions
  AUTHORSHIP.md
  doc/maintenance.md
Labels: maintenance

#3915 CI: Bump to Windows 2022 in the GMT Legacy Tests workflow
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, skip-changelog

#3916 SPEC 0: Bump minimum supported versions to NumPy 1.26
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_legacy.yaml
  environment.yml
  pyproject.toml
  requirements.txt
Labels: deprecation, final review call

#3918 SPEC 0: Bump minimum supported version to xarray>=2023.07
  .github/workflows/ci_tests.yaml
  environment.yml
  pyproject.toml
  requirements.txt
Labels: deprecation

#3917 Bump minimum supported version to pyarrow>=16
  .github/workflows/ci_tests_legacy.yaml
  environment.yml
  pygmt/tests/test_clib_to_numpy.py
  pyproject.toml
Labels: deprecation

#3920 TYP: Add PathLike and TableLike types for type hints and remove the table-like placeholder
  pygmt/_typing.py
  pygmt/clib/session.py
  pygmt/figure.py
  pygmt/helpers/decorators.py
  pygmt/helpers/utils.py
  pygmt/helpers/validators.py
  pygmt/src/binstats.py
  pygmt/src/blockm.py
  pygmt/src/contour.py
  pygmt/src/dimfilter.py
  pygmt/src/filter1d.py
  pygmt/src/grd2cpt.py
  pygmt/src/grd2xyz.py
  pygmt/src/grdclip.py
  pygmt/src/grdcontour.py
  pygmt/src/grdcut.py
  pygmt/src/grdfill.py
  pygmt/src/grdfilter.py
  pygmt/src/grdgradient.py
  pygmt/src/grdhisteq.py
  pygmt/src/grdimage.py
  pygmt/src/grdinfo.py
  pygmt/src/grdlandmask.py
  pygmt/src/grdproject.py
  pygmt/src/grdsample.py
  pygmt/src/grdtrack.py
  pygmt/src/grdview.py
  pygmt/src/grdvolume.py
  pygmt/src/histogram.py
  pygmt/src/image.py
  pygmt/src/info.py
  pygmt/src/legend.py
  pygmt/src/meca.py
  pygmt/src/nearneighbor.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/project.py
  pygmt/src/rose.py
  pygmt/src/select.py
  pygmt/src/sph2grd.py
  pygmt/src/sphdistance.py
  pygmt/src/sphinterpolate.py
  pygmt/src/surface.py
  pygmt/src/ternary.py
  pygmt/src/text.py
  pygmt/src/triangulate.py
  pygmt/src/velo.py
  pygmt/src/which.py
  pygmt/src/wiggle.py
  pygmt/src/x2sys_cross.py
  pygmt/src/xyz2grd.py
Labels: needs review, typing

#3923 Improve the description for the 'cores' parameter
  pygmt/helpers/decorators.py
Labels: documentation, skip-changelog

#3927 Add 'toctree' option to autosummary directive to generate stub pages
  doc/_templates/autosummary/class.rst
  doc/_templates/autosummary/module.rst
Labels: maintenance, skip-changelog

#3926 Remove the lengthy project description on the API reference page
  doc/api/index.rst
Labels: documentation, skip-changelog, final review call

#3919 Implement gmt xarray BackendEntrypoint
  doc/api/index.rst
  pygmt/__init__.py
  pygmt/tests/test_xarray_backend.py
  pygmt/xarray/__init__.py
  pygmt/xarray/backend.py
  pyproject.toml
Labels: feature, final review call

#3883 pygmt.grdclip: Parameters 'between' and 'replace' accept a 2-D sequence
  pygmt/src/grdclip.py
  pygmt/tests/test_grdclip.py
Labels: enhancement, final review call

#3369 Session.virtualfile_in: Deprecate parameter 'required_z'. Use 'mincols' instead (will be removed in v0.20.0)
  pygmt/clib/session.py
  pygmt/helpers/utils.py
  pygmt/src/blockm.py
  pygmt/src/contour.py
  pygmt/src/nearneighbor.py
  pygmt/src/plot3d.py
  pygmt/src/project.py
  pygmt/src/surface.py
  pygmt/src/triangulate.py
  pygmt/src/wiggle.py
  pygmt/src/xyz2grd.py
  pygmt/tests/test_clib_virtualfile_in.py
Labels: deprecation, needs review

#3922 Deprecate pygmt.io.load_dataarray, use xarray.load_dataarray instead
  pygmt/datasets/samples.py
  pygmt/helpers/testing.py
  pygmt/io.py
  pygmt/tests/test_clib_put_matrix.py
  pygmt/tests/test_clib_read_data.py
  pygmt/tests/test_dimfilter.py
  pygmt/tests/test_grdclip.py
  pygmt/tests/test_grdcut.py
  pygmt/tests/test_grdfill.py
  pygmt/tests/test_grdfilter.py
  pygmt/tests/test_grdgradient.py
  pygmt/tests/test_grdhisteq.py
  pygmt/tests/test_grdlandmask.py
  pygmt/tests/test_grdproject.py
  pygmt/tests/test_grdsample.py
  pygmt/tests/test_io.py
  pygmt/tests/test_nearneighbor.py
  pygmt/tests/test_surface.py
  pygmt/tests/test_triangulate.py
  pygmt/tests/test_xarray_accessor.py
  pygmt/tests/test_xarray_backend.py
  pygmt/tests/test_xyz2grd.py
Labels: deprecation, run/benchmark

#3643 Remove the dependency of netCDF4
  .github/workflows/benchmarks.yml
  .github/workflows/cache_data.yaml
  .github/workflows/ci_docs.yml
  .github/workflows/ci_doctests.yaml
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
  .github/workflows/type_checks.yml
  ci/requirements/docs.yml
  doc/install.md
  environment.yml
  pygmt/tests/test_io.py
  pygmt/tests/test_xarray_accessor.py
  pygmt/tests/test_xarray_backend.py
  pyproject.toml
  requirements.txt
Labels: deprecation, needs review

#3933 Bump minimum supported version to packaging>=24.2
  .github/workflows/ci_tests_legacy.yaml
  environment.yml
  pyproject.toml
  requirements.txt
Labels: deprecation
