Repository GenericMappingTools/pygmt, pull requests merged in 2025-08, with the labels that each got.

#4031 pygmt.grdlandmask: Refactor to use the new alias system for bordervalues/maskvalues
  pygmt/src/grdlandmask.py
Labels: maintenance, skip-changelog, final review call

#4034 pygmt.grdclip: Use the new alias system for parameters above/below/between/replace
  pygmt/src/grdclip.py
Labels: maintenance, skip-changelog

#4035 pygmt.grdfill: Use the new alias system for parameters constantfill/gridfill/neighborfill/splinefill/inquire/mode
  pygmt/src/grdfill.py
Labels: maintenance, skip-changelog

#4036 Figure.ternary: Use the new alias system for parameters alabel/blabel/clabel
  pygmt/src/ternary.py
Labels: maintenance, skip-changelog

#4012 Figure.timestamp: Refactor to use the new alias system
  pygmt/src/timestamp.py
Labels: maintenance, skip-changelog

#3012 pygmt.binstats: Let the parameter 'statistic' support descriptive arguments
  pygmt/src/binstats.py
  pygmt/tests/test_binstats.py
Labels: enhancement

#4040 pygmt.select: Remove 'resolution' from the use_alias decorator
  pygmt/src/select.py
Labels: maintenance, skip-changelog, final review call

#4050 Update GitHub username from to "kadatatlukishore" to "K-OS-Dev"
  doc/changes.md
Labels: maintenance, skip-changelog

#4043 Reformat the manually maintained aliases in docstrings
  pygmt/src/basemap.py
  pygmt/src/binstats.py
  pygmt/src/coast.py
  pygmt/src/colorbar.py
  pygmt/src/contour.py
  pygmt/src/grdclip.py
  pygmt/src/grdcontour.py
  pygmt/src/grdcut.py
  pygmt/src/grdfill.py
  pygmt/src/grdimage.py
  pygmt/src/grdlandmask.py
  pygmt/src/grdproject.py
  pygmt/src/grdview.py
  pygmt/src/histogram.py
  pygmt/src/image.py
  pygmt/src/inset.py
  pygmt/src/legend.py
  pygmt/src/logo.py
  pygmt/src/meca.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/select.py
  pygmt/src/solar.py
  pygmt/src/subplot.py
  pygmt/src/ternary.py
  pygmt/src/text.py
  pygmt/src/tilemap.py
  pygmt/src/triangulate.py
  pygmt/src/velo.py
  pygmt/src/wiggle.py
  pygmt/src/xyz2grd.py
Labels: maintenance, skip-changelog

#4041 Figure.wiggle: Refactor the parameter fillpositive/fillnegative using the new alias system
  pygmt/src/wiggle.py
Labels: maintenance, skip-changelog, needs review

#4056 Figure.psconvert: Refactor the dpi/gs_path/gs_option/prefix parameters using the new alias system
  pygmt/src/psconvert.py
Labels: maintenance, skip-changelog, final review call

#4059 DOC: Fix synthax of aliases list for pygmt.grdcut
  pygmt/src/grdcut.py
Labels: maintenance, skip-changelog

#4060 x2sys_cross: Fix IndexError to allow empty dataframe outputs
  pygmt/src/x2sys_cross.py
  pygmt/tests/test_x2sys_cross.py
Labels: bug

#4062 [BREAKING] Figure.grdimage: Raise NotImplementedError instead of GMTInvalidInput for -A option
  pygmt/src/grdimage.py
  pygmt/tests/test_grdimage.py
Labels: maintenance

#4067 Figure.plot/Figure.plot3d: Refactor the straight_line parameter to the new alias system
  pygmt/src/plot.py
  pygmt/src/plot3d.py
Labels: maintenance, skip-changelog

#4065 [BREAKING] Figure.text: Raise GMTTypeError if text is a sequence when position is given
  pygmt/src/text.py
  pygmt/tests/test_text.py
Labels: maintenance

#4068 Figure.plot/Figure.plot3d/Figure.text: Migrate the transparency parameter to the new alias system
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/text.py
Labels: maintenance, skip-changelog, final review call
