Repository GenericMappingTools/pygmt, pull requests merged in 2025-05, with the labels that each got.

#3930 DOC: Improve the docstrings of the 'panel' parameter
  pygmt/helpers/decorators.py
Labels: documentation, skip-changelog, needs review

#3937 Update values for SRTM+ v2.7
  pygmt/tests/test_datasets_earth_relief.py
Labels: maintenance, skip-changelog

#3931 Session.virtualfile_in: Deprecate parameter 'required_data' to 'required' (will be removed in v0.20.0)
  pygmt/clib/session.py
  pygmt/helpers/utils.py
  pygmt/src/grdfill.py
  pygmt/src/grdimage.py
  pygmt/src/grdtrack.py
  pygmt/src/grdview.py
  pygmt/src/legend.py
  pygmt/src/project.py
  pygmt/src/text.py
Labels: deprecation, needs review

#3942 Set registration and gtype properly as enums on gmt accessor init
  pygmt/tests/test_binstats.py
  pygmt/tests/test_datasets_earth_age.py
  pygmt/tests/test_datasets_earth_day.py
  pygmt/tests/test_datasets_earth_deflection.py
  pygmt/tests/test_datasets_earth_dist.py
  pygmt/tests/test_datasets_earth_free_air_anomaly.py
  pygmt/tests/test_datasets_earth_geoid.py
  pygmt/tests/test_datasets_earth_magnetic_anomaly.py
  pygmt/tests/test_datasets_earth_mask.py
  pygmt/tests/test_datasets_earth_mean_sea_surface.py
  pygmt/tests/test_datasets_earth_night.py
  pygmt/tests/test_datasets_earth_relief.py
  pygmt/tests/test_datasets_earth_vertical_gravity_gradient.py
  pygmt/tests/test_datasets_load_remote_datasets.py
  pygmt/tests/test_datasets_mars_relief.py
  pygmt/tests/test_datasets_mean_dynamic_topography.py
  pygmt/tests/test_datasets_mercury_relief.py
  pygmt/tests/test_datasets_moon_relief.py
  pygmt/tests/test_datasets_pluto_relief.py
  pygmt/tests/test_datasets_venus_relief.py
  pygmt/tests/test_dimfilter.py
  pygmt/tests/test_grdclip.py
  pygmt/tests/test_grdfill.py
  pygmt/tests/test_grdfilter.py
  pygmt/tests/test_grdgradient.py
  pygmt/tests/test_grdhisteq.py
  pygmt/tests/test_grdimage.py
  pygmt/tests/test_grdlandmask.py
  pygmt/tests/test_grdproject.py
  pygmt/tests/test_grdsample.py
  pygmt/tests/test_io.py
  pygmt/tests/test_nearneighbor.py
  pygmt/tests/test_sph2grd.py
  pygmt/tests/test_sphdistance.py
  pygmt/tests/test_sphinterpolate.py
  pygmt/tests/test_surface.py
  pygmt/tests/test_triangulate.py
  pygmt/tests/test_xarray_accessor.py
  pygmt/tests/test_xarray_backend.py
  pygmt/tests/test_xyz2grd.py
  pygmt/xarray/accessor.py
Labels: maintenance

#3943 Remove the unnecessary which call in load_static_earth_relief
  pygmt/helpers/testing.py
Labels: maintenance, skip-changelog

#3947 Exclude stackoverflow link from Link Checker Report
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog

#3950 Store first tile as source encoding for tiled grids
  pygmt/datasets/load_remote_dataset.py
  pygmt/tests/test_xarray_accessor.py
Labels: enhancement

#3932 Allow passing region to GMTBackendEntrypoint.open_dataset
  pygmt/datasets/load_remote_dataset.py
  pygmt/tests/test_xarray_backend.py
  pygmt/xarray/backend.py
Labels: enhancement

#3954 Add more remote datasets to caching
  pygmt/helpers/caching.py
Labels: maintenance, skip-changelog, final review call

#3958 CI: Exclude one link that timeouts
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog

#3956 pygmt.select: parameter 'mask' accepts a sequence of strings
  pygmt/src/select.py
Labels: bug, final review call

#3959 Fix one failing test related to earth_relief dataset update
  pygmt/tests/test_datasets_earth_relief.py
Labels: maintenance, skip-changelog
