Repository GenericMappingTools/pygmt, pull requests merged in 2025-02, with the labels that each got.

#3783 Changelog entry for v0.14.1
  CITATION.cff
  README.md
  doc/_static/version_switch.js
  doc/changes.md
  doc/minversions.md
Labels: maintenance, skip-changelog

#3786 Changelog entry for v0.14.1 (#3783)
  CITATION.cff
  README.md
  doc/_static/version_switch.js
  doc/changes.md
  doc/minversions.md
Labels: maintenance, skip-changelog, needs review

#3790 Fix a typo in doc/conf.py
  doc/conf.py
Labels: maintenance, skip-changelog

#3778 CI: Test on Linux arm64 runners
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
  .github/workflows/ci_tests_legacy.yaml
  pygmt/tests/test_contour.py
  pygmt/tests/test_x2sys_cross.py
Labels: maintenance, needs review

#3507 clib.conversion: Remove the unused array_to_datetime function
  pygmt/clib/conversion.py
  pygmt/clib/session.py
Labels: maintenance, final review call

#3795 Fix incorrect reST syntax in the data_kind function
  pygmt/helpers/utils.py
Labels: maintenance, skip-changelog

#3797 CI: Use matrix.os instead of runner.os in artifact name
  .github/workflows/ci_tests.yaml
  .github/workflows/ci_tests_dev.yaml
Labels: maintenance, skip-changelog

#3696 GMTDataArrayAccessor: Support passing values using enums GridRegistration and GridType for grid registration and type
  pygmt/accessors.py
  pygmt/datatypes/grid.py
  pygmt/datatypes/image.py
  pygmt/src/tilemap.py
  pygmt/tests/test_accessor.py
  pygmt/tests/test_binstats.py
  pygmt/tests/test_datasets_earth_age.py
  pygmt/tests/test_datasets_earth_day.py
  pygmt/tests/test_datasets_earth_deflection.py
  pygmt/tests/test_datasets_earth_dist.py
  pygmt/tests/test_datasets_earth_free_air_anomaly.py
  pygmt/tests/test_datasets_earth_geoid.py
  pygmt/tests/test_datasets_earth_magnetic_anomaly.py
  pygmt/tests/test_datasets_earth_mask.py
  pygmt/tests/test_datasets_earth_mean_sea_surface.py
  pygmt/tests/test_datasets_earth_night.py
  pygmt/tests/test_datasets_earth_relief.py
  pygmt/tests/test_datasets_earth_vertical_gravity_gradient.py
  pygmt/tests/test_datasets_load_remote_datasets.py
  pygmt/tests/test_datasets_mars_relief.py
  pygmt/tests/test_datasets_mean_dynamic_topography.py
  pygmt/tests/test_datasets_mercury_relief.py
  pygmt/tests/test_datasets_moon_relief.py
  pygmt/tests/test_datasets_pluto_relief.py
  pygmt/tests/test_datasets_venus_relief.py
  pygmt/tests/test_dimfilter.py
  pygmt/tests/test_grdclip.py
  pygmt/tests/test_grdfill.py
  pygmt/tests/test_grdfilter.py
  pygmt/tests/test_grdgradient.py
  pygmt/tests/test_grdhisteq.py
  pygmt/tests/test_grdimage.py
  pygmt/tests/test_grdlandmask.py
  pygmt/tests/test_grdproject.py
  pygmt/tests/test_grdsample.py
  pygmt/tests/test_io.py
  pygmt/tests/test_nearneighbor.py
  pygmt/tests/test_sph2grd.py
  pygmt/tests/test_sphdistance.py
  pygmt/tests/test_sphinterpolate.py
  pygmt/tests/test_surface.py
  pygmt/tests/test_triangulate.py
  pygmt/tests/test_xyz2grd.py
Labels: enhancement

#3799 Bump to ruff 0.9.6 and fix violations
  environment.yml
  pygmt/encodings.py
  pygmt/helpers/tempfile.py
  pygmt/io.py
  pygmt/src/select.py
Labels: maintenance, skip-changelog, needs review

#3800 Specify supported platforms with classifiers
  pyproject.toml
Labels: maintenance, skip-changelog

#3808 Fix the bug for passing text strings with numeric values (#3804)
  pygmt/clib/conversion.py
  pygmt/tests/baseline/test_text_numeric_text.png.dvc
  pygmt/tests/test_clib_to_numpy.py
  pygmt/tests/test_text.py
Labels: bug

#3809 Changelog entry for v0.14.2
  CITATION.cff
  README.md
  doc/_static/version_switch.js
  doc/changes.md
  doc/minversions.md
Labels: maintenance, skip-changelog, needs review

#3810 Changelog entry for v0.14.2 (#3809)
  CITATION.cff
  README.md
  doc/_static/version_switch.js
  doc/changes.md
  doc/minversions.md
Labels: maintenance, skip-changelog, final review call

#3805 Bump to sphinx-gallery>=0.19 and use list in subsection_order and string in within_subsection_order
  doc/conf.py
  environment.yml
Labels: maintenance

#3594 DOC: Add advanced tutorial "Creating legends"
  examples/tutorials/advanced/legends.py
Labels: documentation, final review call

#3798 Rename _GMT_DATASET.to_dataframe to .to_pandas and _GMT_GRID.to_dataarray/_GMT_IMAGE.to_dataarray to .to_xarray
  pygmt/clib/session.py
  pygmt/datatypes/dataset.py
  pygmt/datatypes/grid.py
  pygmt/datatypes/image.py
  pygmt/tests/test_clib_read_data.py
Labels: maintenance

#3796 Add the private _is_printable_ascii function to simplify codes
  pygmt/helpers/utils.py
Labels: maintenance, skip-changelog

#3794 CI: Deploy documentation HTML ZIP archive and PDF file for dev versions
  .github/workflows/ci_docs.yml
Labels: maintenance

#3812 CI: Disable building PDF documentation in ReadTheDocs
  .readthedocs.yaml
Labels: maintenance, skip-changelog

#3814 CI: Upload documentation HTML ZIP archive and PDF file as release assets
  .github/workflows/ci_docs.yml
Labels: maintenance, final review call

#3811 DOC / Figure.meca: Use table for supported conventions
  pygmt/src/meca.py
Labels: documentation, skip-changelog

#3551 Figure.meca: Add the private _FocalMechanismConvention class to simplify codes
  pygmt/src/_common.py
  pygmt/src/meca.py
Labels: maintenance, skip-changelog

#3105 BREAKING: Support typesetting apostrophe (') and backtick (`)
  pygmt/helpers/utils.py
  pygmt/tests/baseline/test_text_quotation_marks.png.dvc
  pygmt/tests/test_text.py
Labels: enhancement, final review call

#3816 TYP: Add type hints to the GMT accessors
  pygmt/accessors.py
Labels: maintenance, skip-changelog

#2509 Figure.shift_origin: Support shifting origins temporarily when used as a context manager
  pygmt/src/shift_origin.py
  pygmt/tests/baseline/test_shift_origin_context_manager.png.dvc
  pygmt/tests/baseline/test_shift_origin_mixed_modes.png.dvc
  pygmt/tests/baseline/test_shift_origin_nested_context_manager.png.dvc
  pygmt/tests/test_shift_origin.py
Labels: enhancement, final review call

#3819 DOC: Update two gallery examples with Figure.shift_origin as context manager
  examples/gallery/3d_plots/scatter3d.py
  examples/gallery/histograms/scatter_and_histograms.py
Labels: documentation, skip-changelog

#3820 TYP: Add type hints to the is_nonstr_iter and args_in_kwargs functions
  pygmt/helpers/utils.py
Labels: maintenance, skip-changelog, final review call

#3824 DOC: Update Figure.grdview
  pygmt/src/grdview.py
Labels: documentation, skip-changelog, final review call
