Repository GenericMappingTools/pygmt, pull requests merged in 2025-01, with the labels that each got.

#3737 Update License year to 2025
  LICENSE.txt
Labels: maintenance, skip-changelog, final review call

#3740 Fix an image in README.md (broken on PyPI) and rewrap to 88 characters
  README.md
Labels: maintenance, skip-changelog

#3739 clib.Session: Remove deprecated virtualfile_from_data method, use virtualfile_in instead (Deprecated since v0.13.0)
  doc/api/index.rst
  pygmt/clib/session.py
  pygmt/tests/test_clib_virtualfile_in.py
Labels: deprecation

#3738 clib.Session: Remove deprecated open_virtual_file method, use open_virtualfile instead (Deprecated since v0.11.0)
  pygmt/clib/session.py
  pygmt/tests/test_clib_virtualfiles.py
Labels: deprecation, final review call

#3745 Add the missing separators in changelog
  doc/changes.md
Labels: maintenance, skip-changelog, final review call

#3743 Use well-known labels in project URLs following PEP753
  pyproject.toml
Labels: maintenance, skip-changelog

#3741 Update RG description in release checklist
  .github/ISSUE_TEMPLATE/4-release_checklist.md
Labels: maintenance, skip-changelog, needs review

#3692 Update the release checklist post v0.14.0 release
  .github/ISSUE_TEMPLATE/4-release_checklist.md
Labels: maintenance, skip-changelog, final review call

#3720 Figure.plot/Figure.plot3d: Improve the docstrings for straight_line
  pygmt/src/plot.py
  pygmt/src/plot3d.py
Labels: documentation, skip-changelog

#3751 DOC/Gallery example "Choropleth map": Fix typo
  examples/gallery/maps/choropleth_map.py
Labels: documentation, skip-changelog

#3748 Delete the .buildinfo file from gh-pages branch
  .buildinfo
Labels: maintenance, skip-changelog, final review call

#3688 _load_remote_dataset: Add the "kind" attribute to explicitly specify if data is a grid or image
  pygmt/datasets/load_remote_dataset.py
Labels: maintenance

#3754 TYP: Add return type hints for functions that return None
  pygmt/_show_versions.py
  pygmt/clib/session.py
  pygmt/figure.py
  pygmt/helpers/caching.py
  pygmt/helpers/tempfile.py
  pygmt/helpers/utils.py
  pygmt/session_management.py
Labels: skip-changelog, final review call, typing

#3749 CI: Update the doc deploy script to generate CNAME and index.html
  .github/workflows/ci_docs.yml
Labels: maintenance, skip-changelog, final review call

#3750 ruff: Ignore the B018 rule (useless expressions) in examples
  examples/gallery/images/rgb_image.py
  examples/gallery/lines/linestrings.py
  examples/gallery/maps/choropleth_map.py
  examples/tutorials/basics/plot.py
  pyproject.toml
Labels: maintenance, skip-changelog, final review call

#3752 DOC: Make bullet point lists consistent in docstrings (":" and lower-case) Part II
  pygmt/helpers/decorators.py
  pygmt/src/grdfilter.py
  pygmt/src/grdgradient.py
  pygmt/src/grdview.py
  pygmt/src/sphdistance.py
  pygmt/src/x2sys_cross.py
  pygmt/src/x2sys_init.py
Labels: documentation, skip-changelog, final review call

#3756 DOC: Make usage of "lowercase" and "uppercase" consistent across all docs
  doc/techref/patterns.md
  examples/gallery/basemaps/double_y_axes.py
  examples/gallery/embellishments/scalebar.py
  examples/gallery/images/cross_section.py
  examples/gallery/lines/decorated_lines.py
  examples/gallery/lines/quoted_lines.py
  examples/gallery/symbols/multi_parameter_symbols.py
  examples/projections/cyl/cyl_oblique_mercator.py
  examples/projections/nongeo/cartesian_linear.py
  examples/projections/nongeo/cartesian_logarithmic.py
  examples/projections/nongeo/cartesian_power.py
  examples/projections/nongeo/polar.py
  examples/tutorials/basics/frames.py
  pygmt/helpers/decorators.py
  pygmt/src/filter1d.py
  pygmt/src/project.py
  pygmt/src/text.py
Labels: documentation, skip-changelog

#3687 clib.conversion._to_numpy: Add tests for numpy array with np.datetime64 dtypes
  pygmt/tests/test_clib_to_numpy.py
Labels: maintenance, skip-changelog

#3670 clib.converison._to_numpy: Add tests for pandas.Series with datetime dtypes
  pygmt/clib/conversion.py
  pygmt/tests/test_clib_to_numpy.py
Labels: maintenance

#3742 CI: Separate jobs for publishing to TestPyPI and PyPI
  .github/workflows/publish-to-pypi.yml
Labels: maintenance

#3763 Bump to ruff 0.9.0, apply ruff 2025 style, and ignore A005 (stdlib-module-shadowing) violations
  doc/conf.py
  environment.yml
  examples/tutorials/advanced/cartesian_histograms.py
  pygmt/_show_versions.py
  pygmt/encodings.py
  pygmt/helpers/tempfile.py
  pygmt/helpers/utils.py
  pygmt/io.py
  pygmt/src/grd2xyz.py
  pygmt/src/select.py
  pygmt/tests/test_clib_virtualfile_from_stringio.py
  pygmt/tests/test_grdview.py
  pygmt/tests/test_info.py
Labels: maintenance, skip-changelog, needs review

#3761 Simplify doc/Makefile with sphinx-build make-mode
  doc/Makefile
Labels: maintenance, skip-changelog, final review call

#3766 Fix the 'html-noplot' make target for docs
  doc/Makefile
Labels: maintenance, skip-changelog, final review call

#3760 Fix the bug of converting Python sequence of datetime-like objects
  pygmt/clib/conversion.py
Labels: bug

#3758 clib.conversion._to_numpy: Add tests for Python sequence of datetime-like objects
  pygmt/tests/baseline/test_plot_datetime.png.dvc
  pygmt/tests/test_clib_to_numpy.py
  pygmt/tests/test_plot.py
Labels: maintenance, skip-changelog

#3755 Add a gallery example showing the usage of Figure.hlines and Figure.vlines
  examples/gallery/lines/hlines_vlines.py
  pygmt/src/hlines.py
  pygmt/src/vlines.py
Labels: documentation, final review call

#3772 CI: Separate jobs for publishing to TestPyPI and PyPI (#3742)
  .github/workflows/publish-to-pypi.yml
Labels: maintenance

#3773 Fix the bug of converting Python sequence of datetime-like objects (#3760)
  pygmt/clib/conversion.py
Labels: maintenance

#3774 Fix an image in README.md (broken on PyPI) and rewrap to 88 characters (#3740)
  README.md
Labels: maintenance

#3775 Update License year to 2025 (#3737)
  LICENSE.txt
Labels: maintenance

#3776 clib.conversion._to_numpy: Add tests for Python sequence of datetime-like objects (#3758)
  pygmt/tests/baseline/test_plot_datetime.png.dvc
  pygmt/tests/test_clib_to_numpy.py
  pygmt/tests/test_plot.py
Labels: maintenance

#3777 CI: Bump to Ubuntu 22.04 in the GMT Legacy Tests workflow
  .github/workflows/ci_tests_legacy.yaml
Labels: maintenance, skip-changelog

#3781 Fix the dataset link in the RGB image gallery example
  examples/gallery/images/rgb_image.py
Labels: maintenance, skip-changelog

#3782 Fix the dataset link in the RGB image gallery example (#3781)
  examples/gallery/images/rgb_image.py
Labels: maintenance, skip-changelog
