Repository GenericMappingTools/pygmt, pull requests merged in 2025-10, with the labels that each got.

#4126 Figure.colorbar: Add note regarding automatic fontsize scaling
  pygmt/src/colorbar.py
Labels: documentation, needs review

#4131 Make the doc pages for the Box and Pattern classes consistent
  pygmt/params/box.py
Labels: documentation, skip-changelog

#4137 CI: Set persist-credentials: true in format-command.yml
  .github/workflows/format-command.yml
Labels: maintenance, skip-changelog
