Repository GenericMappingTools/pygmt, pull requests merged in 2025-03, with the labels that each got.

#3827 Figure.meca: Refactor and add the private _get_focal_convention function
  pygmt/src/meca.py
Labels: maintenance, skip-changelog

#3828 Use the 'release-branch-semver' version scheme for setuptools_scm
  pyproject.toml
Labels: maintenance

#3832 Improve the docstrings of the validate_output_table_type function
  pygmt/helpers/validators.py
Labels: maintenance, skip-changelog

#3830 Update the option orders in the Sphinx configuration file
  doc/conf.py
Labels: maintenance, skip-changelog

#3833 Add links to the documentation HTML ZIP archive and PDF files
  doc/minversions.md
Labels: maintenance, final review call

#3837 CI: Upload the documentation PDF file as artifact for previewing
  .github/workflows/ci_docs.yml
Labels: maintenance, skip-changelog

#3831 Figure.meca: Refactor to improve the processing of the input data
  pygmt/src/meca.py
Labels: maintenance, skip-changelog, final review call, run/benchmark

#3839 DOC: Separate different kinds of documentation with commas
  doc/minversions.md
Labels: maintenance, skip-changelog, final review call

#3840 DOC: Fix the author information and the structure in the PDF documention
  doc/conf.py
Labels: documentation, skip-changelog

#3838 Rephrase the documentation for dataset loading functions
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_day.py
  pygmt/datasets/earth_deflection.py
  pygmt/datasets/earth_dist.py
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/earth_geoid.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_mask.py
  pygmt/datasets/earth_mean_dynamic_topography.py
  pygmt/datasets/earth_mean_sea_surface.py
  pygmt/datasets/earth_night.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/earth_vertical_gravity_gradient.py
  pygmt/datasets/mars_relief.py
  pygmt/datasets/mercury_relief.py
  pygmt/datasets/moon_relief.py
  pygmt/datasets/pluto_relief.py
  pygmt/datasets/samples.py
  pygmt/datasets/venus_relief.py
Labels: documentation, skip-changelog, final review call

#3841 DOC: Fix typo in remote dataset docs
  pygmt/datasets/earth_age.py
  pygmt/datasets/earth_deflection.py
  pygmt/datasets/earth_dist.py
  pygmt/datasets/earth_free_air_anomaly.py
  pygmt/datasets/earth_geoid.py
  pygmt/datasets/earth_magnetic_anomaly.py
  pygmt/datasets/earth_mask.py
  pygmt/datasets/earth_mean_dynamic_topography.py
  pygmt/datasets/earth_mean_sea_surface.py
  pygmt/datasets/earth_relief.py
  pygmt/datasets/earth_vertical_gravity_gradient.py
  pygmt/datasets/mars_relief.py
  pygmt/datasets/mercury_relief.py
  pygmt/datasets/moon_relief.py
  pygmt/datasets/pluto_relief.py
  pygmt/datasets/venus_relief.py
Labels: documentation, skip-changelog

#3842 Figure.meca: Add type hints and improve docstrings of some parameters
  pygmt/src/meca.py
Labels: documentation, maintenance, skip-changelog, final review call

#3115 **BREAKING** pygmt.grdcut: Refactor to store output in virtualfiles for grids
  pygmt/src/grdcut.py
  pygmt/tests/test_grdcut.py
  pygmt/tests/test_grdcut_image.py
Labels: enhancement

#3850 Bump to ruff 0.10.0 and fix violations
  environment.yml
  pygmt/tests/test_datasets_load_remote_datasets.py
  pygmt/tests/test_figure.py
Labels: maintenance, skip-changelog

#3853 DOC: Use always upper case letters in headings
  doc/techref/patterns.md
Labels: documentation, skip-changelog

#3852 pygmt.grdfill: Deprecate parameter 'no_data' to 'hole' (remove in v0.19.0)
  pygmt/src/grdfill.py
Labels: deprecation, final review call

#3678 Refactor _load_remote_dataset to write CRS information for raster images
  pygmt/datasets/earth_day.py
  pygmt/datasets/earth_night.py
  pygmt/datasets/load_remote_dataset.py
Labels: maintenance, needs review

#3858 DOC: Update gallery example for Figure.solar
  examples/gallery/embellishments/solar.py
Labels: documentation, skip-changelog

#3863 DOC: Use other image (not the GMT logo) in the gallery example for Figure.image
  examples/gallery/images/image.py
Labels: documentation, skip-changelog

#3857 Update the one-sentence description of wrappers to match upstream documentation
  pygmt/src/basemap.py
  pygmt/src/binstats.py
  pygmt/src/coast.py
  pygmt/src/colorbar.py
  pygmt/src/config.py
  pygmt/src/contour.py
  pygmt/src/dimfilter.py
  pygmt/src/filter1d.py
  pygmt/src/grd2cpt.py
  pygmt/src/grd2xyz.py
  pygmt/src/grdclip.py
  pygmt/src/grdcontour.py
  pygmt/src/grdcut.py
  pygmt/src/grdgradient.py
  pygmt/src/grdimage.py
  pygmt/src/grdinfo.py
  pygmt/src/grdlandmask.py
  pygmt/src/grdproject.py
  pygmt/src/grdsample.py
  pygmt/src/grdtrack.py
  pygmt/src/grdview.py
  pygmt/src/grdvolume.py
  pygmt/src/histogram.py
  pygmt/src/image.py
  pygmt/src/inset.py
  pygmt/src/legend.py
  pygmt/src/logo.py
  pygmt/src/plot.py
  pygmt/src/plot3d.py
  pygmt/src/psconvert.py
  pygmt/src/rose.py
  pygmt/src/solar.py
  pygmt/src/sph2grd.py
  pygmt/src/sphdistance.py
  pygmt/src/sphinterpolate.py
  pygmt/src/subplot.py
  pygmt/src/ternary.py
  pygmt/src/text.py
  pygmt/src/triangulate.py
  pygmt/src/which.py
  pygmt/src/xyz2grd.py
Labels: documentation, skip-changelog, final review call

#3865 Update min/max values on earth_wdmam tests
  pygmt/tests/test_datasets_earth_magnetic_anomaly.py
Labels: maintenance, skip-changelog

#2550 Add a tutorial for plotting focal mechanisms (beachballs)
  examples/tutorials/advanced/focal_mechanisms.py
Labels: documentation

#3867 CI: Set persist-credentials to true to allow pushing to the gh-pages branch
  .github/workflows/ci_docs.yml
Labels: maintenance, skip-changelog

#3872 CI: Add content write permission to the Release Drafter workflow
  .github/workflows/release-drafter.yml
Labels: maintenance, skip-changelog, final review call

#3855 pygmt.grdfill: Deprecate parameter 'mode' and add parameters 'constantfill/gridfill/neighborfill/splinefill' (deprecated since v0.15.0 and will be removed in v0.19.0)
  pygmt/src/grdfill.py
  pygmt/tests/test_grdfill.py
Labels: enhancement, deprecation

#3874 CI: Add issues/contents write permission to the slash commands
  .github/workflows/format-command.yml
  .github/workflows/slash-command-dispatch.yml
Labels: maintenance, skip-changelog, final review call

#3870 CI: Fix the condition check and permission in the Check Links workflow
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog, final review call

#3875 DOC: Update URLs
  .github/workflows/check-links.yml
  README.md
  doc/conf.py
Labels: documentation

#3868 DOC: Move description of distcal to the Technical Reference section
  doc/techref/common_parameters.md
  pygmt/helpers/decorators.py
Labels: maintenance, skip-changelog, needs review

#3879 DOC: Set needs_extensions to check sphinx extension versions
  doc/conf.py
Labels: maintenance, skip-changelog, needs review

#3880 pygmt.grdfill: Add new parameter 'inquire' to inquire the bounds of holes
  pygmt/src/grdfill.py
  pygmt/tests/test_grdfill.py
Labels: enhancement, final review call

#3884 pygmt.grdclip: Deprecate parameter 'new' to 'replace' (remove in v0.19.0)
  pygmt/src/grdclip.py
  pygmt/tests/test_grdclip.py
Labels: deprecation, skip-changelog, needs review

#3866 Changelog entry for v0.15.0
  CITATION.cff
  README.md
  doc/_static/version_switch.js
  doc/changes.md
  doc/minversions.md
Labels: maintenance, skip-changelog, final review call

#3886 DOC: Update URLs (Link Checker Report on 2025-03-30)
  .github/workflows/check-links.yml
Labels: maintenance, skip-changelog
